Add logic to handle for f.Close() in util/localconfig/
argoproj/argo-cd pull request #10014
Opened 2022-07-16 12:17 UTC by my-git9

Add logic to handle for f.Close() for util/localconfig/

part of issue: https://github.com/argoproj/argo-cd/issues/9963

2022-07-19 15:43 UTC, crenshaw-dev requested changes
Thanks! Requested one change.

2022-07-19 15:44 UTC, crenshaw-dev commented on util/localconfig/localconfig_test.go
>  			defer f.Close()
This line should be deleted.

2022-07-20 04:47 UTC, my-git9 commented on util/localconfig/localconfig_test.go
>  			defer f.Close()
Updated. Thanks

2022-07-20 20:19 UTC, crenshaw-dev approved these changes

2022-07-20 20:20 UTC, merged