feat(applicationset): reuse repo-creds for an existing GitHub App
argoproj/argo-cd pull request #10092
Opened 2022-07-25 14:03 UTC by iamnoah

Closes #10079

Signed-off-by: Noah Perks Sloan <noah@hackedu.io>

2022-08-09 14:30 UTC, jetersen approved these changes
overall looks good to me.

I can wonder why there is almost no code reuse from the existing implementation for github app authentication or refactor of existing code.

Consider my comment nitpicking.

2022-08-09 20:32 UTC, crenshaw-dev requested changes
Looks like this will be a pretty awesome enhancement!

I think you might have started down the path of auto-discovering the repo creds. Did that end up not being a viable option?

2022-08-09 20:32 UTC, crenshaw-dev commented on applicationset/generators/scm_provider.go
> +			return nil, err
Can you wrap this error, and mention "SCM provider" in the message? Will just help identify the exact code hit.

2022-08-09 20:32 UTC, crenshaw-dev commented on applicationset/services/internal/github_app/client.go
> +func Client(g github_app_auth.Authentication, url string) (*github.Client, error) {
Could you wrap the two errors returned by this function?

2022-08-09 20:32 UTC, crenshaw-dev commented on applicationset/services/internal/github_app/client.go
> +		var err error
Can you reuse the previous declaration?

2022-08-09 20:32 UTC, crenshaw-dev commented on applicationset/services/internal/github_app/try.go
> +func Each[T any, R any](apps []One[T], f func(service T) (R, error)) (result R, err error) {
Is this an artifact of a previous iteration? Might just be GoLand, but as far as I can tell this is unused.

2022-08-09 20:32 UTC, crenshaw-dev commented on applicationset/services/pull_request/github_app.go
> +func NewGithubAppService(_ context.Context, g github_app_auth.Authentication, url, owner, repo string, labels []string) (PullRequestService, error) {
Can the unused context param just be dropped?

2022-08-09 20:45 UTC, iamnoah commented
> why there is almost no code reuse from the existing implementation for github app authentication

I went down this path and the answer is that after `ghinstallation.New`, the logic for checking out a repo vs. making API calls diverges significantly. repo-server uses the git protocol naturally, vs. REST for the GitHub API.

2022-08-09 20:53 UTC, iamnoah commented
> I think you might have started down the path of auto-discovering the repo creds. Did that end up not being a viable option?

I thought better of it for a few reasons: 1. You might want a different app to checkout code than the one that scans for PRs or branches. 2. If you had a credential you didn't expect to be used this way, consuming some rate limit and making unexpected calls just seems like a good way to freak people out.

2022-08-09 20:55 UTC, crenshaw-dev commented
@iamnoah makes sense. Did you find that there's something acting as a hard barrier to auto-discovery, or simply that it was too involved to tackle in this PR?

Just curious, in case someone decides to pick up auto-discovery in the future.

2022-08-09 21:03 UTC, jetersen commented
> I went down this path and the answer is that after ghinstallation.New, the logic for checking out a repo vs. making API calls diverges significantly. repo-server uses the git protocol naturally, vs. REST for the GitHub API.

Thanks for taking the time detailing it 👍 Makes sense.

2022-08-09 21:06 UTC, iamnoah commented
> Did you find that there's something acting as a hard barrier to auto-discovery, or simply that it was too involved to tackle in this PR?

No, I had some code that would inject the argocddb, try each credential, and note if there was a 401 then stopping using it for one hour. But I realized that PRs need a separate permission and felt like the unintended consequences were too great.

I would want auto-discovery to:
 * For PRs, first use the GitHub API to make sure the App has permission to read PRs
 * Load the organization(s) the App is valid for and match that up to the configuration (don't use a credential you know will fail)
 * Some sort of opt-in/out at in argocd-cm and per credential.
 * Maybe refuse to automatically use any app credentials if there are more than one that could work.
 * Optional: the ability to use multiple credentials.

2022-08-18 14:51 UTC, crenshaw-dev commented
@iamnoah do you have time to resolve conflicts?

2022-08-19 20:57 UTC, crenshaw-dev approved these changes
lgtm - thanks @iamnoah!

2022-08-19 20:57 UTC, merged