feat: add annotation to the custom namesapce
argoproj/argo-cd pull request #10221
Opened 2022-08-05 16:35 UTC by ashutosh16

Signed-off-by: Ashutosh <mail.ashutosh8@gmail.com>

TODO: add  unit test cases
Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-08-10 16:49 UTC, crenshaw-dev requested changes

2022-08-10 16:49 UTC, crenshaw-dev commented on pkg/apis/application/v1alpha1/types.go
>  		s := strings.Split(i, "=")
Could you do `strings.SplitN(i, "=", 2)` and add a test to make sure we allow annotations that contain `=` signs?

2022-08-11 08:20 UTC, closed without merging

2022-08-11 14:47 UTC, crenshaw-dev commented
@ashutosh16 looks like a merge went wrong?  :-)

2022-08-11 16:24 UTC, ashutosh16 commented
@crenshaw-dev  Was dabbling btw multiple branch. I'll raise new PR shortly