feat: add permitOnlyProjectScopedClusters flag
argoproj/argo-cd pull request #10237
Opened 2022-08-08 11:50 UTC by blakepettersson

This commit adds a new flag, `permitOnlyProjectScopedClusters`, which
prevents any application from syncing to clusters which are not a part
of the same project. Fixes #10220.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* ~[ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.~
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-08-08 13:08 UTC, blakepettersson commented on controller/appcontroller.go
> +				permitted, _ := proj.IsResourcePermitted(schema.GroupKind{Group: child.ResourceRef.Group, Kind: child.ResourceRef.Kind}, child.Namespace, a.Spec.Destination, func(project string) ([]*appv1.Cluste
I'm not a big fan of silencing errors, we should probably change the signature of `IterateHierarchy` to return an error itself

2022-08-08 13:09 UTC, blakepettersson commented on controller/appcontroller.go
> +				permitted, _ := proj.IsResourcePermitted(schema.GroupKind{Group: child.ResourceRef.Group, Kind: child.ResourceRef.Kind}, child.Namespace, a.Spec.Destination, func(project string) ([]*appv1.Cluste
Likewise, same as above

2022-08-08 13:09 UTC, blakepettersson commented on controller/state.go
> +			return m.db.GetProjectClusters(context.TODO(), project)
I added `context.TODO()` as a placeholder, but should probably be something else

2022-08-08 13:11 UTC, blakepettersson commented on controller/sync.go
> +					return m.db.GetProjectClusters(context.TODO(), project)
I added context.TODO() as a placeholder, but should probably be something else

2022-08-08 13:25 UTC, blakepettersson commented on controller/state.go
> +		if err != nil {
Not sure if this block is the right way to do this; I suspect that this also needs tests

2022-08-08 18:43 UTC, crenshaw-dev requested changes
Just a couple nitpicks. @alexmt would you have time to glance at this? I'm curious if you have any performance concerns.

2022-08-08 18:43 UTC, crenshaw-dev commented on pkg/apis/application/v1alpha1/app_project_types.go
> +			return false, err
Should this error be wrapped?

2022-08-08 18:43 UTC, crenshaw-dev commented on pkg/apis/application/v1alpha1/app_project_types.go
> +		// TODO: If no project clusters are found, return an error instead?
I feel like simply returning "not permitted" is probably sufficient.

2022-08-09 14:59 UTC, blakepettersson commented on pkg/apis/application/v1alpha1/app_project_types.go
> +			return false, err
👍

2022-08-09 16:03 UTC, crenshaw-dev commented
@blakepettersson we discussed this in today's [security meeting](https://docs.google.com/document/d/1nl1adCRf4tD87Y01i3JcrLcHvtm1O5a7slqzNstct94/edit#).

The conclusions were:
1) This PR does solve a problem 😄 
2) Users might be surprised that this behavior isn't the default (so it might be helpful to add a line in the project-scoped cluster docs saying "this feature enables _adding_ clusters, but it does not restrict which clusters may be used. To do that you need to use the destinations field or the permitOnlyProjectScopedClusters flag"
3) @jessesuen wanted to ponder the problem a bit more and see if he could think of a solution that doesn't require a new flag - will wait for his conclusion before merging
4) performance might be a concern, so Jesse and/or @alexmt should take a look

Thanks again for the good work! Assuming we conclude that the change is necessary/performant, I wanna be sure to get this into 2.5, so I'll be watching carefully.

2022-08-10 08:39 UTC, blakepettersson commented
Awesome! Looking forward to what you guys come up with! 😄 

> Users might be surprised that this behavior isn't the default 

I was one of them 😄

2022-08-10 13:14 UTC, crenshaw-dev commented
Looks like something set you up for a bunch of merge conflicts. Can you resolve? It'll probably be easiest to resolve conflicts for the non-generated files and then just run codegen again.

2022-08-19 15:43 UTC, crenshaw-dev commented
Discussed this in the Contributor office hours. @jessesuen and @alexmt are gonna chat about this and review.

2022-09-07 10:28 UTC, blakepettersson commented
@jessesuen @alexmt @crenshaw-dev do you guys have any further thoughts on this PR? :smile:

2022-09-07 13:08 UTC, crenshaw-dev approved these changes
LGTM - will leave this open in case Jesse or Alex have any thoughts, but I'll merge it by the end of the week if not.

2022-09-08 11:33 UTC, merged

2022-09-08 11:38 UTC, blakepettersson commented
Awesome, thanks a lot!! :hugs: :hugs: