chore: add security logging and cve fields
argoproj/argo-cd pull request #10256
Opened 2022-08-09 17:58 UTC by notfromstatefarm

As discussed with the security SIG, this PR implements a `security` and `cve` field to be used in logs and standardizes which level should be used. Obviously there is much more work to be done as I have only added this to a couple of logs, but this lays the foundations so that hopefully we can cover a good amount of ground in separate PRs by the v2.5 release.

This will be 'good first issue' heaven. :shipit: 

Proposed levels:
| Level | Friendly Level | Description                                                                                       | Example                                     |
|-------|----------------|---------------------------------------------------------------------------------------------------|---------------------------------------------|
| 1     | Low            | Unexceptional, non-malicious events                                                               | Successful access                           |
| 2     | Medium         | Could indicate malicious events, but has a high likelihood of being user/system error             | Access denied                               |
| 3     | High           | Likely malicious events but one that had no side effects or was blocked                           | Out of bounds symlinks in repo              |
| 4     | Critical       | Any malicious or exploitable event that had a side effect                                         | Secrets being left behind on the filesystem |
| 5     | Emergency      | Unmistakably malicious events that should NEVER occur accidentally and indicates an active attack | Brute forcing of accounts                   |

cc @crenshaw-dev @jessesuen @todaywasawesome

2022-08-09 20:35 UTC, crenshaw-dev requested changes

2022-08-09 20:35 UTC, crenshaw-dev commented on common/common.go
> +	SecurityCWEField  = "cwe"
Tiny nitpick: maybe capitalize this to make it just a tiny bit clearer at a glance that it's an acronym?

2022-08-09 20:35 UTC, crenshaw-dev commented on docs/operator-manual/security.md
> +Please be aware that all security logs are not comprehensively tagged yet and these examples are not necessarily implemented.
Could you put this in a `!!! warning` block just to draw a bit more attention? You can test with `make serve-docs-local`.

2022-08-11 00:56 UTC, crenshaw-dev approved these changes
I'm in favor of the changes as presented. Thanks @notfromstatefarm!

2022-08-11 20:21 UTC, notfromstatefarm commented
Here's a flowchart on how to decide which level to use. Do you think we should include this in the docs @crenshaw-dev ?
![Security flowchart](https://user-images.githubusercontent.com/86763948/184235120-cd1bf2e4-d337-4c7d-b933-fac981fde799.png)

2022-08-12 15:59 UTC, crenshaw-dev commented
@notfromstatefarm I like that! The phrase "has a vulnerability been exposed" seems slightly ambiguous to me though. I'm not sure whether there's a succinct way to clarify.

2022-08-17 13:32 UTC, crenshaw-dev commented
![Ariana Grande singing "I see it, I like it, I want it, I got it"](https://user-images.githubusercontent.com/350466/185146936-2632be3d-37ee-446b-9126-0c07b0ed949e.gif)

2022-08-17 13:32 UTC, merged