fix: respect ARGOCD_GIT_MODULES_ENABLED in the appset controller (#10285)
argoproj/argo-cd pull request #10287
Opened 2022-08-11 20:11 UTC by crenshaw-dev

Fixes #10285

2022-08-11 20:29 UTC, notfromstatefarm requested changes
LGTM other than doubled up `StringVar`

2022-08-11 20:29 UTC, notfromstatefarm commented on cmd/argocd-applicationset-controller/commands/applicationset_controller.go
> +	command.Flags().StringVar(&logFormat, "logformat", "text", "Set the logging format. One of: text|json")
doubled up on this line somehow?

2022-08-11 22:19 UTC, crenshaw-dev commented on cmd/argocd-applicationset-controller/commands/applicationset_controller.go
> +	command.Flags().StringVar(&logFormat, "logformat", "text", "Set the logging format. One of: text|json")
Oops! Fixed

2022-08-12 18:28 UTC, alexmt approved these changes
Looks good!

2022-08-12 18:37 UTC, merged

2022-08-12 18:47 UTC, crenshaw-dev commented
Cherry-picked onto release-2.4 for 2.4.10.