feat: add prompting to confirm remove of cluster resources
argoproj/argo-cd pull request #10319
Opened 2022-08-13 08:55 UTC by my-git9

Add prompting to confirm remove of cluster resources

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-08-13 09:05 UTC, my-git9 commented
The test result:
```shell
$ ./argocd cluster rm test
Are you sure you want to remove 'test' and all its resources? [y/n] y
Cluster 'test' removed
INFO[0002] ClusterRoleBinding "argocd-manager-role-binding" deleted
INFO[0003] ClusterRole "argocd-manager-role" deleted
INFO[0003] ServiceAccount "argocd-manager" deleted
```
```shell
$ ./argocd cluster rm test -y
Cluster 'test' removed
INFO[0000] ClusterRoleBinding "argocd-manager-role-binding" deleted
INFO[0001] ClusterRole "argocd-manager-role" deleted
INFO[0001] ServiceAccount "argocd-manager" deleted
```
```shell
$ ./argocd cluster rm test local
Are you sure you want to remove 'test' and all its resources? [y/n/A] where 'A' is to remove all specified apps and their resources without prompting A
Cluster 'test' removed
INFO[0002] ClusterRoleBinding "argocd-manager-role-binding" deleted
INFO[0003] ClusterRole "argocd-manager-role" deleted
INFO[0003] ServiceAccount "argocd-manager" deleted
Cluster 'local' removed
INFO[0003] ClusterRoleBinding "argocd-manager-role-binding" deleted
INFO[0004] ClusterRole "argocd-manager-role" deleted
INFO[0004] ServiceAccount "argocd-manager" deleted
```

2022-08-16 12:57 UTC, my-git9 commented
/cc @crenshaw-dev Hi, can you help me review this PR? Thanks

2022-08-18 14:36 UTC, crenshaw-dev reviewed
I'm actually unfamiliar with the effects of deleting a cluster. Does it actually delete all the apps and their resources if they're deployed to that cluster? Or does it just cause those apps to go into "unknown" sync status and health?

2022-08-18 15:00 UTC, my-git9 commented
> I'm actually unfamiliar with the effects of deleting a cluster. Does it actually delete all the apps and their resources if they're deployed to that cluster? Or does it just cause those apps to go into "unknown" sync status and health?

I tested it, it  cause those apps to go into "unknown" sync status and health:
```shell
$ argocd cluster rm https://10.29.12.61:16443
Cluster 'https://10.29.12.61:16443' removed
# this will hang
$ argocd app sync guest2
TIMESTAMP                  GROUP        KIND   NAMESPACE                  NAME    STATUS   HEALTH        HOOK  MESSAGE
2022-08-18T22:51:17+08:00            Service     default          guestbook-ui    Synced  Healthy
2022-08-18T22:51:17+08:00   apps  Deployment     default          guestbook-ui    Synced  Healthy
^C
# the apps go into "unknown" sync status and health
$ argocd app list
NAME            CLUSTER                         NAMESPACE  PROJECT  STATUS     HEALTH       SYNCPOLICY  CONDITIONS        REPO                                                  PATH            TARGET
guest2          https://10.29.12.61:16443       default    default  Unknown    Unknown      <none>      InvalidSpecError  https://gitlab.daocloud.cn/xin.li/argocd-example.git  guestbook
```

2022-08-18 15:03 UTC, crenshaw-dev requested changes

2022-08-18 15:03 UTC, crenshaw-dev commented on cmd/argocd/commands/cluster.go
> +						lowercaseAnswer = cli.AskToProceedS("Are you sure you want to remove '" + clusterSelector + "' and all its resources? [y/n] ")
How about "Are you sure you want to remove 'cluster'? Any Apps deploying to this cluster will go to health status Unknown."

2022-08-18 15:03 UTC, crenshaw-dev commented on cmd/argocd/commands/cluster.go
> +							lowercaseAnswer = cli.AskToProceedS("Are you sure you want to remove '" + clusterSelector + "' and all its resources? [y/n/A] where 'A' is to remove all specified apps and their resources with
Similar prompt change to above.

2022-08-19 15:41 UTC, crenshaw-dev approved these changes
lgtm!

2022-08-19 15:42 UTC, merged