docs: proposal to merge image-updater into argo-cd
argoproj/argo-cd pull request #10447
Opened 2022-08-24 18:37 UTC by jaideepr97

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-09-08 13:12 UTC, jaideepr97 commented
@alexmt @leoluz 
I updated this with the discussion points from the community meeting when I proposed it
could we merge this?

2022-09-08 14:53 UTC, leoluz commented
@jaideepr97 Please avoid force-pushing once the PR is out as now I can't see what was added in the proposal since our last conversation.
Can you please point me to what was updated?

2022-11-04 19:25 UTC, NickLarsenNZ commented
@leoluz, IMO force-pushes (eg: after a rebase) are a good thing, to keep the commit history clean.

Github shows the changes since what you last see (see the Compare buttons below):

<img width="1086" alt="image" src="https://user-images.githubusercontent.com/10092581/200058866-3204656c-4791-4fd8-855a-59f1fd89dc4b.png">

2022-11-04 19:31 UTC, leoluz commented
> @leoluz, IMO force-pushes (eg: after a rebase) are a good thing, to keep the commit history clean.
> 
> Github shows the changes since what you last see (see the Compare buttons below):

@NickLarsenNZ If you click the compare button you get the message:

`There isn’t anything to compare.`

Also, all my previous comments aren't visible in the diff page anymore. Just in the conversation timeline which is far from ideal.

Commit history in the PR branch doesn't matter that much. When we merge the PR into master is the right moment to squash and merge to have a clean timeline.

2022-11-04 20:32 UTC, NickLarsenNZ commented
@leoluz 

> There isn’t anything to compare.

Yes I saw that on one of the changes. It just means it had been rebased (or commit messages changed) so commit IDs are now different, but no actual change since the last time you saw (so ignorable in that case).

> Also, all my previous comments aren't visible in the diff page anymore. Just in the conversation timeline which is far from ideal.

From what I understand, comments in the diffs are bound to the commit IDs which are subject to change on non trunk (master) branches (like in this case). I think a better place to put comments are in the Review which will then show up in the PR (even once outdated).

> When we merge the PR into master is the right moment to squash and merge to have a clean timeline.

That might be true for this particular case, but many times the contributor wants to pull in changes from the trunk (master) so it should probably be tolerated, if not expected.

---

I hope this covers your concerns. I think we should be making contribution easy, and I know many of us are looking forward to the image updater being merged into the main argo-cd repo.

2022-11-29 18:29 UTC, katainaka0503 commented
@jaideepr97 Any update?

2022-12-21 20:36 UTC, jaideepr97 commented
Hi all, sorry for the delay on this
Just wanted to update here, you can find the follow up proposal [here](https://github.com/argoproj/argo-cd/pull/11787)

2023-11-06 11:07 UTC, Jojoooo1 commented
Awesome work! Any targeted release ?

2024-01-07 15:22 UTC, Guy-Rom commented
Hi, is there ETA?
Any chance to add it as 2.10 target?

2024-05-09 17:16 UTC, brjadams commented
What is happening with this?

2024-05-10 22:32 UTC, todaywasawesome requested changes
For this proposal to move forward I think it needs a lot more support. The main issue with Image Updater right now is that it doesn't have enough maintainers working on it. We're working on cutting a new release as there hasn't been one in over a year. 

If there are more people that support this, now is the time to chip in and help, and show your support.

2025-02-28 10:19 UTC, closed without merging

2025-02-28 13:42 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.