fix: Remove quotes from delete dialog #10008
argoproj/argo-cd pull request #10471
Opened 2022-08-29 07:44 UTC by JessieTeng89

fix: Remove quotes from delete dialog #10008
Fixes #10008

2022-08-29 19:16 UTC, ashutosh16 commented on ui/src/app/applications/components/utils.tsx
> +                        <FormField label={`Please type <kbd>${resource.name}</kbd> to confirm the deletion of the resource`} formApi={api} field='resourceName' component={Text} />
The HTML tag should not be displayed in the dialog box, not sure if this is intentional
![Screen Shot 2022-08-29 at 12 06 19 PM](https://user-images.githubusercontent.com/11219262/187278752-82aa9087-21d0-46e0-a6bf-6503f27e8328.png)

2022-08-30 12:18 UTC, jsoref commented
Could you provide a picture of the dialog?

2022-08-30 13:25 UTC, JessieTeng89 commented
> Could you provide a picture of the dialog?

Please find the screenshots for the current changes:
<img width="1003" alt="image" src="https://user-images.githubusercontent.com/101035990/187448198-6256e008-77ad-4295-aa3d-b9b5160cd4a4.png">
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/101035990/187448450-73fe53bf-1b43-4eee-ae5f-3ed53d00f2e2.png">
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/101035990/187448736-7607b27b-e174-4bc5-8e87-969f1ab2ba2a.png">

2022-08-30 13:57 UTC, jsoref approved these changes

2022-08-31 14:48 UTC, JessieTeng89 commented
@rbreeze Can I request your approval? So that we can merge it, or I appreciate with your any comments

2022-08-31 15:00 UTC, rbreeze requested changes
`<kbd>` is intended for keyboard input, could we use `<pre>` instead?

2022-08-31 15:15 UTC, JessieTeng89 commented
> `<kbd>` is intended for keyboard input, could we use `<pre>` instead?

I tried to use `<pre>` instead, we need to add a css style like `display: inline-block` as this tag is a block-level element.

And you can see the change and the style in following screenshot, if it is OK for you, I can do the change
<img width="1367" alt="image" src="https://user-images.githubusercontent.com/101035990/187714821-9144e01d-9518-4735-b3d2-f56d1e7eb839.png">

2022-08-31 15:34 UTC, rbreeze approved these changes
let’s stick with `kbd`

2022-09-01 12:53 UTC, JessieTeng89 commented
> let’s stick with `kbd`

Hi @jsoref @rbreeze Can I know how to merge it, it seems I cannot do that even its status is ready

2022-09-01 13:19 UTC, jsoref commented
Someone with the ability to merge will manage that (it isn't me and it isn't you).

2022-09-01 14:35 UTC, merged