fix: add more info to  creationtime format
argoproj/argo-cd pull request #10493
Opened 2022-09-01 06:04 UTC by ashutosh16

Signed-off-by: Ashutosh <mail.ashutosh8@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-09-06 22:04 UTC, ashutosh16 commented
![Screen Shot 2022-09-06 at 3 01 15 PM](https://user-images.githubusercontent.com/11219262/188748600-62d5833b-6047-48f8-b62f-caa9047cbe64.png)

2022-09-07 18:38 UTC, ashutosh16 commented on ui/src/app/applications/components/application-summary/application-summary.tsx
> -import {ApplicationSyncOptionsField, REPLACE_WARNING} from '../application-sync-options/application-sync-options';
Removed the `REPLACE_WARNING`  as it no longer used in the code.

2022-09-07 18:40 UTC, ashutosh16 commented
@rbreeze  Would you be able to review the code? Changes are related to UI polish no functional change.

2022-09-08 02:32 UTC, rbreeze requested changes, later dismissed
LGTM after changing type `any`

2022-09-08 02:32 UTC, rbreeze commented on ui/src/app/applications/components/utils.tsx
> +export function formatCreationTimestamp(creationTimestamp: any) {
Can we avoid using type `any` here?

2022-09-09 16:41 UTC, crenshaw-dev approved these changes
Looks great, thanks @ashutosh16!

2022-09-09 16:41 UTC, merged