Fix Broken Link in Getting Started Docs
argoproj/argo-cd pull request #10585
Opened 2022-09-13 23:21 UTC by gknoblauch

Signed-off-by: Greg Knoblauch <knoblauch.greg@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-09-14 19:37 UTC, ashutosh16 requested changes

2022-09-14 19:37 UTC, ashutosh16 commented on docs/getting_started.md
> +* Follow the [instructions to configure a certificate](operator-manual/tls) (and ensure that the client OS trusts it).
```suggestion
* Follow the [instructions to configure a certificate](operator-manual/tls.md) (and ensure that the client OS trusts it).
```

2022-09-14 21:49 UTC, ashutosh16 approved these changes

2022-09-15 12:08 UTC, crenshaw-dev approved these changes
Thanks @gknoblauch!

2022-09-15 12:08 UTC, merged

2022-09-15 12:08 UTC, crenshaw-dev commented
Cherry-picked onto release-2.4 for 2.4.12.