updated dex image tag to add ppc64le support
argoproj/argo-cd pull request #10617
Opened 2022-09-16 15:09 UTC by mayurwaghmode

Signed-off-by: mayurwaghmode<waghmodemayur17@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-09-16 15:29 UTC, crenshaw-dev requested changes

2022-09-16 16:54 UTC, 34fathombelow commented
@crenshaw-dev please see https://github.com/dexidp/dex/pull/2352 &  https://github.com/dexidp/dex/issues/2613.  Dexv2.33 introduced some changes to gitlab tokens, can we verify this will not effect our users.

2022-09-16 17:08 UTC, mayurwaghmode commented on manifests/base/dex/argocd-dex-server-deployment.yaml
> +        image: ghcr.io/dexidp/dex:v2.34.0
yes, it is there. Let me modify it :)

2022-09-16 17:09 UTC, crenshaw-dev commented
@34fathombelow ah yep I think you'd mentioned this before, and I forgot. Taking a look...

2022-09-16 17:23 UTC, mayurwaghmode commented on manifests/base/dex/argocd-dex-server-deployment.yaml
> +        image: ghcr.io/dexidp/dex:v2.34.0
@crenshaw-dev I have updated it with distroless image tag

2022-09-18 00:26 UTC, crenshaw-dev commented
I'm hesitant to merge until I understand the Dex bug better or until a fix is merged. Not sure if I'll have time to investigate before 2.5.

The good news is, it's fairly easy for folks to override the tag for that image and run the newer Dex version if they're not worried about the bug @34fathombelow linked.

2022-10-03 21:16 UTC, 34fathombelow commented
@mayurwaghmode Argo CD 2.4.13 now uses dex:v2.35.0 which will support ppc64le. :)

2022-10-03 21:18 UTC, closed without merging

2022-10-04 09:11 UTC, mayurwaghmode commented
> @mayurwaghmode Argo CD 2.4.13 now uses dex:v2.35.0 which will support ppc64le. :)

Thank you @34fathombelow 💯