fix pod portforward
argoproj/argo-cd pull request #10699
Opened 2022-09-25 15:26 UTC by cleverhu

Fixes: https://github.com/argoproj/argo-cd/issues/10610

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-09-27 00:35 UTC, ashutosh16 approved these changes
LGTM!

2022-10-07 19:47 UTC, crenshaw-dev requested changes
@cleverhu looks great! Can you add a unit test? I know testing commands is a little tricky, but [cobra provides some nice testing utils](https://gianarb.it/blog/golang-mockmania-cli-command-with-cobra).

2022-10-07 19:48 UTC, crenshaw-dev commented
Ah, and this isn't even in a command. You can test the function with just a few mocks.

2022-10-08 06:51 UTC, cleverhu commented
> 

I find it difficult to cover this through unit testing. I think it  should be covered by e2e.

2022-10-08 06:52 UTC, cleverhu commented
> @cleverhu looks great! Can you add a unit test? I know testing commands is a little tricky, but [cobra provides some nice testing utils](https://gianarb.it/blog/golang-mockmania-cli-command-with-cobra).

I find it difficult to cover this through unit testing.And I think it should be covered by e2e.

2023-03-30 23:23 UTC, jbury commented
@cleverhu Are you still planning on driving this?  It's currently a painpoint for me, though I likely won't be able to work on this for at least a month or two.

2023-04-11 08:33 UTC, cleverhu commented
> @cleverhu Are you still planning on driving this? It's currently a painpoint for me, though I likely won't be able to work on this for at least a month or two.

I’m sorry that the e2e is difficulty for me.

2025-02-28 10:20 UTC, closed without merging

2025-02-28 13:42 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.