chore: Upgrade shipped version of Redis to 7.0.5 to fix CVE-2022-35951
argoproj/argo-cd pull request #10702
Opened 2022-09-26 06:50 UTC by jannfis

Update shipped version of Redis to 7.0.5 to fix CVE-2022-35951

CVE only affects Redis version >7.0.0, so this only needs to be cherry-picked into release-2.4, as other Argo CD versions do not yet ship 7.x versions of Redis.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-09-26 14:19 UTC, 34fathombelow requested changes
We also need to update redis in ```.github/workflows/CI-build.yaml``` L#411

If you don't mind while your in there I just noticed dex also needs to be updated on L#409.   If you feel that we should open a separate PR for this, im more than happy to take care of it.

2022-09-26 17:55 UTC, jannfis commented
Good catch, @34fathombelow, thanks.

I've updated the images in the CI workflow.

2022-09-26 18:29 UTC, 34fathombelow approved these changes
LGTM!

2022-09-30 23:06 UTC, crenshaw-dev approved these changes
lgtm!

2022-10-01 00:17 UTC, merged

2023-01-10 15:45 UTC, crenshaw-dev commented
Looks like I forgot to cherry-pick this? Anyway, it's now on release-2.4 for 2.4.19.