Change git fetch to prune on every call to fix issue #10664
argoproj/argo-cd pull request #10761
Opened 2022-10-01 23:37 UTC by ADustyOldMuffin

This should clean up any old branches and save on disk space, and fix any errors around bad branch names.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
    - (b) bug fix
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
    - Nothing to change
* [x] Does this PR require documentation updates?
    - I don't think so.
* [x] I've updated documentation as required by this PR.
    - N/A
* [x] Optional. My organization is added to USERS.md.
    - Not at this time
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
    - Tests for this case are already written, but git error message was different. Existing test should still work/pass for this.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-10-01 23:56 UTC, crenshaw-dev requested changes
@ADustyOldMuffin do you think you can design a unit test to demonstrate that this change works? Might be able to use a local directory as the "remote" for a git repo.

2022-10-02 00:03 UTC, ADustyOldMuffin commented
I can add more tests if needed, I was hoping these tests added with the [previous chang](https://github.com/argoproj/argo-cd/pull/9504/files#diff-a7b72b46e16649a80020d533dac6c2c4ed5bbc2dc72852f43a44e01037c48b55)e would cover this change as well to ensure we're also still fixing the previous issue.

2022-10-02 00:21 UTC, crenshaw-dev commented
Yeah, I woulda hoped those tests would have caught this as well. But they must be insufficient, since you're still hitting the `cannot lock ref` error. I wonder under what conditions one of those error messages is produced vs. the other.

2022-10-02 00:22 UTC, ADustyOldMuffin commented
I took a second look and I don't believe those tests actually covered anything since the fetch is being ran in the same local repo. I'll write some tests that add a local remote and actually attempt to fetch.

2022-10-02 14:22 UTC, ADustyOldMuffin commented
@crenshaw-dev I removed the prune and walked through the tests and it throws the same error we had in the issue, but ours didn't include the magic words.

I did some digging and found a multitude of [errors](https://stackoverflow.com/questions/2998832/git-pull-fails-unable-to-resolve-reference-unable-to-update-local-ref) that require pruning to remove the error and some of them having the same messaging but the `try running 'git remote prune origin'` messaging being inconsistent. I'm willing to change back, but I'd vote to prune by default to remove the possibility of hitting any of them.

2022-10-03 13:33 UTC, crenshaw-dev approved these changes
Thanks @ADustyOldMuffin!

2022-10-03 13:33 UTC, merged

2022-10-03 13:34 UTC, crenshaw-dev commented
If we want to consider cherry-picking this back, I think we'll want some metrics demonstrating that there's no performance regression. Maybe the initial tests you did would be sufficient, but it would be nice to have some stats for this code running in a live instance.