Wrap error objects to include context
argoproj/argo-cd pull request #10859
Opened 2022-10-08 17:18 UTC by nirsht

Signed-off-by: Nir Shtein <89006520+nirsht@users.noreply.github.com>

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-10-08 17:18 UTC, nirsht commented
This PR is related to this issue https://github.com/argoproj/argo-cd/issues/10592

2022-10-08 19:02 UTC, crenshaw-dev requested changes
Wording nitpicks.  :-)

2022-10-08 19:02 UTC, crenshaw-dev commented on cmd/argocd/commands/admin/cluster.go
> +							return fmt.Errorf("error updating cluster, cluster name: %s, err: %w", cluster.Name, err)
```suggestion
							return fmt.Errorf("error updating cluste: %w", err)
```

2022-10-08 19:02 UTC, crenshaw-dev commented on cmd/argocd/commands/app.go
> +					return fmt.Errorf("error unmarshal input into updatedSpec: %w", err)
```suggestion
					return fmt.Errorf("error unmarshaling input into application spec: %w", err)
```

2022-10-08 19:02 UTC, crenshaw-dev commented on cmd/argocd/commands/project.go
> +					return fmt.Errorf("error unmarshal input into updatedSpec: %w", err)
```suggestion
					return fmt.Errorf("error unmarshaling input into application spec: %w", err)
```

2022-10-08 19:02 UTC, crenshaw-dev commented on cmd/argocd/commands/project.go
> +					return fmt.Errorf("could not get project by project name, projName: %s, err: %w", projName, err)
```suggestion
					return fmt.Errorf("could not get project by project name: %w", err)
```

The project name was user input, so no need to echo it back.

2022-10-09 16:13 UTC, crenshaw-dev approved these changes
lgtm, thanks @nirsht!

2022-10-09 16:13 UTC, merged