Change ApplicationSpec equal
argoproj/argo-cd pull request #10866
Opened 2022-10-08 22:28 UTC by nirsht

This is related to this issue https://github.com/argoproj/argo-cd/issues/10063.

This error was created due to poor compare of apps Spec's. 

In this PR I change the compare from reflect.DeepEqual to compare each property properly.
The `Destination` weren't equal because we didn't use their compare function - https://github.com/argoproj/argo-cd/blob/41d4ce6fa4820f8790396fc2164b7d75e9139a8e/pkg/apis/application/v1alpha1/types.go#L2283

2022-10-09 01:33 UTC, crenshaw-dev requested changes

2022-10-09 01:33 UTC, crenshaw-dev commented on pkg/apis/application/v1alpha1/types.go
> +func (spec ApplicationSpec) Equals(other ApplicationSpec) bool {
Can you add unit tests to demonstrate the issue and prove the solution?

We might also want to make a note on the ApplicationSpec struct that whenever a field is added, you. gotta update this function.

2024-05-16 17:34 UTC, pasha-codefresh commented
@nirsht are you going to work on it?

2024-09-04 07:30 UTC, closed without merging

2024-09-04 07:30 UTC, pasha-codefresh commented
Closing due no response