feat(kustomize): override namespace (#6067)
argoproj/argo-cd pull request #10872
Opened 2022-10-10 10:06 UTC by AndrewChubatiuk

Fixes #6067

2022-10-10 18:35 UTC, crenshaw-dev commented
@AndrewChubatiuk this is awesome! Care to take a crack at UI/CLI support? If not, we can plan to write a follow-up issue for those.

2022-10-11 12:35 UTC, crenshaw-dev requested changes

2022-10-11 12:35 UTC, crenshaw-dev commented on docs/user-guide/commands/argocd_app_set.md
> +      --kustomize-namespace string                 Kustomize namespace
Do you have time to add the corresponding `argocd app unset` parameter?

2022-10-11 13:11 UTC, crenshaw-dev requested changes
Looks amazing. One last nitpick.

I'm also going to look at the original issue to see if there are any common use cases we should document. But otherwise lgtm.

2022-10-11 13:11 UTC, crenshaw-dev commented on pkg/apis/application/v1alpha1/types.go
> +	// Namespace overrides Kustomize namespace
```suggestion
	// Namespace sets the namespace that Kustomize adds to all resources
```

I think this is slightly more clear?

2022-10-11 13:22 UTC, crenshaw-dev commented
What do you think of adding a new section at the bottom of kustomize.md?

> ### Setting the manifests' namespace
> 
> The `spec.destination.namespace` field only adds a namespace when it's missing from the manifests generated by Kustomize. It also uses `kubectl` to set the namespace, which sometimes misses namespace fields in certain resources (for example, custom resources). In these cases, you might get an error like this: `ClusterRoleBinding.rbac.authorization.k8s.io "example" is invalid: subjects[0].namespace: Required value`.
> 
> Using Kustomize directly to set the missing namespaces can resolve this problem. Setting `spec.source.kustomize.namespace` instructs Kustomize to set namespace fields to the given value. 
> 
> If `spec.destination.namespace` and `spec.source.kustomize.namespace` are both set, Argo CD will defer to the latter, the namespace value set by Kustomize.

2022-10-13 00:05 UTC, ishitasequeira approved these changes
LGTM!!

2022-10-14 18:48 UTC, crenshaw-dev requested changes
@AndrewChubatiuk if I set just `kustomize.namespace` in the `Manifest` tab of the Application Details pane, the entire `kustomize` block gets deleted. I see you updated `IsZero`, so I'm not sure why this is happening.  :-(

2023-02-08 20:01 UTC, crenshaw-dev commented
@AndrewChubatiuk Intuit is going to give me time to make sure this gets into 2.7. I'll circle back when it gets added to my sprint, sometime in the next ~1mo. Thanks for your patience!

2023-03-09 19:58 UTC, crenshaw-dev commented
@AndrewChubatiuk I finally have time. :-) Can you resolve conflicts? If you don't have time, I'll see if GitHub will let me push to your branch.

2023-03-09 20:23 UTC, crenshaw-dev commented
I think I managed to rebase.

2023-03-09 20:34 UTC, crenshaw-dev commented on Makefile
> +codegen-local: ensure-gopath mod-vendor-local gogen protogen clientgen openapigen clidocsgen manifests-local
```suggestion
codegen-local: ensure-gopath mod-vendor-local notification-docs notification-cataloggogen protogen clientgen openapigen clidocsgen manifests-local
```

2023-03-09 20:34 UTC, crenshaw-dev commented on Makefile
> +codegen-local: ensure-gopath mod-vendor-local notification-docs notification-cataloggogen protogen clientgen openapigen clidocsgen manifests-local
```suggestion
codegen-local: ensure-gopath mod-vendor-local notification-docs notification-catalog gogen protogen clientgen openapigen clidocsgen manifests-local
```

2023-03-09 20:37 UTC, crenshaw-dev approved these changes
Thanks for your work and for your patience, @AndrewChubatiuk!

2023-03-10 17:20 UTC, merged

2023-05-06 15:55 UTC, snarlysodboxer commented
@AndrewChubatiuk Awesome work on this, thank you!! This allows us to remove a ton of complexity in our configs. :)