chore: improve log in argo-cd/applicationset/generators/generator_spec_processor.go
argoproj/argo-cd pull request #10906
Opened 2022-10-12 02:50 UTC by karengineering

Signed-off-by: Karengineering <49111213+karengineering@users.noreply.github.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-10-12 13:37 UTC, crenshaw-dev requested changes

2022-10-12 13:38 UTC, crenshaw-dev commented on applicationset/generators/generator_spec_processor.go
> +		return nil, fmt.Errorf("error transforming spec generator: %w", err)
```suggestion
		return nil, fmt.Errorf("error parsing label selector: %w", err)
```

I think this is a bit more specific to the error being throw.

2022-10-13 01:49 UTC, karengineering commented on applicationset/generators/generator_spec_processor.go
> +		return nil, fmt.Errorf("error transforming spec generator: %w", err)
updated

2022-10-13 21:19 UTC, crenshaw-dev approved these changes
Thanks, @karengineering!

2022-10-13 21:26 UTC, merged