chore: improve error logs
argoproj/argo-cd pull request #10944
Opened 2022-10-14 12:36 UTC by smriti0710

Note on DCO:

This PR is related to this issue https://github.com/argoproj/argo-cd/issues/10592

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-10-15 06:35 UTC, smriti0710 commented
@crenshaw-dev please review. Thanks.

2022-10-18 13:12 UTC, crenshaw-dev requested changes
Wording and format tweaks. Thanks!

2022-10-18 13:12 UTC, crenshaw-dev commented on cmd/argocd/commands/admin/app.go
> +			return fmt.Errorf("error marshalling yaml file %w", err)
```suggestion
			return fmt.Errorf("error marshalling yaml: %w", err)
```

2022-10-18 13:12 UTC, crenshaw-dev commented on cmd/argocd/commands/admin/app.go
> +			return fmt.Errorf("error marshalling json file  %w", err)
```suggestion
			return fmt.Errorf("error marshalling json: %w", err)
```

2022-10-18 13:12 UTC, crenshaw-dev commented on cmd/argocd/commands/admin/generatespec_utils.go
> +			return fmt.Errorf("error printing the json file %w", err)
```suggestion
			return fmt.Errorf("error marshaling json: %w", err)
```

2022-10-18 13:12 UTC, crenshaw-dev commented on cmd/argocd/commands/admin/generatespec_utils.go
> +			return fmt.Errorf("error printing the yaml file %w", err)
```suggestion
			return fmt.Errorf("error marshaling yaml: %w", err)
```

2022-10-18 15:16 UTC, crenshaw-dev approved these changes
lgtm, thanks @smriti0710!

2022-10-18 15:16 UTC, merged