fix: add check for trailing/leading whitespace in project role group names (#10919)
argoproj/argo-cd pull request #10988
Opened 2022-10-18 22:00 UTC by FerencoVonMatterhorn

Fixes [ISSUE #10919]
instead of changing the user's config without their knowledge and potentially causing cascading errors, i think it would be nicer to alert the user with an error that their group name contains trailing/leading whitespaces. 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-10-19 14:12 UTC, crenshaw-dev requested changes

2022-10-19 20:26 UTC, FerencoVonMatterhorn commented
@crenshaw-dev do you think the failed tests are coming from my change or is it a general jobs problem?

2022-11-09 18:10 UTC, blakepettersson commented
I think this is a general e2e test error

2022-11-11 10:13 UTC, alexef approved these changes

2022-11-11 11:08 UTC, blakepettersson approved these changes

2022-11-14 13:27 UTC, crenshaw-dev approved these changes
Thanks @FerencoVonMatterhorn!

2022-11-14 13:28 UTC, merged