feat: Tweak the pod logs viewer
argoproj/argo-cd pull request #11030
Opened 2022-10-21 19:00 UTC by alexec

2022-10-25 19:23 UTC, tooptoop4 commented
'Show the first 4 characters of the container name.' - what if 2 containers start with same prefix? current behavior of full name is handy

2022-11-21 16:50 UTC, alexec commented
@rbreeze bump!

2022-12-01 17:08 UTC, alexec commented
@rbreeze bump!

2023-02-10 17:17 UTC, alexec commented
@michael12312 how do I escalate this PR? It's a small(ish) change. It is isolated to one part of the code. It'll make a big improvement is allow you to debug problems using Argo CD. 

The current log viewer is nearly unusable.

2023-02-18 01:30 UTC, alexec commented
Don't merge. Need to figure out what to do with the performance issue when many log lines.

2023-02-18 22:15 UTC, alexec commented
@crenshaw-dev @rbreeze ready for review again.

2023-02-22 22:39 UTC, crenshaw-dev requested changes, later dismissed
1. "show pod name" does not work for me - I get a blank column instead of pod names
2. I find it really difficult to know if a button is "enabled" or "disabled" - introduce check boxes?
3. I don't think the "ERROR" button is helpful - it's easy enough to just type it

Otherwise, I think this is a _huge_ improvement.

2023-02-23 00:00 UTC, alexec commented
> 1. "show pod name" does not work for me - I get a blank column instead of pod names

It is probably there, but it only shows the pod name at the pod of the column, otherwise white-space. When you only have a single pod, and you're in follow mode you likely won't see it.

![image](https://user-images.githubusercontent.com/1142830/220783131-c584b432-5deb-4b10-8f65-6d9a754e91c9.png)

> 2. I find it really difficult to know if a button is "enabled" or "disabled" - introduce check boxes?

![image](https://user-images.githubusercontent.com/1142830/220791480-1d5fde8e-74a4-430c-87c0-d7643ab88ab5.png)

> 3. I don't think the "ERROR" button is helpful - it's easy enough to just type it

Removed.

> Otherwise, I think this is a _huge_ improvement.

Thanks

2023-02-23 15:19 UTC, crenshaw-dev commented
How difficult would it be to re-enable color handling in the logs? 
![image](https://user-images.githubusercontent.com/350466/220949205-b8db98b5-23fc-4ffb-b1ef-88906452bc69.png)

2023-02-23 15:25 UTC, crenshaw-dev commented
I'm not sure the search box makes sense for these three controls. 
![image](https://user-images.githubusercontent.com/350466/220951309-d47a04a9-9e41-4a89-9591-1d2de32de53d.png)

Even if it does make sense for the container dropdown, I think it should be hidden when there's only one container.

2023-02-23 18:53 UTC, alexec commented
- Fixed colors.
- Changed the auto-completes into vanilla selects.

2023-02-23 18:58 UTC, alexec commented
<img width="723" alt="image" src="https://user-images.githubusercontent.com/1142830/221004211-656acd4c-6645-459c-a494-038423246c9b.png">

2023-03-01 22:20 UTC, alexec commented
7 days from chatting with Jesse would be 4:30pm tomorrow.

2023-03-03 18:40 UTC, crenshaw-dev commented
@jessesuen @rbreeze are y'all in alignment that this is the way to go?

2023-03-06 20:47 UTC, rbreeze approved these changes
LGTM, just one comment that can be addressed later: I miss the ability to quickly highlight a line copy it to the clipboard.

2023-03-06 20:47 UTC, rbreeze commented on ui/package.json
> +    "react-virtualized": "^9.22.3",
Where is this being used?

2023-03-06 21:18 UTC, jessesuen approved these changes
Yep directionally when I spoke with @alexec, I liked how this is more in line with the kubectl experience, so I support the change. As for the UI implementation, 🤷‍♂️

2023-03-07 01:17 UTC, merged

2023-03-07 18:11 UTC, alexec commented
🥳

2023-03-27 14:12 UTC, dhirschfeld commented
These improvements look great & I can't wait to try them out! 🚀

Being able to search more than 100 lines will make the logs *much* more useful.

I would've loved if my issue #11455 could have made the cut, but that'll keep for in future...

2023-05-16 21:01 UTC, rodrigc commented
@alexec I'm trying the enhanced log viewer in Argo 2.7.2 and it looks great.  Thanks for doing this!

One comment that I have is that the log viewer has a button to enable Dark Mode, but just for the log viewer.

One suggestion that I have is that the default behavior of Dark Mode for the log viewer
should be to inherit the setting for Dark Mode from `/settings/appearance`.

It is a bit weird to enable Dark Mode for the entire ArgoCD UI, but then have the Log Viewer be not in Dark Mode.

2023-07-26 14:52 UTC, alexec commented
@rodrigc that is strange! Historical. You wanna fix?