feat: add prompting to confirm remove of repository credentials
argoproj/argo-cd pull request #11040
Opened 2022-10-23 04:57 UTC by my-git9

add prompting to confirm remove of repository credentials

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-11-03 19:11 UTC, blakepettersson requested changes
Nice feature! Some nits though 😄 

Would it also be possible to add some tests for this?

2022-11-03 19:11 UTC, blakepettersson commented on cmd/argocd/commands/repocreds.go
> +						lowercaseAnswer = cli.AskToProceedS("Are you sure you want to remove '" + repoURL + "'? [y/n] ")
```suggestion
						lowercaseAnswer = cli.AskToProceedS(fmt.Sprintf("Are you sure you want to remove '%s'? [y/n] ", repoURL))
```

2022-11-03 19:11 UTC, blakepettersson commented on cmd/argocd/commands/repocreds.go
> +							lowercaseAnswer = cli.AskToProceedS("Are you sure you want to remove '" + repoURL + "'? [y/n/A] where 'A' is to remove all specified repository credentials without prompting ")
```suggestion
							lowercaseAnswer = cli.AskToProceedS(fmt.Sprintf("Are you sure you want to remove '%s'? [y/n/A] where 'A' is to remove all specified repository credentials without prompting ", repoURL))
```

2022-11-03 19:11 UTC, blakepettersson commented on cmd/argocd/commands/repocreds.go
> +						fmt.Println("The command to remove '" + repoURL + "' was cancelled.")
```suggestion
						fmt.Printf("The command to remove '%s' was cancelled.\n", repoURL)
```

2024-05-08 14:55 UTC, pasha-codefresh requested changes

2024-05-08 14:55 UTC, pasha-codefresh commented on cmd/argocd/commands/repocreds.go
> +	command.Flags().BoolVarP(&noPrompt, "yes", "y", false, "Turn off prompting to confirm removal of repository credentials")
In case if we make it false by default, here is a chance that we can break automations that people build on top of this command, not sure about it

2025-02-28 10:21 UTC, closed without merging

2025-02-28 13:41 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.