util/db: add fuzzer
argoproj/argo-cd pull request #11146
Opened 2022-11-01 22:17 UTC by AdamKorcz

Moves a fuzzer from https://github.com/cncf/cncf-fuzzing/blob/main/projects/argo/argo-cd_db_fuzzer.go

Signed-off-by: AdamKorcz <adam@adalogics.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-11-02 12:41 UTC, crenshaw-dev requested changes
Nice, thanks @AdamKorcz! Can you run `go mod tidy` and push?

2023-03-29 19:19 UTC, crenshaw-dev commented
@AdamKorcz mind also fixing DCO?

Once I merge, what how do we actually use this fuzzer?

2023-10-15 21:03 UTC, agilgur5 commented
> Once I merge, what how do we actually use this fuzzer?

This seems to be using [Go 1.18+ built-in fuzzing](https://go.dev/security/fuzz/), which can be run with `go test -fuzz=FuzzTestName` for a set period of time.

Usually they're run continuously via OSS-Fuzz as well as for a short period of time on PRs. The CNCF fuzzing repo actually describes [the same thing in more detail]( https://github.com/cncf/cncf-fuzzing/tree/main#2-integrate-continuous-fuzzing-with-oss-fuzz).
It looks like there's a more recent [CIFuzz GH action](https://google.github.io/oss-fuzz/getting-started/continuous-integration/) than can re-use the OSS-Fuzz configuration.

It seems like Argo was already added to OSS-Fuzz [at some point](
https://github.com/google/oss-fuzz/blob/d514fac92686c656633aa8549fd6f239c964b2bc/projects/argo/project.yaml), although I'm not entirely sure where the fuzz tests are referenced (especially as most of them [are located in](https://github.com/cncf/cncf-fuzzing/tree/main/projects/argo) the above mentioned CNCF fuzzing repo)

2025-02-28 10:21 UTC, closed without merging

2025-02-28 13:41 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.