Fixes [10143] Adding missing changes for bitbucket cloud SCM provider
argoproj/argo-cd pull request #11150
Opened 2022-11-01 23:01 UTC by mmerrill3

This PR completes the original PR from #556 in application set controller repo
Signed-off-by: mmerrill3 <jjpaacks@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-11-09 13:20 UTC, crenshaw-dev requested changes
Just a couple tweaks. :-)

2022-11-09 13:20 UTC, crenshaw-dev commented on docs/operator-manual/applicationset/Generators-SCM-Provider.md
> +## Bitbucket
```suggestion
## Bitbucket Cloud
```

2022-11-09 13:20 UTC, crenshaw-dev commented on docs/operator-manual/applicationset/Generators-SCM-Provider.md
> +        user: "mmerrill"
```suggestion
        owner: "example-owner"
        # The user to use for basic authentication with an app password.
        user: "example-user"
```

2022-11-09 13:21 UTC, crenshaw-dev commented
I think this should go all the way back to 2.4?

2022-11-11 17:56 UTC, mmerrill3 commented on docs/operator-manual/applicationset/Generators-SCM-Provider.md
> +        user: "mmerrill"
Updated and rebased.

2022-11-14 20:27 UTC, mmerrill3 commented
@crenshaw-dev updated the PR

2022-12-01 02:01 UTC, crenshaw-dev approved these changes

2022-12-01 02:01 UTC, merged