feat: Add new admin command to print Argo CD initial password (11117)
argoproj/argo-cd pull request #11155
Opened 2022-11-02 09:55 UTC by iam-veeramalla

Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Fixes #11117 
Closes #11117

2022-11-02 12:44 UTC, crenshaw-dev requested changes
Thanks @iam-veeramalla! One small grammar tweak.

Could you also update the quick start guide to reference this new command instead of the `kubectl` command?

2022-11-02 12:44 UTC, crenshaw-dev commented on cmd/argocd/commands/admin/initial_password.go
> +				fmt.Println("\n This password must be only used for first time login. We strongly recommend you to update the password using `argocd account update-password`.")
```suggestion
				fmt.Println("\n This password must be only used for first time login. We strongly recommend you update the password using `argocd account update-password`.")
```

2022-11-02 18:52 UTC, crenshaw-dev commented
Can you run CLI codegen again?

2022-11-03 12:02 UTC, iam-veeramalla commented
My mac is giving me hard time in running the codegen and other make targets :( . Hope this commit will fix the failing CI.

2022-11-03 14:47 UTC, iam-veeramalla commented
@crenshaw-dev got the code-gen working now. PTAL

2022-11-04 07:59 UTC, iam-veeramalla commented
@crenshaw-dev just in case you missed my previous comment. 

Fixed the failing CI and rebased the code.

2022-11-04 12:48 UTC, crenshaw-dev requested changes

2022-11-04 12:48 UTC, crenshaw-dev commented on docs/getting_started.md
> +using `argocd admin command`:
```suggestion
using the `argocd` CLI:
```

2022-11-04 12:48 UTC, crenshaw-dev commented on cmd/argocd/commands/admin/initial_password.go
> +		Short: "Prints initial password to login into Argo CD for the first time",
```suggestion
		Short: "Prints initial password to log in to Argo CD for the first time",
```

2022-11-04 12:48 UTC, crenshaw-dev commented on docs/user-guide/commands/argocd_admin_initial-password.md
> +Prints initial password to login into Argo CD for the first time
```suggestion
Prints initial password to log in to Argo CD for the first time
```

2022-11-04 12:49 UTC, crenshaw-dev approved these changes

2022-11-04 15:51 UTC, crenshaw-dev commented on docs/user-guide/commands/argocd_admin.md
> +* [argocd admin initial-password](argocd_admin_initial-password.md)	 - Prints initial password to login into Argo CD for the first time
```suggestion
* [argocd admin initial-password](argocd_admin_initial-password.md)	 - Prints initial password to log in to Argo CD for the first time
```

2022-11-04 16:57 UTC, merged

2023-02-07 07:15 UTC, ofirshtrull commented
I don't know if I'm missing something but, how is this helpful? if you ran `argocd login` that means that you already have the password in hand...
so how does this benefit the users?

2023-09-17 07:03 UTC, gopikrishna7 commented
@ofirshtrull , Before `argocd login`  you can run this command to get the initial admin password. Using this initial admin password you can login to ArgoCD UI or CLI.