feat: display auto sync status in application details view
argoproj/argo-cd pull request #11200
Opened 2022-11-05 11:11 UTC by alexef

first minor change to display the auto sync status (enabled or not) in the application details page:
<img width="688" alt="Screenshot 2022-11-05 at 12 11 01" src="https://user-images.githubusercontent.com/346576/200117017-2575cbb5-9b3b-4d06-8802-a75929b7e011.png">

see enhancement proposal: https://github.com/argoproj/argo-cd/issues/11102

Signed-off-by: Alex Eftimie <alex.eftimie@getyourguide.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-11-08 06:24 UTC, blakepettersson approved these changes

2022-11-09 14:07 UTC, alexef commented on ui/src/app/applications/components/application-status-panel/application-status-panel.tsx
> +                        <div className='application-status-panel__item-name'>
this empty div makes no sense for Helm source (only for git)

2022-11-10 16:27 UTC, rbreeze requested changes
Hi Alex, thanks for the PR. I agree that we should have a more obvious place to indicate if Auto-Sync is enabled, but I'm not sure this is the best place for it; the Current Sync Status area can already be quite crowded: 

<img width="448" alt="CleanShot 2022-11-10 at 08 25 13@2x" src="https://user-images.githubusercontent.com/6250584/201151075-aa7219c6-a01d-40af-88d9-cc9077755c86.png">

2022-11-11 15:55 UTC, alexef commented
@rbreeze I see your point, but I can't think of a different place.

What if I change the area title, see mockup below? (Auto Sync Status vs Manual Sync Status)
<img width="581" alt="Screenshot 2022-11-11 at 16 54 06" src="https://user-images.githubusercontent.com/346576/201379317-224e99ab-6a32-43f1-b93c-4d330cec1de2.png">
<img width="606" alt="Screenshot 2022-11-11 at 16 54 19" src="https://user-images.githubusercontent.com/346576/201379332-21f78b7b-2422-4d8a-8903-72cc498373bd.png">

2022-11-17 11:42 UTC, alexef commented
@rbreeze after SIG UI yesterday, I assume we can give this approach another chance? I will follow up with the application list filter in a separate PR.

2022-11-18 17:27 UTC, rbreeze approved these changes

2022-11-18 18:51 UTC, merged