feat: add health check for ConfigConnector(CNRM) resources
argoproj/argo-cd pull request #11224
Opened 2022-11-08 13:13 UTC by zelig81

Signed-off-by: Ilya Gorban [zelig81@users.noreply.github.com](mailto:zelig81@users.noreply.github.com)

Added health checks for the following Google Cloud Config Connector resouces.

- compute.cnrm.cloud.google.com
  - ComputeAddress
  - ComputeNetwork
- dns.cnrm.cloud.google.com
  - DNSRecordSet
- memcache.cnrm.cloud.google.com
  - MemcacheInstance
- secretmanager.cnrm.cloud.google.com
  - SecretManagerSecret
- servicenetworking.cnrm.cloud.google.com
  - ServiceNetworkingConnection
 
Since Config Connector uses the same status indication on all resources, the health checks are the same, only difference is the apiVersion and kind in the test objects.

I took as example [this PR](https://github.com/argoproj/argo-cd/pull/9878)

2022-12-16 22:59 UTC, crenshaw-dev commented
@zelig81 yowzer. Yep, that's a lot of files. Thanks for working on this!

@alexmt, @jannfis any concerns about this method of adding support for all those resources? Should we do some kind of wildcard mechanism _first_

2023-10-26 07:33 UTC, griseau commented
@crenshaw-dev any update on this ? We would really appreciate having proper health of our services :)

2024-03-10 16:44 UTC, zelig81 commented
@griseau you are welcome to add the healthcheck to your `argocd-cm` config map in the following way:

```yaml
---
apiVersion: v1
data:
  resource.customizations: |
    "*.cnrm.cloud.google.com/*":
      health.lua.useOpenLibs: true
      health.lua: |
        hs = {
          status = "Progressing",
          message = "Update in progress"
        }
        if obj.status ~= nil then
          if obj.status.conditions ~= nil then
            for i, condition in ipairs(obj.status.conditions) do

              -- Up To Date
              if condition.reason == "UpToDate" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = condition.message
                return hs
              end

              -- Update Failed
              if condition.reason == "UpdateFailed" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end

              -- Dependency Not Found
              if condition.reason == "DependencyNotFound" then
                hs.status = "Degraded"
                hs.message = condition.message
                return hs
              end

              -- Dependency Not Ready
              if condition.reason == "DependencyNotReady" then
                hs.status = "Suspended"
                hs.message = condition.message
                return hs
              end
            end
          end
        end
        return hs
     
kind: ConfigMap
metadata:
  name: argocd-cm
```

2024-03-10 16:47 UTC, zelig81 commented
@crenshaw-dev Hi sir, could it be that there is some way to add the wildcarded health check with the tests for multiple types of resources?

2025-02-28 10:23 UTC, andrii-korotkov-verkada commented
Can you rebase / merge latest master, please?

2025-05-09 19:16 UTC, agaudreault requested changes
@zelig81 I think we are missing a feature to reference resource_customization from trusted sources as a dependency. Do you mind opening an issues to brainstorm and build that mechanism first? 

I see that the PR was opened in 2022, but I dont see a linked issue on the deuplication problem.

2025-09-06 18:17 UTC, crenshaw-dev commented
We now support wildcards for built-in health checks: https://argo-cd.readthedocs.io/en/stable/operator-manual/health/#wildcard-support-for-built-in-health-checks

Closing for now, folks can feel free to reopen using the wildcard approach.

2025-09-06 18:17 UTC, closed without merging