docs: Update Pull Request generator documentation to include application lifecycle
argoproj/argo-cd pull request #11274
Opened 2022-11-11 19:43 UTC by Geethree

The lifecycle of the generated applications was not explained as discussed [here](https://cloud-native.slack.com/archives/C01U45M2SVB/p1668194689295539?thread_ts=1668194193.486229&cid=C01U45M2SVB) in slack.

Happy to modify, mainly throwing this up before I forget about it.

Signed-off-by: Gerald Spencer <Geethree@users.noreply.github.com>

2022-11-12 07:59 UTC, alexef commented on docs/operator-manual/applicationset/Generators-Pull-Request.md
> +An appliction will be generated when a Pull Request is discovered when the configured crietia is met - i.e. for Github when a Pull request matches the specified `labels` and/or `pullRequestState`. Ap
```suggestion
An Application will be generated when a Pull Request is discovered when the configured criteria is met - i.e. for GitHub when a Pull Request matches the specified `labels` and/or `pullRequestState`. Application will be removed when a Pull Request no longer meets the specified criteria.
```

2022-11-12 08:00 UTC, alexef requested changes
typos

2022-11-28 18:10 UTC, Geethree commented
@alexef Any other additions you'd like to see made?

2022-12-02 13:44 UTC, crenshaw-dev approved these changes

2022-12-02 13:44 UTC, merged

2022-12-02 13:45 UTC, crenshaw-dev commented
Cherry-picked onto release-2.5 for 2.5.4. Thanks for your patience, @Geethree!