feat: custom logo config (#3642)
argoproj/argo-cd pull request #11309
Opened 2022-11-16 10:43 UTC by Marvin9

fixes #3642 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-11-17 05:22 UTC, Marvin9 commented
@crenshaw-dev @alexmt would you please review or request review to relevant person?

2022-11-18 17:52 UTC, tanphan-vn approved these changes

2022-11-19 02:46 UTC, crenshaw-dev requested changes

2022-11-19 02:46 UTC, crenshaw-dev commented on docs/operator-manual/argocd-cm.yaml
> +  ui.loginlogo: "https://mysite.com/static/logo-hero.png"
```suggestion
  # Make sure the source of your logo is trusted and well-controlled. Some image formats (like SVG) may
  # be security threat vectors.

  # Logo rendered on the dashboard pages, at top of the sidebar
  ui.dashboardlogo: "https://mysite.com/static/logo.png"
  # Logo rendered on the login page, at center of left section
  ui.loginlogo: "https://mysite.com/static/logo-hero.png"
```

Justification: https://security.stackexchange.com/a/135636/155615

2023-02-24 19:22 UTC, blakepettersson approved these changes

2023-03-23 20:11 UTC, crenshaw-dev requested changes

2023-03-23 20:11 UTC, crenshaw-dev commented on server/settings/settings.go
> +		set.UiDashboardLogo = argoCDSettings.UiDashboardLogo
We should probably validate that this is either `http` or `https` schema before returning it.

2023-05-27 20:28 UTC, crenshaw-dev commented
@Marvin9 do you still have time to push this forward?

2023-05-29 03:17 UTC, Marvin9 commented
> @Marvin9 do you still have time to push this forward?

Yes @crenshaw-dev I will resolve conflicts and address comments this week. Thanks for reminding.

2023-05-30 05:58 UTC, Marvin9 commented on util/settings/settings.go
> +	settings.UiLoginLogo = argoCDCM.Data[settingsUiLoginLogo]
validation added

2023-10-24 12:56 UTC, therapy-lf commented
Is there any updates left?

2023-10-26 15:24 UTC, Marvin9 commented
Nope. I guess I will just resolve merge conflicts and it is ready to review

2025-02-28 10:23 UTC, closed without merging

2025-02-28 13:40 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.