fix add cluster api with ipv6 appending '[' in secret name (#8204)
argoproj/argo-cd pull request #11319
Opened 2022-11-16 18:10 UTC by zillani

**URIToSecretName** method hashes a URI address and returns a secret name
- if ipv6 URI is provided, then the method is appending '[' in secret name 
- this is causing an error like Secret "cluster-[fcff-1931808423" is invalid 
- fixed by trimming '[' from the string

Signed-off-by: zillani <shaikzillani@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-11-16 18:14 UTC, zillani commented
fixes #11319

2022-11-16 20:29 UTC, jessesuen requested changes
Could you please add a unit test for this? Also, is it possible that replacing all occurrences of `[` with `` cause potential collision in secret name?

2022-11-22 14:20 UTC, zillani commented
yea, I am working on it, any suggestions on making the secret unique?

2022-11-23 13:36 UTC, zillani commented
I have just added the test case & also added ipv6 hostname to the string, this will avoid any hash collisions, 

**Format**
A secret name will be created in this format, 
cluster-<IP or Hostname>-HASH

For hashing, argo is already using the **FNV1a** algorithm with 32bit hash which has lesser collisions compared to other algorithms. However, since we are appending the hostname to the secret, these collisions are near impossible. 

**Ipv4**
Input URI -> http://127.0.0.1:8080
Secret name -> cluster-127.0.0.1-2348797202

**Ipv6**
Input URI -> **http://[fcff:69:90:0:5054:ff:fea7:810]:8080**
Secret name -> **cluster-fcff699005054fffea78108080-4259157202**

Here, removing **:** instead of replacing is better, double **:** may occur in ipv6 & extra **:** if port is present

2022-12-05 07:23 UTC, zillani commented
Hi @jessesuen any update?

2023-01-23 04:26 UTC, zillani commented
Hi @jessesuen any update on this?

2023-02-21 05:49 UTC, zillani commented
@jessesuen can you please review

2023-06-26 08:02 UTC, tossmilestone commented on util/db/secrets.go
> +	if len(parsedHost) >= 8 {
Why use `len(parsedHost) >= 8` to determine if it's ipv6 address? There is already a `ParseIP` function in  `net` package to do the work.

2023-08-15 03:10 UTC, tossmilestone commented
Hi, @jessesuen Can you help review this PR? We need ArgoCD to support IPv6 clusters. Thank you！

2023-10-04 02:23 UTC, zillani commented
> Hi, @jessesuen Can you help review this PR? We need ArgoCD to support IPv6 clusters. Thank you！

hey @tossmilestone  will work on this today

2023-11-10 11:35 UTC, tossmilestone commented
> > Hi, @jessesuen Can you help review this PR? We need ArgoCD to support IPv6 clusters. Thank you！
> 
> 
> 
> hey @tossmilestone  will work on this today

@zillani hi，is the pr still woking in process?

2025-02-28 10:23 UTC, closed without merging