feat(kustomize): support envsubst in commonAnnotations and commonLabels
argoproj/argo-cd pull request #11345
Opened 2022-11-18 10:02 UTC by AndrewChubatiuk

Replacement for #11333 PR

2022-11-19 02:38 UTC, crenshaw-dev commented on util/kustomize/kustomize.go
> +				commonLabels[name] = envVars.Envsubst(value)
Suppose someone is already using a `commonAnnotation` with a $ in it, e.g. `$ilikedollarsigns`, and they expect it to be interpreted literally... will this cause their annotations to be replaced with empty strings?

2022-11-19 22:25 UTC, crenshaw-dev commented on util/kustomize/kustomize.go
> +				commonLabels[name] = envVars.Envsubst(value)
We could toggle the behavior on a new field, e.g. `commonLabelsEnvsubst`. I don't like adding a new field, but I really don't wanna mess up folks' labels.

2022-11-19 22:27 UTC, crenshaw-dev commented on util/kustomize/kustomize.go
> +				commonLabels[name] = envVars.Envsubst(value)
Oh wait, these are labels! They can't have dollar signs anyway: https://kubernetes.io/docs/concepts/overview/working-with-objects/labels/#syntax-and-character-set

2022-11-19 22:27 UTC, crenshaw-dev commented on util/kustomize/kustomize.go
> +				commonLabels[name] = envVars.Envsubst(value)
Ah, but we would still need a toggle for annotations.

2022-12-12 12:04 UTC, gxxglyeyez commented
Oren from Komodor, Would love to see this added ❤️

2022-12-16 23:03 UTC, crenshaw-dev commented on util/kustomize/kustomize.go
> +				commonLabels[name] = envVars.Envsubst(value)
@AndrewChubatiuk apologies for the lack of response. I had to prioritize some high-priority stuff for 2.6. Let me target this for 2.7.

2023-03-10 22:04 UTC, crenshaw-dev requested changes
Thanks for your patience @AndrewChubatiuk! Would you mind documenting the new field here? https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/application.yaml

2023-03-22 18:52 UTC, crenshaw-dev approved these changes

2023-03-22 19:54 UTC, merged