docs: clarify value for disabling tools
argoproj/argo-cd pull request #11395
Opened 2022-11-21 21:42 UTC by morey-tech

Although it is implied to set the value for the key to `false`, this explicitly states it to add clarity. Along with some wording changes.

Signed-off-by: Nicholas Morey <nicholas@morey.tech>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-11-21 21:50 UTC, crenshaw-dev requested changes

2022-11-21 21:50 UTC, crenshaw-dev commented on docs/user-guide/tool_detection.md
> +tool is disabled, Argo CD will assume the application target directory contains plain Kubernetes YAML manifests.
```suggestion
Built-in config management tools can be optionally disabled by setting one of the following
keys, in the `argocd-cm` ConfigMap, to `false`: `kustomize.enable`, `helm.enable` or `jsonnet.enable`. Once the
tool is disabled, Argo CD will assume the application target directory contains plain Kubernetes YAML manifests.

Disabling unused config management tools can be a helpful security enhancement. Vulnerabilities are sometimes limited to certain config management tools. Even if there is no vulnerability, an attacker may use a certain tool to take advantage of a misconfiguration in an Argo CD instance. Disabling unused config management tools limits the tools available to malicious actors.
```

2022-11-21 21:50 UTC, crenshaw-dev commented on docs/user-guide/tool_detection.md
> +tool is disabled, Argo CD will assume the application target directory contains plain Kubernetes YAML manifests.
While we're here. :-)

2022-11-25 19:55 UTC, fengshunli commented
@crenshaw-dev @alexef can be merged

2022-12-09 22:03 UTC, alexmt approved these changes
LGTM!

2022-12-09 22:03 UTC, alexmt commented
@crenshaw-dev do you mind merging it ?

2023-01-17 21:52 UTC, crenshaw-dev approved these changes

2023-01-18 21:46 UTC, merged

2023-01-18 21:47 UTC, crenshaw-dev commented
Cherry-picked onto release-2.6 and release-2.5.