Display a warning if the JWT cookie is too large. Fixes #1103
argoproj/argo-cd pull request #1146
Opened 2019-02-19 23:49 UTC by alexec

* [ ] Discus size check.

This is what the error looks like (note - this was done with uncommitted code):

![long cookie error](https://user-images.githubusercontent.com/1142830/53055778-dc0db700-345d-11e9-8920-16b37e936489.png)

2019-02-20 22:59 UTC, jessesuen requested changes

2019-02-20 22:59 UTC, jessesuen commented on util/oidc/oidc.go
> +		http.Error(w, fmt.Sprintf("invalid cookie: %v", err), http.StatusInternalServerError)
I think we're gonna have a message like: "invalid cookie: invalid cookie: longer than max length 4093". Can we remove one level of "invalid cookie"?

2019-02-20 23:57 UTC, jessesuen approved these changes

2019-02-21 00:01 UTC, alexmt approved these changes

2019-02-21 16:27 UTC, merged