feat: add support for cloning Google Cloud Source Repositories
argoproj/argo-cd pull request #11543
Opened 2022-12-02 17:44 UTC by fengshunli

Signed-off-by: fsl <1171313930@qq.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-12-03 14:47 UTC, crenshaw-dev commented
@fengshunli can you run codegen and push?

2022-12-03 14:55 UTC, fengshunli commented
> can you run codegen and push?

@crenshaw-dev There is a test that has failed, please help me find out why

2022-12-03 15:05 UTC, crenshaw-dev commented
@fengshunli it's the generated code check. If you run `make codegen` locally, you should see the required changes.

2022-12-03 17:26 UTC, fengshunli commented
@crenshaw-dev test still failed

2022-12-05 13:25 UTC, crenshaw-dev requested changes

2022-12-05 13:25 UTC, crenshaw-dev commented on util/git/client.go
> +			return nil, err
```suggestion
			return nil, fmt.Errorf("failed to get username from creds: %w", err)
```

2022-12-05 13:25 UTC, crenshaw-dev commented on util/git/client.go
> +			return nil, err
```suggestion
			return nil, fmt.Errorf("failed to get access token from creds: %w", err)
```

2022-12-05 13:25 UTC, crenshaw-dev commented on util/git/creds.go
> +		return NopCloser{}, nil, err
```suggestion
		return NopCloser{}, nil, fmt.Errorf("failed to get username from creds: %w", err)
```

2022-12-05 13:25 UTC, crenshaw-dev commented on util/git/creds.go
> +		return NopCloser{}, nil, err
```suggestion
		return NopCloser{}, nil, fmt.Errorf("failed to get access token from creds: %w", err)
```

2022-12-05 13:25 UTC, crenshaw-dev commented on util/git/creds.go
> +		return "", err
```suggestion
		return "", fmt.Errorf("failed to unmarshal Google Cloud credentials: %w", err)
```

2022-12-09 08:12 UTC, alexef commented
superseeded by #11618

2022-12-09 08:12 UTC, closed without merging