docs: Cluster overview page
argoproj/argo-cd pull request #11637
Opened 2022-12-09 13:36 UTC by kostis-codefresh

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-12-09 16:10 UTC, todaywasawesome commented on docs/basics/clusters/index.md
> +By default an Argo CD instance can deploy applications to the [same cluster](internal/) it is installed on. However, Argo CD has the capability to connect and deploy to [external clusters](external).
```suggestion
By default an Argo CD instance can deploy applications to the [same cluster](internal/) it is installed on. Additionally, Argo CD has the capability to connect and deploy to [external clusters](external).
```

The use of "however" seems in opposition and I think it's better replaced with "Additionally"

2022-12-09 16:13 UTC, todaywasawesome commented on docs/basics/clusters/index.md
> +* Argo CD performance may degrade with many applications and clusters as they scale
```suggestion
* Argo CD performance may degrade with many applications and clusters as they scale - see [High Availability](../../operator-manual/high_availability/) for more information.
```

2022-12-09 16:13 UTC, todaywasawesome commented on docs/basics/clusters/index.md
> +In this example there are different Argo CD instances per region that manage other clusters, while each team gets also its own Argo CD instance. This allows developer teams to have their own config f
```suggestion
In this example there are different Argo CD instances per region that manage other clusters, while each team gets also its own Argo CD instance. This allows developer teams to have their own config for their Argo CD instance and also there is no fear of affecting other teams during upgrades.
```

2022-12-09 16:13 UTC, todaywasawesome commented on docs/basics/clusters/index.md
> +As a starting point we suggest we have at least 2 ArgoCD categories (which might be individual instances or multiple installations)
```suggestion
As a starting point we suggest we have at least 2 Argo CD categories (which might be individual instances or multiple installations)
```

2022-12-10 11:44 UTC, blakepettersson commented on docs/basics/clusters/index.md
> +1. Using a centralized Argo CD instance that handles all cluster
```suggestion
1. Using a centralized Argo CD instance that handles all clusters
```

2022-12-10 11:44 UTC, blakepettersson commented on docs/basics/clusters/index.md
> +* In theory requires less resources per each deployment cluster (as it only runs apps and not ArgoCD itself)
```suggestion
* In theory requires less resources per deployment cluster (as it only runs apps and not Argo CD itself)
```

2022-12-10 11:44 UTC, blakepettersson commented on docs/basics/clusters/index.md
> +In this example there are different Argo CD instances per region that manage other clusters, while each team gets also its own Argo CD instance. This allows developer teams to have their own config f
```suggestion
In this example there are different Argo CD instances per region that manage other clusters, while each team also gets its own Argo CD instance. This allows developer teams to have their own config for their Argo CD instance and there is also no fear of affecting other teams during upgrades.
```

2022-12-10 11:44 UTC, blakepettersson commented on docs/basics/clusters/index.md
> +As a starting point we suggest we have at least 2 ArgoCD categories (which might be individual instances or multiple installations)
```suggestion
As a starting point we suggest to have at least 2 Argo CD categories (which might be individual instances or multiple installations)
```

2022-12-14 15:51 UTC, todaywasawesome approved these changes

2022-12-20 18:55 UTC, crenshaw-dev requested changes
@kostis-codefresh can you run the images through squoosh.app or similar? The files are a bit big right now.

2022-12-20 18:59 UTC, crenshaw-dev requested changes

2022-12-20 18:59 UTC, crenshaw-dev commented on docs/basics/clusters/index.md
> +# Argo CD target clusters
Should this file be added to mkdocs.yml so it shows up in the ToC?

2022-12-22 13:18 UTC, kostis-codefresh commented
@crenshaw-dev I converted the images to jpg using squoosh.app per your suggestion and they are much smaller now.

The page is already added in mkdocs. This doc page is for the new documentation (notice the target is of the pull request is the refresh-docs branch and not master)

Entry https://github.com/argoproj/argo-cd/blob/refresh-docs/mkdocs.yml#L41
How it looks https://argo-cd--11637.org.readthedocs.build/en/11637/basics/clusters/

2022-12-22 18:30 UTC, crenshaw-dev approved these changes

2022-12-22 18:30 UTC, merged