fix: preserve modification time of files for sidecar CMP plugins
argoproj/argo-cd pull request #11825
Opened 2022-12-24 16:55 UTC by dlh

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

---

## Rationale

Our team created a plugin that maintains a local cache for some operations, and that cache was designed to be invalidated when the mtime of `.git/FETCH_HEAD` changes. When I migrated the plugin to a sidecar container I noticed the mtime of the un-tarred repo differed from the reposerver's copy.

This changeset corrects that, and makes it similar to the deprecated _argocd-cm ConfigMap_-style plugin behavior.

2023-01-18 14:19 UTC, alexef approved these changes
The change looks sane to me and I appreciate the unit test.

2023-01-18 14:42 UTC, crenshaw-dev requested changes
Looks great! Just a couple (hopefully) small things.

2023-01-18 14:42 UTC, crenshaw-dev commented on util/io/files/tar.go
> +		err = os.Chtimes(target, header.AccessTime, header.ModTime)
There are quite a few `header.Typeflag` values which are ignored. Can we limit this to only be called when one of the three relevant file types is specified?

2023-01-18 14:42 UTC, crenshaw-dev commented on util/io/files/tar.go
> +	header.Format = tar.FormatPAX
Is this absolutely necessary for your use case? I'm in favor of the smallest possible change to solve the problem.

2023-05-27 20:26 UTC, crenshaw-dev commented
@dlh do you still have time to push this one forward?

2025-02-28 10:25 UTC, closed without merging

2025-02-28 13:39 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.