feat: specify listen address from env / command line
argoproj/argo-cd pull request #11846
Opened 2022-12-28 12:15 UTC by eyusupov

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2023-03-26 17:46 UTC, blakepettersson approved these changes
LGTM 👍

2023-05-27 20:02 UTC, crenshaw-dev requested changes

2023-05-27 20:02 UTC, crenshaw-dev commented on cmd/argocd-repo-server/commands/argocd_repo_server.go
> +	command.Flags().StringVar(&metricsHost, "metrics-address", env.StringFromEnv("ARGOCD_REPO_SERVER_METRICS_LISTEN_ADDRESS", common.DefaultAddressRepoServerMetrics), "Listen on given address for metric
@eyusupov would you mind making these configurable via https://github.com/argoproj/argo-cd/blob/master/docs/operator-manual/argocd-cmd-params-cm.yaml ?

2023-05-28 01:55 UTC, crenshaw-dev commented
@eyusupov thanks for the changes! Can you fix the DCO check? Looks like you'll also need to run `make manifests-local`.

2023-05-29 14:19 UTC, crenshaw-dev approved these changes

2023-05-29 14:19 UTC, merged