fix: support health assessment for prometheus operator < v0.56
argoproj/argo-cd pull request #11901
Opened 2023-01-06 18:35 UTC by aslafy-z

Signed-off-by: Zadkiel Aharonian <hello@zadkiel.fr>

Support health for prometheus operator < v0.56. 
Before v0.56, prometheus operator was not updating the status subresource which made the custom health check remain in `Progressing` state forever. See https://github.com/prometheus-operator/prometheus-operator/blob/main/CHANGELOG.md#0560--2022-04-20

Fixes #5620 
Fixes #11261

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2023-11-09 02:18 UTC, aslafy-z commented
@crenshaw-dev can you please give a look? Thank you

2024-01-25 14:46 UTC, leoluz requested changes
Thank you for working on this.
Please check my comments.

2024-01-25 14:46 UTC, leoluz commented on resource_customizations/monitoring.coreos.com/Prometheus/health.lua
> +    hs = { status = "Unknown", message = "Status is not provided" }
In Argo CD, resources that don't provide status (like ConfigMap and Secrets), are always marked as healthy. The reason is that this impacts the overall Application status and in this case Apps will always be marked as `Unknown`. I suggest changing this to healthy instead.

2024-01-25 14:46 UTC, leoluz commented on resource_customizations/monitoring.coreos.com/Prometheus/health.lua
> +        found_status = true
`found_status` should be set to true right after the `if obj.status ~= nil then` statement.

2024-01-25 14:46 UTC, leoluz commented on resource_customizations/monitoring.coreos.com/Prometheus/health.lua
> +      if condition.type == "Available" then
If no condition is `Available` then it should be marked as `Unknown`

2025-02-28 10:26 UTC, closed without merging

2025-02-28 13:39 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.

2025-02-28 13:57 UTC, aslafy-z commented
These prometheus-operator releases are I hope not used anymore. Let's skip this for now on.