fix: Sending a TERM signal before KILL signal to allow any potential cleanup if needed for CMP commands
argoproj/argo-cd pull request #12087
Opened 2023-01-23 16:59 UTC by Ashwin901

Fixes #9180 
Signed-off-by: Ashwin901 <ashwinprasanna9@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2023-01-31 21:16 UTC, crenshaw-dev requested changes
Can you add a unit test for `runCommand` to show that

1) before this change, subprocesses didn't have time to be cleaned up and 
2) after this change, subprocesses are cleaned up.

Might be tricky to craft that test, but I wouldn't really feel right merging this without validating the fix.

2023-02-01 04:37 UTC, Ashwin901 commented
Sure, I will look into it

2023-05-27 20:22 UTC, crenshaw-dev commented
@Ashwin901 are you still able to push this one forward?

2025-02-28 10:27 UTC, closed without merging

2025-02-28 13:38 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.