fix: use field-wise templating for child matrix generators (#11661)
argoproj/argo-cd pull request #12287
Opened 2023-02-03 17:28 UTC by crenshaw-dev

Fixes #11661

go-templating over a JSON string makes no sense. There will be tons of syntax conflicts.

This change switches matrix generator templating to use the same field-wise templating strategy as is used for the `template` field.

I've confirmed that the test fails with the same error message as in #11661 before this change.

2023-02-20 04:58 UTC, ishitasequeira requested changes
PR LGTM. Just added a nit for additional information while returning error.

2023-02-20 04:58 UTC, ishitasequeira commented on applicationset/utils/utils.go
> +		return nil, err
nit: Add more details to the error messaging.

2023-02-24 15:27 UTC, crenshaw-dev commented on applicationset/utils/utils.go
> +		return nil, err
```suggestion
		return nil, fmt.Errorf("failed to replace parameters in generator: %w", err)
```

2023-02-24 15:29 UTC, crenshaw-dev commented
/cherry-pick release-2.6
/cherry-pick release-2.5

2023-03-01 14:37 UTC, ishitasequeira approved these changes
LGTM!!

2023-03-01 14:37 UTC, ishitasequeira commented
@jannfis @leoluz could you take a look as the approver?

2023-03-08 16:59 UTC, pasha-codefresh approved these changes

2023-03-08 18:08 UTC, merged

2023-03-08 18:13 UTC, crenshaw-dev commented
Manually cherry-picked onto 2.5.

2024-02-19 16:31 UTC, Cyben commented
Hey, is there a way to use it with matrix generator that uses two git generators?
Is there documentation about it?