chore: pin docker images by hash
argoproj/argo-cd pull request #12517
Opened 2023-02-17 20:52 UTC by crenshaw-dev

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2023-02-25 22:40 UTC, 34fathombelow requested changes
All other changes look good.

2023-02-25 22:40 UTC, 34fathombelow commented on Dockerfile
> +ARG BASE_IMAGE=docker.io/library/ubuntu:22.04@sha256:c985bc3f77946b8e92c9a3648c6f31751a7dd972e06604785e47303f4ad47c4c
```suggestion
ARG BASE_IMAGE=docker.io/library/ubuntu:22.04@sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f
```

2023-02-25 22:40 UTC, 34fathombelow commented on Dockerfile
> +FROM docker.io/library/golang:1.20@sha256:2edf6aab2d57644f3fe7407132a0d1770846867465a39c2083770cf62734b05d AS builder
```suggestion
FROM docker.io/library/golang:1.19.6@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71 AS builder
```

2023-02-25 22:40 UTC, 34fathombelow commented on Dockerfile
> +FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.20@sha256:2edf6aab2d57644f3fe7407132a0d1770846867465a39c2083770cf62734b05d AS argocd-build
```suggestion
FROM --platform=$BUILDPLATFORM docker.io/library/golang:1.19.6@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71 AS argocd-build
```

2023-02-25 22:40 UTC, 34fathombelow commented on test/container/Dockerfile
> +FROM docker.io/library/golang:1.20@sha256:2edf6aab2d57644f3fe7407132a0d1770846867465a39c2083770cf62734b05d as golang
```suggestion
FROM docker.io/library/golang:1.19.6@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71 as golang
```

2023-02-25 22:40 UTC, 34fathombelow commented on test/container/Dockerfile
> +FROM docker.io/bitnami/kubectl:1.24.8@sha256:9c1bd1fe7bf4a0c19b4b38e596f355c5172805e14e6a3f71433472e3456e86d8 as kubectl
```suggestion
FROM docker.io/bitnami/docker.io/bitnami/kubectl:1.26@sha256:625467eb8c3a3d60232923404941c32e787eb9003e644d0fa8258b0efa7f6a7f as kubectl
```

2023-02-25 22:40 UTC, 34fathombelow commented on test/container/Dockerfile
> +FROM ubuntu@sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f
```suggestion
FROM docker.io/library/ubuntu:22.04@sha256:9a0bdde4188b896a372804be2384015e90e3f84906b750c1a53539b585fbbe7f
```

2023-02-25 22:40 UTC, 34fathombelow commented on test/remote/Dockerfile
> +FROM golang:1.20@sha256:2edf6aab2d57644f3fe7407132a0d1770846867465a39c2083770cf62734b05d AS go
```suggestion
FROM docker.io/library/golang:1.19.6@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71 AS go
```

2023-02-25 22:40 UTC, 34fathombelow commented on ui-test/Dockerfile
> +FROM node:12.18.4@sha256:8cfe7e8dc60095a4f9d25a3f0f208503559fa033a15e2ddd87dee85bec101a2e AS node
```suggestion
FROM docker.io/library/node:12.18.4@sha256:8cfe7e8dc60095a4f9d25a3f0f208503559fa033a15e2ddd87dee85bec101a2e AS node
```

2023-02-25 22:40 UTC, 34fathombelow commented on .github/dependabot.yml
> +      interval: "daily"
We need to add `package-ecosystem: "docker"` for each directory we want dependabot to scan.  Unfortunately we cannot pass multiple directories as a list.

2023-02-28 14:25 UTC, crenshaw-dev commented on test/container/Dockerfile
> +FROM docker.io/bitnami/docker.io/bitnami/kubectl:1.26@sha256:625467eb8c3a3d60232923404941c32e787eb9003e644d0fa8258b0efa7f6a7f as kubectl
```suggestion
FROM docker.io/bitnami/kubectl:1.26@sha256:625467eb8c3a3d60232923404941c32e787eb9003e644d0fa8258b0efa7f6a7f as kubectl
```

2023-03-08 16:22 UTC, 34fathombelow approved these changes
Lgtm

Just note we need to be cautious when dependabot recommends updates for Golang and node versions.  We should limit these to patch or minor versions.

2023-03-09 19:18 UTC, jannfis approved these changes
LGTM!

2023-03-09 19:18 UTC, merged