build: Support crazy fast dev loop with kit
argoproj/argo-cd pull request #12534
Opened 2023-02-19 17:57 UTC by alexec

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2023-02-22 22:47 UTC, crenshaw-dev requested changes
A few thoughts:

1. I'm a big fan of trying to improve our dev workflow. It's in rough shape.
2. I'm getting this when trying on the web: `Codespace could not be created: SKU name 'basicLinux32gb' is not allowed for this repository`
3. I worry that tasks.yaml duplicates a lot of stuff that's currently in Makefile and Procfile - more maintenance.
4. I'm not sure if this is IDE-agnostic - obviously if you use it on web, it's vscode. But locally, will it work with GoLand?

2023-02-22 22:58 UTC, alexec commented
> A few thoughts:
> 
> 1. I'm a big fan of trying to improve our dev workflow. It's in rough shape.

Good stuff.

> 2. I'm getting this when trying on the web: `Codespace could not be created: SKU name 'basicLinux32gb' is not allowed for this repository`

I've not seen this error. I wonder if it is because this is on a fork.

> 3. I worry that tasks.yaml duplicates a lot of stuff that's currently in Makefile and Procfile - more maintenance.

You're correct, this does duplicate I've found those files pretty difficult to work with, hence replacing them. I'm happy to re-submit without that.

> 4. I'm not sure if this is IDE-agnostic - obviously if you use it on web, it's vscode. But locally, will it work with GoLand?

Codepsaces is VSCode only really. I prefer IntelliJ myself, but I'm happy to use VSCode too.

2023-02-22 23:00 UTC, alexec commented
Further comment, I think that maintainer need to buy in to Codespaces as they could end up maintaining it.

2023-02-23 02:20 UTC, jannfis commented
> I think that maintainer need to buy in to Codespaces as they could end up maintaining it.

Yes, and I think none of the maintainers are using Codespaces. So this would become outdated pretty soon, most likely.

Is there a possibility to have the Codespaces configuration somewhere out-of-tree?

2023-02-23 05:19 UTC, alexec commented
> > I think that maintainer need to buy in to Codespaces as they could end up maintaining it.
> 
> Yes, and I think none of the maintainers are using Codespaces. So this would become outdated pretty soon, most likely.
> 
> Is there a possibility to have the Codespaces configuration somewhere out-of-tree?

You can run Codespaces without any set-up at all, but you don’t get Kubernetes or other pre-requisites.

Codespaces make it easier to dip in and out of the code. I’ve found Argo CD really hard to to do that with because of the complex set-up needed to get it running. I would say I spend about 30% of my time on that, and I wanted it to be easy to set-up. 

One pro of Codespaces is that it will make it easier to try out other users PRs.

One can is that, by reducing the barrier to entry, you could get more PRs.

2023-02-26 16:31 UTC, alexec commented
This is set-up for Argo Workflows. I'll create a video and share with you.

2025-01-05 21:31 UTC, closed without merging