Pinned container images by digest hashes in `test/container/Dockerfile` - Enhancement #12622.
argoproj/argo-cd pull request #12623
Opened 2023-02-25 15:29 UTC by adamiBs

Closes #12622.
Implementation was done according to the proposed implementation in the related issue.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [X] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2023-02-25 17:13 UTC, 34fathombelow requested changes

2023-02-25 17:13 UTC, 34fathombelow commented on test/container/Dockerfile
> +FROM docker.io/library/golang:1.19@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71 as golang
```suggestion
FROM docker.io/library/golang:1.19.6@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71 as golang
```

2023-02-25 17:15 UTC, 34fathombelow commented on test/container/Dockerfile
> +FROM docker.io/library/golang:1.19@sha256:7ce31d15a3a4dbf20446cccffa4020d3a2974ad2287d96123f55caf22c7adb71 as golang
Lets be explicit about the version we are using. So our Dependabot will be able to inform us of any update.

2023-02-25 19:51 UTC, 34fathombelow approved these changes
lgtm, thanks again!

2023-03-01 21:58 UTC, crenshaw-dev approved these changes
Thanks, @adamiBs!

2023-03-01 21:58 UTC, merged