docs: Enable dark mode and follow user preference
argoproj/argo-cd pull request #12631
Opened 2023-02-26 08:35 UTC by mortenn

Not just an aestethic change, some people with certain vision problems are helped by dark mode.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2023-02-27 17:53 UTC, morey-tech requested changes
Thanks for this! Minor change to pass the PR checks

2023-02-27 17:53 UTC, morey-tech commented on mkdocs.yml
> +        name: Switch to light mode
Fix spacing and remove comments to [pass the codegen action](https://github.com/argoproj/argo-cd/actions/runs/4274222709/jobs/7440682373).
```suggestion
  - media: "(prefers-color-scheme: light)"
    scheme: default
    primary: teal
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    scheme: slate
    primary: teal
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
```

2023-03-06 21:20 UTC, crenshaw-dev commented on mkdocs.yml
> +      name: Switch to light mode
```suggestion
  - media: "(prefers-color-scheme: light)"
    primary: teal
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: "(prefers-color-scheme: dark)"
    primary: teal
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
```

2023-03-07 01:22 UTC, crenshaw-dev approved these changes

2023-03-08 18:28 UTC, crenshaw-dev commented on mkdocs.yml
> +      name: Switch to light mode
```suggestion
  - media: '(prefers-color-scheme: light)'
    primary: teal
    scheme: default
    toggle:
      icon: material/brightness-7
      name: Switch to dark mode
  - media: '(prefers-color-scheme: dark)'
    primary: teal
    scheme: slate
    toggle:
      icon: material/brightness-4
      name: Switch to light mode
```

2023-03-08 19:46 UTC, merged

2023-03-08 19:52 UTC, 34fathombelow commented
@mortenn Thank you so much for this contribution.  It makes a night and day difference 😜