feat: add 'user' field to audit logs
argoproj/argo-cd pull request #12644
Opened 2023-02-27 20:10 UTC by crenshaw-dev

This will make it easier to determine who is doing what, without doing a lot of manual parsing.

2023-03-09 08:37 UTC, alexef requested changes
let's remove `<user> <action>` duplication

2023-03-09 08:37 UTC, alexef commented on server/application/application.go
>  	message := fmt.Sprintf("%s %s", user, action)
same

2023-03-09 08:37 UTC, alexef commented on server/applicationset/applicationset.go
>  	message := fmt.Sprintf("%s %s", user, action)
same

2023-03-09 08:37 UTC, alexef commented on server/project/project.go
>  	message := fmt.Sprintf("%s %s", user, action)
same

2023-03-09 19:12 UTC, crenshaw-dev commented on server/application/application.go
>  	message := fmt.Sprintf("%s %s", user, action)
The `message` field ends up populating the Event body that's created along with the log line. I think the duplication is necessary to serve both needs.

2023-03-14 20:28 UTC, alexef approved these changes

2023-03-14 20:28 UTC, alexef commented on server/application/application.go
>  	message := fmt.Sprintf("%s %s", user, action)
got it, makes sense

2023-03-16 20:19 UTC, pasha-codefresh approved these changes

2023-03-16 20:20 UTC, merged