fix: ignore gitlab projects w/o repository (#12819)
argoproj/argo-cd pull request #12820
Opened 2023-03-10 22:30 UTC by pjoomen

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2023-03-11 20:46 UTC, crenshaw-dev requested changes

2023-03-11 20:46 UTC, crenshaw-dev commented on applicationset/services/scm_provider/gitlab.go
> +		if resp != nil && resp.StatusCode == 404 {
```suggestion
		if resp != nil && resp.StatusCode == http.StatusNotFound {
```

2023-03-11 20:46 UTC, crenshaw-dev commented on applicationset/services/scm_provider/gitlab.go
> +		if resp != nil && resp.StatusCode == 404 {
```suggestion
		if resp != nil && resp.StatusCode == http.StatusNotFound {
```

2023-03-11 20:47 UTC, crenshaw-dev commented
/cherry-pick release-2.4

2023-03-11 20:47 UTC, crenshaw-dev commented
/cherry-pick release-2.5

2023-03-11 20:47 UTC, crenshaw-dev commented
/cherry-pick release-2.6

2023-03-12 00:54 UTC, jannfis approved these changes
LGTM!

2023-03-12 00:56 UTC, crenshaw-dev approved these changes

2023-03-12 00:56 UTC, merged