docs: Add Argo CD components architecture doc
argoproj/argo-cd pull request #13194
Opened 2023-04-11 19:38 UTC by leoluz

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

2023-04-24 18:09 UTC, crenshaw-dev requested changes

2023-04-24 18:09 UTC, crenshaw-dev commented on docs/developer-guide/architecture/components.md
> +  types of functionality should be implementation which drives for
```suggestion
  types of functionality should be implemented which drives for
```

2023-04-24 18:09 UTC, crenshaw-dev commented on docs/developer-guide/architecture/components.md
> +The diagram below have represented all dependencies between the
```suggestion
The diagram below has represented all dependencies between the
```

2023-04-24 18:09 UTC, crenshaw-dev commented on docs/developer-guide/architecture/components.md
> +Kubernetes resources to be provided in a Git repository.
```suggestion
### Git

As a gitops tool Argo CD requires that the desired state of the
Kubernetes resources to be provided in a Git repository.

We use "git" here to stand in for an actual git repo, a Helm repo,
or an OCI artifact repo. Argo CD supports all those options.
```

2023-04-24 18:15 UTC, crenshaw-dev approved these changes

2023-04-24 20:02 UTC, merged

2023-04-25 12:35 UTC, cjc7373 commented
Is it reasonable that this doc can be merged with [operator-manual/architecture](https://argo-cd.readthedocs.io/en/latest/operator-manual/architecture/)?