fix: incorrect instructions for site documentation
argoproj/argo-cd pull request #13209
Opened 2023-04-12 20:24 UTC by reginapizza

I noticed the docs for how to build and serve documentation locally were wrong, so making this PR to correct it. 
The make target for lint-docs was removed in https://github.com/argoproj/argo-cd/pull/8722 but was never removed from documentation. 

Proposed new changes look like:
![Screenshot from 2023-04-12 16-20-45](https://user-images.githubusercontent.com/50851526/231575908-6feaebc8-c218-4213-a878-163b1170965f.png)

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

2023-04-15 18:27 UTC, crenshaw-dev requested changes

2023-04-15 18:27 UTC, crenshaw-dev commented on docs/developer-guide/site.md
>  ```
I think we can just drop this whole section. `build-docs` doesn't actually check for broken links. And there's really no need to run `build-docs` if everything looks okay after `serve-docs`.

2023-04-22 20:03 UTC, ishitasequeira approved these changes

2023-05-27 20:20 UTC, crenshaw-dev approved these changes
Thanks, @reginapizza!

2023-05-27 20:20 UTC, merged

2023-05-27 20:20 UTC, crenshaw-dev commented
/cherry-pick release-2.7

2023-05-27 20:21 UTC, crenshaw-dev commented
/cherry-pick release-2.6

2023-05-27 20:21 UTC, crenshaw-dev commented
/cherry-pick release-2.5