fix: Allow notifications controller to notify on all namespaces
argoproj/argo-cd pull request #13352
Opened 2023-04-25 23:23 UTC by Niksko

This adds functionality to the notifications controller to be notified of and send notifications for applications in any namespace. The namespaces to watch are controlled by the same --application-namespaces and ARGOCD_APPLICATION_NAMESPACES variables as in the application controller.

Closes #12912
Closes #11252 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] TODO: I've updated documentation as required by this PR.
* [ ] TODO: Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

2023-04-25 23:28 UTC, Niksko commented
Hi folks, I'd appreciate a few pointers:

* Is there documentation for flags passed to the various commands, other than in the commands themselves? If so can you please point me to them, I'd be happy to update them.
* What sorts of tests are appropriate for this PR? I can't find any existing tests.

2023-05-15 03:04 UTC, iandelahorne commented
I'm facing this exact problem - we use Applications In Any Namespace, and would like to onboard Argo notifications. Thanks a lot for implementing this 🙏  

I tried this out in my cluster and found that I needed to add a ClusterRole with permissions necessary and bind it to the notifications controller's service account. 

Adding a clusterrole and clusterrolebinding to the manifests/cluster-rbac/notifications directory would make this smoother. Also, the deployment should pull `ARGOCD_APPLICATION_NAMESPACES` from the `argocd-cmd-params-cm` configmap similar to the applicationset controller does [here](https://github.com/argoproj/argo-cd/blob/7825821c1cda17b809e44b66cc5980fecf28af4f/manifests/base/applicationset-controller/argocd-applicationset-controller-deployment.yaml#L40-L45)

2023-05-15 15:53 UTC, iandelahorne commented
Another thing that came to mind is the templates in the notifications catalog use `oncePer: app.metadata.name`([example](https://github.com/argoproj/argo-cd/blob/master/notifications_catalog/triggers/on-created.yaml#L4)) which we would need to handle somehow.

2023-05-16 06:19 UTC, Niksko commented
@iandelahorne thanks for the feedback, I'll add in those permissions and handling of the once per namespace template field

2023-06-08 16:42 UTC, jaideepr97 commented
@Niksko 

https://argo-cd.readthedocs.io/en/stable/operator-manual/app-any-namespace/#change-workload-startup-parameters

The app namespace list can also be set in the `argocd-cmd-params-cm`, which I don't think the notifications-controller tracks today
https://github.com/argoproj/argo-cd/blob/master/manifests/install.yaml#L18874

Maybe that could also be addressed in this PR?

2023-08-11 15:46 UTC, major7x commented
Hallo! any updates on this PR? Would be greatly appreciated if this is looked at as it would be greatly beneficial. Thanks

2023-08-11 21:44 UTC, crenshaw-dev requested changes

2023-08-11 21:44 UTC, crenshaw-dev commented on notification_controller/controller/controller.go
> +	appProjInformer := newInformer(newAppProjClient(client), namespace, applicationNamespaces, "")
Projects still just live in the `argocd` namespace, so this informer shouldn't look at all `applicationNamespaces`.

2023-08-12 04:39 UTC, Niksko commented
Apologies folks, I do intend to get back to this, ideally within the next few weeks. If someone else wants to pick this up in the mean time and submit a fix I won't be offended, I acknowledge that I've let this drag on

2023-08-25 17:51 UTC, sthomson-wyn commented
Addressed comments from @iandelahorne @jaideepr97 @crenshaw-dev here: https://github.com/argoproj/argo-cd/pull/15247

2023-08-30 15:55 UTC, major7x commented
Thank you @sthomson-wyn! @crenshaw-dev would it suffice to proceed?

2023-10-06 20:41 UTC, crenshaw-dev commented
Superseded by https://github.com/argoproj/argo-cd/pull/15702

2023-10-06 20:41 UTC, closed without merging