fix: display valuesobject if set
argoproj/argo-cd pull request #14257
Opened 2023-06-28 15:39 UTC by blakepettersson

With #11538 we now have the ability to set helm values as an object instead of a string, but we also need to be able to correctly display it in the UI if it is set.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

2023-06-29 03:04 UTC, ishitasequeira approved these changes
LGTM!!

2023-06-29 05:27 UTC, alexef approved these changes
awesome

2023-06-29 21:52 UTC, crenshaw-dev requested changes
Read support looks good!

Do you have time to look at write behavior? If I make a change, it saves into the `values` field, creating duplicate config.

I also get this error message:

```
Unable to save changes: json: cannot unmarshal array into Go struct field ApplicationSourceHelm.spec.source.helm.values of type string
```

And then with the duplicate config, loading the Parameters tab fails because `/appdetails` returns 403 (forbidden) of all things.

2023-07-06 12:18 UTC, blakepettersson commented
@crenshaw-dev I updated the PR to save correctly if `valuesObject` is present, as well as unsetting `values` to prevent duplicating the same values, PTAL.

2023-07-06 20:44 UTC, crenshaw-dev commented
Hm. I'm still getting duplicate fields with the latest code. 
![image](https://github.com/argoproj/argo-cd/assets/350466/4bfb6593-1143-4fea-92d9-b455c285754b)

Revision: 2ce71eb04

2023-07-06 20:45 UTC, crenshaw-dev commented
That's after 

1) setting `valuesObject` in the Manifest tab
2) updating the values field in the Parameters tab
3) switching back to the Manifest tab to inspect

2023-07-06 21:24 UTC, crenshaw-dev commented
Thought I'd fix it with server-side normalization, but stuff is still broke. https://github.com/blakepettersson/argo-cd/pull/1

2023-07-09 13:18 UTC, blakepettersson commented
@crenshaw-dev this seems to be a UI issue - when checking the `Application` with `kubectl`, the `values` field is not present, only `valuesObject`; however both fields are definitely present when looking at the manifest through the UI. When doing a full refresh it's gone, right up until the point the view is toggled to another view. Once switched back, `values` re-appears 🤔 

```yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  destination:
    namespace: guestbook
    server: https://kubernetes.default.svc
  project: foobar
  source:
    chart: wordpress
    helm:
      valuesObject:
        wordpress:
          mariadb:
            db:
              password: barbarbar
            rootUser:
              password: bazbazbaz
          wordpressPassword: foo
    repoURL: https://charts.helm.sh/stable
    targetRevision: 9.0.3
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

```

2023-07-12 15:18 UTC, blakepettersson commented
Alright so I _think_ that this has been fixed with the addition of

1. Creating a deep copy of the `application` within that component
2. Only setting `spec.source.helm.values` on the application clone when the edit button has been pressed

The UI feels like treading on thin ice though; I was trying to look around all over the place to see where anything could go wrong but couldn't find anything so far. I'd love to find some time to make the component(s) more decoupled and testable, as it stands now it's a bit.. finicky. 😄

2023-07-19 18:48 UTC, blakepettersson commented
@crenshaw-dev would you happen to have time to take another look?

2023-07-19 20:23 UTC, crenshaw-dev commented
> The UI feels like treading on thin ice though

yes

> @crenshaw-dev would you happen to have time to take another look?

Yep! Maybe not today, but I'm putting it in the must-fix bucket for 2.8 GA. Thanks so much for tackling this!!!

2023-07-27 06:10 UTC, ishitasequeira approved these changes
I tested the feature with UI updates. The changes look good now!!

Tests:
1. App updated using spec:
```
source:
  repoURL: 'https://charts.helm.sh/stable'
  targetRevision: 9.0.3
  helm:
    valuesObject:
      wordpress:
        mariadb:
          db:
            password: barbarbar
          rootUser:
            password: bazbazbaz
        wordpressPassword: foo
  chart: wordpress
```


Shows below as spec output in UI (no values field visible)

<img width="706" alt="image" src="https://github.com/argoproj/argo-cd/assets/46771830/0a1ab11e-5bbe-4d03-8adc-85dedad91ee9">


I tried testing the feature with variations by updating the app manifest from UI and CLI:
- Adding only values field
- Adding only valuesObject
- Adding both values and valuesObject

2023-07-27 18:48 UTC, crenshaw-dev approved these changes

2023-07-27 18:48 UTC, crenshaw-dev commented
/cherry-pick release-2.8

2023-07-27 18:48 UTC, merged