fix(ui): handle undefined graphNode when grouping nodes
argoproj/argo-cd pull request #14261
Opened 2023-06-29 03:03 UTC by huynhsontung

After upgrading ArgoCD from v2.5.2 to v2.7.5, I noticed the UI would crash if I use node grouping in one of my apps. This causes by an unhandled condition when modifying the graph.

<img width="1509" alt="Screen Shot 2023-06-28 at 2 00 50 PM" src="https://github.com/argoproj/argo-cd/assets/31434093/45a4acdd-04da-4fbe-b7f8-85dbc060a0b6">

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

2023-06-29 21:21 UTC, crenshaw-dev commented
@ashutosh16 would you mind testing this fix?

2023-06-29 21:22 UTC, crenshaw-dev commented
/cherry-pick release-2.7

2023-06-29 21:22 UTC, crenshaw-dev commented
/cherry-pick release-2.8

2023-06-29 22:40 UTC, ashutosh16 approved these changes
LGTM

2023-06-30 21:57 UTC, huynhsontung commented
@ashutosh16 I think this is the only spot where this problem can occur since it is modifying the graph and reading it in the same loop.

https://github.com/argoproj/argo-cd/blob/1bffe34492031cd45e6c20364d713047ddc95813/ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx#L194C1-L205

2023-07-13 21:20 UTC, ashutosh16 commented
@huynhsontung  thats look good to me.
@crenshaw-dev  let's merge the PR.

2023-12-01 15:07 UTC, crenshaw-dev approved these changes

2024-02-06 20:30 UTC, todaywasawesome requested changes
Needs changes :D

2024-02-06 20:30 UTC, closed without merging

2024-02-06 20:30 UTC, todaywasawesome commented
@huynhsontung closing this PR as it appears to be empty now. Feel free to reopen if it's still an issue.