Overlay selector of argocd-redis-ha service
argoproj/argo-cd pull request #1436
Opened 2019-04-11 13:31 UTC by KarstenSiemer

The selector of the argocd-redis-ha service wasn't being overlayed and the service never got to have endpoints

2019-04-11 13:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=1436) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=1436) before we can accept your contribution.<br/><hr/>**k.siemer** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=1436) it.</sub>

2019-04-11 14:44 UTC, alexec commented
@KarstenSiemer - can you please sign the CLA? We need that to accept your contribution. Thank you.

2019-04-12 07:11 UTC, KarstenSiemer commented
@alexec i did sign it yesterday, why is it still pending?

2019-04-12 14:30 UTC, alexmt approved these changes

2019-04-12 14:32 UTC, alexmt requested changes
Thank you for contribution @KarstenSiemer! Please run `make manifests` to regenerate `install.yaml` and `namespace-install.yaml` files.

2019-04-12 15:47 UTC, KarstenSiemer commented
could you write into a readme or somewhere what kinds and versions you used because i had to make two changes to run the scripts.
In `/hack/update-manifests.sh` is needed to change the shebang like this:
```
#!/bin/sh
set -x -e
```
or else it gives me an `illegal option -` error. On my workstation the default for sh is dash with the version of 0.5.8-2.4.
Also i can't use tar in the same way:
```
-templates=$(tar -tf ./chart/charts/redis-ha-*.tgz 'redis-ha/templates/redis-*.yaml')
+templates=$(tar -tf ./chart/charts/redis-ha-*.tgz --wildcards | grep redis-ha/templates/redis-.*.yaml)
```
I am using `tar (GNU tar) 1.29`
i wont commit these changes of course.
I also do not understand why the validation part in the install.yaml is not already committed since this is part of the crd and was also rendered for me with `make manifests`.
i now removed the validation part in the install yamls manually.

2019-04-12 16:16 UTC, alexmt commented
Looks like `#!/bin/sh -x -e` does not work on linux (tried with ubuntu). We are using mac. The validation was added because we forgot to run `make manifests` after modifying CRDs. Will address scripts compatibility with linux and regenerate manifests in next PR. 

Thank you, @KarstenSiemer ! Merging

2019-04-12 16:16 UTC, alexmt approved these changes

2019-04-12 16:17 UTC, merged