fix(cli): add support for components with non-default names (#10200)
argoproj/argo-cd pull request #14605
Opened 2023-07-19 15:49 UTC by crenshaw-dev

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

2023-08-22 01:26 UTC, ishitasequeira requested changes

2023-08-22 01:26 UTC, ishitasequeira commented on cmd/argocd/commands/admin/cluster.go
> +func loadClusters(ctx context.Context, kubeClient *kubernetes.Clientset, appClient *versioned.Clientset, replicas int, namespace string, portForwardRedis bool, cacheSrc func() (*appstatecache.Cache,
rename the variable to `redisHaHaproxyName ` -> `redisHaproxyName`?

2023-08-22 01:26 UTC, ishitasequeira commented on common/common.go
> +	LabelKeyAppName = "app.kubernetes.io/name"
We should change the comment here to  below or something similar?
```
LabelKeyAppName is the label key to use to uniquely identify name of the Kubernetes application
```

2023-08-22 01:26 UTC, ishitasequeira commented on common/common.go
> +	EnvRedisHaHaproxyName = "ARGOCD_REDIS_HAPROXY_NAME"
Should we represent in the comments that the env variable holds the custom name of the component and not the pod selector label?

2023-08-22 01:35 UTC, ishitasequeira reviewed
Should we also add the same change for applicationset_controller as well?

2023-08-22 17:37 UTC, crenshaw-dev commented
@ishitasequeira completed all the above! Can you detail more what changes you're thinking about for the applicationset controller?

2023-08-22 17:38 UTC, crenshaw-dev commented
@ishitasequeira I don't think the Argo CD API client currently accepts an appset controller name, presumably because the client does not interact with that controller in any way yet.

2023-08-22 19:23 UTC, ishitasequeira commented
> @ishitasequeira I don't think the Argo CD API client currently accepts an appset controller name, presumably because the client does not interact with that controller in any way yet.

That makes sense!! We can ignore the appset controller comment.

2023-08-22 19:23 UTC, ishitasequeira approved these changes
Thanks @crenshaw-dev, LGTM!!

2023-08-22 19:29 UTC, merged

2023-10-09 13:06 UTC, keskad commented
Thanks!