feat(cli): support apply out of sync flag only
argoproj/argo-cd pull request #14624
Opened 2023-07-20 15:55 UTC by pasha-codefresh

2023-08-01 00:21 UTC, jannfis commented
@pasha-codefresh The code doesn't seem to compile, PTAL.

2023-08-09 13:13 UTC, pasha-codefresh commented
@jannfis , yes, sorry, moving it to draft. I am working on e2e things and code completion

2023-08-09 13:15 UTC, pasha-codefresh commented
Depend on this PR 
https://github.com/argoproj/gitops-engine/pull/533

2023-08-09 13:45 UTC, crenshaw-dev commented
@pasha-codefresh merged the gitops-engine PR

2023-08-11 19:02 UTC, pasha-codefresh commented
@jannfis @crenshaw-dev this one is ready for review

2023-08-11 19:43 UTC, crenshaw-dev commented
@pasha-codefresh looks like it needs one docs tweak (i.e. CLI codegen).

2023-08-11 19:45 UTC, crenshaw-dev requested changes

2023-08-11 19:45 UTC, crenshaw-dev commented on cmd/argocd/commands/app.go
> +	command.Flags().BoolVar(&applyOutOfSyncOnly, "apply-out-of-sync-only", false, "Use out-of-sync apply that sync only out of sync resources")
```suggestion
	command.Flags().BoolVar(&applyOutOfSyncOnly, "apply-out-of-sync-only", false, "Sync only out-of-sync resources")
```

I'd simplify the language just a bit.

2023-08-14 19:23 UTC, pasha-codefresh commented
@crenshaw-dev could you please take a look?

2023-08-14 19:53 UTC, crenshaw-dev approved these changes
lgtm, thanks Pasha!

2023-08-14 19:53 UTC, merged