feat(appset): added topic (tag) filter for Gitlab SCM
argoproj/argo-cd pull request #14965
Opened 2023-08-08 20:41 UTC by prune998

Gitlab projects now have `topics` values that are an array of strings that can be associated to repos, like `tags` (now deprecated).

The PR adds a new Gitlab SCM value named `topic` in the CRD that enable to filter targeted repos using a `topic`.

`topic` is a single value string that is used to construct the Gitlab API request to list repos. Not setting it will keep it empty = matching all repos (other selectors still apply, like subgroup and shared projects).

This allows to `filter first` the repo list, cutting down the costs of grabbing the branches and folder tree. It is particularly beneficial in a large org with many repos/sub-folders.

2023-08-09 04:18 UTC, ishitasequeira requested changes
Haven't tested the PR yet but have left some comments.

2023-08-09 11:57 UTC, prune998 commented on applicationset/services/scm_provider/gitlab_test.go
> +		t.Log(r.RequestURI)
done

2023-08-09 11:58 UTC, prune998 commented on assets/swagger.json
> +          "description": "Filter repos list based on Gitlab Topic (tag).",
the `tag` I'm reffering to is actually `tag_list` from https://docs.gitlab.com/ee/api/projects.html#removals-in-api-v5. 
Maybe it's not worth mentioning it at all...

2023-08-09 13:05 UTC, prune998 commented
> Haven't tested the PR yet but have left some comments.

Thanks for the review. Code updated to resolve your comments.

2023-08-10 20:37 UTC, prune998 commented
I guess everything is fine now @ishitasequeira ?

2023-08-17 02:25 UTC, ishitasequeira requested changes

2023-08-17 11:56 UTC, prune998 commented
all done @ishitasequeira, sorry I forgot those...

2023-08-20 22:17 UTC, ishitasequeira approved these changes
LGTM!!

2023-08-20 22:18 UTC, merged

2023-08-21 12:32 UTC, prune998 commented
thanks @ishitasequeira !