docs: Add documentation for Zitadel SSO integration
argoproj/argo-cd pull request #15029
Opened 2023-08-12 10:55 UTC by stephanrenggli

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

Please see [Contribution FAQs](https://argo-cd.readthedocs.io/en/latest/developer-guide/faq/) if you have questions about your pull-request.

This PR adds documentation to the User Management section to document integration of Zitadel SSO with ArgoCD as proposed in this discussion: https://github.com/argoproj/argo-cd/discussions/11855#

2023-08-12 12:35 UTC, fforootd reviewed
Nice PR!

Only some really small feedbacks from my end.

Thank you for doing this.

2023-08-12 12:35 UTC, fforootd commented on docs/operator-manual/user-management/zitadel.md
> +These instructions will take you through the entire process of getting your ArgoCD application authenticating with Zitadel. You will create an application within Zitadel and configure ArgoCD to use Z
```suggestion
These instructions will take you through the entire process of getting your ArgoCD application authenticating and authorizing with Zitadel. You will create an application within Zitadel and configure ArgoCD to use Zitadel for authentication using roles set in Zitadel to determine privileges in ArgoCD.
```

2023-08-12 12:35 UTC, fforootd commented on docs/operator-manual/user-management/zitadel.md
> +4. Set up a action in Zitadel
```suggestion
4. Set up an action in Zitadel
```

2023-08-12 12:47 UTC, fforootd approved these changes

2023-08-16 14:25 UTC, todaywasawesome requested changes
Looks great, I made a few small grammar edits. Once those are accepted, I'll approve.

2023-08-16 14:25 UTC, todaywasawesome commented on docs/operator-manual/user-management/zitadel.md
> +First we will create a new project within Zitadel. Go to **Projects** and select **Create New Project**.
```suggestion
First, we will create a new project within Zitadel. Go to **Projects** and select **Create New Project**.  
```

2023-08-16 14:25 UTC, todaywasawesome commented on docs/operator-manual/user-management/zitadel.md
> +Deploy your ArgoCD configmaps. ArgoCD and Zitadel should now be setup correctly to allow users to log in to ArgoCD using Zitadel.
```suggestion
Deploy your ArgoCD configmaps. ArgoCD and Zitadel should now be set up correctly to allow users to log in to ArgoCD using Zitadel.
```

2023-08-16 14:32 UTC, stephanrenggli commented
Thanks for the suggestions!

2023-08-16 14:34 UTC, todaywasawesome approved these changes

2023-08-21 13:39 UTC, jannfis commented
Thanks! Unfortunately, this page is not linked from the navigation menu. It needs to be linked [here](https://github.com/argoproj/argo-cd/blob/dc8d729078df6fe9d4c480df0e67b2402af75e0b/mkdocs.yml#L29)

2023-08-21 14:42 UTC, pasha-codefresh approved these changes

2023-10-01 11:19 UTC, merged