chore: wrap error objects to include context (#10592)
argoproj/argo-cd pull request #15055
Opened 2023-08-15 06:13 UTC by Pawank06

Fix for https://github.com/argoproj/argo-cd/issues/10592

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

2023-08-15 13:48 UTC, crenshaw-dev requested changes
Looking good! Would you mind replacing `%v` with `%w` in each case?

2023-08-15 13:48 UTC, crenshaw-dev commented on applicationset/utils/utils.go
> +				return fmt.Errorf("error during deep replacement of field #%d: %v", i, err)
```suggestion
				return fmt.Errorf("error during deep replacement of field at index %d: %v", i, err)
```

2023-08-15 13:49 UTC, Pawank06 commented on applicationset/utils/utils.go
> +				return fmt.Errorf("error during deep replacement of field #%d: %v", i, err)
Ok sure!

2023-08-15 17:43 UTC, crenshaw-dev commented on applicationset/utils/utils.go
> +				return fmt.Errorf("error during deep replacement of field #%d: %w", i, err)
```suggestion
				return fmt.Errorf("error during deep replacement of field at index %d: %w", i, err)
```

2023-08-15 17:44 UTC, crenshaw-dev approved these changes

2023-08-15 17:45 UTC, crenshaw-dev commented on applicationset/utils/utils.go
> +			return fmt.Errorf("error during deep replacement: %w", err)
```suggestion
				return fmt.Errorf("error during deep replacement: %w", err)
```

2023-08-16 14:47 UTC, crenshaw-dev requested changes
Had a change of heart on some of these.

2023-08-16 14:47 UTC, crenshaw-dev commented on applicationset/utils/utils.go
> +			return fmt.Errorf("error during deep replacement: %w", err)
```suggestion
			// Not wrapping the error, since this is a recursive function. Avoids excessively long error messages.
			return err
```

2023-08-16 14:47 UTC, crenshaw-dev commented on applicationset/utils/utils.go
> +				return fmt.Errorf("error during deep replacement: %w", err)
```suggestion
				// Not wrapping the error, since this is a recursive function. Avoids excessively long error messages.
				return err
```

2023-08-16 14:47 UTC, crenshaw-dev commented on applicationset/utils/utils.go
> +				return fmt.Errorf("error during deep replacement of field at index %d: %w", i, err)
```suggestion
				// Not wrapping the error, since this is a recursive function. Avoids excessively long error messages.
				return err
```

2023-08-16 14:47 UTC, crenshaw-dev commented on applicationset/utils/utils.go
> +				return fmt.Errorf("error during deep replacement of element at index %d: %w", i, err)
```suggestion
				// Not wrapping the error, since this is a recursive function. Avoids excessively long error messages.
				return err
```

2023-08-16 14:47 UTC, crenshaw-dev commented on applicationset/utils/utils.go
> +				return fmt.Errorf("error during deep replacement: %w", err)
```suggestion
				// Not wrapping the error, since this is a recursive function. Avoids excessively long error messages.
				return err
```

2023-08-16 18:08 UTC, crenshaw-dev approved these changes

2023-08-17 16:46 UTC, merged