feat: Include destination cluster in build environment (14957)
argoproj/argo-cd pull request #15155
Opened 2023-08-22 15:48 UTC by christianh814

Include destination cluster in build environment. Fixes #14957 

It returns both `ARGOCD_APP_CLUSTER_NAME` and `ARGOCD_APP_CLUSTER_SERVER` with the assumption that the end user knows which one to use.

2023-08-22 17:14 UTC, crenshaw-dev requested changes

2024-06-11 19:11 UTC, kencochrane commented
@christianh814, what do you want to do with this PR? It hasn't moved in 10+ months, so do you want to close it?

2024-06-11 19:13 UTC, christianh814 commented
> @christianh814, what do you want to do with this PR? It hasn't moved in 10+ months, so do you want to close it?

My bandwidth is low to revisit this. Unless @blakepettersson wants to pick this up, we should probably close it.

2024-06-11 19:22 UTC, blakepettersson commented
I can take it - it's not too much of a bother to implement 👍

2024-06-13 23:34 UTC, closed without merging