fix: Allow notifications controller to notify on all namespaces (cont.)
argoproj/argo-cd pull request #15247
Opened 2023-08-25 17:32 UTC by sthomson-wyn

This is a continuation of #13352 which addresses the following:
https://github.com/argoproj/argo-cd/pull/13352#issuecomment-1547126375
https://github.com/argoproj/argo-cd/pull/13352#issuecomment-1583012193
https://github.com/argoproj/argo-cd/pull/13352#discussion_r1291797709

This adds functionality to the notifications controller to be notified of and send notifications for applications in any namespace. The namespaces to watch are controlled by the same --application-namespaces and ARGOCD_APPLICATION_NAMESPACES variables as in the application controller.

Closes https://github.com/argoproj/argo-cd/issues/12912
Closes https://github.com/argoproj/argo-cd/issues/11252

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

2023-09-11 12:38 UTC, sthomson-wyn commented
Thanks @mayzhang2000 , I've added the suggested change via https://github.com/argoproj/argo-cd/pull/15247/commits/baa28c84e3adc2efe4d035ae0f6278663f3a0ab2

2023-09-12 20:41 UTC, mayzhang2000 commented
Thank you @sthomson-wyn! 
Tested and worked on my local. Could you please add some tests and documentation?

2023-09-27 17:21 UTC, crenshaw-dev requested changes

2023-09-27 17:21 UTC, crenshaw-dev commented on notification_controller/controller/controller.go
> -	resClient := client.Resource(appProjects).Namespace(namespace)
Is this necessary? AppProjects are still restricted to only living in the controller namespace.

2023-09-27 17:21 UTC, crenshaw-dev commented on examples/k8s-rbac/argocd-server-applications/argocd-notifications-controller-rbac-clusterrole.yaml
> +  - "appprojects"
Since AppProjects only exist in the controller's namespace, I don't think this is necessary at the cluster level.

2023-09-27 17:21 UTC, crenshaw-dev commented on examples/k8s-rbac/argocd-server-applications/argocd-notifications-controller-rbac-clusterrole.yaml
> +  name: argocd-notifications-controller-cluster-apps
Should the apps-in-any-namespace docs be updated to mention the two new resources?

2023-09-27 17:21 UTC, crenshaw-dev commented on notification_controller/controller/controller.go
> +			}
Can we get test coverage on this? If a full test of the `notificationController` would be prohibitively complex, we could pull out this function and just unit-test that.

2023-09-27 17:21 UTC, crenshaw-dev commented on notification_controller/controller/controller.go
> +					return nil, err
```suggestion
					return nil, fmt.Errorf("failed to list applications: %w", err)
```

2023-09-27 17:21 UTC, crenshaw-dev commented on notification_controller/controller/controller_test.go
> +		[]string{},
Would you mind adding some unit tests to cover the apps-in-any-namespace behavior? I think at the minimum we should make sure the notifications controller refuses to manage apps outside the specified namespaces.

2023-09-27 20:58 UTC, mayzhang2000 commented
Thank you @sthomson-wyn and @crenshaw-dev !

I created below PR as a continuation of this PR:
https://github.com/argoproj/argo-cd/pull/15702

2023-10-06 20:41 UTC, closed without merging

2023-10-06 20:41 UTC, crenshaw-dev commented
Superseded by https://github.com/argoproj/argo-cd/pull/15702