fix(redis): go-redis v9 regression missing metrics and reconnect hook (#13415)
argoproj/argo-cd pull request #15275
Opened 2023-08-29 13:29 UTC by phanama

The update to go-redis v9 broke redis metrics generation. The `BeforeProcess()` and `AfterProcess()` hooks were replaced by `ProcessHook()` and `DialHook()` in v9 ([ref](https://pkg.go.dev/github.com/go-redis/redis/v9#Hook)), which are implemented as empty funcs in our codebase.

This PR moves the implementations to the correct functions and improves tests.

ref: https://github.com/argoproj/argo-cd/commit/7b74e1993e6bd8ed063f4b50414163842e08f359

Fixes https://github.com/argoproj/argo-cd/issues/13415
Most probably also fixes an unreported regression of https://github.com/argoproj/argo-cd/pull/7207

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

2023-09-27 03:21 UTC, phanama commented
@crenshaw-dev 
Sorry for mentioning directly, could you please take a look? 🙏 
Redis metrics have been missing since v2.7, I think we need to cherrypick for 2.7-2.9

2024-01-12 20:42 UTC, 34fathombelow commented
@leoluz I created a image based on the `phanama:go-redis-v9-regression` branch and tested.  I can confirm that this PR does indeed fix the issue.  When you get a minute can you do a code review?

2024-01-12 20:43 UTC, 34fathombelow approved these changes
LGTM, thanks for the PR great work!

2024-01-18 19:11 UTC, leoluz requested changes
Minor comment.. Otherwise LGTM

2024-01-18 19:11 UTC, leoluz commented on util/cache/redis_hook.go
> +var dnsError *net.DNSError
Is there any good reason to have this declared at the package global? If not, can you move this variable inside the function that depends on it and avoid the global state?

2024-01-29 15:31 UTC, leoluz approved these changes
LGTM

2024-01-29 15:31 UTC, merged

2024-01-29 15:39 UTC, leoluz commented
/cherry-pick release-2.8

2024-01-29 15:39 UTC, leoluz commented
/cherry-pick release-2.9

2024-01-29 15:39 UTC, leoluz commented
/cherry-pick release-2.10

2024-01-29 15:43 UTC, crenshaw-dev commented
/cherry-pick release-2.8

2024-01-29 15:43 UTC, crenshaw-dev commented
/cherry-pick release-2.9

2024-01-29 15:44 UTC, crenshaw-dev commented
/cherry-pick release-2.10