feat(cli): tree option in output flag for app sync, app wait and app rollback for tree view
argoproj/argo-cd pull request #15572
Opened 2023-09-19 16:15 UTC by schakrad

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

2023-09-19 19:36 UTC, crenshaw-dev requested changes
Small things :-)

2023-09-19 19:36 UTC, crenshaw-dev commented on cmd/argocd/commands/app.go
> +			output, _ = c.Flags().GetString("output")
I don't think this is needed. The `&output` reference below will make sure the `output` value is updated correctly.

2023-09-19 19:36 UTC, crenshaw-dev commented on cmd/argocd/commands/app.go
> +			output, _ = c.Flags().GetString("output")
Ditto, not needed.

2023-09-19 19:36 UTC, crenshaw-dev commented on cmd/argocd/commands/app.go
> +			output, _ = c.Flags().GetString("output")
Not needed

2023-09-20 00:20 UTC, schakrad commented on cmd/argocd/commands/app.go
> +			output, _ = c.Flags().GetString("output")
Removed the stmnt.

2023-09-20 00:39 UTC, schakrad commented on cmd/argocd/commands/app.go
> +			output, _ = c.Flags().GetString("output")
Made the change

2023-09-20 19:40 UTC, crenshaw-dev requested changes

2023-09-20 21:27 UTC, schakrad commented on cmd/argocd/commands/app.go
> +			}
Made the change. Thanks Michael.

2023-09-20 21:27 UTC, schakrad commented on cmd/argocd/commands/app.go
> +		switch output {
Nops Michael,  It is not entirely duplicated.printHeader is a functionality that is extra in app get command, which runs for wide,tree and tree=detailed and not for json,yaml. I initially thought of refactoring that command , but printHeader function is preventing this.

2023-09-22 13:56 UTC, crenshaw-dev commented
> Can we make the initial printout respect the -o flag? Looks like right now it always prints the table.

Ignore that one. I misunderstood how that initial printout is working. Let's leave it as a "table" view.

2023-09-22 18:45 UTC, crenshaw-dev approved these changes

2023-09-22 18:45 UTC, merged