chore(deps): bump gitops-engine
argoproj/argo-cd pull request #15736
Opened 2023-09-29 20:39 UTC by crenshaw-dev

In order to get this change: https://github.com/argoproj/gitops-engine/pull/541

2023-10-02 15:41 UTC, ishitasequeira requested changes
@crenshaw-dev there was an issue building go modules.

2023-10-02 15:56 UTC, crenshaw-dev commented
@ishitasequeira fixed!

2023-10-02 16:21 UTC, ishitasequeira approved these changes

2023-10-05 14:55 UTC, todaywasawesome approved these changes

2023-10-06 22:04 UTC, merged