fix: Add ENV variable to configure GRPC Keep Alive Time (#15656)
argoproj/argo-cd pull request #15806
Opened 2023-10-04 03:02 UTC by BhavikaSharma

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.

Description:
When creating an application that runs a custom plugin that runs for over ~45 seconds, the user is returned an `ENHANCE_YOUR_CALM` error. The CMP timeout is a configurable value with a default of 60s. Multiple `argocd app` commands run the CMP (e.g. as validation). Therefore, the `GRPCKeepAliveEnforcementMinimum` should be configurable.

Closes #15656

2023-10-04 21:42 UTC, BhavikaSharma commented
There seems to be flakiness in the e2e tests. A different test seems to be failing in each run despite no changes, e.g.

Passing: https://github.com/argoproj/argo-cd/actions/runs/6401735616/job/17377379600
Failing: https://github.com/argoproj/argo-cd/actions/runs/6409855823/job/17403620905

Passing: https://github.com/argoproj/argo-cd/actions/runs/6401032458/job/17375509894
Failing: https://github.com/argoproj/argo-cd/actions/runs/6401735616/job/17377289561

Rerunning the pipeline as described [here](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/#why-does-the-test-or-e2e-steps-fail).

2023-10-09 20:27 UTC, renperez-cpi commented
@BhavikaSharma any update on this?

2023-10-11 14:56 UTC, jcogilvie commented
The most recent failure seems to indicate that upstream redis has changed.  Is this a problem for this PR?

2023-10-11 14:57 UTC, crenshaw-dev commented
@jcogilvie merged upstream, should fix the CI failure.

2023-10-11 16:57 UTC, BhavikaSharma commented
@crenshaw-dev , thanks for merging in the upstream. We seem to have a green build.

2023-10-17 03:08 UTC, renperez-cpi commented
@BhavikaSharma is this going to be merge soon? argo seems to be getting worst.
```
2023/10/16 19:29:00 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
2023/10/16 19:41:12 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
2023/10/16 19:50:21 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
2023/10/16 19:54:25 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
2023/10/16 20:06:37 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
2023/10/16 20:16:47 ERROR: [transport] Client received GoAway with error code ENHANCE_YOUR_CALM and debug data equal to ASCII "too_many_pings".
time="2023-10-16T20:31:25Z" level=fatal msg="rpc error: code = Unknown desc = POST https://***:4[43](https://github.com/ChargePoint/payment-services/actions/runs/6535831960/job/17753819951#step:9:44)/application.ApplicationService/Get failed with status code 504"
Error: Process completed with exit code 20.
```

2023-10-17 12:27 UTC, ishitasequeira requested changes
As https://github.com/argoproj/argo-cd/pull/15708 was merged, can you add pkg/apiclient/grpcproxy.go to the change as well?

2023-10-17 18:34 UTC, BhavikaSharma commented
I have added `pkg/apiclient/grpcproxy.go` to the change as well.

2023-10-18 02:58 UTC, ishitasequeira approved these changes
One minor suggestion. Otherwise LGTM!!

2023-10-18 02:58 UTC, ishitasequeira commented on docs/user-guide/environment-variables.md
> +| `ARGOCD_GRPC_KEEP_ALIVE_MIN`         | defines the GRPCKeepAliveEnforcementMinimum, used in the grpc.KeepaliveEnforcementPolicy. Expects a "Duration" format (e.g. `10s`).
Let's mention the default value. 
```suggestion
| `ARGOCD_GRPC_KEEP_ALIVE_MIN`         | defines the GRPCKeepAliveEnforcementMinimum, used in the grpc.KeepaliveEnforcementPolicy. Expects a "Duration" format (default `10s`).                                                                       |
```

2023-10-18 20:53 UTC, BhavikaSharma commented
@ishitasequeira thanks for the approval! I have added the change suggested above and merged in the latest changes from main with a passing pipeline. If it looks good, would you be able to help merge? Thanks 😄 .

2023-10-18 20:56 UTC, ishitasequeira approved these changes

2023-10-18 20:57 UTC, merged