upgrade k8s version and client-go
argoproj/argo-cd pull request #15852
Opened 2023-10-06 18:29 UTC by blakepettersson

This is a continuation of #13965, but with the merge conflicts fixed.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

2023-10-07 19:32 UTC, blakepettersson commented
@crenshaw-dev this branch is looking good now 😄

2023-10-13 18:39 UTC, crenshaw-dev requested changes

2023-10-13 18:39 UTC, crenshaw-dev commented on go.mod
> +	github.com/argoproj/gitops-engine => github.com/fengshunli/gitops-engine v0.7.1-0.20230922195635-cbe8d1c14245
@blakepettersson can you update this now that I've merged the gitops-engine PR? https://github.com/argoproj/gitops-engine/pull/530

2023-10-18 13:14 UTC, blakepettersson commented
@crenshaw-dev done 😄

2023-10-18 15:16 UTC, crenshaw-dev approved these changes
Heck yeah

2023-10-18 15:17 UTC, merged