feat(cli): add the repocred-list-example (#15690)
argoproj/argo-cd pull request #15869
Opened 2023-10-08 07:12 UTC by gaurangkudale

add the repocred-list-example (#15690)

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

2023-10-10 23:01 UTC, ishitasequeira requested changes

2023-10-10 23:31 UTC, gaurangkudale commented on cmd/argocd/commands/repocreds.go
> +			# List all the configured repository credentials in url format
Got it!
Changes are made as per your suggestions

2023-10-11 00:04 UTC, gaurangkudale commented on cmd/argocd/commands/repocreds.go
> +			# List all the configured repository credentials in url format
`Integration tests / Run unit tests with -race for Go packages (pull_request) ` This workflow is failing and the error says  `Received unexpected error:
        	            	Token is expired` 
@ishitasequeira Do we need to rerun the workflow in this case?

2023-10-18 02:45 UTC, ishitasequeira approved these changes
LGTM!!

2023-10-18 02:45 UTC, merged