fix(appset): prevent app deletion according to appset policy (#12172)
argoproj/argo-cd pull request #15903
Opened 2023-10-11 15:27 UTC by mikutas

Fixes #12172 

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

2023-11-08 02:59 UTC, ishitasequeira approved these changes
Thanks @mikutas for the PR!!
The change looks good!!

2023-11-08 03:00 UTC, ishitasequeira requested changes
@mikutas, can you resolve the conflicts?

2023-11-08 04:13 UTC, mikutas commented
rebased but some checks failed. I'm trying to fix in #16275

2023-11-10 04:06 UTC, ishitasequeira approved these changes

2023-11-10 04:06 UTC, merged