fix: implement graceful shutdown for api server
argoproj/argo-cd pull request #15938
Opened 2023-10-13 00:27 UTC by leoluz

Signed-off-by: Leonardo Luz Almeida <leonardo_almeida@intuit.com>

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

2024-06-12 22:09 UTC, crenshaw-dev requested changes
Having trouble getting code coverage for api-server. I hoped graceful shutdown would help, so was testing this.

2024-06-12 22:09 UTC, crenshaw-dev commented on server/server.go
> +		}()
Needs a nil check, since httpsS isn't necessarily set.

2024-06-12 22:09 UTC, crenshaw-dev commented on server/server.go
> +		}()
Needs a nil check, since tlsm isn't necessarily set.

2024-11-28 06:26 UTC, andrii-korotkov-verkada commented
I spoke with @leoluz about picking up this work. I've filed https://github.com/argoproj/argo-cd/pull/20981, since there's been merge conflicts and resolve conflicts didn't work perhaps due to age. I did some fixes and added co-authors.

2024-11-28 06:26 UTC, closed without merging