feat: Added example to admin-cluster.go and projectwindow.go files (RESOLVED)
argoproj/argo-cd pull request #16128
Opened 2023-10-26 17:46 UTC by surajyadav1108

part of the issue #15690 
and part of the PR #16103 

resolved issues 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.

2023-10-28 16:58 UTC, crenshaw-dev requested changes, later dismissed
I think many of these examples rely too heavily on demonstrating global flags. Can you rework the examples to rely only on flags specific to the command?

2023-10-29 08:02 UTC, surajyadav1108 commented
@crenshaw-dev hmm looking back to it yes you are correct,  I will do the required changes

2023-10-30 05:34 UTC, surajyadav1108 commented
@crenshaw-dev made the changes.

2023-11-02 00:55 UTC, ishitasequeira requested changes

2023-11-02 00:55 UTC, ishitasequeira commented on cmd/argocd/commands/admin/cluster.go
> +argocd admin cluster kubeconfig https://cluster-api-url:6443 /path/to/output/kubeconfig.yaml --insecure-skip-tls-verify`,
Please follow the same format for the comments of the command. For example, keep first character capital everywhere.

2023-11-02 00:55 UTC, ishitasequeira commented on cmd/argocd/commands/projectwindows.go
> +argocd proj windows list <project-name>`,
Same comment here. Keep uniform formatting.

2023-11-02 00:55 UTC, ishitasequeira commented on cmd/argocd/commands/projectwindows.go
> +argocd proj windows enable-manual-sync my-app-project --message "Manual sync initiated by admin."`,
Same here.

2023-11-02 16:01 UTC, chengfang commented on cmd/argocd/commands/projectwindows.go
> +agrocd proj windows disable-manual-sync default 0`,
command name should be `argocd`

2023-11-02 16:01 UTC, chengfang commented on cmd/argocd/commands/projectwindows.go
> +agrocd proj windows enable-manual-sync default 2
command name should be `argocd`

2023-11-02 17:22 UTC, surajyadav1108 commented on cmd/argocd/commands/projectwindows.go
> +agrocd proj windows disable-manual-sync default 0`,
man

2023-11-02 17:30 UTC, chengfang approved these changes

2023-11-03 22:31 UTC, ishitasequeira requested changes

2023-11-03 22:31 UTC, ishitasequeira commented on cmd/argocd/commands/admin/cluster.go
> +#listing available kubeconfigs for clusters managed by argocd
```suggestion
#Listing available kubeconfigs for clusters managed by argocd
```

2023-11-03 22:31 UTC, ishitasequeira commented on cmd/argocd/commands/projectwindows.go
> +#list project sync windows
```suggestion
#List project sync windows
```

2023-11-04 09:48 UTC, surajyadav1108 commented on cmd/argocd/commands/admin/cluster.go
> +#listing available kubeconfigs for clusters managed by argocd
never been this  blind

2023-11-04 09:53 UTC, surajyadav1108 commented
@ishitasequeira  build test UI code is  failing even  after retriggering. You can try a manual build to check for errors. I haven't changed anything apart from correcting a spelling mistake, so this check should pass.

2023-11-08 11:51 UTC, surajyadav1108 commented
@ishitasequeira ok found out why the Build test  UI code was failing and fixed it but after updating the branch by pulling in from upstream there were some issues in code that has already been merged into upstream master and that's why my master update check fails for lint and tests but there is a open PR correcting this issue  
#16275  I believe after that PR merge that will resolve these errors  too.

2023-11-09 03:02 UTC, ishitasequeira approved these changes
@surajyadav1108 , Please rebase the PR again. The PR #16275 is merged.

2023-11-09 08:11 UTC, surajyadav1108 commented
@ishitasequeira 
It seems like make lint-ui passes with no issues on my local clone, but it keeps failing here, and I'm not sure why it's happening repeatedly. Instead of making numerous failing commits, I suggest closing this for now. I'll delete my forked repo and reopen a PR after some time. or I can open a new PR now if you say so  what do you suggest?

2023-11-11 07:44 UTC, surajyadav1108 commented
Updating the master branch had no issues is it should be. @ishitasequeira

2023-11-16 12:32 UTC, ishitasequeira approved these changes
Thanks @surajyadav1108 !! LGTM!!

2023-11-17 10:06 UTC, surajyadav1108 commented
@ishitasequeira is there anything stopping auto-merge?

2023-11-30 03:51 UTC, ishitasequeira approved these changes
Thanks @surajyadav1108 for addressing all the comments. Will merge the PR.

2023-11-30 03:52 UTC, merged