fix: notify operators about how to disable in-cluster on remove
argoproj/argo-cd pull request #16556
Opened 2023-12-06 15:42 UTC by morremeyer

This notifies the operator how they can disable the in-cluster cluster
if they try to remove it.

Closes #14531.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] _not applicable_ ~I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.~ 
* [x] Does this PR require documentation updates? - No.
* [x] _not applicable ~I've updated documentation as required by this PR.~
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] _not applicable_ ~My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.~
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

2023-12-06 16:03 UTC, gdsoumya approved these changes
LGTM

2023-12-06 16:04 UTC, gdsoumya requested changes

2023-12-06 16:04 UTC, gdsoumya commented on cmd/argocd/commands/cluster.go
> +				if clusterQuery.Server == "https://kubernetes.default.svc" {
There's probably already a constant for the incluster server url we should probably use that

2023-12-07 01:43 UTC, chengfang commented on cmd/argocd/commands/cluster.go
> +					continue
shouldn't it exit with code 1, since the rm operation effectively failed?

2023-12-15 17:48 UTC, todaywasawesome approved these changes
LGTM

2023-12-21 09:33 UTC, morremeyer commented
Drafting this until I get to fix the tests

2024-02-01 10:58 UTC, morremeyer commented
I tried to add a test for this, but failed so far.
I'm afraid I don't understand the tests well enough to write a correct one .

Can anyone help me out with this?

2024-05-28 13:47 UTC, morremeyer commented
@todaywasawesome @chengfang @gdsoumya Can you provide guidance for https://github.com/argoproj/argo-cd/pull/16556#issuecomment-1921057553?

2024-11-03 13:59 UTC, chengfang approved these changes

2024-11-03 14:03 UTC, morremeyer commented
I looked into how to fix the tests for multiple hours now, and I have no idea how to progress.

Setting up a local environment with make start does not seem to include any of my changes, and setting up a local environment with k3d had the same result.

I couldn’t find any docs on how the custom testing functions work and reading the code didn’t yield any insight for me.

I’ll join the next contributor sync to ask for help on this again, but if that does not result in success, I’ll close the PR.

2024-11-11 14:02 UTC, morremeyer commented
I won't get to this in the forseeable future, since the debugging effort is more than I could take time for it currently.

Therefore, I'm closing this. If anybody wants to pick it up, feel free to use the existing commits.

2024-11-11 14:02 UTC, closed without merging