feat(kustomize): Bump kustomize and add support for new args to pass api and kube versions
argoproj/argo-cd pull request #16583
Opened 2023-12-08 16:41 UTC by MrFreezeex

This bump kustomize to the new version 5.3.0 (https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv5.3.0) and pass the new flags --helm-kube-version and helm-api-versions. 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2023-12-08 17:07 UTC, crenshaw-dev requested changes

2023-12-08 18:16 UTC, MrFreezeex commented
> Thanks, @MrFreezeex! Would you mind adding tests for the new feature?

Thanks for the review @crenshaw-dev , I added some unit test on the params and added some extra check about kustomize version and indeed if helm is enabled as you ask. let me know WDYT about the new code :+1:

2024-02-07 22:37 UTC, MrFreezeex commented
I just rebased this PR as it conflicted with some recent change on kustomize. Interestingly a `parseKustomizeBuildOptions` was added in the main branch, so there is even less code change now :D

2024-03-21 12:31 UTC, MrFreezeex commented
Hi @crenshaw-dev, would you be able to review again this PR :pray:? I fixed the points you raised in your last review!

2024-05-27 09:16 UTC, brotherko commented
Hi @crenshaw-dev can you look into this please?

2024-06-19 19:15 UTC, eric-engberg commented
Would be nice to get 5.3.0 in soon.  5.3.0 automatically downloads charts into a versioned directory.  Currently having to specify a versioned directory in the chart path.

2024-06-19 19:57 UTC, crenshaw-dev commented
THIS PR is outdated, the latest Argo CD RC release is on 5.4.2.

2024-06-19 21:32 UTC, eric-engberg commented
Is there another PR for updating kustomize? Could this PR not just be updated?

2024-06-19 21:33 UTC, crenshaw-dev commented
The task has already been done. https://github.com/argoproj/argo-cd/blob/master/hack/tool-versions.sh#L17

2024-06-19 21:34 UTC, crenshaw-dev commented
Oh! I missed the other necessary pieces. This PR just needs to be rebased.

2024-06-20 09:37 UTC, MrFreezeex commented
> Oh! I missed the other necessary pieces. This PR just needs to be rebased.

@crenshaw-dev no worries, I cleaned it up/rebased + the test are happy :D

2024-07-23 15:30 UTC, crenshaw-dev approved these changes

2024-07-23 15:30 UTC, merged

2024-08-15 09:12 UTC, pvlkov commented
Is there an ETA in which version this change will be released?

2024-08-15 10:47 UTC, MrFreezeex commented
It should be in the 2.13.0 release