feat: add initiated by in history and rollback view
argoproj/argo-cd pull request #16654
Opened 2023-12-19 20:38 UTC by robinlieb

Closes #16612

As mentioned in the issue this PR adds **Initiated by** in the history and rollback view.

<img width="556" alt="argocd-16612" src="https://github.com/argoproj/argo-cd/assets/34332703/be53bd2d-ead4-49ff-9e4d-7f2069ffbd8e">

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [X] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2023-12-19 22:21 UTC, keithchong commented on ui/src/app/applications/components/application-deployment-history/application-deployment-history.tsx
> +                        <div>
Although this is fine to me, maybe confirm with Leo if he wanted this to be on a separate line or on the same line as "Time to deploy" as depicted by his screenshot in the issue?

2023-12-20 18:08 UTC, leoluz approved these changes
Thank you @robinlieb for working on this!
Will wait for @keithchong to conclude the UI review before merging.

2023-12-21 13:59 UTC, keithchong approved these changes
@leoluz , LGTM

2023-12-22 15:21 UTC, leoluz requested changes
@robinlieb There is one last request in this PR. As you are changing the Application CRD, this needs to be stated in the "upgrading" doc.

As we just cut the 2.10 branch a few days ago, the file is not created yet. It needs to be created in:
`/docs/operator-manual/upgrading/2.10-2.11.md` and linked here:
https://github.com/argoproj/argo-cd/blob/7847e7f393c0f83a12d4733a3a887f0875dbb086/mkdocs.yml#L131

See this doc as an example:
https://argo-cd.readthedocs.io/en/stable/operator-manual/upgrading/1.6-1.7/#appproject-tokens-moved-to-status-field

2023-12-22 15:59 UTC, robinlieb commented
@leoluz thanks for the hint! Added the respective upgrading doc and linked it in the `mkdocs.yml`

2023-12-22 16:30 UTC, leoluz approved these changes
LGTM and thank you!

2023-12-22 16:50 UTC, merged

2024-08-01 18:48 UTC, ericblackburn commented
When we manually sync, it shows initiated by "Unknown" instead of using my Username that shows up on the /user-info page.  I don't think this is working with progressive-sync either.

2024-08-15 07:04 UTC, eliya-gloat commented
Same for me with release - v2.11.7+e4a0246 - All actions appears as user "unknown" for field "Initiated By"
v2.11.7+e4a0246