Issue #1668 - Replicasets ordering is not stable on app tree view
argoproj/argo-cd pull request #1669
Opened 2019-05-31 22:39 UTC by alexmt

Closes #1668

2019-05-31 22:50 UTC, alexec requested changes
Tests please

2019-05-31 22:54 UTC, jessesuen approved these changes

2019-05-31 23:46 UTC, alexmt commented
@alexec , added tests

2019-06-01 00:41 UTC, alexec approved these changes

2019-06-01 00:42 UTC, merged