chore(deps): update cve vulnerability
argoproj/argo-cd pull request #16948
Opened 2024-01-22 10:34 UTC by fengshunli

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

see  https://devhub.checkmarx.com/cve-details/CVE-2023-46402/
see https://devhub.checkmarx.com/cve-details/CVE-2023-47108/

2024-01-22 18:05 UTC, blakepettersson requested changes
See #16919 and #16920. For the bits which aren't already handled by Dependabot, can you open new PRs for them?

2024-01-23 02:25 UTC, fengshunli commented
> See #16919 and #16920. For the bits which aren't already handled by Dependabot, can you open new PRs for them?

upgrading otelgrpc requires modifying outdated methods, which cannot be completed by robots, otherwise lint cannot check it.

2024-01-23 12:08 UTC, blakepettersson commented
> upgrading otelgrpc requires modifying outdated methods, which cannot be completed by robots, otherwise lint cannot check it.

I see, then IMO it would make sense to break out anything which is not otelgrpc related and only address otelgrpc in this PR.

2024-02-01 06:11 UTC, fengshunli commented
> > upgrading otelgrpc requires modifying outdated methods, which cannot be completed by robots, otherwise lint cannot check it.
> 
> I see, then IMO it would make sense to break out anything which is not otelgrpc related and only address otelgrpc in this PR.

There are many changes in otelgrpc. Are there any reference use cases here?

2024-05-20 08:11 UTC, blakepettersson commented
Superseded by #18285 (among others)

2024-05-20 08:11 UTC, closed without merging