docs: adding infracloud blog to readme file
argoproj/argo-cd pull request #16955
Opened 2024-01-23 09:26 UTC by chetanpdeshmukh

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-01-23 12:06 UTC, blakepettersson requested changes
This seems to be a duplicate of #16743

2024-01-23 12:15 UTC, chetanpdeshmukh commented
> This seems to be a duplicate of #16743

Thanks Blake, that PR has been closed/deleted.

2024-01-23 12:35 UTC, blakepettersson commented
OK, closing that previous PR seems just a way to get around the fact that changes were requested on it.

2024-01-23 12:39 UTC, chetanpdeshmukh commented
Agreed, it does look like that. But, if you look closely, there are 10+ articles from InfraCloud in the previous PR. Here, I just limited to just 2 of these articles, which our subscribers found the most value in.

Excuse me, If I am breaking/skipping any guidelines, happy to get them incorporated.

2024-01-30 10:06 UTC, chetanpdeshmukh commented
Hey @blakepettersson do suggest what could be the next action item here or any changes that I need work on.

2024-01-30 14:30 UTC, blakepettersson commented
@chetanpdeshmukh I'd like to get some more eyes on this PR. I'm not per se against having blog links, but I'm not sure why this specific content couldn't just be used to improve the core Argo CD docs, in case it's actually missing there (disregarding the promotional aspect for Infracloud).

2024-02-06 16:41 UTC, todaywasawesome commented
I tend to think we should rework this part of the site. Having additional links to external content is great when it's relevant but this was a quick placeholder when it started but there's no reason to add links forever. We need some different approach to index and celebrate community content.

2024-11-16 03:13 UTC, andrii-korotkov-verkada commented
Shall we have a separate page for blog posts, not on the front page?

2026-05-19 21:12 UTC, closed without merging