Make the `--grpc-web` flag more obvious
argoproj/argo-cd pull request #1703
Opened 2019-06-06 04:52 UTC by stgarf

... if you're using ALB/ELB.

2019-06-06 04:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=1703) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=1703) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=1703) it.</sub>

2019-06-06 14:56 UTC, alexec commented
Looks good. Need to sign the CLA.

2019-06-07 21:29 UTC, alexmt approved these changes

2019-06-07 23:20 UTC, alexec requested changes
Please sign CLA.

2019-06-19 18:31 UTC, alexec approved these changes

2019-06-19 18:31 UTC, merged