fix(ui): Include application name in status badge
argoproj/argo-cd pull request #17126
Opened 2024-02-07 18:07 UTC by sonamkshenoy

Resolves [#14162](https://github.com/argoproj/argo-cd/issues/14162)

<img width="243" alt="Screenshot 2024-02-07 at 11 20 45 PM" src="https://github.com/argoproj/argo-cd/assets/49382298/07d64df1-d81d-4cdc-9464-9876c907e139">         
     
<img width="234" alt="Screenshot 2024-02-07 at 11 32 06 PM" src="https://github.com/argoproj/argo-cd/assets/49382298/fc0345d5-f5f0-4bb5-bb36-9cfff72c9648">

2024-02-08 00:10 UTC, todaywasawesome requested changes
Can we do this as an alternate version for people that don't want the app name? And then update the docs https://argo-cd.readthedocs.io/en/stable/user-guide/status-badge/

2024-02-08 17:10 UTC, crenshaw-dev commented
+1 to @todaywasawesome. Let's add something like a `showAppName` param to enable this presentation.

2024-02-08 19:15 UTC, sonamkshenoy commented
Thanks for the feedback!
I have made the suggested changes.
Could you please have another look. Thanks!

2024-02-22 16:09 UTC, todaywasawesome approved these changes
LGTM

2024-02-22 16:35 UTC, sonamkshenoy commented on docs/user-guide/status-badge.md
> +Naturally, to remove the application name from the badge, remove the query parameter from the URL or set it to `false`.
Hey @todaywasawesome, I'm really sorry for missing this. For some weird reason, I didn't receive notifications for any of the above review comments. I'm so sorry you had to make the changes. Sincere apologies again for the inconvenience!

2024-02-24 12:02 UTC, pasha-codefresh approved these changes
LGTM

2024-02-24 12:04 UTC, merged