feat: Add support for passing Redis Sentinel username(ACL) and password
argoproj/argo-cd pull request #17168
Opened 2024-02-10 16:47 UTC by shlomitubul

Currently, when deploying Argo with external Redis with Sentinel setup, users can't pass creds to authenticate against Sentinel, this PR solves it by reading those fields from environment variables and passing the missing fields for buildFailoverRedisClient function.

Note: since charts are set in another different repo I'll open PR in the relevant repo and add the support for passing the values from to the chart
Checklist:

* [v] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [v] The title of the PR states what changed and the related issues number (used for the release note).
* [v] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [v ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-02-10 16:53 UTC, gdsoumya requested changes

2024-02-10 16:53 UTC, gdsoumya commented on util/cache/cache.go
> +	envSentinelUsername = "REDIS_SENTINEL_USERNAME"
```suggestion
	// envRedisSentinelPassword is an env variable name which stores redis sentinel password
	envRedisSentinelPassword = "REDIS_SENTINEL_PASSWORD"
	// envRedisSentinelUsername is an env variable name which stores redis sentinel username
	envRedisSentinelUsername = "REDIS_SENTINEL_USERNAME"
```

2024-02-10 16:53 UTC, gdsoumya commented on util/cache/cache.go
> +	envSentinelUsername = "REDIS_SENTINEL_USERNAME"
Minor nitpick, renaming env var to keep it consistent with the others

2024-02-10 17:59 UTC, gdsoumya approved these changes
LGTM

2024-02-11 05:48 UTC, ishitasequeira approved these changes

2024-02-11 05:48 UTC, merged