Add kustomize labels to source
argoproj/argo-cd pull request #17329
Opened 2024-02-27 20:29 UTC by lets-call-n-walk

Addresses issue https://github.com/argoproj/argo-cd/issues/17328

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-02-27 21:13 UTC, ishitasequeira requested changes

2024-02-27 21:15 UTC, ishitasequeira requested changes
@lets-call-n-walk Please check my comment and also you would need to execute `make codegen` or `make codegen-local` to update the generated code.

2024-02-27 22:26 UTC, lets-call-n-walk commented
@ishitasequeira Thank you for your guidance. I have tried running `make codegen` and `make codegen-local`. The docker image gets to a step
```
ERROR: failed to solve: executor failed running [/bin/sh -c ./install.sh helm-linux &&     ./install.sh kustomize &&     ./install.sh codegen-tools &&     ./install.sh codegen-go-tools &&     ./install.sh lint-tools &&     go install github.com/mattn/goreman@latest &&     go install github.com/kisielk/godepgraph@latest &&     go install github.com/jstemmer/go-junit-report@latest &&     rm -rf /tmp/dl &&     rm -rf /tmp/helm &&     rm -rf /tmp/ks_*]: exit code: 60
make: *** [test-tools-image] Error 1
```
make codegen-local gives the following output. I can't seem to find a way to install this particular piece of protobuf through `brew`
```
./hack/generate-proto.sh: line 60: go-to-protobuf: command not found
```

2024-02-27 22:33 UTC, blakepettersson commented
For `make codegen-local` to work, you first need to run `make install-tools-local`

2024-02-28 00:01 UTC, lets-call-n-walk commented
@blakepettersson thanks

2024-02-28 01:57 UTC, ishitasequeira requested changes
@lets-call-n-walk it seems the commit history got messed up. Can you clean it up? The PR shows way more changes than needed because of it.

2024-02-28 02:02 UTC, ishitasequeira requested changes
You would also need to set the value of the flag from the switch case like https://github.com/argoproj/argo-cd/blob/11210fc9b820d126889bed4db55f0fe6af2848cf/cmd/util/app.go#L233-L236

2024-02-28 14:58 UTC, lets-call-n-walk commented
@ishitasequeira I think I've cleaned it up. I think I messed it up initially with my rebase in order to sign off the commits. After a few failed attempts, I think I have everything how it should be. This has taught me alot more about git.

2024-02-28 16:03 UTC, lets-call-n-walk commented
@ishitasequeira can you see why the e2e 1.25 test failed? Seems like health check timed out for a config map, but I can't tell how that is related.

2024-02-28 20:13 UTC, lets-call-n-walk commented
Looks like updating the branch fixed whatever was going on.

2024-03-01 21:22 UTC, jannfis reviewed
This is great! Thank you @lets-call-n-walk 

I have a question, why is there a "beta" in the PR's title? Is it a beta feature in Kustomize?

2024-03-02 04:25 UTC, lets-call-n-walk commented
@jannfis no, I just thought I had to put something about the status of the feature according to the PR task list. If I misunderstood, we can change that to whatever it needs to be.

2024-03-02 17:28 UTC, jannfis commented on util/kustomize/kustomize_test.go
> +		fmt.Println("beginning")
Is this a debugging leftover?

2024-03-02 17:28 UTC, jannfis commented on util/kustomize/kustomize_test.go
> +		fmt.Println(appPath)
Is this a debugging leftover?

2024-03-02 17:28 UTC, jannfis commented on util/kustomize/kustomize_test.go
> +		fmt.Println("objs: ", len(objs))
Is this a debugging leftover?

2024-03-02 17:28 UTC, jannfis commented on util/kustomize/kustomize_test.go
> +				fmt.Println(len(objs))
Is this a debugging leftover?

2024-03-03 00:19 UTC, lets-call-n-walk commented
@jannfis Thanks for the catch. Removed.

There seems to be a conflict with Master now where a bunch of app options in the cli are missing... Is this because of some major change? What is the best way to proceed?

2024-03-04 12:49 UTC, jannfis commented
@lets-call-n-walk Yes, we merged [another PR](https://github.com/argoproj/argo-cd/pull/17360) that touched the same part of the code on Friday and moved some things around, so your change can't be merged without conflict. You need to rebase your PR and see how to resolve the conflict.

2024-03-04 14:24 UTC, lets-call-n-walk commented
@jannfis Hmm, I don't see where that PR touches `cmd/util/app.go`. But I will hunt around for where the kustomize opts got moved to.

2024-03-04 15:43 UTC, jannfis commented
@lets-call-n-walk, I have unfortunately linked the wrong PR, sorry about that.

It was of course [this one](https://github.com/argoproj/argo-cd/pull/17310).

2024-03-04 16:51 UTC, lets-call-n-walk commented
@jannfis Ok, I think I fixed it. Thank you!

2024-03-04 18:04 UTC, jannfis approved these changes
LGTM, thank you! Well done, and congratulations to your first contribution @lets-call-n-walk :)

2024-03-04 18:05 UTC, jannfis commented
@ishitasequeira Could you please check status of your RfC here?

2024-03-04 20:49 UTC, lets-call-n-walk commented
@jannfis Thank you!  Just curious, do you have an idea of what release this will be packaged in, and very roughly, when we can expect to see that release available?

2024-03-04 22:16 UTC, jannfis commented
@lets-call-n-walk This will be part of the v2.11 release. We do have a policy for not cherry-picking new features into previous releases. 2.11 is planned for May.

2024-03-04 23:13 UTC, ishitasequeira approved these changes

2024-03-04 23:13 UTC, merged

2024-05-01 07:14 UTC, omer2500 commented
Hi,

can you explain @lets-call-n-walk why didn't you choose to implement this feature:
https://kubectl.docs.kubernetes.io/references/kustomize/kustomization/labels/

it seems that it's the modern way to go with kustomize and already have all the flags that cover all the use cases
and commonLabels is already deprecated in kustomize 

don't we want to support the labels to allow all abilities?

#15283

2024-05-01 22:53 UTC, lets-call-n-walk commented
@omer2500 the short answer is that Argo builds applications via the kustomize cli, and the kustomize cli has not fully reached parity with the new kustomize labels API.

The only way to add labels via the cli is to use the flag `--commonlabels`, which obviously adds the labels as `commonLabels`. Thankfully, they have added a flag `--label-without-selector`. Unexpectedly, it makes `--commonlabels` implement `labels` and add the `includeSelectors: false` field. No further development has occurred to my knowledge.

Because the Argo kustomize application source is built around the kustomize cli, I thought it prudent to keep the same fields.

2024-05-02 05:28 UTC, omer2500 commented
Thanks for the detailed answer! @lets-call-n-walk