feat(controller): add env variable to enforce FailOnSharedResource
argoproj/argo-cd pull request #17764
Opened 2024-04-07 04:27 UTC by wilsonwang371

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

Fix #17763

2024-04-08 11:32 UTC, jannfis requested changes
I would prefer this to be implemented in another way, instead of (yet another) undocumented environment variable.

Two options that come to my mind:

1) A command line flag for the application controller or
2) Move the setting to the AppProject level

2024-04-08 17:45 UTC, wilsonwang371 commented
> I would prefer this to be implemented in another way, instead of (yet another) undocumented environment variable.
> 
> Two options that come to my mind:
> 
> 1. A command line flag for the application controller or
> 2. Move the setting to the AppProject level

Now I changed it to command line argument.

2024-11-09 15:16 UTC, andrii-korotkov-verkada commented on hack/gen-crd-spec/main.go
> +		logrus.Error(err)
Why do we need both log and panic?

2024-11-09 15:16 UTC, andrii-korotkov-verkada commented on docs/operator-manual/server-commands/argocd-application-controller.md
> +      --enforce-no-shared-resource             Enforces that no shared resources are accepted in the application
How does it handle when resource is changing the application it's under?

2026-09-13 22:00 UTC, closed without merging