docs: document helm fileParameters / helm-set-file
argoproj/argo-cd pull request #17822
Opened 2024-04-12 21:22 UTC by cardoe

Added documentation for fileParameters in a helm source Application or the --helm-set-file cli option from #2751. Added a note about #13220 so users are aware. #12508 aims to remove this limitation so the warning can probably be removed with that.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-04-12 21:26 UTC, cardoe commented
It seemed like the documentation got missed in the original PR so this adds it. Should be possible to back port this to stable releases.

2024-04-25 13:19 UTC, cardoe commented
Rebased this PR and updated the message to reference #17941 as the PR that implements the feature.

2024-04-25 14:28 UTC, crenshaw-dev requested changes

2024-04-25 14:28 UTC, crenshaw-dev commented on docs/user-guide/helm.md
> +    Please note that using a multiple sources application will not let you load the file by reference. See [argoproj/argo-cd#13220](https://github.com/argoproj/argo-cd/issues/13220)
```suggestion
!!! warning "Reference in multiple sources not supported"
    Please note that using a multiple sources application will not let you load the file by reference. See [argoproj/argo-cd#13220](https://github.com/argoproj/argo-cd/issues/13220)
```

2024-04-25 14:28 UTC, crenshaw-dev commented on docs/user-guide/helm.md
> +              value: path/to/file.ext
```suggestion
source:
  helm:
    fileParameters:
      - name: some.key
        value: path/to/file.ext
```

2024-04-25 14:32 UTC, cardoe commented
Thank you for the feedback. I've applied your changes.

2024-04-25 15:12 UTC, crenshaw-dev approved these changes
Thank you!

2024-04-25 15:12 UTC, merged

2024-11-16 12:00 UTC, laiminhtrung1997 commented
@cardoe @crenshaw-dev