Update repository.go
argoproj/argo-cd pull request #17957
Opened 2024-04-24 15:04 UTC by BarAshkenazi

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-04-25 14:29 UTC, crenshaw-dev requested changes
Changing this could be problematic for some users.

I'd recommend making global exclusions configurable via a glob pattern and defaulting to `.*`.

2024-04-28 11:41 UTC, BarAshkenazi commented
I was thinking of adding a new flag ARGOCD_REPO_SERVER_INCLUDE_HIDDEN_DIRECTORIES that defaults to false to preserve the current behavior.
Do you think it should be enough or is it essential to add an exclusion pattern as you’ve suggested?

2024-05-09 07:58 UTC, BarAshkenazi commented
I've made the changes so it will not interrupt the current behavior as we've discussed using the `ARGOCD_REPO_SERVER_INCLUDE_HIDDEN_DIRECTORIES` option that defaults to false.
Waiting for review

2024-05-21 10:32 UTC, BarAshkenazi commented
@crenshaw-dev Can you please have a look? 🙏

2024-05-28 18:25 UTC, crenshaw-dev approved these changes

2024-05-28 18:25 UTC, merged