oras-go client should fallback to docker config if no credentials specified
argoproj/argo-cd pull request #18133
Opened 2024-05-08 23:44 UTC by tonyay163

I'm using https://github.com/argoproj/argo-cd/issues/17279 to authenticate to Google Artifact Registry as a helm registry using workload identity. Unlike https://github.com/argoproj/argo-cd/issues/10218, the other solution does not require installing ESO. This works in general since the `helm template` can get creds via the `$HOME/.docker/config.json`. However, if you need to use `targetRevision: *` with your application, this ends up using the oras-go client here which is only configured for static credentials.

This change adds a backwards compatible change where if both the username and password is not configured, it will use the oras-go credentials package to get the docker config from the environment and use that to get credentials.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-05-13 16:40 UTC, tonyay163 commented
I tested this ETE and it seems to work well

2024-09-23 18:13 UTC, tonyay163 commented
@crenshaw-dev / @blakepettersson, sorry to ping directly but it looks like you've contributed this recently. I have a pretty simple fix here that I've been running for months now and would like to get it merged. It seems like a pretty small fix for an enhancement proposal.

2024-09-27 03:08 UTC, gdsoumya requested changes

2024-09-27 03:37 UTC, tonyay163 commented on util/helm/client_test.go
> +		t.Logf("authorization received %s", authorization)
hey, I think that's reasonable and have updated the test !

2024-09-27 15:15 UTC, nitishfy approved these changes
overall looks good to me!

2024-09-27 15:17 UTC, tonyay163 commented
thank you @nitishfy! I think we need @gdsoumya to approve or dismiss his requested changes

2024-09-27 15:42 UTC, wanghong230 approved these changes

2024-09-27 16:03 UTC, gdsoumya approved these changes

2024-09-27 16:03 UTC, merged

2024-09-27 17:34 UTC, tonyay163 commented
/cherry-pick release-2.11

2024-10-11 13:14 UTC, tonyay163 commented
@gdsoumya, I'm waiting for this to release so I can upgrade my production envs, can you help me cherry-pick this to 2.11, 2.12 and 2.13 RCs?

2024-10-11 13:48 UTC, tonyay163 commented
thank you !

2024-11-04 18:04 UTC, eestolano commented
Was this fix supposed to be in v2.13.0? It doesn't seem to be there.