chore(deps): upgrade helm to 3.14.4
argoproj/argo-cd pull request #18255
Opened 2024-05-16 18:31 UTC by 34fathombelow

Resolves the following CVE's in the Helm binary:

| Library | Vulnerability | Severity |
| ---| --- | --- |
github.com/docker/docker   |  CVE-2024-24557 | MEDIUM/HIGH  
google.golang.org/protobuf | CVE-2024-24786  | MEDIUM 
stdlib | CVE-2023-45288 | HIGH
stdlib | CVE-2023-45289 | Medium
stdlib | CVE-2023-45290 | Medium
stdlib | CVE-2024-24783  | Medium
stdlib | CVE-2024-24784 | Medium
stdlib | CVE-2024-24785 | Medium

`Cherry-Pick needed for v2.11 & v2.10`

2024-05-16 20:54 UTC, todaywasawesome requested changes
Any reason not to go straight to 3.15?

2024-05-16 21:09 UTC, 34fathombelow commented
> Any reason not to go straight to 3.15?

Yes, this is so we can cherry-pick the update without jumping minor versions.  We don't necessarily want to backport minor version unless we are forced to.

2024-05-16 21:37 UTC, todaywasawesome approved these changes
Even checked the checksums :)

2024-05-17 10:58 UTC, pasha-codefresh approved these changes
LGTM, thank you!

2024-05-17 10:58 UTC, merged

2024-05-20 06:54 UTC, 34fathombelow commented
@pasha-codefresh @crenshaw-dev can we cherry-pick this back to `v2.11` & `v2.10` ?

2024-05-20 07:10 UTC, pasha-codefresh commented
Lets do it on Wednesday, we have planned release on Tuesday

2024-05-20 07:12 UTC, pasha-codefresh commented
@34fathombelow actually, we can, it should not cause conflicts for planned release

2024-05-20 07:16 UTC, pasha-codefresh commented
/cherry-pick release-2.11

2024-05-20 07:16 UTC, pasha-codefresh commented
/cherry-pick release-2.10