fix: check all namespace app when appProject delete
argoproj/argo-cd pull request #18401
Opened 2024-05-24 10:05 UTC by yyzxw

Fix: #18361 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-09-02 10:17 UTC, reggie-k requested changes
Thanks for the PR!
Please note that now apps in all namespaces are returned, and some of those namespaces might not be watched at the controller level (meaning, not allowed in the config map).
```	
appsCount := 0
	for i := range apps {
		if apps[i].Spec.GetProject() == proj.Name {
			appsCount++
		}
	}   
```
So in the above existing code, another check needs to be added - that the ns of the app is allowed, otherwise this app is not relevant for the decision whether to finalize the project deletion.
This can be used for the check:
``` isAppNamespaceAllowed ``` in appcontroller.go

2024-10-06 14:56 UTC, pasha-codefresh commented
@yyzxw any plans to address comment ?

2024-11-16 02:57 UTC, andrii-korotkov-verkada approved these changes

2026-05-01 14:51 UTC, agaudreault commented
Closing as implemented in a duplicate issue

2026-05-01 14:51 UTC, closed without merging