fix: upgrade git-lfs versions used in Docker images #18723
argoproj/argo-cd pull request #18775
Opened 2024-06-23 17:17 UTC by thecooldrop

Part of solution to issue #18723 for release 2.11, other PRs will be created for other minor releases. 

I have cherry-picked the changed onto releases 2.10 and 2.9 and will be adding PRs for that as well

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates? => Answer: No, not visible outside
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-06-28 08:18 UTC, fengshunli commented
please check ci

2024-06-28 08:24 UTC, thecooldrop commented
Hello @fengshunli I saw that CI was failing with generated content containing changes. I was unable to conclude why that is the case. I have looked at other PRs and have seen that many/most PRs are failing in this step. For this reason I assumed that this step is somehow misconfigured, or only relevant at release time. 

I was unable to reproduce the behavior locally though. If there is a way to do that I would be thankful for the explanation.

If you could assist me with debugging, or at least tell me what causes the diffs, or where to look, I would be grateful.

2024-06-28 09:04 UTC, fengshunli commented
run make codegen local

2024-06-28 16:03 UTC, crenshaw-dev commented
Please ignore the codegen failure. It doesn't work correctly for release branches, and we can just ignore it when merging.

2024-06-28 16:05 UTC, crenshaw-dev requested changes
Looks like instead of adding the mantic source, we can just bump the base image hash. 

https://github.com/argoproj/argo-cd/issues/18723#issuecomment-2189399695

2024-06-28 16:39 UTC, fengshunli commented
Version 2.12 uses ubuntu: 24.04, and this problem does not exist, so the way to replace the source is not needed for the time being @thecooldrop

2024-06-28 17:47 UTC, crenshaw-dev commented
@fengshunli the CVEs are high severity, so we'll want to make the change to 2.9-2.11 as well. Let's leave this open and see if @thecooldrop would like to open PRs to bump the sha on those branches.

2024-06-28 18:26 UTC, thecooldrop commented
> Version 2.12 uses ubuntu: 24.04, and this problem does not exist, so the way to replace the source is not needed @thecooldrop

@fengshunli I agree that it is not needed on 2.12, but versions 2.11, 2.10 and 2.9 are built on Ubuntu 22.04, which does not contain new git-lfs, thus addition of new sources is needed. Because of this it is necessary to reopen the PRs #18776 and #18777 

@crenshaw-dev I can bump the SHA of 22.04 Ubuntu base image, but that will not fix the issue. Namely the latest sha of 22.04 Ubuntu still contains the older git-lfs version, as can be seen by running this command `docker run --rm ubuntu:22.04@sha256:19478ce7fc2ffbce89df29fea5725a8d12e57de52eb9ea570890dc5852aac1ac /bin/bash -c "apt update && apt install -y git-lfs && git-lfs version"` which produces the output: `git-lfs/3.0.2 (GitHub; linux amd64; go 1.18.1)`


Should I still bump the Ubuntu SHA, purely as up-keep?

2024-06-28 19:36 UTC, crenshaw-dev commented
Chatted with @34fathombelow, I think probably what we should do is wait for Argo CD 2.12 to be GA for a few weeks and then, if there are no major issues, just bump the base image versions for 2.10 and 2.11. 

One thing he pointed out is that Mantic support ends in July so we probably wouldn't want to use that repo anyway.

2024-06-29 14:07 UTC, thecooldrop commented
Well updating the OS should be a low-risk operation, so I would expect everything to keep working correctly. I find updating the OS to 24.04 instead of adding Mantic repo to be a cleaner solution.

2024-06-30 19:19 UTC, thecooldrop commented
I was thinking about this, and strictly speaking the correct way to go about this would be to cherry pick the changes introduced by PR #18093 from master into supported release branches. Right? @crenshaw-dev

2024-06-30 19:31 UTC, crenshaw-dev commented
Yep, we'd just cherry pick that. 

Should be low-risk, but we've been bitten by stuff like breaking openssl changes before. Better safe than sorry I think.

2024-08-09 09:57 UTC, thecooldrop commented
Hi @crenshaw-dev, just a friendly reminder here. How should this proceed?

2025-05-06 12:59 UTC, blakepettersson commented
Closing since 2.11 is no longer supported

2025-05-06 12:59 UTC, closed without merging