fix(#19271): update Content-Disposition filename extension to .log
argoproj/argo-cd pull request #19272
Opened 2024-07-26 20:35 UTC by rajattrt

Downloaded log files to have the extension ".log" instead of ".txt"

Fixes https://github.com/argoproj/argo-cd/issues/19271

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-07-29 17:50 UTC, crenshaw-dev requested changes

2024-07-29 17:50 UTC, crenshaw-dev commented on docs/operator-manual/upgrading/2.12-2.13.md
> +The default extension for log files generated by ArgoCD when using the "Download Logs" feature has been changed from `.txt` to `.log`. This change aligns with industry standards and improves compatib
```suggestion
The default extension for log files generated by Argo CD when using the "Download Logs" feature has been changed from `.txt` to `.log`. This change aligns with industry standards and improves compatibility with various log management tools and IDEs that offer enhanced features for `.log` files.
```

2024-07-29 17:50 UTC, crenshaw-dev approved these changes

2024-07-30 16:28 UTC, ishitasequeira approved these changes

2024-07-30 17:19 UTC, merged