fix(appset): Retry on conflict when updating status
argoproj/argo-cd pull request #19663
Opened 2024-08-23 11:00 UTC by carlosrejano

# Context:
  When updating the status of the applicationset object it can happen
  that it fails due to a conflict since the resourceVersion has changed
  because of a previous update. This makes the reconcile fails and
  we need to wait until the following reconcile loop updates the
  relevant status fields and hope that the update calls don't fail again
  due to a conflict. It can even happen that it gets stuck constantly due
  to these erriors.

  A better approach I would say is retrying when there is a conflict
  error with the newest version of the object, so we make sure we update
  the object with the latest version always.

  This has been raised in issue #19535 that failing due to conflicts can
  make the reconciliation not able to proceed.

  # What does this PR?
  - Wraps all the `Update().Status` calls inside a retry function that will retry when the update fails due to a conflict.
  - Adds appset to fake client subresources, if not the client can not correctly determine the status subresource. Refer to: https://github.com/kubernetes-sigs/controller-runtime/issues/2386, and https://github.com/kubernetes-sigs/controller-runtime/issues/2362.

2024-08-28 07:54 UTC, gdsoumya requested changes

2024-08-28 11:07 UTC, carlosrejano commented on applicationset/controllers/applicationset_controller.go
> +			updatedAppset := &argov1alpha1.ApplicationSet{}
If I understand correctly in this line we should be covering the case you mention, we copy the newly updated appset to the one given in the params:
https://github.com/argoproj/argo-cd/pull/19663/files#diff-6a561bbfd91ee7d0a619e694e372d34ca6c38967df7e62af4e0026bd1239850fR445

2024-08-29 15:28 UTC, carlosrejano commented on applicationset/controllers/applicationset_controller.go
> +		err := retry.RetryOnConflict(retry.DefaultRetry, func() error {
Sure, in this case we are using this backOff defined:
```
var DefaultRetry = wait.Backoff{
	Steps:    5,
	Duration: 10 * time.Millisecond,
	Factor:   1.0,
	Jitter:   0.1,
}
```
We would be doing around 5 calls every 10 ms.

2024-09-05 16:59 UTC, carlosrejano commented on applicationset/controllers/applicationset_controller.go
> +		err := retry.RetryOnConflict(retry.DefaultRetry, func() error {
Done!

2024-09-07 15:25 UTC, gdsoumya approved these changes

2024-09-07 15:25 UTC, merged