fix(appset): Fix infinite loop caused by not ignoring statuses updates
argoproj/argo-cd pull request #19676
Opened 2024-08-24 16:01 UTC by joliveirinha

This commit fixes a bug where the appset controller updating the status of the resource itself, was causing it be notified for a new reconcile loop.
This happened, because, altough the individual resource (app) statuses were not changing, the order of the list was, as such, resulting in an updated appset resource.

The fix, adds a GenerationPredicate to the Watch on the appSet to guarantee that if no actual change to the AppSet change was done, then it can be ignored.

Fixes [19675]

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-08-25 12:46 UTC, reggie-k commented
Thank you for the detailed description, @joliveirinha.
Could you add tests for this case?

2024-08-28 14:54 UTC, todaywasawesome requested changes
Add tests and it looks 🔥

2024-08-29 18:15 UTC, christianh814 approved these changes

2024-08-31 10:21 UTC, joliveirinha commented
Sorry for the late response. Only had time to look at this now. 

It doesn't seem straight forward to implement a regression test for this.
AFAIK, the tests that exist use fake client and there doesnt seem possible to test the reconcile loop with it.

It seems the only possibility is to use envtest instead.

I maybe missing something since this is my first time looking at this.

2024-09-03 14:15 UTC, wanghong230 approved these changes

2024-09-03 18:04 UTC, joliveirinha commented
> Another option is to ensure order of the `status.resources` which I think is the real cause of this issue. See #19757

Hmm I have mixed feelings about that.

1) altought what you are saying is indeed true in the exact scenario I reported, it feels that "fixing" it that way is not the ideal fix, mainly because:
2) we shouldn't care at all for the reason and contents that changed on the resource status from the perspective of being notified by the controller-runtime due to those changes. Even if the status changed, it should be in the implementation to decide what is best requeue time for the next iteration. Most probably, a couple of seconds. 

For 2) the current fix here proposed, gives all the flexibility for the implementation to decide what is the best requeue time. If we go via the direction you are suggesting, then a status update that changes the actual status content, will always trigger right away  the notification from the runtime, which means you have less flexibility.

You may argue, that it will only happen once because in the next iteration the status is probably the same, still....

2024-09-04 06:23 UTC, jetersen commented
But if you are using SCM Provider and someone creates a new repo, then it should reconcile if a new application is added?

2024-09-04 20:11 UTC, joliveirinha commented
> But if you are using SCM Provider and someone creates a new repo, then it should reconcile if a new application is added?

Yes. The fix doesn't change that. normal requeueing based on the configured requeue time will still happen.

2024-09-10 16:18 UTC, agaudreault reviewed
There are many cases where the behavior of the appset controller may depend on status updates adding back the object to the queue. One that comes to my mind is the progressive delivery. There will be less update events, so less calls to `shouldRequeueApplicationSet`. What are the implication of that? hard to know.

These kinds of scenario are usually coverer by the E2E test suite.

2024-09-12 16:46 UTC, alexmt requested changes
I agree with @agaudreault . Argo CD application controller logic relies on reconciliation after changing the status. It is not ideal, but I'm afraid the AppicationSet controller is the same. We might open a can of worms by disabling reconciliation on status change.

I would implement [this](https://github.com/argoproj/argo-cd/pull/19676#issuecomment-2325991404) suggestion instead.

2025-03-20 20:44 UTC, closed without merging