fix: issue 19395 change delete icon color in dark model
argoproj/argo-cd pull request #19747
Opened 2024-09-02 01:04 UTC by sxt90128

Issue: https://github.com/argoproj/argo-cd/issues/19395

In Darkmode, when edit application, the color for delete icon is not obvious and consistent

To Reproduce
Enable "Dark mode", go to an application, click "DETAILS", in SUMMARY tab, click "EDIT", the delete icon for "ANNOTATIONS" is colored in black, which is not visible and inconsistent.

Result after fix:
![image (13)](https://github.com/user-attachments/assets/51b30fa3-3322-4179-a660-c2b6a818f48c)

2024-09-02 01:32 UTC, sxt90128 commented
@wanghong230 , @pasha-codefresh , @ishitasequeira , @todaywasawesome , @christianh814 
Hi all, I have created a PR the fix that issue of icon color in dark model, could you help to review it, thanks.

2024-09-02 06:18 UTC, gdsoumya submitted a review, later dismissed

2024-09-02 08:08 UTC, sxt90128 commented on ui/src/app/applications/components/application-summary/application-summary.scss
> +}
Sure, will do

2024-09-03 17:54 UTC, todaywasawesome requested changes

2024-09-03 17:54 UTC, todaywasawesome commented on ui/src/app/applications/components/application-summary/application-summary.scss
> +}
@sxt90128 Actually can you revert the other ones? There are quite a few spaces removed.

2024-09-04 13:41 UTC, sxt90128 commented on ui/src/app/applications/components/application-summary/application-summary.scss
> +}
@gdsoumya @todaywasawesome I have reverted all the formatting changes, please review again, thanks

2024-09-04 13:55 UTC, ishitasequeira approved these changes
LGTM!

2024-09-04 14:17 UTC, todaywasawesome approved these changes
Excellent thanks!

2024-09-04 14:18 UTC, pasha-codefresh approved these changes

2024-09-04 23:45 UTC, christianh814 approved these changes

2024-09-05 00:24 UTC, merged