fix(appset): Fix perpetual appset reconciliation
argoproj/argo-cd pull request #19822
Opened 2024-09-06 14:31 UTC by tjamet

ScmProvider does not guarantee order of the application resources from the applicationset which causes rapid sync activity for the applicationset as the objects and hence their resourceVersions are updated after each reconcile loop.

This then triggers reconciliation of all objects watching the ApplicationSet.

In order to prevent this behaviour, ensure that the ApplicationSet reconciler provides an idempotent list of resources, ensuring objects are not updated.

Fixes: #19757

This PR is an alternate approach to #19676.

In #19676, the approach is to only reconcile based on generation changes, i.e. `spec` changes as defined by the [generation implementation in CRDs](https://github.com/kubernetes/kubernetes/pull/55168).
This means that, with this PR, any change of metadata (labels, annotations, ...) or status will be taken into consideration on the next run (triggered by [requeueAfter](https://github.com/argoproj/argo-cd/blob/3d66b05899f4af3ad30df3edd75ed68e36e0e705/applicationset/controllers/applicationset_controller.go#L338), 3mn by default in my trials), which is the way new SCM repos or folders are discovered from my understanding.

This PR takes a different approach, ensuring that status updates are idempotent across reconcile loops and hence prevents from triggering any reconciliation in other reconcilers unless there is an actual change on the ApplicationSet.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [X] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [X] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-09-06 19:22 UTC, tjamet commented
I see there is a license check problem, if I read correctly, the problem also appears on other PRs, is there anything needed from us to fix it?

2024-09-10 15:53 UTC, agaudreault requested changes

2024-09-10 15:53 UTC, agaudreault commented on applicationset/controllers/applicationset_controller.go
> +func keys[T any](m map[string]T) []string {
the `sort` is really what is important in this function, either rename the function to `sortedKeys` or move the `sort.Strings(keys)` outside the function.

```
sort.Slice(statuses, func(i, j int) bool {
	return statuses[i].Name < statuses[j].Name
})
```

2024-09-13 08:53 UTC, jetersen approved these changes
Looks good to me 👍 Thanks for implementing a fix for #19757

2024-09-13 17:43 UTC, agaudreault approved these changes
LGTM

2024-09-13 17:43 UTC, merged

2024-09-16 07:59 UTC, jetersen commented
Would be great to get a patch release for this, it is very noisy inside our etcd 😓

2024-09-18 16:03 UTC, gmauleon commented
yes please! 👆 🙏

2024-09-18 23:57 UTC, agaudreault commented
/cherry-pick release-2.12