docs: Application sets docs
argoproj/argo-cd pull request #19892
Opened 2024-09-11 12:46 UTC by kostis-codefresh

Documentation for https://github.com/argoproj/argo-cd/pull/19691

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [X] Does this PR require documentation updates?
* [X] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [X] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-09-11 13:41 UTC, reggie-k approved these changes

2024-09-11 14:37 UTC, todaywasawesome requested changes
Made a few small grammar suggestions for you to review @kostis-codefresh .

2024-09-11 14:37 UTC, todaywasawesome commented on docs/operator-manual/metrics.md
> +| `argocd_appset_info` | gauge | Information about Application Sets. It contains labels for name and namespace of an application set as well as `Resource_update_status`  that reflects the `ResourcesU
```suggestion
| `argocd_appset_info` | gauge | Information about Application Sets. It contains labels for the name and namespace of an application set as well as `Resource_update_status`  that reflects the `ResourcesUpToDate` property |
```

2024-09-11 14:37 UTC, todaywasawesome commented on docs/operator-manual/metrics.md
> +| `argocd_appset_reconcile` | histogram | Application reconciliation performance in seconds. It contains labels for name and namespace of an applicationset |
```suggestion
| `argocd_appset_reconcile` | histogram | Application reconciliation performance in seconds. It contains labels for the name and namespace of an applicationset |
```

2024-09-11 14:37 UTC, todaywasawesome commented on docs/operator-manual/metrics.md
> +Similar to the same metric in application controller (`argocd_app_labels`) the metric `argocd_appset_labels` is disabled by default. You can enable it by providing the `–metrics-applicationset-labels
```suggestion
Similar to the same metric in application controller (`argocd_app_labels`) the metric `argocd_appset_labels` is disabled by default. You can enable it by providing the `–metrics-applicationset-labels` argument to the applicationset controller.
```

2024-09-11 15:31 UTC, nitishfy commented on docs/operator-manual/metrics.md
> +
```suggestion

```

2024-09-11 15:31 UTC, nitishfy commented on docs/operator-manual/metrics.md
> +
nit

2024-09-11 15:31 UTC, nitishfy approved these changes

2024-09-11 22:29 UTC, wanghong230 approved these changes
Thank you for documenting those things well.

2024-09-11 22:29 UTC, alexmt approved these changes

2024-09-12 01:46 UTC, ishitasequeira approved these changes

2024-09-12 01:47 UTC, ishitasequeira reviewed
@todaywasawesome are you good with the changes you requested?

2024-09-12 03:19 UTC, alexmt approved these changes
Thank you.

2024-09-12 14:57 UTC, todaywasawesome approved these changes
Great!

2024-09-12 15:02 UTC, merged