Prevent crash during timer expiration after stream is closed
argoproj/argo-cd pull request #19917
Opened 2024-09-12 17:11 UTC by morapet

Reorder ticker stop and close merge to prevent send(true) happens after merge is closed, in rare situation when the timer expires exactly at the point between close(merge) and ticker.Stop()

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates? No
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [X] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

This is a bug
Closes [ISSUE #7006]

2024-09-16 06:56 UTC, nitishfy requested changes
Please resolve the Lint Issues for this PR by running the `gofumpt` command against the `logs.go`. Thanks!

2024-09-17 09:32 UTC, gdsoumya approved these changes
LGTM

2024-09-17 09:32 UTC, merged

2024-10-02 13:26 UTC, agaudreault commented
/cherry-pick 2.13

2024-10-02 13:27 UTC, agaudreault commented
/cherry-pick release-2.13

2024-10-07 13:56 UTC, crenshaw-dev commented
/cherry-pick release-2.13

2024-10-07 15:53 UTC, agaudreault commented
/cherry-pick release-2.13

2024-10-07 15:53 UTC, agaudreault commented
last try! I'll do it manually :(