Change the file name convention when downloading pod logs
argoproj/argo-cd pull request #19938
Opened 2024-09-15 12:26 UTC by itaynvn-runai

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-09-16 06:25 UTC, reggie-k reviewed
I think we shouldn't give up the container name entirely, for cases of pods with sidecars.
Can we append the container name to the ns and pod in the file name?

2024-09-16 06:31 UTC, nitishfy commented on pkg/apiclient/application/forwarder_overwrite.go
> +			if kube.IsValidResourceName(appNamespace) && kube.IsValidResourceName(podName) {
```suggestion
			if kube.IsValidResourceName(appNamespace) && kube.IsValidResourceName(podName) {
```

`appNameswpace` is argocd always (until you change the namespace where argocd has been installed). Instead, the namespace should be the one that the pod is part of. Furthermore, testing the above changes will give me a filename as `argocd-my-app-dev-798dbbd986-kc2vz.log`. If my pod wasn't part of deployment, I'd want to have log file in this format - `<namespace that pod is part of>-<pod-name>`.

2024-09-16 06:31 UTC, nitishfy requested changes
PTAL. 

I also agree with @reggie-k comments for the same. Thanks!

2024-09-17 09:18 UTC, gdsoumya requested changes

2024-09-18 08:10 UTC, gdsoumya approved these changes
LGTM

2024-09-18 08:14 UTC, merged