fix(ui): Sync Health Statuses for Applications and everything else (#12056)
argoproj/argo-cd pull request #20020
Opened 2024-09-19 22:43 UTC by jsoref

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

Fixes #12056

2024-09-19 23:02 UTC, jsoref commented
As seen on bunnyshell:
<img width="1691" alt="image" src="https://github.com/user-attachments/assets/4503a3e0-3a89-4e69-adba-d3eb96a73497">

2024-09-20 11:22 UTC, nitishfy approved these changes

2024-09-20 14:57 UTC, christianh814 approved these changes

2024-09-20 15:17 UTC, gdsoumya requested changes
Don't see it solving the issue with sync statuses, do you plan to add that too?

2024-09-20 15:19 UTC, gdsoumya approved these changes
Nvm I misread the issues. LGTM

2024-09-20 15:19 UTC, merged