docs: Add `404 Not Found` github notify error to troubleshooting docs
argoproj/argo-cd pull request #20085
Opened 2024-09-24 18:23 UTC by moleus

This PR is similar to my [previous PR](https://github.com/argoproj/argo-cd/pull/19926). Default go template for `revisionPath` is not suitable for mutliple-source applications and error message doesn't really help understand the source of the problem:
```
{"level":"error","msg":"Failed to notify recipient {github } defined in resource argo/xxxx: POST https://api.github.com/repos/xxxx/yyyy/statuses/:  404 Not Found [] using the configuration in namespace argo","resource":"argo/xxxx","time":"2024-09-13T06:32:34Z"}
``` 

I've added the description of this case to the troubleshooting doc.
 
Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-09-25 11:28 UTC, nitishfy approved these changes

2024-09-26 08:16 UTC, reggie-k approved these changes

2024-10-02 15:15 UTC, todaywasawesome requested changes

2024-10-02 15:16 UTC, todaywasawesome commented
@moleus Please fix your DCO, [instructions here](https://github.com/argoproj/argo-cd/pull/20085/checks?check_run_id=30978929657).

2024-10-03 13:48 UTC, todaywasawesome approved these changes
Any more and I think we'll need to combine them all into a single type of error related. We can only tell them to use an index so many times ;)

2024-10-03 14:32 UTC, wanghong230 approved these changes

2024-10-03 14:36 UTC, alexmt approved these changes

2024-10-03 16:03 UTC, nitishfy reviewed
Please sign-off the commits

2024-10-07 11:42 UTC, gdsoumya approved these changes

2024-10-07 11:43 UTC, merged