Testing strict semver functionality (#20083)
argoproj/argo-cd pull request #20096
Opened 2024-09-25 07:52 UTC by PaulSonOfLars

Testing a potential fix for #20083, where ArgoCD's semver resolution is too lax, which causes non-semver tags to be incorrectly coerced into semver. This then causes unexpected tags to be used when they shouldn't be.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-09-25 11:27 UTC, nitishfy reviewed
can you fix the CI failures?

2024-09-25 12:58 UTC, PaulSonOfLars commented
@nitishfy apologies for that, the PR is just aiming to be a draft for now - to see if the silly basic approach would work against the full testsuite (onboarding and spinning up the tests locally is quite painful if you're not a regular contributor!). Clearly it doesn't!

I've now narrowed down on the exact issue, and should be able to make the git semver logic match the helm logic, avoiding any big "breaking" changes.

I'll aim to have that in a proper PR open with tests and the actual fix later tonight, ready for tomorrow's contributors meeting.

2024-09-25 20:52 UTC, rumstead commented on util/git/client.go
> +	log.Infof("Semver constraint '%s' resolved to tag '%s', at reference '%s'", revision, maxVersion.Original(), maxVersionHash.String())
Should we make this a debug log?

2024-09-25 20:55 UTC, rumstead commented on util/git/client.go
> +	if _, err := semver.NewVersion(revision); err == nil {
Do we need this check given a a valid semver isn't a constraint and 

```
constraint, err := semver.NewConstraint(revision)
```
should return an error?

2024-09-29 15:46 UTC, blakepettersson approved these changes
I agree with @rumstead's comment, otherwise LGTM. To unblock this error I'd ship this as-is, but would like to see a follow-up PR which consolidates this with the Helm semver resolution.

2024-09-30 08:51 UTC, gdsoumya approved these changes
LGTM

2024-09-30 08:57 UTC, gdsoumya requested changes

2024-09-30 14:47 UTC, christianh814 approved these changes

2024-09-30 15:44 UTC, PaulSonOfLars commented on util/git/client_test.go
> +	}, {
Just to clarify - are you asking to update the argo docs, or to add a test that covers this case? Or both? :)

2024-09-30 15:49 UTC, blakepettersson commented on util/git/client_test.go
> +	}, {
I think Soumya would like a test case that exercises this case, with ideally some kind of defined expectation on what this should do.

2024-09-30 16:15 UTC, PaulSonOfLars commented on util/git/client_test.go
> +	}, {
Gotcha - done. 
Added a tescase for v1.0, which should only resolve to v1.0.
If users want wildcard versions, they should be explicitly defined

2024-10-02 12:50 UTC, PaulSonOfLars commented on util/git/client_test.go
> +	}, {
Done - but worth noting that these functions are all going to be removed in the follow up PR to unify semver resolution anyway

2024-10-02 13:09 UTC, nitishfy approved these changes
LGTM!

2024-10-03 10:22 UTC, gdsoumya approved these changes

2024-10-03 10:22 UTC, merged

2024-10-03 14:35 UTC, blakepettersson commented
/cherry-pick release-2.12

2024-10-03 14:35 UTC, blakepettersson commented
/cherry-pick release-2.13

2024-10-03 14:36 UTC, blakepettersson commented
@PaulSonOfLars can you create a cherry-pick PR for 2.12 as well?

2024-10-03 17:17 UTC, PaulSonOfLars commented
> @PaulSonOfLars can you create a cherry-pick PR for 2.12 as well?

Done - https://github.com/argoproj/argo-cd/pull/20215