fix: support managing cluster with multiple argocd instances and annotation based tracking
argoproj/argo-cd pull request #20222
Opened 2024-10-03 22:41 UTC by alexmt

Closes https://github.com/argoproj/argo-cd/issues/13079

PR implements forgot part of a [proposal](https://github.com/argoproj/argo-cd/blob/master/docs/proposals/application-name-identifier.md#allow-multiple-argo-cd-instances-manage-applications-on-same-cluster): introduces `installationID` setting that allows to manage one cluster using multiple Argo CD instances.

2024-10-04 16:15 UTC, christianh814 approved these changes

2024-10-04 16:35 UTC, gdsoumya requested changes

2024-10-04 17:18 UTC, gdsoumya approved these changes

2024-10-04 17:58 UTC, alexmt commented on reposerver/cache/cache.go
> +		key = fmt.Sprintf("%s|%s", key, installationID)
Repo server generate manifests with the tracking label/annotation and store them in cache. So we have to reset cache every time when tracking settings changes. I had to follow the same design, so installation id change also require cache reset.

2024-10-05 00:54 UTC, merged

2024-10-18 17:14 UTC, rahulbollisetty commented
Is the installationID calculated automatically? because I don't see the annotation added on creating a app.
Could you please help me out to reproduce it?