[19259] - disableCompression flag --added
argoproj/argo-cd pull request #20292
Opened 2024-10-08 13:48 UTC by nikzayn

Description:
This PR supports the kubectl option to have one optional flag, disableCompression, to support the response compression.

* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Fixes [#19259]" in the description to automatically close the associated issue.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.

2024-10-08 14:16 UTC, OpenGuidou commented
Thanks, I backported this as part of #20291

2024-10-09 12:30 UTC, pasha-codefresh requested changes

2024-10-09 12:30 UTC, pasha-codefresh commented on cmd/util/cluster.go
> +	DisableCompression      bool
You added variable, but you are not using it. 

Take a look here 

https://github.com/argoproj/argo-cd/pull/20291/files#diff-1a32760cee151b5181abcd273fb66e286a02fd8c99573d988e423528760cc293R3194

This is how it should be used. Sorry if i reviewed it too early, maybe you just didnt finish your work

2024-10-10 04:51 UTC, nitishfy reviewed
If this PR isn't ready for a review yet, I'd suggest marking it as WIP

2024-10-10 08:27 UTC, pasha-codefresh commented
It can be closed, because issue is resolved. Huge thanks to @nikzayn , you did significant part of the work in order to resolve this issue.

2024-10-10 08:27 UTC, closed without merging