feat: Enable ignoreResourceUpdate by default #19992
argoproj/argo-cd pull request #20303
Opened 2024-10-09 05:19 UTC by jaehanbyun

Closes: #19992 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [X] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [X] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

## What I have done:
*  Enable ignoreResourceUpdate by default

2024-10-09 10:23 UTC, nitishfy approved these changes
LGTM!

2024-10-09 15:13 UTC, crenshaw-dev commented
Please also update documentation

2024-10-09 15:54 UTC, jaehanbyun commented
> Please also update documentation
I updated documentation. Thanks!

2024-10-09 17:15 UTC, crenshaw-dev requested changes, later dismissed

2024-10-09 17:15 UTC, crenshaw-dev commented on docs/operator-manual/argocd-cm.yaml
> +  resource.ignoreResourceUpdatesEnabled: "true"
Could you also update the docs in reconcile.md?

2024-10-09 18:07 UTC, jaehanbyun commented
@crenshaw-dev I'm not sure if the option has been well explained, PTAL!

2024-10-09 18:33 UTC, rumstead approved these changes

2024-10-10 00:10 UTC, christianh814 approved these changes
Just needs to resolve feedback from Crenshaw but other than that LGTM

2024-10-10 02:40 UTC, agaudreault approved these changes
LGTM. We discussed it a bit today in the SIG Scalability. I have been involved in monitoring the usage of this feature through slack and GitHub issues, i haven't seen any negative impact after enabling it with the default configurations.

Obviously, it still needs to be configured to improve the performance significantly. Perhaps 3.0 can include default confirmation for known resources.

Let's bring it up at the next contributors meeting just in case, but it's safe to merge after that IMO.

2024-10-10 04:43 UTC, jaehanbyun commented
@agaudreault Understood. Please let me know if there are any additional details related to this PR after the meeting. Thanks!

2024-10-10 16:39 UTC, merged