Issue #118 - app delete should be done through controller using finalizers
argoproj/argo-cd pull request #206
Opened 2018-05-15 21:57 UTC by alexmt

2018-05-15 22:06 UTC, merenbach approved these changes
:+1:

2018-05-16 00:40 UTC, jessesuen commented on server/application/application.proto
> +	bool force = 2;
The term force is unclear what will happen in the delete request. This flag really indicates whether or not to perform cascaded deletion or not.

Can we rename this to `cascade` which can either be nil, true or false?

I think the semantics should be:
* If cascade is false, remove the finalizer (if present). delete the object directly from kubernetes. this should not involve the controller.
* If cascade is true, set the finalizer (if not already set). delete the object directly from kubernetes. deletion will be blocked until the finalizer is removed by the controller
* If cascade is nil. don't touch finalizers one way or the other. delete the object directly from kubernetes. deletion may or may not involve controller depending on if finalizer was already set.

2018-05-16 00:47 UTC, jessesuen commented on pkg/apis/application/v1alpha1/types.go
> +func (app *Application) NeedPruneResources() bool {
I think prune may be incorrect terminology.  Pruning implies something will be left over (e.g. your have resources that is no longer managed in git and you want to delete those). But this field indicates whether or not you should delete all the dependant resources.

How about:
app.CascadeDelete()
app.OrphanDependants()

2018-05-16 00:54 UTC, jessesuen requested changes

2018-05-16 00:54 UTC, jessesuen commented on pkg/apis/application/v1alpha1/types.go
> +func (app *Application) SetNeedPruneResources(prune bool) {
I think SetCascadedDeletion(true) is better.

2018-05-16 00:54 UTC, jessesuen commented on server/application/application.proto
> +	bool force = 2;
I think to support nullable fields you may need (gogoproto.nullable) = true.

2018-05-16 00:54 UTC, jessesuen commented on controller/controller.go
> +		log.Infof("Successfully deleted resources for application %s", app.Name)
If we fail to delete the app dependencies, the user has no visibility of why the app won't be deleted in the event of an error. Should we update HealthStatus here?

2018-05-16 22:52 UTC, alexmt commented
@jessesuen your comments are addressed. PTAL

2018-05-16 23:07 UTC, jessesuen commented on server/application/application.go
> +			a.SetCascadedDeletion(true)
This seems like a bug? If q.Cascade is false, but a.CascadedDeletion is true,  then we always set cascaded deletion to be true and do not honor the request from the API.

2018-05-16 23:19 UTC, jessesuen requested changes

2018-05-16 23:27 UTC, jessesuen approved these changes

2018-05-16 23:30 UTC, merged