feat(ui): support display sync wave
argoproj/argo-cd pull request #20614
Opened 2024-10-31 12:30 UTC by linghaoSu

Fixes https://github.com/argoproj/argo-cd/issues/20585

This PR adds the ability to set up the display of sync waves in the sync result list. Since this list already has too many columns, I’ve provided a checkbox to choose whether to display it or not.

## After

https://github.com/user-attachments/assets/d53401fb-ce76-4dcc-9520-ff305e6e394e

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-10-31 20:37 UTC, andrii-korotkov-verkada approved these changes

2024-10-31 22:00 UTC, andrii-korotkov-verkada commented
Maybe we can still just show by default to reduce developer friction.

2024-11-04 02:26 UTC, linghaoSu commented
> Maybe we can still just show by default to reduce developer friction.

Hi @andrii-korotkov-verkada, thank you for your suggestion! Should I just remove the checkbox or set the default value of "display sync wave" to true?

I initially set it to false because some of my apps don’t specify a sync wave, so they would all have the same value, making this column unnecessary in that case. That’s why I chose to keep the default as false.

2024-11-04 11:42 UTC, andrii-korotkov-verkada commented
> Hi @andrii-korotkov-verkada, thank you for your suggestion! Should I just remove the checkbox or set the default value of "display sync wave" to true?
Yeah, that's what I'm thinking.

2024-11-04 18:43 UTC, andrii-korotkov-verkada approved these changes

2024-11-07 18:44 UTC, andrii-korotkov-verkada commented
I've brought this PR up on the contributors meeting and the consensus was to just show the column and not have a checkbox.

2024-11-08 13:59 UTC, linghaoSu commented
> I've brought this PR up on the contributors meeting and the consensus was to just show the column and not have a checkbox.

Hi @andrii-korotkov-verkada,

I've removed the checkbox for sync wave. Could you please review it again?

2024-11-08 15:04 UTC, andrii-korotkov-verkada approved these changes

2024-12-20 14:52 UTC, andrii-korotkov-verkada commented
Can you fix merge conflict, please? @keithchong, can you TAL, please?

2025-01-24 22:49 UTC, keithchong requested changes

2025-01-24 22:49 UTC, keithchong commented on ui/src/app/applications/components/application-operation-state/application-operation-state.tsx
>                                              <div className='application-operation-state__icons_container'>
This is a nit, but there should be spacing between the Resource lifecycle hook anchor and the left edge of the table.  It appears that the Resource lifecycle hook anchor should be moved to the new first column. 

<img width="754" alt="Screenshot 2025-01-24 at 5 44 39 PM" src="https://github.com/user-attachments/assets/761155bc-3e40-443d-8e4e-66f427a263fd" />

<img width="759" alt="Screenshot 2025-01-24 at 5 45 09 PM" src="https://github.com/user-attachments/assets/b3758d0b-60b8-49f3-89b6-1939ca862d7d" />

2025-02-06 15:29 UTC, andrii-korotkov-verkada commented on ui/src/app/applications/components/application-operation-state/application-operation-state.tsx
>                                              <div className='application-operation-state__icons_container'>
Can we move the number to the right or the center of the column? Otherwise it leaves a lot of empty space to the side.

2025-02-17 14:57 UTC, andrii-korotkov-verkada commented
@keithchong, would you be able to re-review? Thank you.

2025-02-25 09:29 UTC, linghaoSu commented on ui/src/app/applications/components/application-operation-state/application-operation-state.tsx
>                                              <div className='application-operation-state__icons_container'>
![image](https://github.com/user-attachments/assets/145db5c7-a5c8-449c-a34d-d9bdc2bf4511)

2025-02-25 12:22 UTC, andrii-korotkov-verkada commented on ui/src/app/applications/components/application-operation-state/application-operation-state.tsx
> +    `${res.group || ''}-${res.kind || ''}-${res.version || ''}-${res.kind === 'Namespace' ? res.name : res.kind}-${res.name}`;
Why do we fallback on kind, as we already have it earlier?

2025-02-25 21:32 UTC, keithchong commented
LGTM. Just how have to rebase and we can merge it after.

2025-02-25 21:34 UTC, keithchong reviewed
Also, just have to answer Andrii's question

2025-03-04 02:36 UTC, linghaoSu commented on ui/src/app/applications/components/application-operation-state/application-operation-state.tsx
> +    `${res.group || ''}-${res.kind || ''}-${res.version || ''}-${res.kind === 'Namespace' ? res.name : res.kind}-${res.name}`;
Yes, you're right—I shouldn't have fallen back to kind. I originally intended to fall back to name when the resource kind is Namespace, but I mistakenly changed it to kind, which was a typo. Now, I think we should keep the original order since this information already exists, making the fallback to name meaningless.

2025-03-05 22:21 UTC, andrii-korotkov-verkada approved these changes

2025-03-07 22:32 UTC, andrii-korotkov-verkada approved these changes

2025-03-13 18:14 UTC, andrii-korotkov-verkada commented
@keithchong, can you take another look, please?

2025-03-14 16:04 UTC, keithchong commented
> @keithchong, can you take another look, please?

LGTM, looks like your question is resolved.

2025-03-14 16:05 UTC, keithchong approved these changes
LGTM

2025-03-14 16:05 UTC, merged