Bugfix: Ensure we have a valid hostname when adding certificates
argoproj/argo-cd pull request #2064
Opened 2019-07-31 20:46 UTC by jannfis

This is a small bugfix to ensure that a valid hostname was given to `CreateCertificate` of API `CertificateService`, so that we don't end up with weird (and invalid) entries in the certificate list or in the worst case, with a security issue (although K8S API limits what can be used as a key in the ConfigMap already).

2019-07-31 21:11 UTC, alexec requested changes

2019-07-31 21:11 UTC, alexec commented on util/cert/cert.go
> +func IsValidHostname(hostname string, fqdn bool) bool {
tests?

2019-07-31 21:11 UTC, alexec commented on util/db/certificate.go
> +			return nil, fmt.Errorf("Invalid hostname in request: %s", certificate.ServerName)
tests?

2019-07-31 21:26 UTC, jannfis commented on util/cert/cert.go
> +func IsValidHostname(hostname string, fqdn bool) bool {
Yup, commited

2019-07-31 21:27 UTC, jannfis commented on util/db/certificate.go
> +			return nil, fmt.Errorf("Invalid hostname in request: %s", certificate.ServerName)
Yup, commited

2019-07-31 21:30 UTC, alexec approved these changes

2019-07-31 22:16 UTC, alexec commented
needs linting

2019-08-01 00:34 UTC, alexmt approved these changes
LGTM. Please fix linting error

2019-08-01 15:08 UTC, jannfis commented
Satisfied the almighty lint monster.

2019-08-01 15:29 UTC, merged

2019-08-01 15:30 UTC, alexec commented
https://www.deviantart.com/khialat/art/Round-the-Twist-Lint-Monster-740912894

2019-08-01 15:47 UTC, jannfis commented
> https://www.deviantart.com/khialat/art/Round-the-Twist-Lint-Monster-740912894

it looks as scary as it is!