docs: fix aws sso documentation
argoproj/argo-cd pull request #20681
Opened 2024-11-06 15:00 UTC by chansuke

Fixes: #20680 

- Update the image of [Identity Center (AWS SSO)](https://argo-cd.readthedocs.io/en/latest/operator-manual/user-management/identity-center/)
- Removed the comma next to the picture
![Screenshot from 2024-11-06 23-59-22](https://github.com/user-attachments/assets/d80c38f5-0988-4570-85d9-42a54f798ec5)

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-11-06 18:15 UTC, gdsoumya requested changes

2024-11-09 04:31 UTC, chansuke commented on docs/operator-manual/user-management/identity-center.md
> +
Thank you for your comment!
I plan to replace the current image with [docs/assets/identity-center-1.png](https://github.com/argoproj/argo-cd/pull/20681/files#diff-9d32f02f9978292c660b15f69e54a0155654778e51d5aa70b27eae45513e8e41) to reflect the latest UI.
I believe that removing the * is reasonable for consistency.
but on the page below, some images have a * on the left side, and i'm not entirely sure about the rule or pattern being followed..
https://argo-cd.readthedocs.io/en/stable/operator-manual/user-management/okta/

2024-11-12 12:26 UTC, gdsoumya approved these changes

2024-11-14 16:08 UTC, blakepettersson approved these changes
LGTM

2024-12-18 14:15 UTC, pasha-codefresh approved these changes

2024-12-18 14:15 UTC, merged