Adam  scm filtering archived repos
argoproj/argo-cd pull request #20736
Opened 2024-11-10 18:52 UTC by aburan28

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-11-10 20:37 UTC, andrii-korotkov-verkada approved these changes
LGTM

2024-11-12 01:32 UTC, ishitasequeira requested changes
Overall PR looks good!! @aburan28 can you resolve the conflicts?

2024-11-12 01:32 UTC, ishitasequeira commented on docs/operator-manual/applicationset/Generators-SCM-Provider.md
> +* `excludeArchivedRepos`: exclude repositories that are archived. defaults to false\
nit: remove the additional `\` at the end?

2024-11-14 13:25 UTC, ishitasequeira reviewed
@aburan28 , looks like the CI are failing with your latest changes.

2025-01-01 18:31 UTC, andrii-korotkov-verkada reviewed
There are a lot of unrelated changes. Can they be split into different PRs?

2025-01-14 17:40 UTC, prune998 commented
anyone working on this ? 
If you move forward I could add the code for `gitlab` scm ?
In Gitlab, we could also check for repositories `marked for deletion`, which would/could be another option to filter repos

2025-01-16 19:55 UTC, prune998 commented
Hey all, it was easier to me to duplicate the PR and refresh it.

If you will, please close this and transition to https://github.com/argoproj/argo-cd/pull/21505

2025-07-31 23:12 UTC, agaudreault commented
Closing as stale in favor of https://github.com/argoproj/argo-cd/pull/21505

2025-07-31 23:12 UTC, closed without merging