fix: order conditions summary
argoproj/argo-cd pull request #20759
Opened 2024-11-11 17:11 UTC by mmorel-35

The formatConditionsSummary doesn't have a predictable outcome.
This fixes this situation caused by https://github.com/argoproj/argo-cd/pull/20750/files#diff-09dc2060ef1815120b6ffc55153594e558691f94bd2fcd47e0e0acb8ba68066aL536-R494

2024-11-12 08:48 UTC, OpenGuidou commented
LGTM !

2024-11-14 13:53 UTC, andrii-korotkov-verkada approved these changes

2024-11-19 17:32 UTC, pasha-codefresh requested changes
Could you please cover it with tests ?

2024-11-20 15:39 UTC, pasha-codefresh approved these changes

2024-11-20 15:46 UTC, merged