feat: allow for specifying pre-release in regex
argoproj/argo-cd pull request #20862
Opened 2024-11-20 13:30 UTC by Spazzy757

This PR allows for checking for pre-release specific tags

previously in the case of having a pre-release (i.e `v1.0.*-rc`) the git check would ignore the pre-release versions and just do the latest tag (i.e v1.0.1) which could be a different release entirely.

**NOTE:** My assumption is that this is only valid with wildcards as I dont think something like `< v1.2.*-rc` would be a valid constraint, but if this is incorrect please let me know

I am not entirely sure if this is considered a bug fix or a feature

Related Issue: https://github.com/argoproj/argo-cd/issues/18899

Related Discussion: https://github.com/argoproj/argo-cd/discussions/20595

would be great to have this patched in `v2.12`

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-11-21 02:13 UTC, andrii-korotkov-verkada commented on USERS.md
> +1. [Vandebron](https://www.vandebron.nl/)
Let's have a separate PR for this

2024-11-26 08:35 UTC, Spazzy757 commented
Hi, is there anything further thats needed for this change?

2024-11-26 10:18 UTC, andrii-korotkov-verkada commented
Would you be able to join the contributors meeting and discuss this?

2024-11-26 10:46 UTC, blakepettersson requested changes
I'd like to see #20216 merged before considering this - since otherwise the way semver is handled in Git would differ from how it is done in Helm (and in the future, OCI)

To be fair, I'm not sure how Helm handles pre-release tags, so it could very well be that this may need to differ.

2024-11-26 10:49 UTC, Spazzy757 commented
> Would you be able to join the contributors meeting and discuss this?

Yes sure, is it at: Thursday at 8:15AM Pacific Time?

2024-11-26 10:51 UTC, Spazzy757 commented
> I'd like to see #20216 merged before considering this - since otherwise the way semver is handled in Git would differ from how it is done in Helm (and in the future, OCI)
> 
> To be fair, I'm not sure how Helm handles pre-release tags, so it could very well be that this may need to differ.

@blakepettersson I'd be happy to fix this there once that is merged, is there a time frame on when that refactor is being merged?

2024-11-26 10:56 UTC, blakepettersson commented
> Yes sure, is it at: Thursday at 8:15AM Pacific Time?

It is, but due to Thanksgiving this upcoming one is cancelled, so it'll have to be the contributors' meeting next week. Alternatively feel free to ask for other opinions on the #argo-cd-contributors channel on the CNCF Slack.

2024-11-26 15:01 UTC, Spazzy757 commented
> > Yes sure, is it at: Thursday at 8:15AM Pacific Time?
> 
> It is, but due to Thanksgiving this upcoming one is cancelled, so it'll have to be the contributors' meeting next week. Alternatively feel free to ask for other opinions on the #argo-cd-contributors channel on the CNCF Slack.
> 
> > @blakepettersson I'd be happy to fix this there once that is merged, is there a time frame on when that refactor is being merged?
> 
> No idea, but IMO this should be good to go right now. I'll need to poke a maintainer to merge that PR.

2024-11-26 15:01 UTC, closed without merging

2025-08-06 14:22 UTC, bitwise-id commented
Hi! 👋

This feature is still very important for many workflows. Currently, suffix-aware semver matching (e.g. *.*.*-qa or *-stag) is not supported in Argo CD. The changes in this PR seem to address this gap, but the PR was closed without merging.

As of the latest master, this functionality is still missing. Could you please consider reopening this PR or resubmitting it? It would help users who rely on pre-release tags for environments like QA or staging.

Thank you for the great work on the initial implementation!

2025-08-21 07:24 UTC, Spazzy757 commented
> Hi! 👋
> 
> This feature is still very important for many workflows. Currently, suffix-aware semver matching (e.g. _._.*-qa or *-stag) is not supported in Argo CD. The changes in this PR seem to address this gap, but the PR was closed without merging.
> 
> As of the latest master, this functionality is still missing. Could you please consider reopening this PR or resubmitting it? It would help users who rely on pre-release tags for environments like QA or staging.
> 
> Thank you for the great work on the initial implementation!

I will retry this when I have time, the reason it was closed because there was a big rewrite in this section of code and they wanted to finalize that before allowing this contribution. I will look into this next week

2025-10-27 06:46 UTC, devops-k4 commented
@Spazzy757 any updates please?

2025-10-27 06:48 UTC, Spazzy757 commented
> @Spazzy757 any updates please?

They have fully refactored the logic where this change needs to be made, so my logic no longer applies. while my team also desperately needs this, I have a full time job and currently don't have time or capacity on this. But if you have capacity or time feel free to