feat: Add basic support for tag path prefixes
argoproj/argo-cd pull request #20948
Opened 2024-11-25 18:29 UTC by chzar

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-11-25 18:56 UTC, chzar commented
To me this change is not so much a feature as a logic change to tolerate tag prefixes - therefor I have not created an enhancement proposal. Happy to do so if the maintainer believe otherwise.

2024-11-26 09:10 UTC, chzar commented
I want to improve this PR to move the constraints to the left side of the targetRevision string and support multiple constraints. Standby...

2024-11-26 15:02 UTC, andrii-korotkov-verkada approved these changes

2024-11-26 15:02 UTC, andrii-korotkov-verkada commented
Please, sign off your commits.

2024-11-26 16:11 UTC, chzar commented
I signed my commits and added a mention of this functionality in the docs under tracking strategies: use cases.

2024-12-04 14:07 UTC, chzar commented
@andrii-korotkov-verkada

Just checking if I need to do anything else or just sit tight and wait for a review?

2024-12-04 14:24 UTC, andrii-korotkov-verkada commented
Just wait for review. You may show up at the contributors meeting and introduce your changes.

2025-01-27 12:43 UTC, dplacencia commented
Hi, any progress on this new feature?

2025-01-27 12:49 UTC, chzar commented
> Hi, any progress on this new feature?

@dplacencia This feature is complete, but the maintainers have asked for more context before giving the greenlight. You can help out by voicing your support in issue #20949

2025-09-12 21:23 UTC, agaudreault requested changes
Wrong PR

2026-02-02 07:41 UTC, k4r1 commented
Hey @chzar, this is great - will be really useful to get this in. Since there's been a refactor around semver in #23310, I've taken the liberty of updating your logic to work with the new structure. I've opened a new PR referencing this one to help get it across the line

2026-02-02 08:07 UTC, chzar commented
> Hey @chzar, this is great - will be really useful to get this in. Since there's been a refactor around semver in #23310, I've taken the liberty of updating your logic to work with the new structure. I've opened a new PR referencing this one to help get it across the line

2026-02-02 08:07 UTC, chzar commented
@k4r1 Thanks for the assist, if you need anything from me - just let me know.

2026-02-02 09:33 UTC, chzar commented
closing in favor of #26207.

2026-02-02 09:33 UTC, closed without merging