fix: repository.Init() to Add gitRepoPaths using the proper new cache key format
argoproj/argo-cd pull request #20962
Opened 2024-11-26 14:44 UTC by jpbelangerupgrade

Regression from https://github.com/argoproj/argo-cd/pull/18388

The gitRepoPaths cache key was updated to now include not just the repository url but the repository Project. Since during init we have no way of knowing the repository project. At least add that repository into cache as the "default" / undefined project.

Note: Cherrypicking this in all active release would be great given 2.12+ are all impacted.

Context:
Our manifest repository is ~20Gi or so. It takes about 5mins minimum to get it cloned properly. What happens on repo-server startup is that repo-server become available BEFORE the manifest repository is cloned. Creating a high cpu usage and also a massive pile-up of request to the restarting repo-server which then cause app to become "unknown" and paging our dev team. This makes argo-cd completely freeze up for 5-15mins everytime we do a node update, recycle a node or any update to repo-server itself.
More information and alternative discussed can be read on https://github.com/argoproj/argo-cd/issues/7927#issuecomment-2437694580

To alleviate that situation, we run an init-container that pre-clones the repo before starting the repo-server process. Which makes repo-server startup much more stable and doesn't come with a freeze on argo-cd reconciliation

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-11-26 20:50 UTC, adminjpbelangerupgrade commented
To add more information related to this use-case and fix
We use pre-cloned repository so if a repository is already cloned, before it would cache that repo location. Now because of the project key, it’s ignoring the existing cloned repository and cloning a new one.
There are also other using persistent volume for their repo-server to have long live repo. Since some apparently have monorepo in the 20+ gig size. 
So before this change. we’d end up with twice the repo cloned.
After, the cache is use and our existing cloned repo is getting used again (same as 2.11.x)

2024-11-26 20:50 UTC, jpbelangerupgrade commented
We use pre-cloned repository so if a repository is already cloned, before it would cache that repo location. Now because of the project key, it’s ignoring the existing cloned repository and cloning a new one.
There are also other using persistent volume for their repo-server to have long live repo. Since some apparently have monorepo in the 20+ gig size.
[3:50](https://cloud-native.slack.com/archives/C01TSERG0KZ/p1732654202821229?thread_ts=1732643596.341869&cid=C01TSERG0KZ)
So before this change. we’d end up with twice the repo cloned.
After, the cache is use and our existing cloned repo is getting used again (same as 2.11.x)

2024-11-27 02:20 UTC, andrii-korotkov-verkada commented on reposerver/repository/repository.go
> +				s.gitRepoPaths.Add(string(keyData), fullPath)
Shall we update getters as well? How does it work?

2024-11-27 14:32 UTC, andrii-korotkov-verkada approved these changes

2024-12-19 20:08 UTC, ddumaisupgrade commented
Hey @andrii-korotkov-verkada . Do you have think we can have an ETA on that ? We are waiting for that to be able to update.

2024-12-19 20:11 UTC, andrii-korotkov-verkada commented
Unfortunately no. I'm not an approver myself and it's a holiday season. I suggest posting in #argo-cd-contributors in CNCF Slack, but still it can take time.

2025-01-07 16:43 UTC, rumstead commented
@blakepettersson just as an FYI

2025-01-07 21:19 UTC, crenshaw-dev commented
We should have a unit test that reproduces the bug.

2025-01-14 15:16 UTC, jpbelangerupgrade commented
@crenshaw-dev As much as I'd like to, this whole method uses os package and binds itself to the filesystem. This would be extremely hard to mock and actually do a valid test case. 
Any chance we can move forward as-is to fix the regression at least. That will allow us to update argo-cd that's lagging being 2 major release right now. As the behavior makes argo-cd unusable for us given the size of our repo.

2025-01-16 20:06 UTC, leoluz requested changes
Hey JP! Long time no see :)

Can you please clarify in the PR description the real impact of this supposed regression?
It seems that you are trying to pre-clone the monorepo and have the repo-server using it. Can you pls confirm? Why is this a hard requirement for monorepos? I'd like to understand how impactful this regression really is.

2025-01-16 20:06 UTC, leoluz commented on reposerver/repository/repository.go
> +					return err
please add context in returned errors.
E.g. `return fmt.Errorf("json.Marshal error while creating cache key: %w", err)`

2025-01-16 20:08 UTC, leoluz commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
@blakepettersson Do you see an issue about setting the project with an empty string at this stage? User is claiming that the introduction of the project in the key broke this flow.

2025-01-16 20:30 UTC, jpbelangerupgrade commented on reposerver/repository/repository.go
> +					return err
Absolutely, reused the same code block as elsewhere which didn't have more than that. But more than happy to make this better ;)

2025-01-16 20:30 UTC, jpbelangerupgrade commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
Also updated PR description with more details and link to another issue we were discussing for alternative

2025-01-16 20:32 UTC, jpbelangerupgrade commented
> Hey JP! Long time no see :)
> 
> @jpbelangerupgrade Can you please clarify in the PR description the real impact of this supposed regression? It seems that you are trying to pre-clone the monorepo and have the repo-server using it. Can you pls confirm? Why is this a hard requirement for monorepos? I'd like to understand how impactful this regression really is.

Long time no see indeed. Thank for taking a look. Update description with more details and impact on our side.

2025-01-16 21:36 UTC, leoluz commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
@jpbelangerupgrade Can you pls confirm how you use AppProject at your company? Do you have a single AppProject for all your apps, 1:1 or everything goes in the default project??

2025-01-17 15:33 UTC, blakepettersson commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
To follow up on @leoluz's question, I presume you have a single (non-project scoped) credential for the repo (I presume yes since you have not yet upgraded to 2.12)?

My concern with this approach is that while this may solve your immediate predicament, this would break once/if a project scoped repo credential is added for the same repo url, since that would involve another git clone. Thinking out loud, it might be worthwhile having a way to configure these cache mappings in the repo-server which it would then use to initialize the cache mappings? Something like Repo URL -> n projects + paths? IMO this needs a bit more thought before saying yay nor nay.

Ultimately, since your repo is ginormous (20gb+) I think alternative ways should be considered (e.g #11198 and/or something more immediate, e.g this [comment](https://github.com/argoproj/argo-cd/issues/7927#issuecomment-2477107148)).

2025-01-17 19:29 UTC, crenshaw-dev commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
Shallow and sparse checkouts aren't a viable short-term option. I'm really not sure they're even a viable long-term option. We really should be able to support 20GB repos without too much pain.

I'm trying to make sure I understand _why_ we don't have the project name available in `Service.Init`. It looks to me as if we're reconstructing the git paths cache from the repos found on disk. If we need additional info from storage (i.e. the project(s) associated with each repo dir), why don't we just write that info to disk so it's available when we need it?

2025-01-17 19:32 UTC, crenshaw-dev commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
@blakepettersson just for my knowledge, can you explain why the project name needs to be part of the path cache key? If I'm reading correctly, this means that each project will have its own clone of any given repo. Why isn't it possible for multiple projects to share the same clone?

2025-01-17 21:20 UTC, jpbelangerupgrade commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
To confirm, yes we have a single mono-repo with no project based repo. 
We don't have plan either to use project based repo, since we have only a single repo. (or eventually one per cluster)

Also we don't do helm generate using argo-cd, we pre-generate all our manifest on our pipeline before merging to our mono-repo manifest. 

We explored a few alternatives last year before settling on the "pre-clone"
- Statefulset repo-server w/ fixed file-system: Helm chart doesn't support it and no plan to support it soon and we didn't want start forking our own (Also going this route would be broken also with this project base repo change, since cloning a repo for a specific project wouldn't survive a restart on a persistent fs, it would end up recloning another repo again)
- Shallow clone: Doesn't really solve the problem, as each git file need will end up with a checkout or fetch that will end up pulling most of the repo

Which left us with using what was in put, init-container, and adding the cloning at that point. 
This gave us slow init-container start, but no perf impact when repo-server start. Just to show you how bad things were, here is the before and after using init-container
![image](https://github.com/user-attachments/assets/90dedaba-fc14-4f0f-8dfc-72f9e775b5a8)
and some git-fetch perf. 20s+ and over for each "call"
![image](https://github.com/user-attachments/assets/87d79df2-6b99-4142-9a76-3da749539d87)

2025-01-20 19:07 UTC, blakepettersson commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
>If I'm reading correctly, this means that each project will have its own clone of any given repo. Why isn't it possible for multiple projects to share the same clone?

@crenshaw-dev not every project, rather every repository credential. If multiple projects are sharing the same repo credential (a "globally scoped" credential using an empty project) then the cache would be reused. The reason we do not share the cache amongst multiple projects is so that we do not risk projects seeing / having access to manifests which it should not have (in theory the same repo url could potentially yield different access to the same repo depending on the credentials given, even if that in practice is minuscule).

We could improve upon this behavior in the future so that the same credentials would yield the same cache key regardless of project (we would just need to do this in a manner which won't somehow inadvertently expose the credentials).

> If we need additional info from storage (i.e. the project(s) associated with each repo dir), why don't we just write that info to disk so it's available when we need it?

Sounds good to me 👍 The question becomes how

2025-01-21 18:36 UTC, crenshaw-dev commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
> The question becomes how

Just as an initial idea, I wonder if we could write a file adjacent to the repo dir. So if the repo dir is `<random UUID>`, the file might be called `<random UUID>_argocd_project` and would just contain the project name associated with the clone.

2025-01-21 18:38 UTC, crenshaw-dev commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
Personally, I feel reasonably okay w/ multiple projects sharing the same cache dir. Even though different credentials could _technically_ expose different contents, I think that would be super atypical. The permissions granularity in every SCM afaik is "clone the repo" or "not clone the repo."

2025-01-23 21:45 UTC, leoluz commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
>Personally, I feel reasonably okay w/ multiple projects sharing the same cache dir. Even though different credentials could technically expose different contents, I think that would be super atypical. The permissions granularity in every SCM afaik is "clone the repo" or "not clone the repo."

Do you mean, removing the project from the cache key?

2025-01-30 16:06 UTC, crenshaw-dev commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
My first comment is proposing keeping the cache key, but storing it on disk so it's available for cache restoration.

My second comment is, yep, might make sense to just remove the project from the cache key.

2025-01-30 16:45 UTC, devopsjedi commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
Which entity is the owner of the cached revision?  Would it be the project or the credentials used to access the repo?

2025-01-30 17:03 UTC, crenshaw-dev commented on reposerver/repository/repository.go
> +				keyData, err := json.Marshal(map[string]string{"url": git.NormalizeGitURL(remotes[0].Config().URLs[0]), "project": ""})
Strictly speaking, I think it makes sense to say that the credential owns the cached revision. But practically, I think project serves as a reasonably proxy for credentials which may or may not be different. At worst, we treat two projects as different when the credentials are actually the same.

But I'm not sure it makes sense to differentiate cache ownership by credential or project. I feel like it's safe to assume that each credential has the same read access to the repo (full clone access) and that any write operations performed by applications in different projects are protected by the concurrent access lock (i.e. one project can't lift a secret that was written to disk by a different project).

But I think it would be fair to review any write operations that occur during manifest generation (for example, modifications to files in the .git config repository) to ensure that 1) they're protected by the concurrent access lock and 2) sensitive changes are cleaned up between operations.

2025-02-03 20:55 UTC, jpbelangerupgrade commented
I did a validation of before and after this change. One thing that @leoluz was mentioning was that my change would regress the current behavior of the project based auth. 

Based on my test it doesn't:
1. If a user leverage project based repo clone, this PR change won't do anything. The repo will be added as default but also, the repo will get recloned for the required project on first use. So this will be of no impact for this use-case
2. If a user doesn't use projects, which is probably most people (like me), then this will behave as before and allow user to reuse existing clone instead of recloning on each startup of repo-server

@crenshaw-dev and @blakepettersson this might be of interest to figure out the next step here.

```
Running v2.13.1
Pre-Cloning enabled
drwx------. 30 argocd argocd 16384 Feb  3 15:07 461130fb-e5de-4983-a8b8-7f5484835df8
drwxr-xr-x.  3 argocd argocd    18 Feb  3 15:17 f6e0b016-48c9-4893-8601-771d433a06b7
d---------. 30 argocd root   16384 Feb  3 15:02 k8s-manifests

Default init
time="2025-02-03T15:04:03Z" level=info msg="Initializing https://github.com/credify/k8s-manifests.git to /tmp/_argocd-repo/461130fb-e5de-4983-a8b8-7f5484835df8"
time="2025-02-03T15:07:46Z" level=info msg=Trace args="[git fetch origin --tags --force --prune]" dir=/tmp/_argocd-repo/461130fb-e5de-4983-a8b8-7f5484835df8 operation_name="exec git" time_ms=222532.09260099998

Project based init
time="2025-02-03T15:17:48Z" level=info msg="Initializing https://github.com/credify/k8s-manifests to /tmp/_argocd-repo/f6e0b016-48c9-4893-8601-771d433a06b7"
level=info msg=Trace args="[git fetch origin --tags --force --prune]" dir=/tmp/_argocd-repo/f6e0b016-48c9-4893-8601-771d433a06b7 operation_name="exec git" time_ms=484082.929101


Results:
- Pre-cloned repo is unused. Associated to a cache item that is never able to be looked up
- f6e0b016-48c9-4893-8601-771d433a06b7 is a project based clone
- 461130fb-e5de-4983-a8b8-7f5484835df8 is the default (no project) clone

——
Updated to PR code w/ pre-cloning enabled

total 16
drwxr-xr-x.  3 argocd root    27 Feb  3 18:25 .
drwxrwxrwx.  3 root   root    58 Feb  3 18:32 ..
d---------. 30 argocd root 16384 Feb  3 18:31 k8s-manifests

time="2025-02-03T18:39:52Z" level=info msg="Initializing https://github.com/credify/k8s-manifests to /tmp/_argocd-repo/7131c06f-3577-4da1-95c8-6f72afbbc22f"
time="2025-02-03T18:46:35Z" level=info msg=Trace args="[git fetch origin --tags --force --prune]" dir=/tmp/_argocd-repo/7131c06f-3577-4da1-95c8-6f72afbbc22f operation_name="exec git" time_ms=402383.445823
time="2025-02-03T18:46:35Z" level=error msg="finished unary call with code Unknown" error="failed to initialize repository resources: rpc error: code = Internal desc = Failed to fetch default: `git fetch origin --tags --force --prune` failed timeout after 1m30s" grpc.code=Unknown grpc.method=GenerateManifest grpc.service=repository.RepoServerService grpc.start_time="2025-02-03T18:39:52Z" grpc.time_ms=403061.62 span.kind=server system=grpc

No repo initializing done for “default” reused the pre-clone
total 32
drwxr-xr-x.  4 argocd root      71 Feb  3 18:39 .
drwxrwxrwx.  3 root   root      58 Feb  3 18:32 ..
drwx------. 30 argocd argocd 16384 Feb  3 18:56 7131c06f-3577-4da1-95c8-6f72afbbc22f
d---------. 30 argocd root   16384 Feb  3 18:31 k8s-manifests

Results:
- Pre-cloned repo was reused. And no other clone was done
- 7131c06f-3577-4da1-95c8-6f72afbbc22f is a project based clone
```

2025-05-06 12:57 UTC, blakepettersson commented
This should be rendered moot with #22712

2025-05-06 12:57 UTC, closed without merging