fix(ui): Replace current spinning webfont icon with svg icons
argoproj/argo-cd pull request #21012
Opened 2024-12-01 08:40 UTC by surajyadav1108

Webfonts have a problem in spinning icons (wobbling issue) which is well discussed and documented
reference: https://github.com/FortAwesome/Font-Awesome/issues/16495

Closes: #10065 

This might look like  an overkill to fix this minor issue but Switching to svg was the only way. I did try tweaking css but didn't work.

before: 

https://github.com/user-attachments/assets/7131f154-c8c1-4b55-9a68-d23d1b723b32

https://github.com/user-attachments/assets/bf4301ab-8163-4280-8821-b07cf977f6e9

After:

https://github.com/user-attachments/assets/16054f70-bd29-40cf-8b4a-e70f06e360a0

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-12-02 03:50 UTC, linghaoSu reviewed
It seems the color is missing when the pod is in the loading state. Could we look into fixing this?

## Before
![image](https://github.com/user-attachments/assets/fe18eed3-2c98-4ee5-9c92-f39fc7439e9f)

## Now
![img_v3_02h6_c0e4c129-6012-4e7a-94d8-b828cc89673g](https://github.com/user-attachments/assets/a269c60e-a6d6-4fd0-88d2-aec35164b968)

2024-12-02 07:37 UTC, surajyadav1108 commented
Thanks for pointing it out @linghaoSu 
I think this should work now 


https://github.com/user-attachments/assets/382b44d1-e12b-474c-814b-98456a577838

2024-12-02 10:40 UTC, nitishfy approved these changes
LGTM!

2024-12-18 20:56 UTC, surajyadav1108 commented
> @surajyadav1108 could you please resolve conflicts ?

Resolved. I have some few other small PRs opened, if you can take a look at those, thank you.

2025-01-05 11:17 UTC, bashlion approved these changes

2025-01-15 18:18 UTC, crenshaw-dev requested changes, later dismissed
This change is awesome! My only concern is the affect on bundle size. 

Before:

```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (16.5 MiB)
      main.b9d7eb03e2adee59afc8.js
```

After:

```
WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  main (19.2 MiB)
      main.ee9e8916fc9c34c77899.js
```

Is there some tree-shaking improvement we can make? Alternatively, can we just hard-code the part we need?

2025-01-16 08:30 UTC, surajyadav1108 commented
> This change is awesome! My only concern is the affect on bundle size.
> 
> Before:
> 
> ```
> WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>   main (16.5 MiB)
>       main.b9d7eb03e2adee59afc8.js
> ```
> 
> After:
> 
> ```
> WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
> Entrypoints:
>   main (19.2 MiB)
>       main.ee9e8916fc9c34c77899.js
> ```
> 
> Is there some tree-shaking improvement we can make? Alternatively, can we just hard-code the part we need?

will try and hardcode all spinning SVGs

2025-01-19 07:05 UTC, surajyadav1108 commented
you can merge this now @crenshaw-dev used SVG directly , this won't affect bundle size 

<img width="751" alt="bundler-size" src="https://github.com/user-attachments/assets/e21d6102-2dbb-47a6-9a16-c87acc668b6a" />


Screenshots


https://github.com/user-attachments/assets/ffeb451d-797d-4ebf-b54c-4928b4415c1d




https://github.com/user-attachments/assets/84bce79d-7bdc-49a5-9a01-d2869a591c4f

2025-02-25 14:51 UTC, crenshaw-dev commented
Thanks, @surajyadav1108! One more request: can you add comments where the SVGs are hard-coded linking to the original source? And we might have to provide some kind of copyright notice to comply with the upstream license.

2025-03-10 08:07 UTC, surajyadav1108 commented
@crenshaw-dev Added original resource, sorry for the late response 😅

2025-05-08 21:41 UTC, agaudreault approved these changes

2025-05-09 00:14 UTC, merged