Update argocd-cmd-params-cm.yaml
argoproj/argo-cd pull request #21046
Opened 2024-12-03 16:07 UTC by lf32

This is an update to docs by adding exponential backoff timeout.
Correction to `controller.self.heal.backoff.timeout.seconds`
Fixes https://github.com/argoproj/argo-cd/issues/21021

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-12-03 16:29 UTC, crenshaw-dev requested changes
It looks like both of these settings exist. I'm not sure how they differ.

```
        - name: ARGOCD_APPLICATION_CONTROLLER_SELF_HEAL_TIMEOUT_SECONDS
          valueFrom:
            configMapKeyRef:
              name: argocd-cmd-params-cm
              key: controller.self.heal.timeout.seconds
              optional: true
        - name: ARGOCD_APPLICATION_CONTROLLER_SELF_HEAL_BACKOFF_TIMEOUT_SECONDS
          valueFrom:
            configMapKeyRef:
              name: argocd-cmd-params-cm
              key: controller.self.heal.backoff.timeout.seconds
              optional: true
```

2024-12-04 15:15 UTC, todaywasawesome commented
I would assume timeout is how long before a request times out and the backoff is how long it will wait before trying again?

2024-12-09 10:03 UTC, reggie-k requested changes
As far as I understand from https://github.com/argoproj/argo-cd/blob/master/controller/appcontroller.go#L2137, 
if selfHealBackOff is not configured, then the selfHealTimeout is used.
So both fields are relevant.
Maybe it is worth to highlight that in the documentation though.

2024-12-10 03:51 UTC, nitishfy approved these changes

2024-12-10 03:52 UTC, nitishfy requested changes
Please go through @reggie-k comment to document it otherwise LGTM

2024-12-11 10:16 UTC, ishitasequeira approved these changes

2024-12-25 10:28 UTC, revitalbarletz commented on docs/operator-manual/argocd-cmd-params-cm.yaml
> +  controller.self.heal.backoff.timeout.seconds: "2"
Is there a way to test this?

2025-01-05 11:15 UTC, bashlion approved these changes

2025-05-02 08:28 UTC, closed without merging