feat(ui): split arrays in yaml to fix ambiguous collapse when array items have nested objects
argoproj/argo-cd pull request #21064
Opened 2024-12-04 21:58 UTC by aali309

Fixes: #20905 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

### Motivation
[see link](https://github.com/argoproj/argo-cd/issues/20905#:~:text=Motivation-,Typically,-the%20first%20item)

### Description of the change
Improve YAML array formatting in the UI to avoid ambiguous collapse behavior. When an array item contains nested objects, the dash (`-`) is now placed on its own line, making it clear which elements can be collapsed independently.

2024-12-04 22:08 UTC, aali309 commented
### Before 
![1](https://github.com/user-attachments/assets/b8f0685a-6979-4c3f-9326-52ba758be0b6)

in collapse

![1b](https://github.com/user-attachments/assets/6fd2d425-98d6-4f84-b216-5bd11bc566cf)

### After
![2](https://github.com/user-attachments/assets/f43925f2-e515-47d0-9645-f3ab63057db9)

in collapse 

![2b](https://github.com/user-attachments/assets/60c641bf-641e-4da1-8f4e-d9999f0d4d94)

2024-12-09 18:10 UTC, keithchong requested changes
Note also that the user can edit the yaml and put the item on the same line as the dash.

Did you check if the formatting will affect the diff?

2024-12-09 21:51 UTC, aali309 commented on ui/src/app/shared/components/yaml-editor/yaml-editor.tsx
> +    yaml = yaml.replace(/^(\s*)-\s+(\w+):/gm, '$1-\n$1  $2:');
<img width="1489" alt="Screenshot 2024-12-09 at 9 04 33 AM" src="https://github.com/user-attachments/assets/977b6c60-601b-4e0e-9ddc-b6253abed41b">

2024-12-09 21:52 UTC, aali309 commented on ui/src/app/shared/components/yaml-editor/yaml-editor.tsx
> +    yaml = yaml.replace(/^(\s*)-\s+(\w+):/gm, '$1-\n$1  $2:');
![Screenshot 2024-12-09 at 4 52 23 PM](https://github.com/user-attachments/assets/a8cdf8f4-77e1-4176-a5cd-e12c91fe904a)

2024-12-10 20:27 UTC, aali309 commented
@jsoref, please review this for me.

2024-12-10 21:14 UTC, jsoref commented
/bns:deploy

2024-12-10 21:23 UTC, jsoref reviewed
It seems good. I'm hoping to play with it, but that'd require someone to poke bunny

2025-01-13 18:58 UTC, aali309 commented
@jsoref PING!

2025-01-13 21:50 UTC, jsoref commented
https://argocd-77zpnz.bunnyenv.com/applications/env-77zpnz/guestbook-77zpnz?view=tree&resource=&node=apps%2FDeployment%2Fenv-77zpnz-guestbook%2Fguestbook-ui%2F0

```yaml
    spec:
      containers:
        - image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          imagePullPolicy: IfNotPresent
          name: guestbook-ui
          ports:
            - containerPort: 80
              protocol: TCP
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
        - command:
            - /shared/argocd-dex
            - rundex
          env:
            - name: ARGOCD_DEX_SERVER_LOGFORMAT
              valueFrom:
                configMapKeyRef:
                  key: dexserver.log.format
                  name: argocd-cmd-params-cm
                  optional: true
          image: gcr.io/heptio-images/ks-guestbook-demo:0.2
          imagePullPolicy: IfNotPresent
          name: guestbook-ui-sidecar
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
```

I don't think it's doing what I want:
<img width="532" alt="image" src="https://github.com/user-attachments/assets/e7ffc5b8-0516-4fc1-a4de-a936d71fff72" />

2025-02-14 22:33 UTC, aali309 commented
https://github.com/user-attachments/assets/73fbbc87-9ad1-4f38-ac73-50ac66668e98

@jsoref, how about now?

2025-02-25 16:12 UTC, aali309 commented
@jsoref is this good to merge?

2025-02-25 17:06 UTC, jsoref commented
I'm happy with the current video assuming things haven't changed since then.

2025-02-25 17:54 UTC, aali309 commented
> I'm happy with the current video assuming things haven't changed since then.

Yes, nothing changed, just rebasing.

2025-02-25 18:33 UTC, jsoref approved these changes

2025-02-27 20:26 UTC, keithchong approved these changes
LGTM

2025-02-27 20:54 UTC, merged

2025-03-03 08:13 UTC, andrii-korotkov-verkada commented
Unfortunately, this might be breaking the ability to edit the live manifest from the UI, as newlines are still there when entering the edit mode. I've opened https://github.com/argoproj/argo-cd/issues/22099, happy to discuss more.

2025-03-03 08:14 UTC, andrii-korotkov-verkada commented
Also, my IMO is that readability is worse with the new approach, as it deviates from how Yaml typically looks like.

2025-03-03 14:36 UTC, andrii-korotkov-verkada commented
I'm afraid this has to be reverted for now, since it indeed results in malformed yaml when editing and saving.