chore: reduce default max payload size in webhooks to 50MB
argoproj/argo-cd pull request #21101
Opened 2024-12-09 10:26 UTC by pasha-codefresh

During the implementation of [GHSA-jmvp-698c-4x3w](https://github.com/argoproj/argo-cd/security/advisories/GHSA-jmvp-698c-4x3w), we initially set the payload size limit to 1GB by default. However, after further discussion with the SIG-Security group, we decided to reduce this limit to 50MB, as 1GB was still considered too large for a payload size.

2024-12-09 10:49 UTC, svghadi requested changes
Requires doc update:
- https://github.com/argoproj/argo-cd/blob/96d0226a4963d9639aea81ec1d3a310fed390133/docs/operator-manual/argocd-cm.yaml#L434-L435 
- https://github.com/argoproj/argo-cd/blob/96d0226a4963d9639aea81ec1d3a310fed390133/docs/operator-manual/webhook.md?plain=1#L22 

and a nit for consistency 
- https://github.com/argoproj/argo-cd/blob/96d0226a4963d9639aea81ec1d3a310fed390133/util/webhook/webhook_test.go#L63

2024-12-09 11:01 UTC, pasha-codefresh commented
> Thanks @pasha-codefresh. Suggesting few additional changes.
> 
> Doc update:
> 
> * https://github.com/argoproj/argo-cd/blob/96d0226a4963d9639aea81ec1d3a310fed390133/docs/operator-manual/argocd-cm.yaml#L434-L435
> * https://github.com/argoproj/argo-cd/blob/96d0226a4963d9639aea81ec1d3a310fed390133/docs/operator-manual/webhook.md?plain=1#L22
> 
> and a nit for consistency
> 
> * https://github.com/argoproj/argo-cd/blob/96d0226a4963d9639aea81ec1d3a310fed390133/util/webhook/webhook_test.go#L63

Oh, thank you!

2024-12-09 11:52 UTC, pasha-codefresh commented
@svghadi fixed

2024-12-09 13:02 UTC, svghadi approved these changes
LGTM. Thanks.

2024-12-09 14:43 UTC, reggie-k approved these changes

2024-12-10 03:44 UTC, nitishfy approved these changes
LGTM! Thanks

2024-12-10 07:38 UTC, ishitasequeira approved these changes
LGTM!!

2024-12-10 07:38 UTC, merged