feat: use project-scoped repos in git generators
argoproj/argo-cd pull request #21167
Opened 2024-12-13 09:14 UTC by blakepettersson

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-12-16 13:28 UTC, gdsoumya submitted a review, later dismissed

2024-12-26 19:43 UTC, blakepettersson commented on util/repository/repository.go
> +	}
After discussing this with @crenshaw-dev, this has been amended to only lookup a repo cred which matches the project found in `.spec.template.spec.project`, and falling back to a repo cred with an empty project if a matching project cannot be found. If the project field is templated, we will only lookup repo creds with an empty project.

2025-01-09 16:29 UTC, agaudreault commented
Looking at the intended behavior, LGTM. 👍 I haven't looked at the code. I'll try to find some time

- if the project is not templated, then
  - Attempt to look up a repository credential with a matching project and url
  - If not found, attempt to look up a repository credential with a matching url, but an empty project (as today)
- Else, when the project is templated, attempt to look up a repository credential with a matching url, but an empty project

2025-01-09 16:34 UTC, agaudreault commented on docs/user-guide/projects.md
> +Please keep in mind when using a project-scoped repository, only applications or applicationsets with a matching project
Can we document this somewhere in the applicationSet section of the doc as well? :)

2025-01-09 16:34 UTC, agaudreault commented on applicationset/services/repo_service_test.go
I think in addition of the unit tests we should have 3 e2e test for the behavior described in the PR.

2025-01-16 12:40 UTC, reggie-k approved these changes

2025-01-20 18:57 UTC, leoluz reviewed
Please check my comments.

2025-01-20 18:57 UTC, leoluz commented on applicationset/services/repo_service.go
> +	getGitDirectories      func(ctx context.Context, req *apiclient.GitDirectoriesRequest) (*apiclient.GitDirectoriesResponse, error)
why not having a single attribute like the following instead of 2 functions signatures in the struct?
`repo Repos`

2025-01-20 18:57 UTC, leoluz commented on applicationset/services/repo_service.go
> +func NewArgoCDService(db db.ArgoDB, submoduleEnabled bool, repoClientset apiclient.Clientset, newFileGlobbingEnabled bool) (Repos, error) {
It seems that there no reason for this function to return error. Can you please confirm and remove it from the returned values if it is the case?

2025-01-21 09:29 UTC, blakepettersson commented on applicationset/services/repo_service.go
> +func NewArgoCDService(db db.ArgoDB, submoduleEnabled bool, repoClientset apiclient.Clientset, newFileGlobbingEnabled bool) (Repos, error) {
You're right - fixed.

2025-01-24 09:41 UTC, blakepettersson commented on applicationset/services/repo_service.go
> +	getGitDirectories      func(ctx context.Context, req *apiclient.GitDirectoriesRequest) (*apiclient.GitDirectoriesResponse, error)
@leoluz I renamed those functions to hopefully make things more clear. Does that make sense?

2025-01-28 17:05 UTC, agaudreault requested changes
@blakepettersson Few small comments. Other than that, LGTM.
 
 Ping me on Slack after they are fixed to merge this!

2025-01-28 17:05 UTC, agaudreault commented on test/e2e/git_generator_test.go
Rename to applicationset_git_generator_test.go

2025-01-28 17:05 UTC, agaudreault commented on test/e2e/fixture/fixture.go
> +	ArgoCDRedisName         string
I don't see any reason to have this var plublic

2025-01-28 20:18 UTC, blakepettersson commented on test/e2e/fixture/fixture.go
> +	ArgoCDRedisName         string
That was not intended - fixing.

2025-01-31 22:44 UTC, agaudreault commented on applicationset/generators/git_test.go
> +			name: "Project field is not templated - verify that project is passed through to repo-server as-is",
I am not sure I understand the tests. The new appProject params does not seem to be used.
The two tests dont seem to assert on whether the project is passed when non-templated or is "" when templating. The both call a mock that mocks `mock.Anything` that will always return the same result.

2025-02-04 18:14 UTC, gdsoumya approved these changes

2025-02-07 15:22 UTC, agaudreault approved these changes

2025-02-07 15:22 UTC, merged