fix: Redis Compression Handling for `argocd app diff`
argoproj/argo-cd pull request #21168
Opened 2024-12-13 14:16 UTC by pcallewaert

When using the argocd app diff command, it fails with the error cache: key is missing. After investigating, I discovered that the Redis compression setting is hardcoded to None, whereas the default for new installations is Gzip. This mismatch causes the feature to break in new setups.

To resolve this, I created a function to dynamically fetch the redis.compression option from the ConfigMap, similar to how Redis credentials are retrieved.

This change also simplifies the argocd admin dashboard by allowing it to detect the Redis compression setting automatically, eliminating the need for a CLI flag.

```txt
ERRO[0000] finished unary call with code Unknown         error="error getting cached app managed resources: cache: key is missing" grpc.code=Unknown grpc.method=ManagedResources grpc.service=application.ApplicationService grpc.start_time="2024-12-13T14:07:57Z" grpc.time_ms=101.72 span.kind=server system=grpc
FATA[0000] rpc error: code = Unknown desc = error getting cached app managed resources: cache: key is missing
```

Fixes https://github.com/argoproj/argo-cd/issues/10554

This would best be cherry-picked on 2.13 (and maybe 2.12) as we encountered the issues on these versions.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-12-19 11:19 UTC, pasha-codefresh requested changes

2024-12-19 11:19 UTC, pasha-codefresh commented on common/common.go
> +func GetRedisCompressionFromKubeConfig(ctx context.Context, kubeClient kubernetes.Interface, namespace string) (string, error) {
would be nice to document this change, also add details how to get correct compression type from your redis server, maybe default values for different redis and argocd versions

2025-01-06 08:25 UTC, pcallewaert commented on common/common.go
> +func GetRedisCompressionFromKubeConfig(ctx context.Context, kubeClient kubernetes.Interface, namespace string) (string, error) {
@pasha-codefresh I added some missing comments, but I'm a bit confused what you mean with different redis or argocd versions. The codebase is pretty new for me but I don't see why this would impact anything?

For `argocd app diff` this code is only hit when using the `--core` authentication, and in that case the API version does not matter. The only requirement would be that the CLI you are using is in the same minor as the server. (No idea if this is checked globally)

For `argocd admin dashboard` I think it is the same requirement that it should be at least in the same minor release for both the CLI and server.

Or am I misunderstanding your question?

2025-01-31 11:35 UTC, pcallewaert commented on common/common.go
> +func GetRedisCompressionFromKubeConfig(ctx context.Context, kubeClient kubernetes.Interface, namespace string) (string, error) {
@pasha-codefresh friendly reminder :)

2025-02-23 19:47 UTC, pasha-codefresh requested changes

2025-02-23 19:47 UTC, pasha-codefresh commented on common/common.go
> +		return "gzip", nil
Please use RedisCompressionGZip variable instead hardcode

2025-02-23 20:00 UTC, pasha-codefresh commented on common/common.go
> +		return "gzip", nil
The default type has been changed long time ago, so i think we are fine with this change also.

2025-02-23 20:00 UTC, pasha-codefresh commented
@pcallewaert small change and lGTM

2025-02-24 16:23 UTC, pcallewaert commented on common/common.go
> +		return "gzip", nil
Do you mean the `RedisCompressionGZip` from the `cache` package? When I want to use this I trigger a import cycle error

2025-02-24 16:32 UTC, pcallewaert commented
It seems this is conflicting now with a PR that got recently merged: https://github.com/argoproj/argo-cd/pull/21786
My PR is to avoid to set the `redis-compress` flag for each CLI command, where @nitishfy 's PR introduces it for each command 😅 Tagging the reviewers of the other PR to see how to proceed: @alexmt @gdsoumya @ishitasequeira

2025-02-24 16:42 UTC, pasha-codefresh commented
@pcallewaert from first glance @nitishfy PR resolve same problem just in different way, right?

2025-02-24 17:52 UTC, nitishfy commented
> It seems this is conflicting now with a PR that got recently merged: #21786 My PR is to avoid to set the `redis-compress` flag for most CLI commands, where @nitishfy 's PR introduces it for each command 😅 Tagging the reviewers of the other PR to see how to proceed: @alexmt @gdsoumya @ishitasequeira

You don't need to do that. Adding the flag as a global flag makes it available to all commands. Looking at the issue specified, it looks like your argocd server version is too old. Please take a look at below references:
- https://github.com/argoproj/argo-cd/pull/21786#discussion_r1944828101

2025-02-25 08:16 UTC, pcallewaert commented
While I do agree that it fixes the issue, I find it odd that you have to pass a server config to "match". It's not that user-friendly. It's quite analogue as the redis password in my point of view.
But as the default is gzip anyway and almost all installations are gzip, I don't think it's a big problem. I'll be closing this one then :)

2025-02-25 08:16 UTC, closed without merging