fix(in-cluster): do not allow the cluster to be used when disabled
argoproj/argo-cd pull request #21208
Opened 2024-12-16 22:40 UTC by agaudreault

Fix https://github.com/argoproj/argo-cd/issues/21207

2024-12-17 16:35 UTC, rumstead requested changes
Could you fix the linting errors? It seems that there is a race condition being caught. The stack traces look like a similar problem I fixed before - https://github.com/argoproj/argo-cd/pull/20805/files

2024-12-18 00:50 UTC, terrytangyuan reviewed
Good catch. Thanks!

2024-12-18 16:34 UTC, agaudreault commented
Cherry pick in 2.13 will require https://github.com/argoproj/argo-cd/pull/20805 and https://github.com/argoproj/argo-cd/pull/21225

2024-12-18 17:52 UTC, ishitasequeira reviewed
The changes LGTM
@agaudreault can you fix the CI failures?

2025-01-03 21:33 UTC, agaudreault commented
@ishitasequeira @terrytangyuan @rumstead  lint/test fixed. Let's wait for discussion on the issue to know if we should cherry-pick.

Thanks for the review!

2025-01-03 21:51 UTC, crenshaw-dev requested changes
lgtm besides a few nitpicks. One final suggestion would be to change the tests to tabular tests for readability. Will go with your decision on whether that's worth the time.

2025-01-03 21:51 UTC, crenshaw-dev commented on applicationset/controllers/applicationset_controller_test.go
> +	kubeclientset := kubefake.NewSimpleClientset(objects...)
NewSimpleClientset is deprecated, you can use NewClientset. Should work fine as a drop-in replacement.

2025-01-03 21:51 UTC, crenshaw-dev commented on applicationset/controllers/applicationset_controller_test.go
> +			err := kubeclientset.Tracker().Add(secret)
Instead of accessing the tracker like this, maybe just parameterize `getDefaultTestClientSet` to accept additional objects? I've seen that pattern in other tests.

2025-01-03 21:51 UTC, crenshaw-dev commented on util/db/cluster.go
> +			return err
Wrap the error?

2025-01-06 14:51 UTC, rumstead approved these changes
Overall LGTM

2025-01-08 16:18 UTC, crenshaw-dev approved these changes

2025-01-22 14:34 UTC, agaudreault commented
Need https://github.com/argoproj/argo-cd/pull/21615 to fix an incorrect behavior making the new e2e fail

2025-01-22 20:36 UTC, merged