Add FuturePLC to List of companies using ArgoCD
argoproj/argo-cd pull request #2122
Opened 2019-08-08 09:55 UTC by warmfusion

We've been using ArgoCD for a few months now, and are using it to deploy onto 5 on prem clusters, 1 cloud cluster and have implemented some of our own code to support hands-off deployment onto review branches into dedicated namespaces.

Using the App of Apps pattern to self-manage argo, the clusters, and the services on those clusters.

Keep up the good work

2019-08-08 09:55 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=2122) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=2122) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=2122) it.</sub>

2019-08-08 16:05 UTC, alexec requested changes
Thank you Toby - a great addition to the list! Do you think you could sign the CLA please?

2019-08-08 16:05 UTC, alexec submitted a review, later dismissed

2019-08-08 16:05 UTC, alexec commented on README.md
> +1. [Future PLC](https://www.futureplc.com/)
minor - but I think this list in alphabetical order?

2019-08-20 21:37 UTC, alexec commented
@warmfusion - we'd love to have this merged -  but we need the CLA signed - can you do that please?

2019-08-26 20:50 UTC, alexmt approved these changes
Got a confirmation that docs changes do not require CLA.  LGTM

2019-08-26 20:51 UTC, merged