chore: use github.com/golang-jwt/jwt/v5
argoproj/argo-cd pull request #21276
Opened 2024-12-20 12:13 UTC by mmorel-35

#### Description 

[gomodguard](https://golangci-lint.run/usage/linters/#gomodguard) allows to block some dependencies.

This ensure that `github.com/golang-jwt/jwt/v5` is used instead of `github.com/golang-jwt/jwt/v4`

2024-12-21 01:41 UTC, terrytangyuan approved these changes
LGTM

2024-12-29 02:46 UTC, andrii-korotkov-verkada commented on util/clusterauth/clusterauth_test.go
> +	},
Why does this change? Can you keep the field names, please?

2024-12-29 02:46 UTC, andrii-korotkov-verkada commented on util/clusterauth/clusterauth.go
> +	jwtgo "github.com/golang-jwt/jwt/v5"
Why do we call it jwtgo here but not in some other places?

2024-12-29 20:51 UTC, andrii-korotkov-verkada approved these changes

2025-01-02 21:52 UTC, crenshaw-dev requested changes

2025-01-02 21:52 UTC, crenshaw-dev commented on pkg/apiclient/apiclient.go
> +	if validator.Validate(claims) == nil {
I'm not sure we should set a 5s leeway here. I don't think there was any leeway in v4 (https://github.com/golang-jwt/jwt/compare/v4.5.1...v5.2.1#diff-9803198a7ae31435cd378cab1ca22b1c0bb28c58c9d9b308d246ac96982bdc95L250), and I think the `5 * time.Second` example in the migration guide is just an example. https://github.com/golang-jwt/jwt/blob/main/MIGRATION_GUIDE.md

2025-01-02 23:22 UTC, crenshaw-dev approved these changes

2025-01-02 23:23 UTC, merged