fix: Policy/policy.open-cluster-management.io stuck in progressing status when no clusters match the policy (#21296)
argoproj/argo-cd pull request #21297
Opened 2024-12-23 09:58 UTC by mbaldessari

When a policy does not apply to a cluster because the placementrule matches no cluster at all then the status will look like the following:

    status:
      placement:
      - placementBinding: group-one-placement-binding
        placementRule: group-one-placement

Without this change the above will show up as progressing even though there is really nothing to progress.

Let's take care of this case by returning healthy when there is no compliant field but the array under placement is non-zero, which means that its placement resolution has happened and there is nothing to do.

Fixes: #21296

Ideally this should be backported to release-2.13 (only)

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [n/a] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [no] Does this PR require documentation updates?
* [n/a] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [n/a] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [x] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [x] Optional. My organization is added to USERS.md.
* [x] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

2024-12-29 02:59 UTC, andrii-korotkov-verkada approved these changes

2025-01-02 19:45 UTC, dhaiducek requested changes
Thanks for the update, @mbaldessari!

FYI @JustinKuli

2025-01-02 19:45 UTC, dhaiducek commented on resource_customizations/policy.open-cluster-management.io/Policy/health.lua
> +  hs.message = "No clusters are matching this policy"
nit: wording
```suggestion
  hs.message = "No clusters match this policy"
```

2025-01-02 19:45 UTC, dhaiducek commented on resource_customizations/policy.open-cluster-management.io/Policy/health.lua
> +if obj.status.compliant == nil and #obj.status.placement > 0 then
An additional conditional is required for the case where clusters were matched but are not yet reporting status.

```suggestion
-- A policy will not have a compliant field but will have a placement key set if
-- it is not being applied to any clusters
if obj.status.compliant == nil and #obj.status.placement > 0 and obj.status.status == nil then
```

2025-01-13 22:14 UTC, agaudreault reviewed
@mbaldessari LGTM. Please address open comments. It can be merged after., 👍

2025-01-19 19:39 UTC, mbaldessari commented on resource_customizations/policy.open-cluster-management.io/Policy/health.lua
> +if obj.status.compliant == nil and #obj.status.placement > 0 then
Ack, done

2025-01-19 19:40 UTC, mbaldessari commented
Thanks for the feedback and apologies for the delay, I addressed both and rebased the PR while I was at it.

2025-01-20 14:20 UTC, dhaiducek commented
@mbaldessari The conversations were marked resolved, but I don't see the requested updates here in the PR.

2025-01-20 14:34 UTC, mbaldessari commented
> @mbaldessari The conversations were marked resolved, but I don't see the requested updates here in the PR.

Holy guacamole, I must have pushed the wrong thing. Apologies. Taking a look now

2025-01-20 14:39 UTC, mbaldessari commented
> @mbaldessari The conversations were marked resolved, but I don't see the requested updates here in the PR.

Ok, now the right branch should be pushed up. Serves me well for doing it late at night I guess. Thanks for noticing and letting me know

2025-01-20 20:34 UTC, dhaiducek approved these changes
LGTM! Thanks for the update, @mbaldessari! 😄

2025-01-20 20:35 UTC, dhaiducek commented
Looks like this PR is blocked until this gets merged/resolved, though:
- https://github.com/argoproj/argo-cd/pull/21580

2025-01-21 05:25 UTC, mbaldessari commented
Ah thanks for that info, I have rebased on top of that PR now that it merged. Let's see if this clears up CI

2025-01-21 13:19 UTC, ishitasequeira approved these changes
LGTM!!

2025-01-21 13:19 UTC, merged

2025-01-21 13:19 UTC, ishitasequeira commented
/cherry-pick release-2.13

2025-01-21 20:56 UTC, ishitasequeira commented
/cherry-pick release-2.14