fix: x509 error when adding cluster with different cadata (Fixes #21326)
argoproj/argo-cd pull request #21327
Opened 2024-12-29 18:40 UTC by aminarefzadeh

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] The title of the PR conforms to the [Toolchain Guide](https://argo-cd.readthedocs.io/en/latest/developer-guide/toolchain-guide/#title-of-the-pr)
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/blob/master/community/CONTRIBUTING.md#legal)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).
* [ ] My new feature complies with the [feature status](https://github.com/argoproj/argoproj/blob/master/community/feature-status.md) guidelines.
* [ ] I have added a brief description of why this PR is necessary and/or what this PR solves.
* [ ] Optional. My organization is added to USERS.md.
* [ ] Optional. For bug fixes, I've indicated what older releases this fix should be cherry-picked into (this may or may not happen depending on risk/complexity).

This PR Fixes #21326

2025-01-01 18:34 UTC, andrii-korotkov-verkada reviewed
Looks good overall, move adding user to a different PR and resolve the merge conflict.

2025-01-01 18:34 UTC, andrii-korotkov-verkada commented on USERS.md
> +1. [Divar](https://divar.ir)
Let's have a separate PR for this.

2025-01-01 20:29 UTC, aminarefzadeh commented on USERS.md
> +1. [Divar](https://divar.ir)
Thanks, I'v resolved the conflicts and created a separate PR for adding the organization here:
https://github.com/argoproj/argo-cd/pull/21344

2025-01-02 21:38 UTC, aminarefzadeh commented
> Looks good overall, move adding user to a different PR and resolve the merge conflict.

Hi Andrii, Can you tell me what is the status of this PR? If there is any problem, please tell me so I can resolve it.

2025-01-03 12:39 UTC, nitishfy reviewed
The changes look good to me though. However, I'd suggest adding a description for this PR on what error were you typically getting earlier/or consider raising an issue for the same.

2025-01-04 13:13 UTC, aminarefzadeh commented
> The changes look good to me though. However, I'd suggest adding a description for this PR on what error were you typically getting earlier/or consider raising an issue for the same.

Thanks for your feedback. I have updated the description of this PR and described the bug we are trying to fix. 
If the description is vague or lacks information, please inform me so I could provide more information and screen shots for this bug.

2025-01-04 13:20 UTC, aminarefzadeh commented
I have also built these changes and tested them in my local environment, and it seems like the problem has been fixed.

2025-01-05 11:15 UTC, nitishfy commented on cmd/util/cluster.go
>  // GetKubePublicEndpoint returns the kubernetes apiserver endpoint as published
```suggestion
// GetKubePublicEndpoint returns the kubernetes apiserver endpoint and certificate authority data as published
```

nit

2025-01-05 11:18 UTC, nitishfy commented on cmd/util/cluster.go
> +	return config.Clusters[0].Cluster.Server, config.Clusters[0].Cluster.CertificateAuthorityData, nil
```suggestion
	return config.Clusters[0].Cluster.Server, config.Clusters[0].Cluster.CertificateAuthorityData, nil
```

Instead of returning them as direct values, we can assign them as variables and return them.  In future, if we ever want to update or play with the apiserver endpoint and certification authority data, we can use those variable instead.

2025-01-05 11:21 UTC, nitishfy requested changes
Left some minor comments, overall LGTM!

2025-01-05 12:51 UTC, aminarefzadeh commented
> Left some minor comments, overall LGTM!

Thanks for the suggestions, I have applied them in the latest commit.

2025-01-06 11:21 UTC, aminarefzadeh commented
Hello again @nitishfy. Do you happen to have any update on this PR?

2025-01-07 10:19 UTC, nitishfy approved these changes

2025-01-13 17:34 UTC, gdsoumya approved these changes

2025-01-14 00:07 UTC, agaudreault approved these changes

2025-01-14 00:07 UTC, merged