[WIP] Add `argocd app wait` command
argoproj/argo-cd pull request #216
Opened 2018-05-17 15:52 UTC by merenbach

2018-05-17 16:41 UTC, alexmt approved these changes

2018-05-17 16:41 UTC, alexmt commented on util/util.go
> +	next := time.Tick(time.Duration(checkInterval) * time.Second)
👍

2018-05-17 16:45 UTC, alexmt requested changes

2018-05-17 16:45 UTC, alexmt commented on cmd/argocd/commands/app.go
> +				log.Printf("Timed out before seeing app %q match desired state", appName)
Please print more details to stderr if app has not reached desired state:

if app is not healthy then we need to print list of unhealthy components and reason
if app is not synced then we need to list of unsynced components

2018-05-17 17:50 UTC, alexmt approved these changes

2018-05-17 18:00 UTC, jessesuen requested changes

2018-05-17 18:37 UTC, merenbach commented on cmd/argocd/commands/app.go
> +			success := util.Wait(DEFAULT_CHECK_INTERVAL_SECONDS, timeout, func() bool {
@jessesuen thanks!  I have pushed an update.  I'm not sure if it's complete yet, although it might be.  Interested in your thoughts.

2018-05-17 20:35 UTC, merenbach commented
oops, still need to timeout

2018-05-18 15:15 UTC, alexmt commented
LGTM again :)

2018-05-18 17:59 UTC, jessesuen approved these changes
Thanks Andrew! The only change I would like to see is that defaultCheckTimeoutSeconds to be defaulted to infinite. 10 seconds is way to short, and we don't know enough about a user's app to come up with a better number. (i.e. they their readiness probe might have a 60 second delay.)

2018-05-18 18:50 UTC, merged