Duct tape fix for displaying hooks in app diff view. Fixes #2215
argoproj/argo-cd pull request #2218
Opened 2019-08-24 00:38 UTC by alexec

Fixes #2215

2019-08-24 01:06 UTC, alexec commented on ui/src/app/applications/components/application-resources-diff/application-resources-diff.tsx
> +                    hook: state.liveState.metadata.annotations['argocd.argoproj.io/hook'],
I'm aware that this will not deal with Helm, but it'll do for now, and Helm can be fixed in #1865.

2019-08-24 01:06 UTC, alexec commented
Should back-port to v1.2

2019-08-26 17:52 UTC, alexmt requested changes

2019-08-26 20:25 UTC, alexmt approved these changes

2019-08-26 20:50 UTC, merged