Disables TestAutoSyncSelfHealEnabled.
argoproj/argo-cd pull request #2703
Opened 2019-11-13 01:01 UTC by alexec

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to the README.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2019-11-17 20:42 UTC, alexmt requested changes
Test should be fixed instead of being disabled. Since I don't have time to work on it right noe, can you take it @alexec ?

2019-11-18 01:37 UTC, alexec commented
I don’t know the code that is failing,  @alexmt I think fixing really needs to lie with you. I don’t think we should fail PRs due to this. Instead we should disable it and fix it in another ticket with can be prioritized appropriately.

2019-11-18 23:11 UTC, alexmt approved these changes

2019-11-18 23:12 UTC, alexmt commented
ok, created https://github.com/argoproj/argo-cd/issues/2739

2019-11-18 23:12 UTC, merged