Adds revision history limit. Closes #2790
argoproj/argo-cd pull request #2818
Opened 2019-12-05 21:26 UTC by alexec

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to the README.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Closes #2790

2019-12-06 02:15 UTC, alexec commented
@jessesuen can I request a go/no go on this PR?

2019-12-09 17:22 UTC, alexmt requested changes

2019-12-09 17:22 UTC, alexmt commented on pkg/apis/application/v1alpha1/types.go
> +func (in RevisionHistories) Find(predicate func(h RevisionHistory) bool) *RevisionHistory {
Unused? Please remove method and test if it is not used anywhere

2019-12-13 18:55 UTC, alexmt approved these changes

2019-12-13 18:55 UTC, alexmt commented on pkg/apis/application/v1alpha1/types.go
> +func (in RevisionHistories) Find(predicate func(h RevisionHistory) bool) *RevisionHistory {
removed

2019-12-13 19:14 UTC, merged