check ssh and https url in bitbucketserver webhook #2773
argoproj/argo-cd pull request #3036
Opened 2020-01-27 08:53 UTC by eSamS

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-01-27 08:54 UTC, claassistantio commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=3036) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=3036) before we can accept your contribution.<br/><hr/>**Esra Siegert** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=3036) it.</sub>

2020-01-31 20:00 UTC, jannfis requested changes
Thanks for your PR, @eSamS ! Looks good so far, I just have some minor comments that I want to discuss. Please have a look.

2020-02-03 07:28 UTC, eSamS commented on util/webhook/webhook.go
> +			return
You are right. I've added the changes.

2020-02-03 07:28 UTC, eSamS commented on util/webhook/webhook.go
> +			return
Same here.

2020-02-03 09:01 UTC, jannfis approved these changes
LGTM, thank you!

2020-02-03 09:03 UTC, merged