fix: don't double-prepend basehref to redirect URLs (fixes #3137)
argoproj/argo-cd pull request #3138
Opened 2020-02-19 23:55 UTC by gpaul

Fixes https://github.com/argoproj/argo-cd/issues/3137

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to the README.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-02-24 02:20 UTC, gpaul commented
@alexmt mind taking a look? I can confirm this fixes the issue.

2020-02-26 21:52 UTC, alexmt requested changes
Thanks you for the fix @gpaul ! Requested one minor change

2020-02-26 21:52 UTC, alexmt commented on ui/src/app/app.tsx
> -            window.location.href = `${basehref}/auth/login?return_url=${encodeURIComponent(location.href)}`;
It appears that this change is not required for SSO flow. Looks like `history.push` taking into account page basehref but `window.location.href` don't. so we still need to has set `basehref` manually here. Can you please revert this line?

2020-02-26 22:51 UTC, gpaul commented
Ah right, done.

2020-02-26 23:13 UTC, alexmt approved these changes

2020-02-26 23:13 UTC, merged