feat: Custom application icon
argoproj/argo-cd pull request #3220
Opened 2020-03-10 22:29 UTC by carlosjgp

Relates to #2961 

I'm trying to add a field to the UI forms and components to allow to render a custom icon for apps and default to Helm `Chart.yaml` icon field if it's defined but NodeJs is not my strength
and I'm struggling to figure out how to get/post the information from the two different components (`application` and `server`) and where on the UI this information should be merged

I'll post a message on the Slack channel and use this PR to share the code

Signed-off-by: Carlos Juan Gómez Peñalver <carlosjuangp@gmail.com>

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-03-16 18:01 UTC, jannfis requested changes
Hi @carlosjgp, thanks for submitting your PR, it's much appreciated!

While I think the change you are introducing indeed is useful, I feel a little uncomfortable with having the UI display images from possibly untrusted sources. I think that this feature should be toggleable, maybe on a project level, to prevent unwanted tracking of UI users. Maybe even go so far to whitelist certain URLs usable as icon source. I'm not sure whether I'm being too paranoid here, so I'd love to hear other opinions @alexmt @jessesuen 

Also, please find some minor things I found during my review in the comments below .

2020-03-19 21:08 UTC, carlosjgp commented on ui/.node-version
> +v11.15.0
I use AVN to switch between NodeJS version on different repository automatically
https://github.com/wbyoung/avn

Advised by my company's NodeJS developers (I'm on the infrastructure/DevOps team)
I didn't mean to commit this file

I'll remove it!

2020-03-19 21:09 UTC, carlosjgp commented on docs/CONTRIBUTING.md
>  ```
I'll raise a separate PR to update the documentation and add the instructions for `helm2`

2020-03-19 21:13 UTC, carlosjgp commented on pkg/apiclient/repository/repository.pb.go
> +}
Yeah, I tried to use it to update the NodeJS models but it seems to be a manual process...

I tried
```
make protogen codegen codegen-local                                                                                                                                                                
make codegen openapigen                                                                                                                                                                            
make codegen lint test cli image 
```

I'll revert that

2020-05-03 20:10 UTC, carlosjgp commented
Looks like the contributing guidelines have been moved it looks very nice!

and this PR is now a little bit behind `master`. I'll close it and will start over again and maybe raise a draft PR which I just discovered while starting to contribute to [Terraform](https://github.com/hashicorp/terraform/blob/master/.github/CONTRIBUTING.md#pull-request-lifecycle)
https://github.blog/2019-02-14-introducing-draft-pull-requests/

Something that might interest Argo Project Team to add to the contributing guidelines?

Thanks for your time and comments @jannfis

2020-05-03 20:10 UTC, closed without merging