Fix issue when the application status panel item was too big. #3459
argoproj/argo-cd pull request #3460
Opened 2020-04-22 01:28 UTC by martinjaimem

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, **(b) this is a bug fix**, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-04-22 01:28 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=3460) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=3460) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=3460) it.</sub>

2020-04-22 15:55 UTC, alexmt requested changes
Did you mean `overflow: hidden`. I think this is correct fix. With overflow scroll panels does not look good.

![image](https://user-images.githubusercontent.com/426437/80003939-93dd9080-8476-11ea-9c5a-1d154c753911.png)

Can you please change overflow value to `hidden`? User will be able full commit message in the tooltip.

2020-04-23 01:08 UTC, alexmt commented
Thank you @martinjaimem!

Please ignore sonarqube CI failure. We are fixing it right now, It is not related to your change.

2020-04-23 01:12 UTC, martinjaimem commented
> Thank you @martinjaimem!
> 
> Please ignore sonarqube CI failure. We are fixing it right now, It is not related to your change.

No, thank you for the feedback! 🚀

2020-04-30 21:22 UTC, alexmt approved these changes

2020-04-30 21:23 UTC, merged