feat: adding failure retry
argoproj/argo-cd pull request #3548
Opened 2020-05-05 18:27 UTC by mayzhang2000

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Ref: #2960

2020-05-12 16:14 UTC, alexmt requested changes

2020-05-12 16:14 UTC, alexmt commented on cmd/argocd-server/commands/root.go
> +		failureRetryCount         int
Settings, that we don't expect the user to change, typically configured using environment variables. Can you please create two environment variables instead ? `ARGOCD_K8S_RETRY_COUNT` and `ARGOCD_K8S_RETRY_DURATION_MILLISECONDS`

2020-05-12 16:14 UTC, alexmt commented on cmd/argocd-server/commands/root.go
> +		failureRetryPeriodSeconds int
1 second between retries might be too much. Can you please change the unit to milliseconds and change default to 100 milliseconds.

2020-05-12 16:14 UTC, alexmt commented on controller/metrics/failureretrywrapper.go
> +		time.Sleep(time.Duration(frt.failureRetryPeriodSeconds) * time.Second)
Roundtripper unnecessary sleeps if retry attempt is successful. Can you please fix it?

2020-05-18 15:42 UTC, alexmt approved these changes
LGTM. 

Please group imports in failureretrywrapper.go and  root.go files. Typically we have three groups: imports from golang standard libraries, third-party imports, imports from argoproj.io/argo-cd

Example is in https://github.com/argoproj/argo-cd/blob/master/reposerver/server.go

2020-05-18 15:42 UTC, alexmt commented on cmd/argocd-server/commands/root.go
> +	"github.com/argoproj/argo-cd/util/env"
Nitpick: please keep imports grouped.

2020-05-18 16:51 UTC, merged

2020-05-20 04:13 UTC, mayzhang2000 commented
fixes #2960