feat: update cluster secret from metrics
argoproj/argo-cd pull request #3569
Opened 2020-05-12 03:51 UTC by mayzhang2000

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-05-12 16:41 UTC, alexmt requested changes

2020-05-12 16:41 UTC, alexmt commented on pkg/apis/application/v1alpha1/types.go
> +	LastCacheSyncTime string `json:"lastSyncTime,omitempty" protobuf:"bytes,7,opt,name=lastSyncTime"`
`ConnectionState` data structure already has `ModifiedAt` field. Let's use it instead.

2020-05-12 16:41 UTC, alexmt commented on server/cluster/cluster.go
> +	if cluster.LastCacheSyncTime != "" {
If the controller is down the cluster connection state will be obsolete. I think we should introduce `Unknown` status in addition to `Successful` and `Failed`. The `Unknown` status should be used is status attribute is missing or `modifiedAt` is too old.

2020-05-12 16:41 UTC, alexmt commented on controller/metrics/clustersecretupdater.go
> +				cluster.LastCacheSyncTime = info.LastCacheSyncTime.String()
The controller might be unable to connect to cluster. In this case the status should be failed with the appropriate error message. The connection error is not available in ClusterInfo data structure but it is easy to add it:

https://github.com/argoproj/argo-cd/blob/8ad928330f26b3eea523626d306306e4929aaa7a/controller/cache/cluster.go#L675

Lets store both ConnectionState and Message in cluster secret annotations

2020-05-18 01:57 UTC, mayzhang2000 commented
This is replaced by https://github.com/argoproj/argo-cd/pull/3604.

2020-05-18 01:57 UTC, closed without merging