feat: CLI: Allow setting Helm values literal (#3601)
argoproj/argo-cd pull request #3646
Opened 2020-05-25 21:41 UTC by sfynx

While you could already set values files using the `--values` flag with external data using the CLI with `argocd app create` and `argocd app set`, this was not yet possible for managing the literal `.spec.source.helm.values` value in an Application without resorting to a complicated `argocd app patch` escaped parameter or by generating the entire application YAML manifest by yourself.

Therefore, this PR adds a `--values-literal-file` flag to the `argocd app create` and `argocd app set` commands, which accepts a local file name or URL to a values file, which will be read and included as a multiline string in the application manifest. This is different from the `--helm-set-file` flag which expects the file in the chart itself.

The `argocd app unset` command is expanded with a `--values-literal` flag, so we can also unset this field again.

I hope I chose nice enough names for the flags, I wanted to make clear it expects a file name, but also distinguish it enough from the existing `--values` flag which actually points to values files.

Because the current `setHelmOpt()` functionality would not work for unsetting things to an empty value and it was difficult to do these changes independently, this PR also contains the fix for issue #3644. A separate PR has still been created for that one because I think it should end up as a separate issue in the release notes.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-05-25 22:06 UTC, sfynx commented
Not sure how I could reasonable cover more of the 24 lines that have been added, it is mainly added CLI structure.

2020-05-27 07:06 UTC, jannfis requested changes
Hi @sfynx, thanks a lot for your contribution!

Please ignore the Sonarcloud quality gate for now, we have no good mechanisms for unit testing the CLI yet, so we don't expect people to deliver unit tests for CLI changes. However, it would be great if you could write an end-to-end test (have a look at `test/e2e` directory) that ensures your feature works as expected.

2020-05-27 22:40 UTC, sfynx commented
I have added the tests for both the local and remote file scenarios for adding a literal values block to an application, and also checked that it is cleared out as well when unsetting it.

2020-05-28 13:39 UTC, jannfis approved these changes
This is awesome, thank you! 

Changes look good to me - @alexmt, your say?

2020-05-29 15:56 UTC, alexmt commented on cmd/argocd/commands/app.go
> -							specValueFiles = append(specValueFiles[0:i], specValueFiles[i+1:]...)
👍

2020-05-29 15:59 UTC, alexmt approved these changes
LGTM. Thank you!

2020-05-29 16:00 UTC, merged