upgrade to go 1.14.4
argoproj/argo-cd pull request #3716
Opened 2020-06-05 15:56 UTC by tareqhs

trying work-around for https://github.com/golang/go/issues/37436

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-06-05 15:56 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=3716) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=3716) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=3716) it.</sub>

2020-06-05 17:30 UTC, alexmt requested changes
hello @tareqhs ,

Can you please send PR to master branch instead?

2020-06-06 06:51 UTC, tareqhs commented
hi @alexmt , a change in master will be made of course. the issue is the existing installations of argo are crashing in some system running on kernel versions described in the bug - not doing this in 1.5 means affected users will have to revert to older versions of argocd and wait for 1.6

2020-06-06 12:15 UTC, jannfis requested changes
Hi @tareqhs, we can only accept PRs for master branch and will cherry-pick bug fixes to the respective release branches if appropriate.

Also, there are a few more places that need update version of Go, i.e. in the integration test workflows. We shouldn't push an image built with a Golang version that has not gone through testing, IMHO.

So can you please send PR against master and also update the other places? And please also have a look at https://argoproj.github.io/argo-cd/developer-guide/contributing/#submitting-prs :)

Thank you!

2020-07-17 19:27 UTC, closed without merging