fix: Reap orphaned ("zombie") processes in argocd-repo-server pod (#3611)
argoproj/argo-cd pull request #3721
Opened 2020-06-07 20:48 UTC by jannfis

Fixes #3611

Use [tini](https://github.com/krallin/tini) as fallback, if user choses to set `shareProcessNamespace` to false for `argocd-repo-server` pod for whatever reason they might have.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-06-08 22:57 UTC, jessesuen requested changes
I think we should run **_without_** shareProcessNamespace: true, and rely only on tini, since they are redundant.

That said, we should be *compatible* if someone set `shareProcessNamespace: true`, so I agree with the changes to uid_entrypoint.sh. But I rather not propagate `shareProcessNamespace: true` in the install manifests.

`shareProcessNamespace: true` has the consequence of any sidecars having access to the process namespace of the peer containers. So there is potential security concerns, especially if those peer containers run as root.

2020-06-09 09:39 UTC, jannfis commented
Thanks @jesse, that was exactly the kind of feedback I was looking for. Also, I have taken a look at the code for K8s' `pause` container, they don't use code from `tini`, they just install a simple signal handler for `SIGCHLD` and do a `waitpid()` call with `WNOHANG` flag to catch any orphaned processes (https://github.com/kubernetes/kubernetes/blob/master/build/pause/pause.c). According to the `tini` GitHub page, Docker implemented `tini` when started with the `--init` flag.

I will remove the `shareProcessNamespace` from the manifests, since I agree upon your concerns regarding consequences.

2020-06-09 19:00 UTC, alexmt approved these changes
LGTM

2020-06-09 20:50 UTC, jessesuen approved these changes

2020-06-09 20:58 UTC, merged