Add Revision to app_info
argoproj/argo-cd pull request #3869
Opened 2020-06-29 14:31 UTC by Cytram

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-06-29 14:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=3869) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=3869) before we can accept your contribution.<br/><hr/>**Jesper Petersen** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=3869) it.</sub>

2020-08-18 07:55 UTC, Cytram commented
Is it possible to get an update for this PR?

2020-08-18 17:13 UTC, alexmt requested changes
Prometheus doesn't like is high-cardinality labels. Each unique combination of key-value creates new time series which is stored in memory. So if we add revision label then it will significantly increase api-server memory usage and Prometheus itself won't be able to handle it.


I'm afraid it is impossible to expose revision via Prometheus metrics.

2021-04-01 14:05 UTC, sbose78 commented
Given that this changes impacts resource consumption in a significant way :( , we should explore alternatives. This could be closed @alexmt ?

2022-03-01 09:56 UTC, closed without merging