fix: not hide resource when resource is owned by other resource
argoproj/argo-cd pull request #4022
Opened 2020-07-31 02:37 UTC by mayzhang2000

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-08-03 16:31 UTC, alexmt requested changes

2020-08-03 16:31 UTC, alexmt commented on ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx
> +    function isManagedResource(node: ResourceTreeNode) {
Minor improvement. Please store keys of `props.app.status.resources` in Set to avoid `n*m` complexity.

2020-08-04 20:53 UTC, alexmt approved these changes
LGTM

2020-08-05 16:35 UTC, merged

2020-08-05 16:35 UTC, mayzhang2000 commented
fixes #2798