enhancement(ui): Project summary settings redesign. Fix #4015
argoproj/argo-cd pull request #4066
Opened 2020-08-07 19:59 UTC by rbreeze

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-08-07 23:24 UTC, rbreeze commented
Features / Improvements:
- Edit settings in the same place you view them
- Access to all k8s ResourceTypes in a dropdown where appropriate, to prevent typos and ease entry
- Indication when fields are set to all (*)
- Quickly open source repo links with a convenient button
- Batch select rows in any section to delete them
- Links to documentation where relevant

2020-08-07 23:24 UTC, rbreeze commented
Demo video: 

https://youtu.be/Sr2EeZ-ZrA4

2020-08-18 17:01 UTC, alexmt requested changes
Great start. I really like the idea to visually group settings and inline editing. The help text and links to the documentation is very useful too. 

The only concern is the consistency with the existing user interface:

- let's not use a separate set of colors and input field styles for the project details page. Instead, re-use the existing palette and if required update existing common colors/styles in a separate PR. 

- Argo CD already has a way to visually group collection of controls using `white-box` and `white-box_details` classes. I suggest to use it and improve if necessary, instead of inventing the new pattern:

![image](https://user-images.githubusercontent.com/426437/90542670-509be180-e139-11ea-8acb-7306d5d15281.png)

Probably the best way is to try to use `EditablePanel` component since it already encapsulates switch between view and edit modes.

2020-08-20 16:03 UTC, sbose78 commented
( fixes #4015 )

2020-08-30 22:22 UTC, RichiCoder1 commented
Pardon if this is WP, and hope feedback is welcome! Had a few things I noticed:

### Header
* It looks like the revert operation doesn't work?
![description bug](https://user-images.githubusercontent.com/2391878/91670490-b1d19680-eae3-11ea-9fe5-3227a6174d0d.gif)
* It'd be nice if that field turned into either an underlined or outlined form field so it more clear it's editable.
* Does the act of editing the field set the description? If not, maybe "cancel" would be more clear than undo?
* Designer nit pick: The buttons don't seem to have hover states.

### All Groups
* I like the notes when the fields have wildcards, but they don't say anything about why I should care? Why `*` is worth calling out?
* The position and state of the checkmark doesn't say "confirm" to me, it looks like a validation artifact saying the input of that field is valid? Somewhat ok since there's a `SAVE` button at the end, but it's still confusing.

### Destinations
* This is called Cluster everywhere else, no?
![image](https://user-images.githubusercontent.com/2391878/91670573-74213d80-eae4-11ea-93bb-7f1e393f25ba.png)

### [Allow|Deny] List
* Ditto on feedback about allowing CRs.

### Orphaned Resources
* This is a personal bias, but magically appearing and disappearing UI can be confusing. It's especially a bit confusing in this case as it results in the contents appearing off screen. I'd say either show this UI and then gray it out, or scroll down when this UI appears so it stays in view.

![off_screen_orphaned](https://user-images.githubusercontent.com/2391878/91670629-e09c3c80-eae4-11ea-95bb-4e949716539f.gif)
* Other nit is that the buttons aren't in a group'd box.
* For the switches, it'd be nice if the `off` state had the `ON` text a more neutral color as otherwise it looks like these switches are actually toggled on.


That mountain of feedback out of the way, this looks like a massive step forward for this screen!

2020-09-01 15:34 UTC, rbreeze commented
@RichiCoder1 Thank you for the feedback! This is still WIP, but your feedback is still helpful. 

With regards to the description field, editing doesn't persist the changes until `SAVE` is clicked. The intended behavior of `REVERT` is to revert the field back to what it was before the user started editing. I believe I pushed a fix for the buggy revert in the latest commit, and maybe when it works as intended it'll be more clear. 

I hadn't thought of the potential confusion with the checkmarks. Maybe a checkbox instead of 'check circles' would make that clearer? 

I think you're right that `SERVER` is called `CLUSTER` everywhere else. 

I also agree with your thoughts about the toggles. I'll explore some different options.

Thanks!

2020-09-01 17:23 UTC, RichiCoder1 commented
> I hadn't thought of the potential confusion with the checkmarks. Maybe a checkbox instead of 'check circles' would make that clearer?

Hmmm. I'm concerned that a checkbox or circle isn't the best way to communicate committed vs uncommitted inputs. 
Maybe something like this instead? 
![image](https://user-images.githubusercontent.com/2391878/91885716-dd709000-ec4d-11ea-9b62-490086ef3f6f.png)

2020-09-01 17:39 UTC, rbreeze commented
the problem with this is it doesn't allow for selecting multiple line items.

2020-09-01 17:41 UTC, RichiCoder1 commented
> the problem with this is it doesn't allow for selecting multiple line items.

Ahh, didn't realize that was a goal. Is the intent for this to be table-like without looking like a table? It's a little confusing in that regard

2020-09-11 17:12 UTC, rbreeze commented on ui/src/app/settings/components/project/card/card.tsx
> +                                        save={value => this.props.save(i, value)}
Addressed by adding a new 'save all' button. Users now have the option to do either a batch save or save one line item at a time:

![save-all-demo](https://user-images.githubusercontent.com/6250584/92953813-39d66b00-f417-11ea-99d8-9ca2ca863673.gif)

2020-09-11 19:13 UTC, rbreeze commented
In progress: removing Project Edit Panel altogether by streamlining project creation

2020-09-21 19:17 UTC, alexmt requested changes
Looks like card.scss, card.tsx almost re-implement form input [styles](https://github.com/argoproj/argo-ui/blob/master/src/styles/elements/form-controls.scss) and partially form state management. 

I've tried to implement inline editing using what we have. Converted only general settings, sources and destinations. I think result looks ok and requires significantly fewer changes: https://github.com/alexmt/argo-cd/commit/eb7e8a42db06b05dc5dcba5b8949fcb8d54fdedc

![image](https://user-images.githubusercontent.com/426437/93810737-f09ace00-fc03-11ea-8bd9-2f655ba1d8ef.png)

I agree what our UI "framework" can be improved. CSS is not pixel perfect, react-form library is abandoned etc. But I think we should work on each improvement separately. E.g. replace react-form with the successor, improve input fields colors etc.

What do you think?

2020-09-21 22:09 UTC, rbreeze commented
@alexmt Thanks for looking at that and making those improvements - I completely agree that the improvements should be done one at a time, and that minimizing style changes in this PR is ideal. You're also right that I pretty much re-implemented the form styles, so your way is more efficient for sure.

Do you think inline editing (without having to click an "edit" button) is an improvement? I'm leaning toward yes. If not though, the last commit to this branch includes a newer version of "card" that has identical behaviour to the existing EditablePanel.

2020-09-21 22:13 UTC, RichiCoder1 commented
> Do you think inline editing (without having to click an "edit" button) is an improvement?

To somewhat butt in again, I'm camp both. Nice to have a quick and explicit way for discovery.

> But I think we should work on each improvement separately. E.g. replace react-form with the successor, improve input fields colors etc.

I do it less these days, but frontend UX is one major area I work in if there's any specific improvements or development I can assist with!

2020-09-21 23:27 UTC, alexmt commented
The "edit" button helps up to load page quicker. Almost every edit page requires a loading list of some additional data to provide autocompletion.  So we can load view mode quicker and load autocompletion data only when the user click "Edit". 

Can you move the project details page to EditablePanel first? 

As a next step, we can work on two separate PRs for styles and for EditablePanel refactoring. This way we can ensure all edge cases are covered and new EditablePanel/Card can fully replace the existing one.

2020-09-30 18:33 UTC, rbreeze commented
![proj-refactor](https://user-images.githubusercontent.com/6250584/94725494-b53d8500-0310-11eb-9a52-909ad5acc1e2.gif)

2022-02-18 17:59 UTC, closed without merging