docs: Debug Remote Development Environment
argoproj/argo-cd pull request #4125
Opened 2020-08-19 10:24 UTC by olegsu

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] ~~I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.~~
* [ ] ~~Optional. My organization is added to USERS.md.~~
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-08-19 12:58 UTC, jannfis requested changes
Thank you, this looks useful. I have found quite a few typos, please see below.

2020-08-19 12:58 UTC, jannfis commented on docs/developer-guide/debugging-remote-environment.md
> +In this artical we will describe how to debug a remote environment with [Telepresence](https://telepresence.io/).
`artical` -> `article`

2020-08-19 12:58 UTC, jannfis commented on docs/developer-guide/debugging-remote-environment.md
> +* Increase feedback loop time
Do you mean decrease instead of increase (regarding the time)?

2020-08-19 12:58 UTC, jannfis commented on docs/developer-guide/debugging-remote-environment.md
> +* Gain more confidance about the delivered code.
`confidance` -> `confidence`

2020-08-19 12:58 UTC, jannfis commented on docs/developer-guide/debugging-remote-environment.md
> +To read more about it refer to official documentation on [telepresence.io](https://telepresence.io/) or [Medium](https://medium.com/containers-101/development-environment-using-telepresence-634bd7210
`refer to` -> `refer to the`

2020-08-19 12:58 UTC, jannfis commented on docs/developer-guide/debugging-remote-environment.md
> +First of all install ArgoCD on you cluster
`you` -> `your`

2020-08-19 12:58 UTC, jannfis commented on docs/developer-guide/debugging-remote-environment.md
> +Connect to one of the services, for example debug the main ArgoCD server run:
`debug` -> `to debug`

2020-08-19 12:58 UTC, jannfis commented on docs/developer-guide/debugging-remote-environment.md
> +* `--expose` forwarf trafic comes to ports 8080 and 8083 to the same ports locally
`forwarf` -> `forward`
`trafic` -> `traffic`

2020-08-19 12:58 UTC, jannfis commented on docs/developer-guide/debugging-remote-environment.md
> +Make sure to run `packr` before starting the debug to generated the assest.
`generated` -> `generate`
`assest` -> `assets`

2020-08-19 12:58 UTC, jannfis commented on docs/developer-guide/debugging-remote-environment.md
> +Update the configuration file ot point to kubeconfig file: `KUBECONFIG=` (required)
`ot` -> `to`

2020-08-19 13:39 UTC, olegsu commented
> Thank you, this looks useful. I have found quite a few typos, please see below.

Thank you @jannfis, fixed them.

2020-08-20 04:43 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=4125) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=4125) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: olegsu<br/>:x: kostis-codefresh<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=4125) it.</sub>

2020-08-24 14:39 UTC, jannfis approved these changes
LGTM, thank you!

2020-08-24 14:39 UTC, merged