fix: Cluster remove should return an error for unknown cluster name ( #3476 )
argoproj/argo-cd pull request #4366
Opened 2020-09-17 13:30 UTC by chetan-rns

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

The argocd cluster remove command should return an error if an unknown cluster name is passed as an argument

Example:
```shell
$ argocd cluster rm unknown

FATA[0000] rpc error: code = NotFound desc = cluster "unknown" not found
```

Fixes: #3476

2020-09-17 21:08 UTC, jessesuen requested changes
I believe all of the delete APIs are intentionally idempotent and deletes of something non-existent are intended to not return error. I don't think we should do this, especially given that it will introduce inconsistency in our API.

2020-09-18 04:24 UTC, chetan-rns commented
Hi @jessesuen, I tried the delete command for app and proj, they return an error for a non-existent object. Is this behaviour only specific to cluster delete?

2020-09-18 21:05 UTC, jessesuen commented
Ok if I'm wrong about idempotency, I agree with the change.

2020-09-21 08:20 UTC, chetan-rns commented on util/db/cluster.go
>  		}
Thanks for the review. It was my mistake. I've removed that check

2020-09-21 08:56 UTC, jannfis approved these changes
LGTM, thank you

2020-09-21 08:57 UTC, jannfis commented
@jessesuen Can you please revoke your RfC so we can merge this PR?

2020-09-21 20:56 UTC, jessesuen approved these changes

2020-09-21 20:56 UTC, merged