Resolves 398 -> errors set status to known, status details set to error message
argoproj/argo-cd pull request #437
Opened 2018-07-19 21:41 UTC by JazminGonzalez-Rivero

Tested by: 

forced  runtime.DefaultUnstructuredConverter.FromUnstructured to return an error

result: health was set to unknown.

2018-07-20 01:29 UTC, jessesuen requested changes

2018-07-20 01:29 UTC, jessesuen commented on controller/appcontroller.go
> +			}
Why do we only set savedErr in the health.IsWorth block?

2018-07-20 01:29 UTC, jessesuen commented on controller/appcontroller.go
> +			poErr = err
I think we only need to keep track the first error, as opposed to poErr and savedErr. Basically if *any* error occurs, we will set it once (and not override it). The first error that occurs (if any), will be the one we return as a result of this function.

2018-07-20 01:32 UTC, jessesuen commented on util/health/health.go
> +		return &health, err
It looks like we are repeating this logic over and over again. It's better to move the setting of the Status and StatusDetails to the caller of all of these functions if it returns an error.

2018-07-20 17:11 UTC, JazminGonzalez-Rivero commented
@jessesuen addressed issues mentioned.

2018-07-21 07:46 UTC, jessesuen approved these changes

2018-07-23 15:58 UTC, alexmt approved these changes

2018-07-23 18:32 UTC, merged