Issue #438 - audit logging interceptor is logging passwords in the clear
argoproj/argo-cd pull request #441
Opened 2018-07-20 20:55 UTC by alexmt

2018-07-21 00:32 UTC, jessesuen approved these changes

2018-07-23 08:16 UTC, jessesuen requested changes
Just saw that repo server is doing this as well:

https://github.com/argoproj/argo-cd/issues/445

2018-07-23 14:59 UTC, alexmt commented
Removed logging from repo-server completely.

2018-07-23 16:10 UTC, merenbach approved these changes

2018-07-24 01:11 UTC, jessesuen approved these changes

2018-07-24 04:07 UTC, merged