refactor(makefile): adding kubernetes client version to LDFLAGS
argoproj/argo-cd pull request #4457
Opened 2020-09-30 05:12 UTC by igaskin

adding version of kubernetes go-client library at compile time

#4385

This is a proposal to the changes discussed in https://github.com/argoproj/argo-cd/issues/4385

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-09-30 06:18 UTC, jannfis requested changes
Hey, thanks a lot for tackling this!

You can retrieve the actual K8s client version conveniently in code from a method `Get()` in `k8s.io/client-go/pkg/version` package (refer to https://github.com/kubernetes/client-go/blob/master/pkg/version/version.go). I think grepping `go.mod` could lead to unwelcome side-effects. 

Plus, I have two more thoughts:

1) I think we need to adapt `server/version/version.go` additionally, because current K8s client version is reported server-side
2) I'm unsure whether we should remove `kubectl` from the resulting image, due to debugging purposes. As I said, I'm unsure and would like to hear opinions on that. On the pro-side would be, that each binary we do not ship reduces the size of our (very bloated) image, in case of static Golang binaries even significantly.

2020-09-30 20:52 UTC, jessesuen commented on Makefile
> +KUBE_CLIENT_VERSION=$(shell cat go.mod | grep kubernetes | awk '{print $$2}')
I think this should grep for `k8s.io/kubectl` and not kubernetes

2020-09-30 21:24 UTC, igaskin commented
> Hey, thanks a lot for tackling this!
> 
> You can retrieve the actual K8s client version conveniently in code from a method `Get()` in `k8s.io/client-go/pkg/version` package (refer to https://github.com/kubernetes/client-go/blob/master/pkg/version/version.go). I think grepping `go.mod` could lead to unwelcome side-effects.
> 
> Plus, I have two more thoughts:
> 
> 1. I think we need to adapt `server/version/version.go` additionally, because current K8s client version is reported server-side
> 2. I'm unsure whether we should remove `kubectl` from the resulting image, due to debugging purposes. As I said, I'm unsure and would like to hear opinions on that. On the pro-side would be, that each binary we do not ship reduces the size of our (very bloated) image, in case of static Golang binaries even significantly.

Thanks for pointing me in the right direction, I'll take a look at that library.

2020-10-01 04:09 UTC, igaskin commented
Hmm, I tried leveraging the `Get` method in that package, and it only returns defaults.  This note about it populating them from `ldflags` makes me think that it isn't meant to to be imported as a library.
https://github.com/kubernetes/client-go/blob/master/pkg/version/version.go#L29-L30

```
Major:""
Minor:""
GitVersion:"v0.0.0-master+$Format:%h$"
GitCommit:"$Format:%H$"
GitTreeState:""
BuildDate:"1970-01-01T00:00:00Z"
GoVersion:"go1.14.4"
Compiler:"gc"
Platform:"linux/amd64"
```

2020-10-01 11:27 UTC, jannfis commented
> Hmm, I tried leveraging the `Get` method in that package, and it only returns defaults. This note about it populating them from `ldflags` makes me think that it isn't meant to to be imported as a runtime library.
> https://github.com/kubernetes/client-go/blob/master/pkg/version/version.go#L29-L30

Damnit :) Sorry for sending you on the wrong route, then. I was assuming they'd provide some more valuable information within the K8s libraries, but I must have skipped the comment section. Thanks for pointing that out.

Anyway, although I think a different mechanism than to read out the K8s version from go.mod (especially from the `require` section, which can be easily overwritten using a `replace` directive) would be better, there is no other solution I can think of right now.

Two nitpicks about the commands you use:

* A simple statement such as `cat go.mod | grep kubernetes | awk ...` is usually considered as "useless-use-of-cat" and "useless-use-of-grep" and could be easily written as `awk '/kubernetes/ { print $2 }' go.mod`. Even without `awk`, could simply be written as `grep kubernetes go.mod` without having to leverage `cat` (admitted, this is nitpicking on a very low level and just something you can book on your shell-efficiency skills account :)
* We should make sure that the command used to get the version identifier will always only yield exactly one result. Using the string `kubernetes` as matching pattern might result in unexpected surprised. Maybe using the pattern `/k8s.io\/kubernetes v/` and using a final `head -1` would be slightly better. This wouldn't take into account any replacement rules defined in the `go.mod` tho.

So, not as simple as it initially seemed, but I'm sure we're going to find a proper solution.

2022-03-07 23:21 UTC, closed without merging