feat(ui): Pod View in UI to improve usability of Large Applications
argoproj/argo-cd pull request #4497
Opened 2020-10-06 23:47 UTC by rbreeze

![pod-view](https://user-images.githubusercontent.com/6250584/95271770-939e3b00-07f3-11eb-9e15-b535811e6c7b.png)

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-10-06 23:47 UTC, rbreeze commented
![Uploading pod-view.gif…]()

2020-10-07 16:01 UTC, rbreeze commented
![Uploading pod-view.gif…]()

2020-10-08 15:22 UTC, rbreeze commented
![pod-view-live](https://user-images.githubusercontent.com/6250584/95479219-5e066880-093f-11eb-836c-5aef2b99c705.gif)

2020-10-15 21:53 UTC, alexec commented
this looks ace

2020-11-03 17:48 UTC, simster7 commented
This looks great!

2020-11-04 21:30 UTC, rbreeze commented
Additional iconography coming to improve usability for color blind users.

<img width="236" alt="Screen Shot 2020-11-04 at 1 28 19 PM" src="https://user-images.githubusercontent.com/6250584/98169725-a57e0700-1ea1-11eb-89de-a64a31839c3e.png">

Simulated view with deuteranopia:
<img width="238" alt="Screen Shot 2020-11-04 at 1 28 13 PM" src="https://user-images.githubusercontent.com/6250584/98169727-a6169d80-1ea1-11eb-8d98-86bafac075fc.png">

2020-11-12 19:09 UTC, rbreeze commented
Updated view with node information and improved iconography: 

<img width="672" alt="Screen Shot 2020-11-12 at 11 08 30 AM" src="https://user-images.githubusercontent.com/6250584/98984697-6837fb80-24d7-11eb-9313-b41eea8ceb28.png">

2020-11-13 21:19 UTC, rbreeze commented
Preview of ability to sort pods by parent resource

<img width="849" alt="Screen Shot 2020-11-13 at 1 19 09 PM" src="https://user-images.githubusercontent.com/6250584/99122246-d1d90800-25b2-11eb-9d6e-1728ccfc55a3.png">

2020-12-01 22:29 UTC, jsoref commented
Could you at least check:
- [ ] Does this PR require documentation updates?

2020-12-06 02:32 UTC, jsoref commented
Fwiw, it's probably better to move the images from the discussion into the description (speaking from experience landing a major feature to jenkins).

2020-12-08 23:00 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=4497) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=4497) before we can accept your contribution.<br/>**16** out of **17** committers have signed the CLA.<br/><br/>:white_check_mark: alexmt<br/>:white_check_mark: rbreeze<br/>:white_check_mark: chetan-rns<br/>:white_check_mark: iam-veeramalla<br/>:white_check_mark: jessesuen<br/>:white_check_mark: mgoodness<br/>:white_check_mark: maxbrunet<br/>:white_check_mark: mjpitz<br/>:white_check_mark: jannfis<br/>:white_check_mark: sbose78<br/>:white_check_mark: djajcevic<br/>:white_check_mark: keithchong<br/>:white_check_mark: hacktron95<br/>:white_check_mark: kennethtxytqw<br/>:white_check_mark: backjo<br/>:white_check_mark: kshamajain99<br/>:x: IliaGe<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=4497) it.</sub>

2020-12-14 19:03 UTC, alexmt requested changes
Awesome work! Added few mostly minor comments. Also please run `yarn lint --fix --project .` in `ui` folder to fix linter errors.

2020-12-14 19:03 UTC, alexmt commented on ui/src/app/applications/components/application-pod-view/pod-view.tsx
> +                                                        <div style={{display: 'flex', alignItems: 'center'}}>
Please let's make sure node containers have the same width:


![image](https://user-images.githubusercontent.com/426437/102123464-b94f4e00-3dfb-11eb-8d98-43ddefdb173b.png)

2020-12-14 19:05 UTC, alexmt requested changes

2020-12-14 19:05 UTC, alexmt commented on ui/src/app/applications/components/application-pod-view/pod-view.scss
> +.nodes-container {
Please make `nodes-container` and `node` sub-classes of `pod-view` . E.g. `pod-view__nodes-container` and `pod-view__node`

2020-12-14 19:18 UTC, alexmt requested changes

2020-12-14 19:18 UTC, alexmt commented on ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx
> +                {(node.info || [])
Pods now have a lot of "info items": 

![image](https://user-images.githubusercontent.com/426437/102125126-08967e00-3dfe-11eb-95af-5cc073a05b7f.png)

I suggest to show top 4 and add tooltip with all info items.

2020-12-18 18:15 UTC, merged