feat: Global Project UI
argoproj/argo-cd pull request #4587
Opened 2020-10-16 00:05 UTC by mayzhang2000

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

fixes: #4416

2020-10-16 00:09 UTC, mayzhang2000 commented
![Uploading image.png…]()

2020-10-16 16:20 UTC, mayzhang2000 commented
![image](https://user-images.githubusercontent.com/7737306/96283261-cc2adb00-0f90-11eb-9fdc-068fb75bd014.png)

2020-10-19 20:55 UTC, alexmt reviewed
added few comments

2020-10-22 21:03 UTC, alexmt requested changes

2020-10-22 21:03 UTC, alexmt commented on ui/src/app/shared/services/projects-service.ts
> +        return requests.get(`/projects/${name}/globalprojects`).then(res => res.body as models.GlobalProjectState);
I think it not worth defining a separate interface for `GlobalProjectState` . Please remove GlobalProjectState and just use:

```
public getGlobalProjects(name: string): Promise<models.Project[]> {
        return requests.get(`/projects/${name}/globalprojects`).then(res => res.body.globalprojects as models.Project[]);
}
```

2020-10-22 21:03 UTC, alexmt commented on ui/src/app/settings/components/project-details/project-details.tsx
> +                                        {gpNamespaceResourceBlacklist.length > 0 ? (
Let's hide this section is it has no rows. And same for other inherited lists from global project.

2020-10-23 19:06 UTC, alexmt approved these changes
LGTM

2020-10-26 17:39 UTC, merged