fix: exclude files listed under exclusions
argoproj/argo-cd pull request #4686
Opened 2020-10-28 00:42 UTC by mayzhang2000

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-10-30 16:45 UTC, alexmt requested changes

2020-10-30 16:45 UTC, alexmt commented on reposerver/repository/repository.go
> +		for _, exclusion := range directory.Exclusions {
It is better to use "glob" expression instead of Regex since we are using it to filter file paths. Please use `Match` from `util/glob` package.

2020-10-30 16:45 UTC, alexmt commented on pkg/apis/application/v1alpha1/types.go
> +	Exclusions []string                 `json:"exclusions,omitempty" protobuf:"bytes,3,opt,name=exclusions"`
Both regex and glob support list of patterns (e.g. glob: `{dir1,dir2}` )  So we don't really need list here. I would change it to `Exclude string`

2020-10-30 16:45 UTC, alexmt commented on cmd/argocd/commands/app.go
> +	command.Flags().StringArrayVar(&opts.exclusions, "exclusions", []string{}, "Set file exclusions")
Flag should be prefixed with `directory-` for consistency

2020-10-31 01:18 UTC, alexmt requested changes

2020-10-31 01:18 UTC, alexmt commented on cmd/argocd/commands/app.go
> +	command.Flags().StringVar(&opts.directoryExclusions, "directory-exclusions", "", "Set file exclusions")
```suggestion
	command.Flags().StringVar(&opts.directoryExclusions, "directory-exclude", "", "Set glob expression used to exclude files from application source path")
```

2020-10-31 01:18 UTC, alexmt commented on pkg/apis/application/v1alpha1/types.go
> +	Exclude string                   `json:"Exclude,omitempty" protobuf:"bytes,3,opt,name=Exclude"`
```suggestion
	Exclude string                   `json:"exclude,omitempty" protobuf:"bytes,3,opt,name=exclude"`
```

2020-10-31 01:18 UTC, alexmt commented on reposerver/repository/repository.go
> +		fileNameWithPath := fmt.Sprintf("%s%s%s", appPath, string(filepath.Separator), f.Name())
Please use `file.Join` instead.

2020-11-02 16:04 UTC, alexmt approved these changes
LGTM!

2020-11-02 16:46 UTC, merged

2020-11-02 22:13 UTC, mayzhang2000 commented
fixes #4432