chore: Add a GitHub action that runs unit tests with -race to CI build (#4774)
argoproj/argo-cd pull request #4775
Opened 2020-11-06 04:56 UTC by jgwest

See [parent issue](https://github.com/argoproj/argo-cd/issues/4774) for the full details of the PR.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

Signed-off-by: Jonathan West <jonwest@redhat.com>

2020-11-06 15:05 UTC, jannfis requested changes
Awesome, I like the idea to leverage race detection in our CI builds. Also, I like the implementation of segregating our technical debt (or existing bugs...) to be excluded, so it gives us time to fix them while preventing new race conditions to sneak in.

If I understood it correctly, we'll be progressively fix the existing race conditions and then move them to the "normal" unit tests without the `!race` pragma. Is that a correct understanding?

One last question: Will we still be able to run race tests explicitly (i.e. using `go test -race -run '...'`) with those build pragmas added to the files?

I have a couple of minor comments, please see inline.

PS: Thanks (again) for the very detailed problem description and writing down your train of thoughts in the related issue, can't stress how much appreciated this is!

2020-11-07 03:10 UTC, jgwest commented on .github/workflows/ci-build.yaml
> +          path: coverage.out
Aha, good catch, I have removed this step.

2020-11-07 03:11 UTC, jgwest commented on .github/workflows/ci-build.yaml
> +          name: test-results
Good thinking, still new to GitHub actions so I had assumed each job had a different upload scope, but obviously not. Fixed to `race-results`.

2020-11-07 03:16 UTC, jgwest commented
> If I understood it correctly, we'll be progressively fix the existing race conditions and then move them to the "normal" unit tests without the !race pragma. Is that a correct understanding?

This is exactly correct... we don't necessarily want to wait for all possible issues to be fixed before we enable it, but we can enable this now to prevent further data races from being introduced to the tests. Once that's done, we can progressively fix the remaining issues (which are clearly visible just by looking for the `_norace_` files and/or the build pragma). And of course, as mentioned in the original issue, I've gone and squashed a bunch of existing races in order to get us to where we can enable this.


> One last question: Will we still be able to run race tests explicitly (i.e. using go test -race -run '...') with those build pragmas added to the files?

Afraid not, or at least I'm not aware of a way to tell `go test` to explicitly override the pragma. If you attempt to individually run one of these with `-race`, as in your example, you will get a `no test files` message from `go test`.

In my local development environment I've just been removing the `// +build !race` tag whenever I need to test an individual test, and I'm sure one could construct a recursive `sed` to temporarily remove them if necessary (which is imperfect, but works).

(@jannfis)

2020-11-07 11:55 UTC, jannfis commented
> > One last question: Will we still be able to run race tests explicitly (i.e. using go test -race -run '...') with those build pragmas added to the files?
> 
> Afraid not, or at least I'm not aware of a way to tell `go test` to explicitly override the pragma. If you attempt to individually run one of these with `-race`, as in your example, you will get a `no test files` message from `go test`.
> 
> In my local development environment I've just been removing the `// +build !race` tag whenever I need to test an individual test, and I'm sure one could construct a recursive `sed` to temporarily remove them if necessary (which is imperfect, but works).

That's fair enough from my pov. It's obvious from the outside that the contained tests are run with `!race` pragma, and for manual re-testing, removing the pragma locally by hand is not much of a hassle. I think we won't need some `sed`-script/command to do that.

We should document the `_norace_` tests in the contribution guide, however (tho not necessarily with this PR). I hope I can finish setting up the contribution documentation repository this weekend and migrate existing documentation. Then updating the docs would not be that much of a hassle as it is right now.

2020-11-07 11:56 UTC, jannfis approved these changes
LGTM

2020-11-07 11:56 UTC, jannfis commented
@alexmt @jessesuen FYI

2020-11-07 11:57 UTC, merged