fix: Include Headers in login clientopts (#4918)
argoproj/argo-cd pull request #4941
Opened 2020-12-01 12:12 UTC by iam-veeramalla

Signed-off-by: Abhishek Veeramalla aveerama@redhat.com

Fixes: #4918 

ArgoCD cli currently does not pass the headers[--header] to server when login command is used. This is because headers is not added to the local clientOpts. Updated the required change.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I've signed the CLA and my build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-12-01 21:55 UTC, jgwest requested changes
Looks great, short and sweet :smile: ! While it wasn't reported in the original issue, it looks like the `relogin` command has the same issue (ignoring the global client opts, and therefore missing the header params, see [here](https://github.com/argoproj/argo-cd/blob/f6a32a9ebc9ac459be0abc59ec84cf7863087876/cmd/argocd/commands/relogin.go#L45)), and the fix is likely the same, it couldn't hurt to fix it there too.

2020-12-02 05:51 UTC, iam-veeramalla commented
> Looks great, short and sweet 😄 ! While it wasn't reported in the original issue, it looks like the `relogin` command has the same issue (ignoring the global client opts, and therefore missing the header params, see [here](https://github.com/argoproj/argo-cd/blob/f6a32a9ebc9ac459be0abc59ec84cf7863087876/cmd/argocd/commands/relogin.go#L45)), and the fix is likely the same, it couldn't hurt to fix it there too.

2020-12-02 11:25 UTC, jgwest approved these changes
LGTM!

2020-12-02 15:22 UTC, iam-veeramalla commented
@jannfis Can you approve the PR to merge?

2020-12-02 16:07 UTC, alexmt approved these changes
LGTM. Thank you!

2020-12-02 16:08 UTC, merged