feat: Make Argo UI aware of OpenShift objects#4601
argoproj/argo-cd pull request #5096
Opened 2020-12-21 12:43 UTC by iam-veeramalla

Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

This PR will make Argo UI aware of OpenShift objects. It provides details such as the route url and services attached to route. This feature is currently available for ingress.

2020-12-21 15:23 UTC, iam-veeramalla commented
@alexmt can you review this ?

2020-12-21 22:06 UTC, jessesuen commented
I think @jgwest and/or @wtam2018 would be good ones to review this

2020-12-21 23:25 UTC, wtam2018 commented
@iam-veeramalla do you mind to create an issue to describe the enhancement?  It would be nice to include some screen shots to  illustrate the enhancement.

2020-12-22 01:39 UTC, iam-veeramalla commented
> @iam-veeramalla do you mind to create an issue to describe the enhancement? It would be nice to include some screen shots to illustrate the enhancement.


Sure @wtam2018

2020-12-22 11:21 UTC, iam-veeramalla commented
> > @iam-veeramalla do you mind to create an issue to describe the enhancement? It would be nice to include some screen shots to illustrate the enhancement.
> 
> Sure @wtam2018

Argo renders the Ingress url for Ingress resource deployed in k8s, This will help users to access their applications(pods) directly from the Argo UI. This feature is not available for openshift routes as Argo does not identify/render/provide any route details. Also, by the nature of openshift, it will convert any ingress resource into routes. So, Argo does not render the url, health details of k8s ingress or openshift routes deployed in openshift. 

This enhancement will allow users to access the openshift route url from Argo UI. This will make user experience better as they don't have to describe route using `oc cli` and frame the route url(typically `host+path`) to access their applications. This feature is already available for ingress and istio virtual service. This feature is added as per the requirement in issue  https://github.com/argoproj/argo-cd/issues/4601

<img width="360" alt="Screenshot 2020-12-22 at 4 29 21 PM" src="https://user-images.githubusercontent.com/43399466/102881456-e0002b00-4472-11eb-8a15-4fc994836389.png">


Another screenshot to explain how this enhancement will provide 
<img width="1330" alt="Screenshot 2020-12-22 at 4 50 05 PM" src="https://user-images.githubusercontent.com/43399466/102883304-d2987000-4475-11eb-9c3e-390860f5d896.png">

Openshift route object identified by Argo does not even provide the health details. I will create an issue for that and add it as a follow up enhancement to this.

Please let me know, If you need more details.

2020-12-22 13:41 UTC, wtam2018 commented
Fixes #4601

2020-12-23 16:57 UTC, iam-veeramalla commented
I think this is good to merge @jessesuen

2020-12-23 19:54 UTC, wtam2018 commented
I'll take a look.

2020-12-24 05:22 UTC, wtam2018 requested changes
#4601 also propose to support  `DeploymentConfig` .     Should we address  it?    We could do it in a different PR.

2020-12-24 05:22 UTC, wtam2018 commented on controller/cache/info.go
> +	}
There is only one `to` backend service per route but there can be a list of `alternateBackends`.  Please see https://docs.openshift.com/container-platform/3.6/architecture/networking/routes.html#alternateBackends

2020-12-24 05:22 UTC, wtam2018 commented on controller/cache/info.go
> +			Kind:      kube.ServiceKind,
Currently, `Kind` can only be `Service` currently but should we not hardcode here?   Perhaps, use `backend["kind"]` instead?

2020-12-24 05:22 UTC, wtam2018 commented on controller/cache/info.go
> +			if hostname := lbIngress["routerCanonicalHostname"]; hostname != nil {
`routerCanonicalHostname` is optional.   Please see https://docs.openshift.com/container-platform/4.6/rest_api/network_apis/route-route-openshift-io-v1.html

2020-12-24 05:22 UTC, wtam2018 commented on controller/cache/info.go
> +	res.NetworkingInfo = &v1alpha1.ResourceNetworkingInfo{TargetRefs: targets, Ingress: route, ExternalURLs: urls}
I think we need to handle the edge cases when we are unable to extract backend services, ingress, and urls.

2021-01-04 12:56 UTC, dlmorais-pbh commented
> #4601 also propose to support `DeploymentConfig` . Should we address it? We could do it in a different PR.

One thing I know that Argo supports for Deployment, but not for DeploymentConfig, is the ability to trigger a rollout by using the "three dots menu" on Deployment object.

And there is also the icon at object's box.

2021-08-10 23:00 UTC, mbecca commented
any update for this PR?

2021-10-06 06:26 UTC, iam-veeramalla commented
> any update for this PR?

I started to work back on this. I will probably get a PR for this by end of the week :)

2022-03-01 11:21 UTC, pasha-codefresh commented
@iam-veeramalla could you please update on this? Do you need some help?

2023-05-29 20:35 UTC, crenshaw-dev commented
Closing for now, @iam-veeramalla feel free to reopen when ready. :-)

2023-05-29 20:35 UTC, closed without merging