fix: Remove kubectl binary from argo image(#5005)
argoproj/argo-cd pull request #5101
Opened 2020-12-21 16:01 UTC by iam-veeramalla

Signed-off-by: iam-veeramalla <abhishek.veeramalla@gmail.com>

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2020-12-21 17:24 UTC, iam-veeramalla commented
@jannfis @jessesuen This is as part of our discussion at #5005

2020-12-21 22:10 UTC, alexmt requested changes
Please also remove `hack/installers/install-kubectl-linux.sh`

2020-12-21 22:11 UTC, jessesuen requested changes, later dismissed
This change is incomplete, because the last place where we still use kubectl is at the version endpoint:

See: https://github.com/argoproj/argo-cd/blob/master/server/version/version.go#L32-L51

Can you also update version.go to somehow report the version that we import in go modules?

2020-12-22 05:43 UTC, iam-veeramalla commented
> This change is incomplete, because the last place where we still use kubectl is at the version endpoint:
> 
> See: https://github.com/argoproj/argo-cd/blob/master/server/version/version.go#L32-L51
> 
> Can you also update version.go to somehow report the version that we import in go modules?

If we decide to remove kubectl from the image, why should we import or print the version ?

2020-12-22 18:36 UTC, alexmt commented
> If we decide to remove kubectl from the image, why should we import or print the version ? @jessesuen

Was trying to find a related discussion but looks like it is gone in slack history. Argo CD still uses kubectl as a library. So user still need to know which version it is e.g. to determine if the target k8s cluster compatible or not.

2020-12-22 22:06 UTC, jessesuen commented
We still care about the version of library because it's intended to be equivalent in behavior to the corresponding kubectl binary (including its bugs and fixes)

2021-01-12 07:40 UTC, jannfis commented
Since we use a version pin on the Kubernetes libraries in `go.mod` (in the `replace`) section, I think the version could be figured out as follows (Kubernetes libraries use a weird versioning scheme, but effectively v0.20.1 is v1.20.1, v0.18.6 is v1.18.6 etc):

```bash
awk '/k8s.io\/client-go => k8s.io\/client-go/ { print $4 }' go.mod | sed -e 's/v0\.\(.*\)/v1\.\1/'
```

I.e. on current master code this will yield:

```
$ awk '/k8s.io\/client-go => k8s.io\/client-go/ { print $4 }' go.mod | sed -e 's/v0\.\(.*\)/v1\.\1/'
v1.20.1
```

We can pass this in `Makefile` via linker flags to the build process of the binaries, like we already do with the Argo CD version and Git commit SHA, as seen here:

https://github.com/argoproj/argo-cd/blob/64e1c3825a421892c7297777e960af48f8139c50/Makefile#L118

Then use this version identifier in the version endpoint, and get rid of `kubectl` for good. 

Btw, there is a version discrepancy in client libs used and kubectl installed in the image currently, so the version information is quite misleading currently.

2021-01-19 16:12 UTC, iam-veeramalla commented
> Please also remove `hack/installers/install-kubectl-linux.sh`

Please review @alexmt

2021-01-19 16:13 UTC, iam-veeramalla commented
> Since we use a version pin on the Kubernetes libraries in `go.mod` (in the `replace`) section, I think the version could be figured out as follows (Kubernetes libraries use a weird versioning scheme, but effectively v0.20.1 is v1.20.1, v0.18.6 is v1.18.6 etc):
> 
> ```shell
> awk '/k8s.io\/client-go => k8s.io\/client-go/ { print $4 }' go.mod | sed -e 's/v0\.\(.*\)/v1\.\1/'
> ```
> 
> I.e. on current master code this will yield:
> 
> ```
> $ awk '/k8s.io\/client-go => k8s.io\/client-go/ { print $4 }' go.mod | sed -e 's/v0\.\(.*\)/v1\.\1/'
> v1.20.1
> ```
> 
> We can pass this in `Makefile` via linker flags to the build process of the binaries, like we already do with the Argo CD version and Git commit SHA, as seen here:
> 
> https://github.com/argoproj/argo-cd/blob/64e1c3825a421892c7297777e960af48f8139c50/Makefile#L118
> 
> Then use this version identifier in the version endpoint, and get rid of `kubectl` for good.
> 
> Btw, there is a version discrepancy in client libs used and kubectl installed in the image currently, so the version information is quite misleading currently.

Please review @jannfis

2021-01-20 09:49 UTC, jannfis commented on Makefile
> +KUBECTL_VERSION=$(shell awk '/k8s.io\/client-go => k8s.io\/client-go/ { print $4 }' go.mod | sed -e 's/v0\.\(.*\)/v1\.\1/')
Due to GNU make's own variable expansion, `print $4` should be `print $$4` here so that the identifier will be processed correctly by `awk`

2021-01-20 15:48 UTC, iam-veeramalla commented
> Please also remove `hack/installers/install-kubectl-linux.sh`

Please review

2021-01-20 15:52 UTC, iam-veeramalla commented
> This change is incomplete, because the last place where we still use kubectl is at the version endpoint:
> 
> See: https://github.com/argoproj/argo-cd/blob/master/server/version/version.go#L32-L51
> 
> Can you also update version.go to somehow report the version that we import in go modules?

Please check

2021-01-21 07:47 UTC, jannfis approved these changes
LGTM!

2021-01-21 17:31 UTC, alexmt approved these changes
LGTM. Awesome! Minus 42 MB from the image.

2021-01-21 17:49 UTC, merged