fix(ui): Overlapping buttons at narrow screen widths
argoproj/argo-cd pull request #5259
Opened 2021-01-16 00:29 UTC by rbreeze

Also addresses other various visual artifacts at narrow browser window widths: 
![Jan-15-2021 16-22-40](https://user-images.githubusercontent.com/6250584/104791205-be7f2000-574e-11eb-8bc5-4693f675fb1d.gif)

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)).

2021-01-16 23:04 UTC, jsoref commented
If you could avoid the scrolling in favor of the compacting (for the top buttons) or wrapping (for the lower three boxes), that'd be better.

But this is still a huge improvement.

2021-01-19 17:03 UTC, rbreeze commented
Fixed to compact buttons rather than have scrolling. I left the lower 3 boxes with a scroll because to wrap them would mean pushing all the information below that status bar off the screen, which I don't like.

2021-01-19 17:13 UTC, jsoref commented
Eventually one should imagine viewing this on a phone. On phones those three boxes should end up stacked vertically, and the content below them pushed down further (side scrolling is really bad on mobile). But, for now, this is an incremental improvement.

One thing you could do to address the offscreen problem is:

<details>
<summary> 🔵  Progressing</summary>
> The lines that you
> would normally see
> in progressing
</details>

<details>
<summary> ✅  Synced </summary>
> The lines that you
> would normally see
> in synced
</details>

<details>
<summary> ❌   Sync Error </summary>
> The lines that you
> would normally see
> in Sync Error
</details>

---

_Content Area_

2021-01-23 00:37 UTC, alexmt requested changes
Tested locally and noticed strange horizontal bar between button rows:


![image](https://user-images.githubusercontent.com/426437/105562671-03b3cc80-5cd0-11eb-828f-0d8e2ad15475.png)

I think because of that row `Group By` label is semi-hidden. Can you please fix it?

2021-01-25 20:32 UTC, rbreeze commented
What browser are you using? I can't seem to reproduce on Chrome, Firefox or Safari

2021-01-29 01:09 UTC, alexmt commented
I use chrome, tried again. Here is video.

https://user-images.githubusercontent.com/426437/106218111-8aaeec00-618b-11eb-8dd6-4a1c7af3ffc7.mov

hopefully it can help reproducing it

2021-01-29 01:53 UTC, jsoref commented
That horizontal bar looks like a scrollbar gutter.

2021-01-29 01:55 UTC, jsoref commented
@alexmt: can you try incognito? (morbidly curious)

@rbreeze: maybe change the `overflow-x` to something other than `scroll`?

2021-01-29 19:11 UTC, rbreeze commented
hmm, I just tried in Chrome again and still can't see it: 

https://user-images.githubusercontent.com/6250584/106317123-ab765080-6222-11eb-931f-30d6430def9d.mov

Could you try maybe clearing the cache to see if there's potential old CSS causing it?

2021-01-29 19:15 UTC, rbreeze commented
Ah, I think I found the problem. Do you have this setting set on your Mac? 

<img width="464" alt="Screen Shot 2021-01-29 at 11 14 50 AM" src="https://user-images.githubusercontent.com/6250584/106317470-36574b00-6223-11eb-8d32-d63fd77a54c8.png">

Turning this on reproduced it for me. I'll find a fix

2021-01-29 19:43 UTC, jsoref commented
Yeah, that's what I was expecting https://github.com/argoproj/argo-cd/pull/5259#issuecomment-769520123 👍

2021-02-01 17:07 UTC, alexmt requested changes
Looks awesome! one last nitpick

2021-02-01 17:07 UTC, alexmt commented on ui/src/app/applications/components/application-status-panel/application-status-panel.scss
> +    & .info-popup-title {
CSS styles started from this line were deleted in this commit: https://github.com/argoproj/argo-cd/commit/7165b45aeaa15044cec514e7de3d300d448b2df9#diff-4b88f846774c449afe371a91f0a5184f764cc1cc98a947003281c74407dc4074L82

Please delete obsolte styles

2021-02-02 17:52 UTC, alexmt approved these changes
LGTM

2021-02-02 17:53 UTC, merged