feat: selective sync (#3877)
argoproj/argo-cd pull request #5347
Opened 2021-01-28 20:11 UTC by kshamajain99

Signed-off-by: kshamajain99 <kshamajain99@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] My build is green ([troubleshooting builds](https://argoproj.github.io/argo-cd/developer-guide/ci/)). 

issue: https://github.com/argoproj/argo-cd/issues/3877

This feature applies only out-of-sync resources when `ApplyOutOfSync=true` option is provided by user. 

#### Test performed:

Scenario: For an application with 10 deployments and 1 svc, deleting svc and syncing entire application (performing same action)

With `ApplyOutOfSync=true` enabled
```
INFO[0040] sync/terminate complete              application=guestbook duration=507.61639ms syncId=00001-NPWVT
```

Without `ApplyOutOfSync=true` enabled
```
INFO[0114] sync/terminate complete              application=guestbook duration=1.983608856s syncId=00002-orWNj
```

2021-01-28 21:42 UTC, mayzhang2000 reviewed
go.mod needs to be updated once the change in gitops-engine is merged.

2021-01-28 21:57 UTC, mayzhang2000 commented on controller/sync.go
> +				return false
If there is err, should we return true?

2021-01-28 22:00 UTC, kshamajain99 commented on controller/sync.go
> +				return false
yes

2021-01-28 23:27 UTC, alexmt requested changes

2021-01-28 23:27 UTC, alexmt commented on controller/sync.go
> +			diffResult, err := diff.Diff(target, live,
Please see suggestion in https://github.com/argoproj/gitops-engine/pull/213#pullrequestreview-578825696


The `diffResults` is available in `CompareAppState` method and can be returned in an additional field of `comparisonResult` struct:
https://github.com/argoproj/argo-cd/blob/3967baf0c95fa2678f499f23a773e19249265d99/controller/state.go#L82

2021-01-29 18:20 UTC, alexmt approved these changes
LGTM. Merging after gitops engine reference is updated to https://github.com/argoproj/gitops-engine/pull/213

2021-01-29 20:26 UTC, merged