fix: update kustomize to 4.0.5
argoproj/argo-cd pull request #5851
Opened 2021-03-24 05:24 UTC by sbose78

Note, v4.0.5 is also the candidate for kubectl integration

---

Signed-off-by: Shoubhik Bose <shbose@redhat.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2021-03-24 16:54 UTC, sbose78 commented
yet to test..

2021-03-25 23:58 UTC, r0bj commented
Just FYI, kustomize 4.x has unresolved bug https://github.com/kubernetes-sigs/kustomize/issues/3446 - using integer key generates error.

2021-03-30 00:10 UTC, sbose78 commented
Thank you!

2021-04-01 22:20 UTC, cguertin14 requested changes

2021-04-01 22:20 UTC, cguertin14 commented on hack/tool-versions.sh
> +kustomize3_version=4.0.5
Probably will need to add a `kustomize4_version` here instead.

2021-04-26 16:07 UTC, alexmt commented
Closing in favor of https://github.com/argoproj/argo-cd/pull/6059

2021-04-26 16:07 UTC, closed without merging