feat: Ask for confirmation when adding a cluster
argoproj/argo-cd pull request #6172
Opened 2021-05-05 22:08 UTC by dominikbraun

Closes #6159.

2021-05-06 11:03 UTC, jannfis requested changes
Hi @dominikbraun, thanks a lot for your contribution!

I have a small request for change, please see below.

2021-05-06 11:18 UTC, dominikbraun commented on cmd/argocd/commands/cluster.go
> +			isTTY := fileInfo.Mode()&os.ModeCharDevice != 0
Thanks! I didn't know this existing function.

2021-05-10 08:28 UTC, jannfis reviewed
Can you please fix the linter issue as described below?

Also, our CLI docs are auto-generated. Please run `make clidocsgen` and commit the changes, so that the `codegen` CI check will succeed.

Thanks!

2021-05-10 08:28 UTC, jannfis commented on cmd/argocd/commands/cluster.go
> +	"github.com/mattn/go-isatty"
The linter is complaining about the location of this import. The imports are divided in three distinct blocks, each of which must be alphabetically sorted:

1. Golang standard libary
2. Own package imports
3. External package imports

Can you please move the import line to its own block to quiet the linter?

2021-05-10 09:46 UTC, dominikbraun commented
Thanks, I generated the CLI docs.

2021-05-10 11:32 UTC, jannfis approved these changes
LGTM. thank you @dominikbraun !

2021-05-10 11:33 UTC, merged