feat(ui): Add option to sort applications list by name and deploy time
argoproj/argo-cd pull request #6217
Opened 2021-05-12 01:29 UTC by rbreeze

Signed-off-by: Remington Breeze <remington@breeze.software>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2021-07-13 17:44 UTC, alexmt requested changes
Thank you! Notificed couple things that can be improved: 
* icons/checkboxes and corresponding text are not on the same line
* checkboxes should be radio buttons instead since user cannot sort but both at the same time

![image](https://user-images.githubusercontent.com/426437/125499840-2419523c-c7a4-47dc-ac60-2f3ce44e3bf6.png)

What do you think about moving sort options to `Sort by` dropdown next to `Items per page` dropdown?

2021-07-13 22:01 UTC, rbreeze commented
I think next to items-per-page is a good location for Sort By options. However, right now the items-per-page dropdown is part of a shared component, so it would require refactoring that component to put a dropdown there. 

I changed the options to radio buttons, and they now change appearance based on screen size. What do you think?

<img width="398" alt="Screen Shot 2021-07-13 at 2 58 01 PM" src="https://user-images.githubusercontent.com/6250584/125530866-3623963d-882a-4380-b1d1-5b8c6a1776a5.png">
<img width="1167" alt="Screen Shot 2021-07-13 at 3 00 36 PM" src="https://user-images.githubusercontent.com/6250584/125530964-814c4ddf-7116-48cb-b96a-eaa7cf8a7cb3.png">

2022-02-20 14:30 UTC, pasha-codefresh commented
I am not sure that it is usable in terms of UI, maybe better put it on top of filters as you did before just in some better way? 

<img width="898" alt="Снимок экрана 2022-02-20 в 16 29 45" src="https://user-images.githubusercontent.com/39732895/154847656-db026665-9e39-4e22-80af-408ee1baa2fb.png">

In same style as we have for filters

WHYT @rbreeze

2022-04-06 03:28 UTC, dhirschfeld commented
I think this would be a great improvement to the UI (even if not perfect yet).

Is there anything remaining to be addressed before this can be merged?

2022-12-09 16:13 UTC, alexef commented
@rbreeze I'm also interested in this, can I help rebase/bring it back to life?

2022-12-09 16:17 UTC, alexef commented on ui/src/app/applications/components/applications-list/applications-list.tsx
> +    'Deployment Time': ((a, b) => (a.status.observedAt < b.status.observedAt ? 1 : -1)) as AppSorter
Looks like the `ApplicationStatus.ObservedAt` field has been deprecated, probably `ApplicationStatus.OperationState.FinishedAt` would be a better replacement?

2023-05-29 20:37 UTC, crenshaw-dev commented
@alexef was this superseded by https://github.com/argoproj/argo-cd/pull/11645?

2023-05-30 08:18 UTC, alexef commented
@crenshaw-dev yes, and there was a follow up also charging the default order.

I believe this PR can be closed.

2023-05-30 08:18 UTC, closed without merging