Make Argo CD naming consistent
argoproj/argo-cd pull request #694
Opened 2018-10-17 18:42 UTC by tedmiston

This small PR changes instances of `ArgoCD` to `Argo CD` throughout the repo, and also fixes a few small typos.

Note: There are a few *.pb.go that are generated and I believe should not have been edited, however I'm not sure where I should edit upstream from the generation process.  Can you make a suggestion on that?

---

On the official Argo CD product page, docs, and throughout most of this repo, the name is spelled "Argo CD".

- https://argoproj.github.io/argo-cd
- https://blog.argoproj.io/introducing-argo-cd-declarative-continuous-delivery-for-kubernetes-da2a73a780cd

2018-10-17 18:42 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/argoproj/argo-cd?pullRequest=694) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/argoproj/argo-cd?pullRequest=694) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/argoproj/argo-cd?pullRequest=694) it.</sub>

2018-10-18 13:36 UTC, tedmiston commented
I've signed the CLA above, so I believe this PR is now ready for review.

2018-10-19 04:18 UTC, alexmt requested changes
Thank you for making this cleanup, @tedmiston !  The *.pb.go files are generated using `make codegen`  command (upstream files are *.pb and https://github.com/argoproj/argo-cd/blob/master/pkg/apis/application/v1alpha1/types.go) but it is fine to make changes manually. 

You've missed the only one autogenerated file: https://github.com/argoproj/argo-cd/blob/master/server/settings/settings.pb.go#L9

2018-10-19 04:18 UTC, alexmt commented on server/settings/settings.proto
> +// Settings Service API retrives Argo CD settings
Please apply the same change in https://github.com/argoproj/argo-cd/blob/master/server/settings/settings.pb.go#L9

2018-10-20 17:30 UTC, tedmiston commented
@alexmt Thank you for reviewing.  I resolved the typo and also freshly rebased off of upstream master.  Please let me know if any other revisions should be made.

2018-10-21 12:03 UTC, tedmiston commented
The single word for SEO makes sense.

FWIW, it was me browsing your product site first and seeing `Argo CD` and not `ArgoCD` everywhere, then seeing mixed usage in the codebase that motivated this PR.

[I'd also be happy to take this PR in the other direction if `ArgoCD` is the current preference.]

Sample Google query results:

- `"argo cd" site:argoproj.io` ~= 15
- `"argocd" site:argoproj.io` = 0
- `"argo cd" site:github.*` ~= 1100
- `"argocd" site:github.*` ~= 773

2018-11-01 23:09 UTC, tedmiston commented
Just wanted to touch base on this PR for canonicalizing the naming to see if any action is required on my end.

2018-11-02 19:39 UTC, jessesuen commented
> Just wanted to touch base on this PR for canonicalizing the naming to see if any action is required on my end.

I've been overruled. Argo CD will be the correct usage going forward and not ArgoCD. Once the conflicts are resolved, it should be good to go.

2018-11-02 19:40 UTC, alexmt approved these changes

2018-11-05 18:46 UTC, tedmiston commented
Thanks for checking @jessesuen and approving @alexmt.

I've rebased off master and resolved the conflicts.  I believe this PR is good to go.

2018-11-05 19:29 UTC, merged