Scoped clusters
argoproj/argo-cd pull request #7039
Opened 2021-08-20 15:02 UTC by pasha-codefresh

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2021-08-24 18:20 UTC, alexmt requested changes

2021-08-24 18:20 UTC, alexmt commented on util/argo/argo.go
> +		project.Spec.Destinations = append(project.Spec.Destinations, argoappv1.ApplicationDestination{Server: cluster.Server, Namespace: "*"})
Cluster might be connected in a "namespaced" mode - `cluster.Namespaces` is not empty.  In this case only these namespaces should be auto-added to the destination. E.g.

```golang
if len(cluster.Namespaces) == 0 {
  project.Spec.Destinations = append(project.Spec.Destinations, argoappv1.ApplicationDestination{Server: cluster.Server, Namespace: "*"})
} else {
  for _, ns := range cluster.Namespaces { 
    project.Spec.Destinations = append(project.Spec.Destinations, argoappv1.ApplicationDestination{Server: cluster.Server, Namespace: ns})
  }
}
```

2021-08-24 18:20 UTC, alexmt reviewed
Thank you @pasha-codefresh ! Found only one minor issue and it is ready to go

2021-08-24 18:34 UTC, alexmt approved these changes
LGTM

2021-08-25 16:53 UTC, merged

2021-08-31 17:45 UTC, sbose78 commented
Sorry, is there a PR description or an issue I could read up ? :(

2021-09-02 15:58 UTC, alexmt commented
hello @sbose78 . Sure, here it is: https://github.com/argoproj/argo-cd/issues/5283. We also discussed implementation in the proposal: https://github.com/argoproj/argo-cd/blob/master/docs/proposals/project-repos-and-clusters.md