WIP: long banner messages get cut off
argoproj/argo-cd pull request #7264
Opened 2021-09-20 19:47 UTC by reginapizza

Linked to issue #7056 

**Looking for just a tiny bit of help on finishing this issue**! It's driving me crazy but I cannot center this no matter what I try, I'm not sure if there is an alternate way I can do this instead, or if there can be character limits to banner messages at all that would avoid this problem altogether. I've tried centering the text for shorter messages every way that I could find, but it either gets cut off at the top of longer messages if `height: 100%` is taken off of `.ui-banner-text`, or it will do as it's doing in the video and not be centered with the dismiss buttons. I'm really not sure what's happening here, would love a second opinion on it. Thanks in advance!

https://user-images.githubusercontent.com/50851526/134064661-54452bd6-9b2f-4021-ab60-75848b7a750d.mp4

cc: @rbreeze 

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2021-09-23 15:45 UTC, keithchong commented
Hey @reginapizza, one suggestion is to increase the margins around the buttons.  They are touching the banner border when the text is long and needs to wrap.

2021-09-24 02:53 UTC, reginapizza commented
@keithchong good point- what do you think about this? I've just slightly decreased the line height on it 
![banner-smaller-line-height1](https://user-images.githubusercontent.com/50851526/134610912-a3720601-cec5-4518-a4ff-a433f897ae9e.png)


![banner-smaller-line-height2](https://user-images.githubusercontent.com/50851526/134610901-f1ad7a7f-bc7d-4919-8386-bfde30c0ed17.png)

2021-09-24 13:48 UTC, keithchong commented
Hey @reginapizza, looks better.  @rbreeze, your thoughts? Please review and approve/merge?

2021-09-27 19:45 UTC, rbreeze requested changes
Other than the tiny comment below, looks good!

2021-09-27 19:45 UTC, rbreeze commented on ui/src/app/ui-banner/ui-banner.scss
> +    line-height: 1.1
Super super minor, semi-colon here? 😅

2021-09-27 20:31 UTC, rbreeze approved these changes

2021-09-27 20:31 UTC, merged