feat: cache argo cd rbac
argoproj/argo-cd pull request #7587
Opened 2021-11-01 12:10 UTC by pasha-codefresh

Continuation on https://github.com/argoproj/argo-cd/pull/6739/files

2021-11-01 20:28 UTC, yeya24 commented
IIUC, the `AddFunction` call needs to invalidate the cache as well?

2021-11-02 02:48 UTC, yeya24 commented
We also implemented the rbac cache based on #6739 and have been using it on prod for several weeks. The issue of the casbin cached enforcer is that it doesn't free memory and will hold cached items forever.

2021-11-02 09:54 UTC, pasha-codefresh commented
Thank you for comment @yeya24

2021-11-02 21:01 UTC, alexmt requested changes

2021-11-02 21:01 UTC, alexmt commented on util/rbac/rbac.go
>  		enf, err = newEnforcerSafe(newBuiltInModel(), newAdapter(e.adapter.builtinPolicy, e.adapter.userDefinedPolicy, policy))
If the project has roles with policies then the cache is not used. We should support this use case as well and use cached enforces with project with policies.

2021-11-03 18:27 UTC, alexmt approved these changes
LGTM

2021-11-03 18:28 UTC, alexmt commented
Thanks a lot to @farodin91 for working on initial implementation in  https://github.com/argoproj/argo-cd/pull/6739!

2021-11-03 18:28 UTC, merged