feat: Show resource usage per pod (#6989)
argoproj/argo-cd pull request #7746
Opened 2021-11-18 20:56 UTC by keithchong

Signed-off-by: Keith Chong <kykchong@redhat.com>

This potentially could be the first part of the solution for https://github.com/argoproj/argo-cd/issues/6989
We need specific resource request information per pod.

- Note that I've included some of the logic from the existing front end to the controller, thinking that perhaps this logic should better reside there instead, and the UI should simply display the info.
- Note getMetric. I investigated that this is one way to get the pod metrics.
- Please suggest where to place the structs
- The idea is that if the metrics server is not available, then the UI will simply usage as N/A or Metrics not available. (Eg. it should not be a catastrophic failure)
- See issue for screen shots

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:
* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2021-11-20 00:37 UTC, keithchong commented on controller/appcontroller.go
> +	data, err := clientset.RESTClient().Get().AbsPath("apis/metrics.k8s.io/v1beta1/namespaces/" + podNamespace + "/pods/" + podName).DoRaw(context.Background())
Alex: This function is used by getResourceTree method. The getResourceTree get's called every reconciliation and for performance, resources cannot make API called - it access only in-memory cached data. Can we use informer to store metrics?

Hi @alexmt, could you please elaborate on that question? Do we for example store the metrics whenever the informer is updated? It looks like that tree needs to be updated regardless to 'hold' the metric info so the UI can retrieve it. What do you think about populatePodInfo in info and have PodInfo store the metrics?

2024-05-22 14:45 UTC, todaywasawesome requested changes
@keithchong I think this feature is still relevant if you want to fix the merge conflicts we can take another crack at it.

2024-08-20 15:23 UTC, nitishfy commented
Hi @keithchong are you willing to work on this issue?

2025-02-28 10:14 UTC, closed without merging

2025-02-28 13:43 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.