feat: Ability define default Refresh mode on application level
argoproj/argo-cd pull request #7783
Opened 2021-11-26 10:55 UTC by pasha-codefresh

Closes #7774

2021-12-01 17:45 UTC, alexmt requested changes
I think automatic hard refresh is useful in some cases but it is not safe to let end-user enable it.  

Argo CD performance depends on manifest caching a lot. Disabling caching for one application might affect other Argo CD tenants. Can we discuss this PR in contributors meeting please?

2021-12-02 07:12 UTC, itshaungmu commented
1. This function is not enabled by default and does not affect the original cache. It feels very troublesome to trigger the hard refresh every time when deploying the application using helm. Turning on this function can facilitate automatic mandatory update detection of the helm application deployed in the development phase.
2. If you are worried that it may affect other tenants, can you only allow the admin to configure this parameter?

2021-12-02 09:31 UTC, pasha-codefresh commented
@itshaungmu We have meeting today and I think we will conclude a solution. The problem that if you enable hard refresh even for the single application you can affect the whole cluster. I tend to agree with @alexmt comment. I will keep you updated

2021-12-02 15:43 UTC, leoluz commented on pkg/apis/application/v1alpha1/application_annotations.go
> +	AnnotationKeyRefreshType string = "argocd.argoproj.io/refresh-type"
Please add missing docs

2021-12-02 21:22 UTC, jessesuen commented
I put my concern as well in this comment https://github.com/argoproj/argo-cd/issues/7774#issuecomment-985010716. This has come up before and we don't want to perform hard refreshes ever reconciliation.

2022-02-01 19:10 UTC, closed without merging