fix: Nested Refresh dropdown does not work on Application Details page #1524
argoproj/argo-cd pull request #7950
Opened 2021-12-16 05:03 UTC by ciiay

Closes #1524
Signed-off-by: ciiay yicai@redhat.com

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2021-12-16 15:58 UTC, rbreeze approved these changes

2021-12-16 16:00 UTC, rbreeze requested changes
Is it possible to update argo-ui only without introducing all the other changes?

2021-12-17 14:04 UTC, ciiay commented
Thanks for the approval and the comment @rbreeze . I will update this PR to make it only this issue focused and request review again.

2021-12-17 18:13 UTC, rbreeze approved these changes
LGTM

2021-12-22 13:10 UTC, merged