#7960 Add JSON logs parsing into pod-logs-viewer on click
argoproj/argo-cd pull request #7962
Opened 2021-12-16 15:26 UTC by Sujimoshi

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Fixes [ISSUE #7960]

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community. Feature request: https://github.com/argoproj/argo-cd/issues/7960
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-03-19 14:08 UTC, pasha-codefresh commented
It would be nice if you can improve this feature and add support also when "Wrap lines" feature is enabled

![Uploading Снимок экрана 2022-03-19 в 16.08.11.png…]()

2022-03-19 14:09 UTC, pasha-codefresh requested changes

2022-03-19 14:09 UTC, pasha-codefresh commented on ui/src/app/applications/components/pod-logs-viewer/pod-logs-viewer.tsx
> +        return JSON.stringify(JSON.parse(line), null, 2)
Please change code according linter 

<img width="775" alt="Снимок экрана 2022-03-19 в 16 09 26" src="https://user-images.githubusercontent.com/39732895/159124415-de64fdbe-457a-4d1b-90a3-95dbe38eaec2.png">

2022-04-23 19:30 UTC, Sujimoshi commented on ui/src/app/applications/components/pod-logs-viewer/pod-logs-viewer.tsx
> +        return JSON.stringify(JSON.parse(line), null, 2)
Linter fixed

2022-04-23 19:46 UTC, Sujimoshi commented
> It would be nice if you can improve this feature and add support also when "Wrap lines" feature is enabled
> 
> <img alt="Снимок экрана 2022-03-19 в 16 08 11" width="1327" src="https://user-images.githubusercontent.com/39732895/159124438-0c828cdc-94e5-49e8-bd7b-de24854018dd.png">

It should correctly work with `whiteSpace: wrap` wich used for wrap lines

2023-08-15 13:35 UTC, ebuildy commented
hey what happen to this PR ?

Also will be great to have pretty colorized JSON

2024-04-29 07:22 UTC, presidenten commented
@pasha-codefresh 
Please continue the review so we can get the json logs parsing

2024-05-08 14:20 UTC, pasha-codefresh approved these changes
LGTM, thank you!

2024-05-08 14:20 UTC, todaywasawesome approved these changes
LGTM

2024-05-08 14:21 UTC, pasha-codefresh commented
@Sujimoshi , i am sorry for delays in review, could you please resolve conflicts ?

2024-06-24 14:58 UTC, kencochrane commented
@Sujimoshi thank you for working on this, if you can help resolve the conflicts we can get it merged. If you no longer have interest in working on this, let us know and we can see if we can find someone else to take it over for you. Thanks again!

2024-08-20 15:27 UTC, nitishfy commented
@Sujimoshi do you have the bandwidth to resolve the conflicts? 

Once the conflicts are resolved, we can merge this PR. If you don't have the bandwidth, please let us know so that someone else can take up this taks. Thanks!

2024-09-04 07:21 UTC, pasha-codefresh commented
I am closing it for now, because even fix conflicts is pretty hard right now, due to a lot of changes in pod-logs-viewer.ts 

@Sujimoshi please let me know if you want to continue to work on this fix. Thanks in advance

2024-09-04 07:21 UTC, closed without merging