feat: bundle applicationset-controller with argocd
argoproj/argo-cd pull request #8148
Opened 2022-01-11 21:36 UTC by ishitasequeira

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [x] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Fixes #7351 

Signed off by [Ishita Sequeira](@ishitasequeira)

2022-01-15 09:39 UTC, jannfis commented
I have some concerns regarding the _huge_ ApplicationSet CRD (>800kb). 

This will make self-managing Argo CD - which is a quite common pattern - quite painful. `kubectl` struggles to apply a new version of the CRD into the cluster. For example:

```shell
# Initial loading of CRD into the cluster
$ time kubectl apply -f argoproj.io_applicationsets.yaml 
customresourcedefinition.apiextensions.k8s.io/applicationsets.argoproj.io created

real    0m0.579s
user    0m0.363s
sys     0m0.069s

# Adding an annotation to the CRD in the source file
$ vi argoproj.io_applicationsets.yaml

# Apply modified file - aborting after a couple of minutes...
$ time kubectl apply -f argoproj.io_applicationsets.yaml
^C
real    11m46.482s
user    11m31.281s
sys     0m3.023s
```

So, it's obvious that things will break on Day 2.

We should either patch the CRD to have Argo CD use `replace` instead of `apply` with the appropriate sync option, or make that change directly in the source CRD.

2022-01-19 05:01 UTC, chetan-rns commented on docs/operator-manual/architecture.md
> +### ApplicationSet Controller
Please add more information about the ApplicationSet Controller in the architecture section

2022-01-19 11:07 UTC, jgwest requested changes
LGTM, _but_ we probably want to wait until we have an ApplicationSet version that has https://github.com/argoproj/applicationset/issues/462 released, before we merge. So I've marked this as 'request changes' until then.

2022-01-23 19:13 UTC, alexmt requested changes

2022-01-23 19:13 UTC, alexmt commented on manifests/ha/namespace-install.yaml
> +
A lot of users install Argo CD into non `argocd` namespace. Please remove hardcoded namespace from applicationset components.

2022-01-24 16:25 UTC, jgwest requested changes

2022-01-24 16:25 UTC, jgwest commented on manifests/base/applicationset/kustomization.yaml
> +  - https://raw.githubusercontent.com/argoproj/applicationset/release-0.3.0/manifests/install.yaml
I believe this should point to `https://raw.githubusercontent.com/argoproj/applicationset/master/manifests/install.yaml`

I have included my reasoning here: https://github.com/argoproj/argo-cd/issues/7351#issuecomment-1020282879

2022-01-26 00:53 UTC, alexmt approved these changes
LGTM

2022-01-26 11:17 UTC, jgwest approved these changes
LGTM, thanks @ishitasequeira!

2022-01-26 11:18 UTC, merged