feat: Introduce RBAC based approach to pod logs #7211
argoproj/argo-cd pull request #8353
Opened 2022-02-03 11:43 UTC by reggie-k

The required changes in the cli were performed, the UI changes will come in a separate PR.
The enforcement is disabled by default, to mitigate the breaking change.
The switch will reside in the main argocd-cm.
Not sure whether I should document the switch explicitly myself or will it be documented in the release blog?

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [V] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [V] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [V] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [V] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [V] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [V] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-02-03 13:34 UTC, pasha-codefresh requested changes

2022-02-03 13:34 UTC, pasha-codefresh commented on server/account/account.go
> +		// logsRBACEnforceEnable := env.ParseBoolFromEnv("ARGOCD_SERVER_RBAC_LOG_ENFORCE_ENABLE", false)
i think it is redundant changes

2022-02-03 13:34 UTC, pasha-codefresh commented on server/application/application.go
> +	logsRBACEnforceEnable, _ := s.settingsMgr.GetServerRBACLogEnforceEnable()
not ignore error here

2022-02-03 13:34 UTC, pasha-codefresh commented on util/settings/settings.go
> +	return argoCDCM.Data[settingsServerRBACLogEnforceEnableKey] == "true", nil
maybe better use strconv.ParseBool(

2022-02-03 13:34 UTC, pasha-codefresh commented on util/settings/settings.go
> +	ServerRBACLogEnforceEnable bool `json:"serverRBACLogEnforceEnable"`
i dont think you need it anymore after migrate to settings manager

2022-02-04 15:01 UTC, reggie-k commented
Fixed according to the remarks.
Signed off the commits.
Perhaps additional discussion needed on [util/settings/settings.go](https://github.com/argoproj/argo-cd/pull/8353/files/97222fc22f7495b64436b02c3819c87523f687da#diff-3b21889f7a356a28ebba12c6d339b945d7171a83b4dd603c0902e62cee3051ff)

2022-02-16 14:11 UTC, crenshaw-dev requested changes
Could you also do a quick update in rbac.md? Seems like a good place to document this.

2022-02-16 14:46 UTC, reggie-k commented on server/account/account.go
> +	// Temporarily, logs RBAC will be enforced only if an intermediate env var serverRBACLogEnforceEnable is defined and has a "true" value
Internal var based on a value of an env var. Will clarify the comment, thanks.

2022-02-17 10:06 UTC, reggie-k commented on server/account/account.go
> +	// Temporarily, logs RBAC will be enforced only if an intermediate env var serverRBACLogEnforceEnable is defined and has a "true" value
Done

2022-02-18 14:06 UTC, crenshaw-dev approved these changes
LGTM!

2022-02-18 14:55 UTC, reggie-k commented
Great!
As for the UI changes needed (both backend and UI changes will have to appear in a release), should they come after this PR is merged or can they be based on my branch as it is now?  They will be performed by my colleague.

2022-02-18 15:51 UTC, pasha-codefresh approved these changes

2022-02-18 15:52 UTC, pasha-codefresh commented
Well done @reggie-k

2022-02-18 16:11 UTC, yonimoses commented
> Great! As for the UI changes needed (both backend and UI changes will have to appear in a release), should they come after this PR is merged or can they be based on my branch as it is now? They will be performed by my colleague.

Awsome!

2022-02-18 19:16 UTC, crenshaw-dev requested changes
Oh! You asked a question that I failed to answer. `settingsServerRBACLogEnforceEnableKey` should be documented in docs/operator-manual/argocd-cm.yaml.

Nitpick: could you replace the hard-coded instances of the config key in tests with the variable?

2022-02-23 16:19 UTC, reggie-k commented
> > As for the UI changes needed (both backend and UI changes will have to appear in a release), should they come after this PR is merged or can they be based on my branch as it is now?
> 
> If the backend changes shouldn't be allowed to go out without frontend changes, I'd recommend making them all part of one PR.

I see the reason behind this. How can this be achieved, given my colleague will work on the UI changes, and will need the backend to have my changes? Can you guide me through the process from Github perspective? Where does he fork from, where does he create PRs to, etc?

2022-02-23 16:30 UTC, crenshaw-dev commented
> Done, now wondering whether part of that belongs in the release blog :) What do you think?

I think it probably does. @alexmt do we keep a running list anywhere of things that need to be in the release blog?

> Am a total go newbie, but the const key names in settings.go are private and used within the package, as far as I understand, do you want me to make this particular one a global const so that it can be referenced outside?

I'm relatively new to go as well, so I missed that problem. 😆 I think hard-coding is fine in this case. Searching text is easy.

> Can you guide me through the process from Github perspective? Where does he fork from, where does he create PRs to, etc?

I think he could 1) fork argo-cd, 2) add your fork as a remote, 3) checkout your branch, 4) create a new branch based on yours, 5) make changes and then open a PR against your branch. Once the UI changes are merged into your branch, this PR will be ready for final review/merge.

2022-03-11 21:45 UTC, alexmt commented
Thank you for review @pasha-codefresh and @crenshaw-dev  . Doing one final round and merging

2022-03-18 18:29 UTC, alexmt approved these changes
LGTM. 


I think we should resolve https://github.com/argoproj/argo-cd/pull/8353/files#r798567363 but I propose to merge PR for the sake of time and create follow up PR to do it.

2022-03-18 18:40 UTC, crenshaw-dev approved these changes
LGTM!

2022-03-18 18:40 UTC, merged

2022-03-18 19:20 UTC, pasha-codefresh commented
Great job @reggie-k !

2022-03-18 19:25 UTC, alexmt commented
Thank you @reggie-k !