fix: Make zoom level a user preference (#7183)
argoproj/argo-cd pull request #8460
Opened 2022-02-10 18:13 UTC by keithchong

Signed-off-by: Keith Chong <kykchong@redhat.com>

No specific issue for this PR, but is a follow-up change to address the Alex's comment made here:

https://github.com/argoproj/argo-cd/pull/8290#pullrequestreview-865564568

So, with this change, each browser tab Argo CD UI instance will have the same zoom level. 
See bullet point 2 from here: https://github.com/argoproj/argo-cd/pull/8290#issue-1115669298

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-02-13 04:40 UTC, alexmt requested changes
Thank you @keithchong . Noticed one minor issue. Can you take a look?

2022-02-23 19:00 UTC, keithchong commented on ui/src/app/applications/components/application-details/application-details.tsx
> +                            const zoomNum = (pref.zoom * 100).toFixed(0);
Hi @alexmt , done.

2022-02-23 19:21 UTC, alexmt approved these changes
LGTM

2022-03-04 19:29 UTC, ciiay approved these changes
LGTM!

2022-03-10 21:44 UTC, keithchong commented
Hi @alexmt, this has been rebased.

2022-03-10 21:45 UTC, merged