fix: Upgrade gitops-engine to fix compatibility with v1 CRDs
argoproj/argo-cd pull request #8515
Opened 2022-02-15 22:18 UTC by terrytangyuan

This will include a fix https://github.com/argoproj/gitops-engine/pull/378 for an issue discovered in https://github.com/argoproj/argo-cd/pull/8431. 

Signed-off-by: Yuan Tang <terrytangyuan@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-02-15 22:20 UTC, jessesuen approved these changes

2022-02-15 22:22 UTC, jessesuen requested changes
CI is failing with:

```
# github.com/argoproj/gitops-engine/pkg/utils/kube
Error: ../../../go/pkg/mod/github.com/argoproj/gitops-engine@v0.5.4/pkg/utils/kube/resource_ops.go:245:7: undefined: apply.NewApplyOptions
Error: ../../../go/pkg/mod/github.com/argoproj/gitops-engine@v0.5.4/pkg/utils/kube/resource_ops.go:256:19: cannot assign validation.Schema to o.Validator in multiple assignment
Error: ../../../go/pkg/mod/github.com/argoproj/gitops-engine@v0.5.4/pkg/utils/kube/resource_ops.go:266:16: cannot assign meta.RESTMapper to o.Mapper in multiple assignment
k8s.io/kubectl/pkg/util/podutils
```

2022-02-15 23:54 UTC, terrytangyuan commented
For the record, we ended up upgrading to the latest commit in gitops-engine since https://github.com/argoproj/gitops-engine/commit/b5600162862f1bc5d5b9540cf12de4f1e394bbfc is not included in any gitops-engine releases yet and that fix is necessary to match `k8s.io/kubectl` version.

2022-02-16 00:51 UTC, alexmt approved these changes

2022-02-16 00:52 UTC, jessesuen approved these changes

2022-02-16 00:54 UTC, merged