fix(ui): pass getResource function to the extension component
argoproj/argo-cd pull request #8617
Opened 2022-02-28 02:47 UTC by yq314

This is an attempt to address https://github.com/argoproj-labs/argocd-extensions/issues/10

When `workloadRef` is used in `Rollout` resource, the extension is not able to access `spec.template` as it's defined in the `Deployment` resource. We need additional call to the api to fetch necessary information from `Deployment`.

The fix is to pass the `getResource()` function to the extension component.

I clearly miss a lot of contexts and background knowledge of the project, let me know if the attempt doesn't make sense and I'm happy to update the implementation.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-02-28 02:56 UTC, yq314 commented
@rbreeze @alexmt could you take a look thanks

2022-03-01 17:03 UTC, rbreeze requested changes

2022-03-02 00:33 UTC, yq314 commented on ui/src/app/applications/components/resource-details/resource-details.tsx
> +                        <ExtensionComponent tree={tree} resource={state} getResourceFunc={resource => services.applications.getResource(application.metadata.name, resource)} />
@rbreeze the second solution was actually the first approach I attempted, however, the tree doesn't have all the information we need.

This is the deployment in tree:
```
{
  createdAt: "2022-03-01T11:03:34Z",
  group: "apps",
  health: { status: "Healthy" },
  info: [{ name: "Revision", value: "Rev:1" }],
  kind: "Deployment",
  name: "pice-service",
  namespace: "pricing",
  resourceVersion: "71769635",
  uid: "bbffaa75-ae9f-44da-88d9-a817fa0fd70d",
  version: "v1",
}
```
We still don't have access to the spec of deployment. We do need the information in tree to call the getResource() function.

It looks like solution 1 is more viable, or can we actually just enrich the items in the tree with what is returned in `services.applications.getResource(application.metadata.name, resource)` ?

2022-06-10 08:06 UTC, mihstaub commented
Hey guys,

Any update on this pr?

2024-06-13 00:08 UTC, christianh814 commented
> Hey guys,
> 
> Any update on this pr?

Looks like we're still waiting for @yq314 and @rbreeze to resolve conflicts

2024-06-24 15:00 UTC, kencochrane commented
@rbreeze, do you have a few minutes to help with this? If not, let us know, and we can see if we can find someone else.

2024-06-24 15:02 UTC, rbreeze commented
@kencochrane Sure thing, I should have some time this week

2025-02-28 10:16 UTC, closed without merging

2025-02-28 13:43 UTC, andrii-korotkov-verkada commented
Closed the PR due to it being old and unlikely to be able to resolve merge conflicts. But feel free to re-open/re-submit if the work is still planned.