UI: Grid-tree view to improve information density and preserve visual hierarchy (#6936)
argoproj/argo-cd pull request #8661
Opened 2022-03-03 07:30 UTC by keithchong

Signed-off-by: Keith Chong <kykchong@redhat.com>

This fixes https://github.com/argoproj/argo-cd/issues/6936

This is a preliminary solution to address the concerns in 6936, as well as several other issues. 

Points:
1. This PR changes the line connections that are somewhat disorganized, with multiple outward-bound points from the originating node, and multiple inward-bound points to the target node. At times, it is hard to distinguish which nodes the lines are connected to.
2. This PR adds expansion and collapse support for each node that has children. This directly addresses the information density problem. The Expand All and Collapse All buttons are added to the floating toolbar.
3. The line connection re-layout change can be pulled out into a separate PR if desired.
4. The implementation of the expansion and collapse feature involves keeping track of the collapsed nodes. Upon entering the tree view, by default, all nodes are expanded. Therefore, no node is in the list of collapsed nodes.  Collapse All means all applicable nodes will be added to this list. Performance might be a concern here so the Collapse All button could be removed. Users might not collapse all nodes by hand anyway. Perhaps, another solution will be to write the expansion state value as an attribute on the element.
5. It is hard to distinguish the node "kind" in the view. This fix includes changing the background color for Pods. This change can be easily removed, but is included here to address this usability issue and a separate feature can be opened to perhaps customize the node colors.
6. Can't find Expand/Collapse All icons with multiple squares behind the +/- symbol. These are better than using only the plus and minus icons.
7. The issue in https://github.com/argoproj/argo-cd/issues/5468 is arguably in part due to the many pods that are shown. However, in honoring the concept of the tree structure, and the parent-child relationship, part of this concern is addressed. Note, this fix does not preclude the fix for 5468, since the collapsed state can still show the "Pod view node" representation.

Please try this fix out, especially with applications with many nodes.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-03-03 07:46 UTC, keithchong commented
![Screenshot from 2022-03-03 02-33-57](https://user-images.githubusercontent.com/7726022/156518073-76d2ba35-4c2c-4259-9186-99f3dbd4f5c6.png)

![Screenshot from 2022-03-03 02-35-29](https://user-images.githubusercontent.com/7726022/156518011-13ecb036-7c7e-4e5d-81ae-75410ad364cd.png)

![Screenshot from 2022-03-03 02-44-35](https://user-images.githubusercontent.com/7726022/156519570-f8501fe9-1dff-499e-ba80-39489b1dd4e8.png)

Collapsed ReplicaSet
![Screenshot from 2022-03-03 02-44-47](https://user-images.githubusercontent.com/7726022/156519585-16f5553e-5e18-45dd-95f2-7c19c38a857d.png)

2022-03-03 15:36 UTC, keithchong commented
Before:

<img width="1150" alt="Screen Shot 2022-03-03 at 10 36 00 AM" src="https://user-images.githubusercontent.com/7726022/156597717-451d5f25-60a4-4579-8a33-1d0e66f0c1ed.png">

2022-03-03 20:42 UTC, reginapizza reviewed
Hi Keith! I checked this out and it looks good to me. One suggestion I have is to add a tooltip to the smaller +/- on the resource so that a user will know it's for collapsing/expanding child nodes. You also had a point about the line connectors disappearing when zoomed out but I didn't observe that so I'm curious where you're seeing that happening?

2022-03-04 21:28 UTC, ciiay commented
Hi Keith, great work on this complicated task! Good learning from reviewing the PR 👍 Thank you for that.

I only have one small concern that if we can pass the color to the SCSS so that the right arrow would have same color as the dashed line in the network view? That way it looks a little bit more clearer when it comes to very complex graph.

You probably already know the trick, but here's an example of what I mean: https://css-tricks.com/getting-javascript-to-talk-to-css-and-sass/

2022-04-21 00:24 UTC, rbreeze requested changes
Looks good, but I agree with both @reginapizza and @ciiay 's suggestions that: 
1) Matching the color of the arrows in network view and 
2) Adding a tooltip indicating what the minimize/maximize button does

2022-05-11 21:43 UTC, keithchong commented
Also, the arrow will be centred along the connecting line and the line ends at the arrow, unlike the current behavior now:

https://user-images.githubusercontent.com/7726022/167952535-04544e90-4850-41e3-b019-6a4115ba8b5b.mov

2022-05-15 22:48 UTC, rbreeze approved these changes
LGTM once comment is addressed

2022-05-15 22:48 UTC, rbreeze commented on ui/src/app/applications/components/application-resource-tree/application-resource-tree.tsx
> +    // >();//nodesHavingChildren: ResourceTreeNode[]) { // Map<string, number>) {
is this comment intentional?

2022-05-16 15:47 UTC, keithchong commented
More testing:

Before:

<img width="823" alt="Before-NetworkView" src="https://user-images.githubusercontent.com/7726022/168632335-9f4f8f78-da0c-4250-acd6-64de4e26c604.png">

After:

<img width="861" alt="After-NetworkView" src="https://user-images.githubusercontent.com/7726022/168631893-3ae8e757-32d1-4f72-bae6-b88bef50a443.png">

From resolved conversation, pod and non-pod children of parent:

Before:
<img width="1096" alt="Before-ChildPodsAndNonPods" src="https://user-images.githubusercontent.com/7726022/168632147-37f7af28-d6e5-42cc-9519-267561506ab6.png">

After:

<img width="1164" alt="After-ChildPodsAndNonPods" src="https://user-images.githubusercontent.com/7726022/168632273-e825bac3-8e2a-4fe6-bf94-3eef9eb92f4c.png">

<img width="890" alt="After-PodGroupWithExpansionToAccountForNonPodChildren" src="https://user-images.githubusercontent.com/7726022/168631967-c18cbf6c-b1d4-4c07-a701-8c8f2d08cb32.png">

2022-05-16 16:53 UTC, merged