including MavenCode
argoproj/argo-cd pull request #8687
Opened 2022-03-05 02:19 UTC by charlesa101

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-03-07 17:40 UTC, alexmt requested changes
Thank you @charlesa101 ,

Can you please revert numbering changes (use `1.` on each line)

2022-03-08 18:00 UTC, jessesuen requested changes
Can you change the numbering to use `1.` across the board? Otherwise, it becomes unmaintainable?

EDIT: oops, I see alex had same comment

2022-03-22 19:29 UTC, pasha-codefresh requested changes

2022-03-22 19:29 UTC, pasha-codefresh commented on USERS.md
> +82. [WSpot](https://www.wspot.com.br/)
please revert numeration changes

2022-04-09 18:21 UTC, crenshaw-dev commented
Closing because stale.

2022-04-09 18:21 UTC, closed without merging