feat: Make spec.source.helm.values field accepts either a string or a rawExtension
argoproj/argo-cd pull request #8794
Opened 2022-03-16 16:03 UTC by mcbenjemaa

Test using this demo repo: https://github.com/mcbenjemaa/argocd-apps

Fixes: https://github.com/argoproj/argo-cd/issues/8013
Ref: https://github.com/argoproj/argo-cd/issues/2936
Enhancement Proposal Ref: https://github.com/argoproj/argo-cd/issues/8579

Thanks @crenshaw-dev  for guidance.

CC @alexec 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-03-16 17:55 UTC, mcbenjemaa commented
I will fix the tests

2022-03-16 17:56 UTC, mcbenjemaa commented
Fixes: https://github.com/argoproj/argo-cd/issues/2936

2022-03-17 20:50 UTC, crenshaw-dev reviewed
Just tested this locally, and things seem to behave quite nicely! We could probably use an e2e test or two.

My questions might have been silly. Mostly stuff that surprised me / I was curious about, not necessarily anything wrong!

2022-03-23 14:34 UTC, mcbenjemaa commented on cmd/util/app.go
> +	command.Flags().StringVar(&opts.valuesRaw, "values-raw-literal-file", "", "Filename or URL to import as a literal Helm values raw object")
I added this flag `--values-raw-literal-file`

2022-03-25 14:17 UTC, mcbenjemaa commented
Strange! Why this test is failing `docs/readthedocs.org:argo-cd`

2022-03-25 14:23 UTC, crenshaw-dev commented
@mcbenjemaa oh, there was a dependency in docs/requirements.txt that needed to be pinned. If you merge master, it should work. :-)

2022-03-29 13:16 UTC, crenshaw-dev commented
Hey, @mcbenjemaa, how's this going? Anything I can do to help?

2022-03-29 15:59 UTC, mcbenjemaa commented
I have rebased it with master! 
If the tests succeeds we are ready!

2022-03-29 16:56 UTC, crenshaw-dev commented
@mcbenjemaa could you run `make codegen-local`? Looks like the CLI docs need to be updated.

2022-03-31 07:43 UTC, mcbenjemaa commented
I don't know Why

`license/snyk (Argoproj)` test has failed
`security/snyk (Argoproj)` test has failed

2022-03-31 10:21 UTC, mcbenjemaa commented
@crenshaw-dev  Can you restart the test ?

`Integration tests / Run end-to-end tests (v1.22.6)`

2022-03-31 13:48 UTC, crenshaw-dev commented
I don't think I have permissions to rerun tests. @alexmt can you kick it off again?

Alternatively @mcbenjemaa, you could push an empty commit.

2022-03-31 15:40 UTC, mcbenjemaa commented
I'm gonna try to add an empty commit.

2022-03-31 17:23 UTC, crenshaw-dev reviewed
Alrighty. I'm _super_ excited about this PR. It's been a marathon, thanks for all your work @mcbenjemaa! I want to do a line-by-line review of this PR and do some manual testing. So please be patient with any comments that come up. But this is really good code, I'm excited to get it merged.

2022-04-04 15:43 UTC, crenshaw-dev requested changes

2022-04-06 14:03 UTC, crenshaw-dev commented
@mcbenjemaa lmk if I can do anything to help with this!

2022-04-12 17:14 UTC, crenshaw-dev commented on cmd/util/app.go
> +	command.Flags().StringVar(&opts.valuesRaw, "values-raw-literal-file", "", "Filename or URL to import as a literal Helm values raw object")
done here: https://github.com/argoproj/argo-cd/pull/9079

2022-04-12 17:14 UTC, crenshaw-dev commented on cmd/util/app.go
> +	command.Flags().StringVar(&opts.valuesRaw, "values-raw-literal-file", "", "Filename or URL to import as a literal Helm values raw object")
done here: https://github.com/argoproj/argo-cd/pull/9079

2022-04-12 17:21 UTC, crenshaw-dev commented
@mcbenjemaa closing this in favor of https://github.com/argoproj/argo-cd/pull/9079, where I'll try to get it across the finish line. Thanks so much again for all your work on this!

2022-04-12 17:22 UTC, closed without merging

2022-04-14 02:27 UTC, crenshaw-dev commented on pkg/apis/application/v1alpha1/stringorobject_types.go
> +type StringOrObject struct {
done in https://github.com/argoproj/argo-cd/pull/9079

2022-04-14 02:27 UTC, crenshaw-dev commented on assets/swagger.json
> +    "v1alpha1StringOrObject": {
done in https://github.com/argoproj/argo-cd/pull/9079