Add linking statement for the terminologies below
argoproj/argo-cd pull request #8869
Opened 2022-03-23 15:38 UTC by datsabk

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-03-23 15:42 UTC, crenshaw-dev requested changes
Good catch! The lack of a bridge statement was really awkward.

2022-03-23 16:06 UTC, datsabk commented on docs/core_concepts.md
> +Let's assume you're familiar with core Git, Docker, Kubernetes, Continuous Delivery, and GitOps concepts. Let us understand some of the terminologies pertaining to ArgoCD.
I think below statement would sound better. 

`Let's familiarize ourselves with the concepts that are specific to Argo CD`

2022-03-23 16:07 UTC, crenshaw-dev commented on docs/core_concepts.md
> +Let's assume you're familiar with core Git, Docker, Kubernetes, Continuous Delivery, and GitOps concepts. Let us understand some of the terminologies pertaining to ArgoCD.
Yes, that's much better than mine!

2022-03-23 16:48 UTC, datsabk commented on docs/core_concepts.md
> +Let's assume you're familiar with core Git, Docker, Kubernetes, Continuous Delivery, and GitOps concepts. Let us understand some of the terminologies pertaining to ArgoCD.
Done! Pushed the change with commit sign off as requested

2022-04-07 19:09 UTC, crenshaw-dev commented
Closing in favor of https://github.com/argoproj/argo-cd/pull/9036

2022-04-07 19:09 UTC, closed without merging