feat: Merge applicationset docs and examples
argoproj/argo-cd pull request #8955
Opened 2022-03-31 11:56 UTC by rishabh625

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [x] Does this PR require documentation updates?
* [x] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Related #8864 
This PR copy's examples and documentation of applicationset into argocd, have changed text of documentation wherever required please review with extra attention as may have mistakes.

2022-03-31 14:07 UTC, crenshaw-dev requested changes
Overall, looks awesome!

A few top-level things:
1) I see a few absolute links that could be changed to relative. I think you can find them all with a search for `https://argo-cd.readthedocs.io`.
2) I'm getting an error on `make serve-docs-local` regarding the `google_analytics` config option.

2022-03-31 16:15 UTC, dmolik commented on docs/assets/applicationset/broken-link-ignore-list.txt
> +https://1.2.3.4
thanks!

2022-04-01 12:36 UTC, crenshaw-dev approved these changes
lgtm!

2022-04-01 12:36 UTC, crenshaw-dev commented
Will wait for one more review, since it's a big PR.  :-)

2022-04-04 11:07 UTC, rishabh625 commented
@jannfis @alexmt : can u plz take some time and review this?

2022-04-04 14:46 UTC, jannfis approved these changes
LGTM as well! Thanks @rishabh625

2022-04-04 15:22 UTC, merged