feat: remove rbac when using argocd cluster rm
argoproj/argo-cd pull request #8969
Opened 2022-04-01 14:20 UTC by danielhelfand

Closes #8958 

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-04-07 17:35 UTC, crenshaw-dev requested changes
Can we get some test coverage on this? I'm not sure how difficult that might be, since it involves multiple clusters.

Also, should we consider this a breaking change? Seems unlikely, but I could imagine a script which assumes the config will be removed but the RBAC will remain.

2022-04-07 17:43 UTC, danielhelfand commented
> Can we get some test coverage on this? I'm not sure how difficult that might be, since it involves multiple clusters.

I'll look into some of the e2e tests and see how challenging this would be. But yeah, that was my only initial hesitation was how complex the test could end up being.

> Also, should we consider this a breaking change? Seems unlikely, but I could imagine a script which assumes the config will be removed but the RBAC will remain.

Yeah, maybe scripts exist to clean up the rbac after the fact. I would consider it breaking in that sense. But hopefully that's more of an edge case, and I would assume this would be a welcome change by anyone doing that. 

If we want to treat this as breaking, fine by me. Just let me know what that process would be to introduce a change like this then.

2022-04-07 17:49 UTC, crenshaw-dev commented
If e2e tests are too complex, maybe we can just test `getRestConfig`.

@alexmt what's the process for a minor breaking change? I'm thinking:
1) add an exclamation mark to the issue name so we remember to make a note in release notes
2) add a breaking label to this PR so we avoid cherry-picking it unless someone really wants this feature

2022-04-08 14:38 UTC, danielhelfand commented
@crenshaw-dev Added some unit tests for `getRestConfig` and an e2e test for ClusterDeletion/RBAC is removed. I'll keep an eye out for updates on introducing this as a breaking change.

2022-04-08 17:55 UTC, crenshaw-dev commented
I'm just gonna roll with the label and the title change. Someone can correct me later if that's wrong. Will review the additional tests!

2022-04-08 18:20 UTC, crenshaw-dev requested changes

2022-04-08 18:20 UTC, crenshaw-dev commented on test/e2e/cluster_test.go
> +	}
Could you add a check before `DeleteByName` to verify that these resources existed at some point?

2022-04-09 16:58 UTC, crenshaw-dev approved these changes
LGTM!

2022-04-09 16:58 UTC, merged