chore: eliminate go-mpatch dependency
argoproj/argo-cd pull request #9045
Opened 2022-04-08 15:26 UTC by crenshaw-dev

This test was failing on my Mac due to dependency issues.

I think the modified test is equivalent to the original test. Three methods had been monkey-patched to deterministically generate `serverResources`. I've refactored `generateProjectAllowList` to simply accept the calculated `serverResources` value as a parameter.

2022-04-08 20:08 UTC, leoluz commented on go.mod
> -	github.com/undefinedlabs/go-mpatch v1.0.6
🙏🏻

2022-04-08 20:25 UTC, leoluz requested changes
Suggesting a different approach to properly test this.

2022-04-08 20:25 UTC, leoluz commented on cmd/argocd/commands/admin/project_allowlist.go
> +			globalProj := generateProjectAllowList(serverResources, clusterRoleFileName, projName)
I don't think the logic to retrieve the resourceList should be added directly in the `NewProjectAllowListGenCommand`. Ideally, commands should be very dry in terms of logic mainly dealing with CLI flags and delegating the execution to an underlying function like it was before. Another possibility to achieve the same goal is defining an interface like:
```go
type ResourceGetter interface {
    GetServerResources(c clientcmd.ClientConfig) ([]*metav1.APIResourceList, error)
}
```
And then have this interface as the first argument of `generateProjectAllowList()`. This way you can easily mock this logic and properly test it.

2022-04-09 22:30 UTC, leoluz commented on cmd/argocd/commands/admin/project_allowlist.go
> +		return nil, err
As we change code that just return `err` I think we should start adding more context to better understand exceptional scenarios in logs. Example:
```go
return nil, fmt.Errorf("error while creating client config: %s", err)
```

2022-04-09 22:31 UTC, leoluz commented on cmd/argocd/commands/admin/project_allowlist.go
> +		return nil, err
please add error context

2022-04-09 22:31 UTC, leoluz commented on cmd/argocd/commands/admin/project_allowlist.go
> +		return nil, err
please add error context

2022-04-09 22:32 UTC, leoluz commented on cmd/argocd/commands/admin/project_allowlist.go
> +		return nil, err
please add error context

2022-04-09 22:32 UTC, leoluz commented on cmd/argocd/commands/admin/project_allowlist.go
> +		return nil, err
please add error context

2022-04-09 22:32 UTC, leoluz commented on cmd/argocd/commands/admin/project_allowlist.go
> +		return nil, err
please add error context

2022-04-11 13:37 UTC, leoluz approved these changes

2022-04-11 13:49 UTC, merged

2022-06-13 21:32 UTC, crenshaw-dev commented
Cherry-picked onto 2.3.

2022-06-13 21:59 UTC, crenshaw-dev commented
Cherry-picked onto 2.2.