Prefix controller resource names with 'argocd-'
argoproj/argo-cd pull request #917
Opened 2018-12-10 14:23 UTC by zcahana

This PR renames the various controller resources (and their corresponding YAML files) such that they'll be prefixed with 'argocd-', similarly to other core Argo CD resources.

Aside from improving consistency, this clarifies the origin of non-namespaced Argo CD resources such as `argocd-application-controller-clusterrole` (previously named `application-controller-clusterrole`).

2018-12-12 18:01 UTC, alexmt commented
It makes sense to me. Thank you for contribution @zcahana !

@jessesuen, what do you think?

2018-12-13 01:51 UTC, jessesuen commented
Makes sense to me. Go for it

2018-12-14 21:23 UTC, alexmt requested changes
Looks good! Found one missing change in `common.go`. Please check me comment

2018-12-16 11:00 UTC, zcahana commented on manifests/base/argocd-application-controller-service.yaml
> +  name: argocd-application-controller
Great catch! Fixing...

2018-12-19 05:31 UTC, mgoodness commented
I applaud this change! May I also recommend dropping the resource type from some of the resource names?

*-role
*-role-binding
*-clusterrole
*-clusterrolebinding

2018-12-20 00:25 UTC, alexmt approved these changes

2018-12-20 09:03 UTC, zcahana commented
Per @mgoodness' suggestion, I've also renamed the various `[Cluster]Role[Binding]` resources to omit the resource type from their names. @alexmt I hope you're good with this change too, otherwise I can revert.
Also rebased and resolved a minor conflict.

2018-12-20 21:15 UTC, alexmt commented
Looks good. Thanks for contribution @zcahana !

2018-12-20 21:16 UTC, merged