chore: resource state tests
argoproj/argo-cd pull request #9307
Opened 2022-05-05 12:22 UTC by pasha-codefresh

Resource state tests inside app.cmd

2022-05-05 20:51 UTC, crenshaw-dev requested changes
Just nitpicks.  :-)

2022-05-05 20:51 UTC, crenshaw-dev commented on cmd/argocd/commands/app_test.go
> +	assert.Equal(t, key, "group/kind/namespace/name")
I think the assertion is backwards here. shouldn't the expected value be first?

2022-05-05 20:51 UTC, crenshaw-dev commented on cmd/argocd/commands/app_test.go
> +func TestCheckResourceStatus(t *testing.T) {
Not required but would be nice: could you add a docstring to the checkResourceStatus function? It's not immediately obvious what it's meant to do.

2022-05-06 17:00 UTC, leoluz approved these changes

2022-05-10 13:13 UTC, crenshaw-dev approved these changes

2022-05-10 13:13 UTC, merged