docs: clarify Role/ClusterRole uses for exec feature
argoproj/argo-cd pull request #9354
Opened 2022-05-11 00:23 UTC by crenshaw-dev

Related to https://github.com/argoproj/argo-cd/issues/9335

2022-05-11 04:13 UTC, 34fathombelow reviewed
update line 82
`p, role:org-admin, exec, create, *, allow`

2022-05-11 04:15 UTC, 34fathombelow requested changes
update line 98
`p, role:staging-db-admins, exec, create, staging-db-admins/*, allow`

2022-05-12 13:47 UTC, leoluz approved these changes
LGTM

2022-05-12 15:13 UTC, merged

2022-05-31 16:14 UTC, crenshaw-dev commented
Cherry-picked into 2.4.