chore: add labels to notifications controller serviceaccount
argoproj/argo-cd pull request #9373
Opened 2022-05-11 20:57 UTC by danielhelfand

Closes #9359 

Adds labels to notifications controller serviceaccount to be consistent with how other serviceaccounts have labels.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-05-12 03:59 UTC, ashutosh16 requested changes
Do we need to make similar changes [here](https://github.com/argoproj/argo-cd/blob/cec18790ce594c7b3bb480630896c096273e498c/manifests/namespace-install.yaml#L32)

2022-05-12 06:22 UTC, chetan-rns approved these changes
LGTM. Thanks @danielhelfand

2022-05-12 13:50 UTC, danielhelfand commented
> Do we need to make similar changes [here](https://github.com/argoproj/argo-cd/blob/cec18790ce594c7b3bb480630896c096273e498c/manifests/namespace-install.yaml#L32)

The labels are included in the namespace install in this pr. Is there somewhere else you were referring that they should be included that I missed?

2022-05-12 15:06 UTC, ashutosh16 commented
> > Do we need to make similar changes [here](https://github.com/argoproj/argo-cd/blob/cec18790ce594c7b3bb480630896c096273e498c/manifests/namespace-install.yaml#L32)
> 
> The labels are included in the namespace install in this pr. Is there somewhere else you were referring that they should be included that I missed?

oh yes, it is covered in the PR :)

2022-05-12 15:06 UTC, ashutosh16 approved these changes
LGTM

2022-05-17 01:04 UTC, ishitasequeira approved these changes
LGTM
@alexmt @jannfis @crenshaw-dev should we get this merged?

2022-05-17 02:13 UTC, crenshaw-dev approved these changes

2022-05-17 02:13 UTC, merged