fix: Added mock for gitea response in appset PR,SCM generator
argoproj/argo-cd pull request #9400
Opened 2022-05-13 12:33 UTC by rishabh625

Signed-off-by: rishabh625 <rishabhmishra625@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Fixes #9287

2022-05-13 12:47 UTC, crenshaw-dev requested changes
Looks awesome. Just a couple nitpicks. Thanks @rishabh625!

2022-05-13 12:47 UTC, crenshaw-dev commented on applicationset/services/pull_request/gitea_test.go
> +			_, err := io.WriteString(w, `[{"id":50721,"url":"https://gitea.com/test-argocd/pr-test/pulls/1","number":1,"user":{"id":4476,"login":"graytshirt","full_name":"Dan","email":"graytshirt@noreply.gite
Could you run this JSON through a formatter for readability?

2022-05-13 12:47 UTC, crenshaw-dev commented on applicationset/services/scm_provider/gitea_test.go
> +		//case "/api/v1/repos/test-argocd/pr-test/labels?limit=0&page=1":
Can this line be dropped?

2022-05-13 12:55 UTC, rishabh625 commented on applicationset/services/scm_provider/gitea_test.go
> +		//case "/api/v1/repos/test-argocd/pr-test/labels?limit=0&page=1":
Done

2022-05-13 13:29 UTC, crenshaw-dev approved these changes
Thanks @rishabh625 !

2022-05-13 13:50 UTC, merged

2022-09-06 13:54 UTC, crenshaw-dev commented
Cherry-picked onto release-2.4 for 2.4.12.