fix: Use time library for parsing cache duration
argoproj/argo-cd pull request #9405
Opened 2022-05-13 16:26 UTC by pdrastil

Fixes https://github.com/argoproj/argo-cd/issues/9328

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-05-17 01:15 UTC, ishitasequeira approved these changes
@pdrastil Thanks for the PR! LGTM!

2022-05-19 20:11 UTC, pdrastil commented
Not really sure why race occured after merging master - is there a way to rerun test suite?

2022-05-27 15:10 UTC, crenshaw-dev requested changes
Thanks for the PR!

In this case, I think I'd rather update the docs than change the parsing behavior. Either one is probably fine, but the PR as currently written may be a breaking change for some users.

Would you be willing to update the PR to just be a docs fix?

2022-05-27 15:30 UTC, pdrastil commented
@crenshaw-dev I'm probably not seeing why this could be breaking. Can you please explain? If you provide just single digit number it still works as before (currently: 90s = `time.ParseDuration` would allow to use 90s or 1m30s).

2022-05-27 17:43 UTC, crenshaw-dev commented
Although we do use `time.ParseDuration` for a lot of other stuff, so I definitely think it's worth switching eventually. Just maybe by toggling on the presence of a `d` to avoid making a hard break?

2022-05-27 18:16 UTC, pdrastil commented
Thanks for the explanation - from documentation I've seen the `d` is not present because it could cause ambiguity.  Ref: https://github.com/golang/go/issues/17767

Kinda elegant solution would be:
- Regex capture of `([0-9]+)d` from original string
- Parse the rest with time util
- Add 24h * number of days to result

2022-05-27 21:01 UTC, crenshaw-dev commented
I like that solution! 

I see four places in the code using that utility function. To be honest, I'd rather copy/paste the function into Argo CD and modify it than editing it in the source package. I don't see the value of abstracting that function out.

2022-05-29 08:09 UTC, pdrastil commented
@crenshaw-dev Enhanced as proposed. As a bonus fractions now works as well like `1.5d`

2022-06-07 06:12 UTC, pdrastil commented
@crenshaw-dev Hi, any chance you can take a look again?

2022-07-29 17:20 UTC, pdrastil commented
@crenshaw-dev Hi - this is here for a long time - any chance you can look again?

2023-09-22 15:47 UTC, blakepettersson commented
In general LGTM (once the merge conflicts have been fixed)

2024-06-13 00:08 UTC, christianh814 approved these changes

2024-06-18 08:03 UTC, buker commented
Can someone move forward with this or do you need any help? I can contribute a bit.

2024-06-24 15:04 UTC, kencochrane commented
@buker I think we are just waiting for someone to help resolve the conflicts if you can help with those, that would be great. Thank you

2025-02-28 10:17 UTC, closed without merging