fix: Use the matchMode specified in the rbac configmap
argoproj/argo-cd pull request #9419
Opened 2022-05-16 13:03 UTC by chetan-rns

Closes: #9363 

Signed-off-by: Chetan Banavikalmutt <chetanrns1997@gmail.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-05-16 13:35 UTC, crenshaw-dev commented
@chetan-rns looks like a pretty important bugfix. Do you think it should be cherry-picked to 2.4?

2022-05-17 01:00 UTC, ishitasequeira commented on cmd/argocd/commands/admin/settings_rbac_test.go
> +		ok := checkPolicy("role:user", "get", "certificates", "*", "", uPol, "role:readonly", "regex", true)
I guess this is failing as expected considering the check is on `require.False`

2022-05-17 01:01 UTC, ishitasequeira reviewed
@chetan-rns The PR LGTM! 

A minor comment, should we add a test case for below scenarios too?
* match mode = "glob" , and we pass in a regex
* match mode = "regex", and we pass in a glob

2022-05-17 02:10 UTC, crenshaw-dev commented on cmd/argocd/commands/admin/settings_rbac_test.go
> +		ok := checkPolicy("role:user", "get", "certificates", "*", "", uPol, "role:readonly", "regex", true)
😆  thanks, @ishitasequeira, missed that!

2022-05-17 02:12 UTC, crenshaw-dev requested changes

2022-05-17 02:12 UTC, crenshaw-dev commented on cmd/argocd/commands/admin/settings_rbac_test.go
> +		ok := checkPolicy("role:user", "get", "certificates", "*", "", uPol, "role:readonly", "regex", true)
@chetan-rns could you add a test (or a few) showing that regex policy checking works for `true` cases?

2022-05-17 12:38 UTC, chetan-rns commented
@crenshaw-dev I don't have a strong opinion about cherry picking, since the bug only affects the `admin settings rbac can` command. Regex match mode still works fine when invoked in the argocd server.

2022-05-17 13:41 UTC, crenshaw-dev commented
Ah gotcha. Let's let it wait for 2.5 then.

2022-05-27 15:06 UTC, crenshaw-dev commented
@chetan-rns just checking in on this one. Will you have a chance to add tests?

2022-05-30 12:25 UTC, chetan-rns commented
@crenshaw-dev I've included unit tests. PTAL

2022-06-02 20:39 UTC, crenshaw-dev approved these changes
lgtm, thanks!

2022-06-02 20:39 UTC, merged