chore: Improve application logs adding message context
argoproj/argo-cd pull request #9435
Opened 2022-05-17 15:58 UTC by leoluz

Signed-off-by: Leonardo Luz Almeida <leonardo_almeida@intuit.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-05-18 16:53 UTC, jannfis approved these changes
LGTM.

Just a very opinionated nit, feel free to merge though :)

2022-05-18 18:38 UTC, leoluz commented on server/application/application.go
> +			log.Warnf("failed to force refresh application details: %v", err)
I actually agree with you. 
To be frank, this shouldn't be a matter of opinion. We should probably have this defined somewhere. 
For example:
https://github.com/golang/go/wiki/CodeReviewComments#error-strings

Will revert the change in this line. 👍🏻

2022-05-19 18:42 UTC, leoluz commented
After analysing failing unit-tests I realized that this PR could potentially introduce an API breaking change by returning wrapped errors. It seems grpc library doesn't play nicely with wrapped errors:
https://github.com/grpc/grpc-go/issues/2934

Improved the code to avoid introducing API breaking change.
Can you pls take another look @jannfis ?

2022-05-20 18:54 UTC, crenshaw-dev requested changes
There's no way to overstate what a big deal this is for debugging. Thanks for doing this.

Comments include mostly nits and one important change.

2022-05-20 18:54 UTC, crenshaw-dev commented on server/application/application.go
> +		return fmt.Errorf("error listing help repositories: %w", err)
s/help/helm

2022-05-20 18:54 UTC, crenshaw-dev commented on server/application/application.go
> +		return fmt.Errorf("error retrieving permitter repos: %w", err)
s/permitter/permitted

2022-05-20 18:54 UTC, crenshaw-dev commented on server/application/application.go
> +			return nil, fmt.Errorf("failed to patch Secret %s/%s: %w", res.Namespace, res.Name, err)
Revert due to comment above. Might want to log the real error instead.

2022-05-20 18:54 UTC, crenshaw-dev commented on server/application/application.go
> +		return a, fmt.Errorf("error setting app operation: %w", err)
I think you can explicitly return nil, like in the refactor above. `SetAppOperation` won't return a non-nil value with an error.

2022-05-20 18:54 UTC, crenshaw-dev commented on util/grpc/errors.go
> +func UnwrapGRPCStatus(err error) *status.Status {
Is this unit-testable?

2022-05-20 18:54 UTC, crenshaw-dev commented on util/grpc/errors.go
>  func kubeErrToGRPC(err error) error {
Ditto, does this need test coverage?

2022-05-20 20:22 UTC, leoluz commented on util/grpc/errors.go
>  func kubeErrToGRPC(err error) error {
added

2022-05-20 20:22 UTC, leoluz commented on util/grpc/errors.go
> +func UnwrapGRPCStatus(err error) *status.Status {
yes :)

2022-05-20 20:44 UTC, crenshaw-dev approved these changes
lgtm!

2022-05-20 21:16 UTC, merged

2022-05-31 18:19 UTC, crenshaw-dev commented
Cherry-picked onto 2.4.