update: index.md
argoproj/argo-cd pull request #9474
Opened 2022-05-21 15:46 UTC by aoshfan

* Currently guide is confusing.
* Fixing the "Subscribe" patch.

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-05-24 22:35 UTC, crenshaw-dev requested changes

2022-05-24 22:35 UTC, crenshaw-dev commented on docs/operator-manual/notifications/index.md
> +  email-password: <email_password>
If you prefer this over env vars, I'd recommend removing the `export` lines above.

2022-05-24 22:35 UTC, crenshaw-dev commented on docs/operator-manual/notifications/index.md
>  * Subscribe to notifications by adding the `notifications.argoproj.io/subscribe.on-sync-succeeded.slack` annotation to the Argo CD application or project:
Looks like this line should be updated as well.

2024-03-13 14:42 UTC, todaywasawesome commented
It's easier to let people do this with the export variables. Closing PR.

2024-03-13 14:42 UTC, closed without merging