docs: updated okta oidc config
argoproj/argo-cd pull request #9588
Opened 2022-06-06 17:28 UTC by huynhj93

### Summary

The OKTA OIDC docs are missing details on how to set up the OKTA application. I've added that and pictures to reference on how to do so. I've also added in detail how to edit the config maps and secrets for the client secret for the application. 

Checklist:

* [ c] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ n/a] The title of the PR states what changed and the related issues number (used for the release note).
* [n/a ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ n/a] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ no] Does this PR require documentation updates?
* [ yes] I've updated documentation as required by this PR.
* [ no] Optional. My organization is added to USERS.md.
* [ yes] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ n/a] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ n/a] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-06-06 19:53 UTC, crenshaw-dev requested changes
This looks awesome! Hoping someone more familiar w/ Okta can also review. In the meantime, one nitpick.

2022-06-06 19:53 UTC, crenshaw-dev commented on docs/operator-manual/user-management/okta.md
> +1. Choose your `default` authorization server, or create a new one called `argo`, which an audience of `api://argo`.
s/which/with ?

2022-08-16 19:16 UTC, jdmaguire commented
In terms of feedback, I was able to follow this and get everything working. Thanks for figuring this out!

2022-08-16 19:21 UTC, jdmaguire commented on docs/operator-manual/user-management/okta.md
> +## OIDC
The link on line 9 needs to be updated.

2022-10-18 22:32 UTC, john-kajabi commented on docs/operator-manual/user-management/okta.md
> +## OIDC
updated this line!

2022-10-18 22:32 UTC, john-kajabi commented on docs/operator-manual/user-management/okta.md
> +1. Note, if you see `grpc client` errors, you might want to restart your argocd server: `kubectl rollout restart deploy/argocd-server -n argocd`
also updated this!

2022-10-18 22:33 UTC, huynhj93 commented on docs/operator-manual/user-management/okta.md
> +## OIDC
updated this line to match line 9

2022-10-18 22:33 UTC, huynhj93 commented on docs/operator-manual/user-management/okta.md
> +1. Note, if you see `grpc client` errors, you might want to restart your argocd server: `kubectl rollout restart deploy/argocd-server -n argocd`
updated!

2022-10-18 22:47 UTC, john-kajabi commented on docs/operator-manual/user-management/okta.md
> +    1. For `Sign-in redirect URIs`, enter `https://${your.fqdn.com}/auth/callback` and `http://localhost:8085/auth/callback` (this is for signing in with CLI)
left a note in line 152 that this isn't the correct url but the default value

2024-03-13 15:28 UTC, todaywasawesome requested changes
Closing in favor of changes made in #13811

2024-03-13 15:28 UTC, closed without merging