Fixes #9429: A couple of notes that the default certificate is insecure.
argoproj/argo-cd pull request #9784
Opened 2022-06-24 13:54 UTC by YaytayAtWork

The default certificate created by Argo CD is a standard self-signed certificate.
There is nothing wrong with this, but it means that the instructions in the Getting Started guide cannot be followed.
This PR adds a note to point users in the correct direction to set up a secure cert (or to use --insecure on all the examples in Getting Started).

Signed-off-by: Jim Talbut <jim.talbut@groupgti.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-06-24 15:23 UTC, crenshaw-dev requested changes
One nitpick. Thanks!

2022-06-24 16:06 UTC, YaytayAtWork commented on docs/getting_started.md
> +This default installation will have a self-signed certificate and cannot be accessed securely.
Hmm, so really there are three options:
1. Your own cert.
2.  Add the self-signed cert.
3. --insecure.

How about:
This default installation will have a self-signed certificate and cannot be accessed without a bit of extra work.
Do one of:

-  Follow the [instructions to configure a certificate](./operator-manual/tls) (and ensure that the client OS trusts it).
-  Configure the client OS to trust the self signed certificate.
-  Use the --insecure flag on all Argo CD CLI operations in this guide.



Accurate and complete, but a bit long winded.

2022-06-27 13:41 UTC, jannfis approved these changes
LGTM. Thank you!

2022-06-27 14:21 UTC, crenshaw-dev commented on docs/getting_started.md
> +This default installation will have a self-signed certificate and cannot be accessed securely.
I like it!

2022-06-27 19:49 UTC, YaytayAtWork commented
Not sure what I need to do to unblock the merge.

2022-06-28 12:59 UTC, crenshaw-dev commented
@YaytayAtWork nothing, I was just being slow. 🙂 lgtm, thanks again!

2022-06-28 13:00 UTC, crenshaw-dev approved these changes

2022-06-28 13:00 UTC, merged

2022-07-04 06:08 UTC, Yaytay commented
Does anyone know why the list hasn't rendered correctly in the latest docs (https://argo-cd.readthedocs.io/en/latest/getting_started/)?
Should I have left a space before the first entry?