fix: set Content-Security-Policy header
argoproj/argo-cd pull request #9787
Opened 2022-06-25 14:08 UTC by deepto98

Signed-off-by: deepto <ddepp98@outlook.com>

Fixes #9637

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [ ] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-06-27 14:26 UTC, crenshaw-dev requested changes
Thanks @deepto98! Can you run `make clidocsgen`?

2022-06-28 16:46 UTC, deepto98 commented
> Thanks @deepto98! Can you run `make clidocsgen`?

Okay, sure.

2022-06-30 15:12 UTC, crenshaw-dev commented
@deepto98 let me know if I can be any help here!

2022-06-30 15:35 UTC, crenshaw-dev requested changes

2022-06-30 15:35 UTC, crenshaw-dev commented on cmd/argocd-server/commands/argocd_server.go
> +	command.Flags().StringVar(&contentSecurityPolicy, "content-security-policy", env.StringFromEnv("ARGOCD_SERVER_CONTENT_SECURITY_POLICY", "default-src 'self'; script-src 'self' 'unsafe-eval'; style-sr
Do we need unsafe-eval? I don't see any use of eval in our source.

2022-07-03 16:16 UTC, deepto98 commented
@crenshaw-dev I've run `make clidocsgen` and pushed the changes, have kept `unsafe-eval` as per the discussion in #9637. Do let me know if this is okay.

2022-07-18 14:29 UTC, deepto98 commented
@crenshaw-dev Can you review this once, and let me know if further changes are required?

2022-07-20 19:30 UTC, crenshaw-dev commented
@deepto98 I have this on my TODO list, but I'd like to do a thorough review of our default CSP settings. I think there's room for improvement.

2022-07-28 20:16 UTC, crenshaw-dev commented
@deepto98 finally had a chance to look into it. Can you drop the unsafe-eval? Testing locally, I don't think it's necessary. Otherwise I think this policy is the best we can currently do.

2024-02-21 23:09 UTC, manish222agr commented
When do we plan to merge this pr, and in which tag will it be available.

2025-02-28 10:18 UTC, closed without merging