feat: UI part for logs RBAC - hide the logs panel when no RBAC in place #7211
argoproj/argo-cd pull request #9828
Opened 2022-06-29 18:30 UTC by reggie-k

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [X] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [X] The title of the PR states what changed and the related issues number (used for the release note).
* [ ] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [X] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [X] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [X] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)).

2022-06-29 18:32 UTC, reggie-k commented
Hope this one can be merged with squash commits.

2022-06-30 03:56 UTC, reggie-k commented
@crenshaw-dev Thanks for changing the name :)
I am not sure about the docs though - the known UI issue note is relevant for those, who use <= 2.4.3.
Now, if this one makes it to 2.4.4, then 2.4.4 and above does not need the note, indeed.
The docs are on a minor version level, right? If I remove the note in this PR, the docs will be changed and <= 2.4.3 users will see neither the note nor the fixed behavior - right?

2022-06-30 13:08 UTC, reggie-k commented
I will add it then.
If the commit eventually goes to 2.4.5 or later, I will change the doc to
contain the correct version, I will just need to know before it is merged 🙂

On Thu, Jun 30, 2022, 15:52 Michael Crenshaw ***@***.***>
wrote:

> @reggie-k <https://github.com/reggie-k> true, it's a good thought... My
> hope is that if people are already on 2.4.x, then they are already aware of
> the issue. If someone is upgrading to 2.4.x, hopefully they're going
> immediately to 2.4.4.
>
> One way to do it would be to just add "before 2.4.4" to the "known issue"
> docs.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/argoproj/argo-cd/pull/9828#issuecomment-1171181981>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEVDWBDLTLEEBYI3GX2XJ3TVRWJ7HANCNFSM52GWTX7Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-06 17:47 UTC, crenshaw-dev requested changes

2022-07-06 17:47 UTC, crenshaw-dev commented on CHANGELOG.md
> +make lint-ui ; \
Accidental copy/paste?

2022-07-06 20:11 UTC, rbreeze reviewed
LGTM, once the accidental docs edit is fixed 🙂

2022-07-07 07:31 UTC, reggie-k commented
I am a bit concerned about the fix because I only tested it manually. Tested thoroughly, of course, for both allow and deny use cases, and it behaves like I expect, but ArgoCD server side has many unit and end-to-end tests for multiple components, while the UI side has much less overall.
I am very new to React, was hoping to find some other UI pod view tests I can look at and then write my own based on them, but didn't find relevant ones.
I can learn more and write pod view tests, not only for this particular change, but wider, this will obviously take some time, what do you guys think about the PR from the release perspective? Goes in or waits for automatic tests?

2022-07-07 13:27 UTC, reggie-k commented
Sure, I will update it. If you can test it as well it would be awesome!

On Thu, Jul 7, 2022, 16:23 Michael Crenshaw ***@***.***>
wrote:

> @reggie-k <https://github.com/reggie-k> I'm comfortable merging without
> the tests, but I do agree, I think frontend tests could use some work.
> Would you like me to test locally as well, just to add a bit more
> confidence?
>
> Side note: Jann released 2.4.4 yesterday, and I'm going to release 2.4.5
> Tuesday before cherry-picking this change. Can you update the docs to say
> 2.4.6? :-)
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/argoproj/argo-cd/pull/9828#issuecomment-1177608039>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEVDWBB37IFVJ2MF5AWNXRLVS3K5VANCNFSM52GWTX7Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-07-11 05:26 UTC, reggie-k commented
Converted to draft since found some problems upon additional testing, still fixing

2022-07-11 16:21 UTC, crenshaw-dev approved these changes
Looks good on local test! Will hold off merging in case I'm right about the `Boolean` call.  :-)

2022-07-12 12:59 UTC, reggie-k commented on ui/src/app/applications/components/resource-details/resource-details.tsx
> +                        const logsAllowed = Boolean(await services.accounts.canI('logs', 'get', application.spec.project + '/' + application.metadata.name));
Done

2022-07-13 14:55 UTC, crenshaw-dev commented
@reggie-k apologies, I mean to get this into 2.4.6 and failed to do so. Can you push a docs update to say 2.4.7? Hopefully that push will also fix the hung DCO check. :-P

2022-07-13 15:38 UTC, crenshaw-dev commented
Brilliant, thank you!

2022-07-13 16:08 UTC, merged

2022-08-08 20:30 UTC, crenshaw-dev commented
I 100% forgot to cherry-pick this. Will add a commit to update docs.

2022-08-08 20:32 UTC, crenshaw-dev commented
Cherry-picked onto release-2.4 for 2.4.9.

2022-08-09 16:35 UTC, reggie-k commented
Great, thanks!


On Mon, Aug 8, 2022, 23:33 Michael Crenshaw ***@***.***>
wrote:

> Cherry-picked onto release-2.4 for 2.4.9.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/argoproj/argo-cd/pull/9828#issuecomment-1208582327>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEVDWBBB2ICVHHTHJC5BI3LVYFVILANCNFSM52GWTX7Q>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>