fix: err create application when repoUrl with a trailing slash (#9857)
argoproj/argo-cd pull request #9952
Opened 2022-07-12 13:37 UTC by yyzxw

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [ ] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Fixes [#9857]

2022-07-15 17:12 UTC, ashutosh16 commented
@yyzxw  Will, you be able to add a unit test for this change.

2022-07-16 05:24 UTC, yyzxw commented
@ashutosh16 Thank you for review, I have added unit tests for this change, can you help me review it again?

2022-07-19 13:44 UTC, yyzxw commented on util/argo/argo.go
> +		return nil, apierr.NewBadRequest(fmt.Sprintf("repository URL '%s' ends with '/', it seems to be consistent with '%s'", spec.Source.RepoURL, strings.TrimSuffix(spec.Source.RepoURL, "/")))
Oh, sorry, I've corrected it

2022-07-19 14:50 UTC, ashutosh16 commented
thanks, LGTM
@crenshaw-dev  Can you review the PR and merge?

2022-07-21 17:29 UTC, ashutosh16 approved these changes
LG

2022-07-25 14:05 UTC, yyzxw commented
@ashutosh16 This PR has not been merged. Please help me merge it again, thank you

2022-07-26 17:16 UTC, ashutosh16 commented
@yyzxw  @crenshaw-dev wants to relook the changes before approving/merging.

2022-12-22 14:37 UTC, blakepettersson approved these changes

2023-02-17 19:38 UTC, crenshaw-dev requested changes
I don't think this is the right approach. It's acceptable to use a repo with a trailing slash. The problem is when you accidentally use a trailing slash when the configured repo does not have one.

See this comment for an explanation of how I think we ought to fix the issue: https://github.com/argoproj/argo-cd/issues/9857#issuecomment-1175049809

2023-12-27 06:50 UTC, closed without merging