fix: prevent ../ in application path (#9964)
argoproj/argo-cd pull request #9971
Opened 2022-07-13 02:57 UTC by notfromstatefarm

Signed-off-by: notfromstatefarm <86763948+notfromstatefarm@users.noreply.github.com>

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [x] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [x] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [x] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 

Fixes #9964

2022-07-13 15:15 UTC, crenshaw-dev requested changes
Need to follow up on one thing.  :-)

2022-07-13 15:15 UTC, crenshaw-dev commented on util/argo/argo.go
> +		return fmt.Errorf("application path is absolute")
I think we actually have logic elsewhere to interpret absolute paths as being relative to the repo root. I gotta double-check though.

2022-07-13 15:16 UTC, crenshaw-dev commented
Would you be willing to write a unit test from the top level as well, i.e. trying to create/update the app?

2022-07-13 15:17 UTC, notfromstatefarm commented
I shall try! Tests are my weak spot. 😄

2022-07-13 15:39 UTC, crenshaw-dev commented
Haha mine as well. If I can't copy/paste it, I'm in a tough spot. :-P

2023-05-27 20:50 UTC, crenshaw-dev commented
Closing for now since I don't think either Jake or I have the time to tackle it now. Can always reopen.

2023-05-27 20:50 UTC, closed without merging