fix: api server should use ARGOCD_SERVER_LOG_LEVEL instead of ARGOCD_REPO_SERVER_LOGLEVEL (#9970)
argoproj/argo-cd pull request #9975
Opened 2022-07-13 16:30 UTC by usernameisnull

Note on DCO:

If the DCO action in the integration test fails, one or more of your commits are not signed off. Please click on the *Details* link next to the DCO action for instructions on how to resolve this.

Checklist:

* [ ] Either (a) I've created an [enhancement proposal](https://github.com/argoproj/argo-cd/issues/new/choose) and discussed it with the community, (b) this is a bug fix, or (c) this does not need to be in the release notes.
* [x] The title of the PR states what changed and the related issues number (used for the release note).
* [x] I've included "Closes [ISSUE #]" or "Fixes [ISSUE #]" in the description to automatically close the associated issue.
* [ ] I've updated both the CLI and UI to expose my feature, or I plan to submit a second PR with them.
* [ ] Does this PR require documentation updates?
* [ ] I've updated documentation as required by this PR.
* [ ] Optional. My organization is added to USERS.md.
* [x] I have signed off all my commits as required by [DCO](https://github.com/argoproj/argoproj/tree/master/community#contributing-to-argo)
* [ ] I have written unit and/or e2e tests for my change. PRs without these are unlikely to be merged.
* [ ] My build is green ([troubleshooting builds](https://argo-cd.readthedocs.io/en/latest/developer-guide/ci/)). 
Fixes #9970

2022-07-13 17:13 UTC, crenshaw-dev requested changes
Changed a little bit too much.  :-) But after those changes are reverted, the remaining changes are correct!

2022-07-13 17:13 UTC, crenshaw-dev commented on manifests/base/repo-server/argocd-repo-server-deployment.yaml
> +          - name: ARGOCD_SERVER_LOG_LEVEL
This should not be changed here, since it is the repo-server deployment.

2022-07-13 17:13 UTC, crenshaw-dev commented on cmd/argocd-repo-server/commands/argocd_repo_server.go
> +	command.Flags().StringVar(&cmdutil.LogLevel, "loglevel", env.StringFromEnv("ARGOCD_SERVER_LOG_LEVEL", "info"), "Set the logging level. One of: debug|info|warn|error")
These should not be changed, since this is the repo server command code.

2022-07-13 17:29 UTC, crenshaw-dev commented on manifests/ha/install.yaml
> +        - name: ARGOCD_SERVER_LOG_LEVEL
You might have to run `make manifests` or `make manifests-local` to clear this up. :-)

2022-07-14 18:35 UTC, notfromstatefarm approved these changes
LGTM. @crenshaw-dev regarding your concern on Slack, I think that if someone dropped the default 'env' block for a hard-coded value, they did so knowing the consequences for their upgrade process. Besides that, in most cases you only change the log level temporarily.

I also recommend changing the PR title to `fix: api server should use ARGOCD_SERVER_LOG_LEVEL instead of ARGOCD_REPO_SERVER_LOGLEVEL`. Otherwise it may be unclear in the release notes.

2022-07-14 20:55 UTC, crenshaw-dev approved these changes
thanks again @usernameisnull !

2022-07-14 20:57 UTC, merged